### PR TITLE
Fix #4060 Cloning a DualDuct AirLoopHVAC breaks the existing loop

### LINKED ISSUE #4060: Cloning a DualDuct AirLoopHVAC breaks the existing loop.
Issue overview
--------------

Cloning an AirLoopHVAC will break the existing loop, dangling three nodes.

## Steps to Reproduce

```ruby
include OpenStudio::Model

def renameNodes(a)
  a.supplyInletNode.setName("#{a.nameString} Supply Inlet Node")
  a.supplyOutletNodes[0].setName("#{a.nameString} Supply Outlet 1 Node")
  a.supplyOutletNodes[1].setName("#{a.nameString} Supply Outlet 2 Node")
  a.demandInletNodes[0].setName("#{a.nameString} Demand Inlet 1 Node")
  a.demandOutletNode.setName("#{a.nameString} Demand Outlet Node")
  a.demandComponents(a.demandSplitter, a.demandMixer, "OS:Node".to_IddObjectType)[0].setName("#{a.nameString} Demand Connection Node")
end

m = Model.new
# Make a dual duct loop
a = AirLoopHVAC.new(m, true)
a.setName("Loop")
renameNodes(a)
raise if m.getNodes.size != 6
n_nodes = a.components("OS:Node".to_IddObjectType).size
raise "Expected 6 nodes on AirLoopHVAC 'Loop', found #{n_nodes}" if  n_nodes != 6

m.save('1.osm', true)

a2 = a.clone(m).to_AirLoopHVAC.get
a2.setName("LoopClone")
raise if m.getNodes.size != 12
# Throws, because it's 3 actually
n_nodes = a.components("OS:Node".to_IddObjectType).size
raise "Expected 6 nodes on AirLoopHVAC 'Loop', found #{n_nodes}" if  n_nodes != 6

n_nodesClone = a2.components("OS:Node".to_IddObjectType).size
raise "Expected 6 nodes on AirLoopHVAC 'LoopClone', found #{n_nodesClone}" if  n_nodesClone != 6

renameNodes(a2)


m.save('2.osm', true)


a.remove()
raise "There should be only 6 nodes after deleting 'Loop', but there are #{m.getNodes.size}" if m.getNodes.size != 6 # <= Throws, we have 9
n_nodesClone = a2.components("OS:Node".to_IddObjectType).size
raise "Expected 6 nodes on AirLoopHVAC 'LoopClone', found #{n_nodesClone}" if  n_nodesClone != 6

m.save('3.osm', true)

```

## Possible Solution

The AirLoopHVAC::clone isn't adding the supply splitter like it should (createTopology doesn't do it)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): Current develop, circa 3.1.0-alpha (757b0337ae7bc75a2d17a5853ef891300c47a154)

### Context

https://github.com/openstudiocoalition/OpenStudioApplication/issues/217

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fix #4060
 -  Cloning a DualDuct AirLoopHVAC breaks the existing loop

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate): N/A
 - [x] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/AirLoopHVAC.cpp [hunk 1]
```diff
@@ -721,40 +721,101 @@ namespace model {
...
+        auto supplyOutletNodes = this->supplyOutletNodes();
+
+        pathsToHandle.emplace_back(supplyInletNode, supplySplitter, supplySplitterClone, supplyInletNodeClone, true);
+        pathsToHandle.emplace_back(supplySplitter, supplyOutletNodes[0], supplySplitterClone, supplyOutletNodeClones[0], false);
+        pathsToHandle.emplace_back(supplySplitter, supplyOutletNodes[1], supplySplitterClone, supplyOutletNodeClones[1], false);
+
+      } else {
+
+        pathsToHandle.emplace_back(this->supplyInletNode(), this->supplyOutletNode(), airLoopClone.supplyInletNode(), airLoopClone.supplyOutletNode(),
+                                   false);
```
Comment (jmarrec) [inline src/model/AirLoopHVAC.cpp:763]: Single Duct: everything from supply inlet to supply outlet in one go, adding always to supplyOutletNode so it's in the right order

File: src/model/AirLoopHVAC.cpp [hunk 2]
```diff
@@ -721,40 +721,101 @@ namespace model {
...
+        supplySplitterClone.addToNode(supplyInletNodeClone);
+        airLoopClone.getImpl<detail::AirLoopHVAC_Impl>()->setSupplySplitter(supplySplitterClone);
+
+        auto supplyOutletNodeClones = airLoopClone.supplyOutletNodes();
+
+        auto supplySplitter = this->supplySplitter().get();
+        auto supplyInletNode = this->supplyInletNode();
+        auto supplyOutletNodes = this->supplyOutletNodes();
+
+        pathsToHandle.emplace_back(supplyInletNode, supplySplitter, supplySplitterClone, supplyInletNodeClone, true);
```
Comment (jmarrec) [inline src/model/AirLoopHVAC.cpp:756]: Dual Duct: Take components between supply inlet and supply splitter. Reverse them, and add that always to the supply inlet Node, so they end up in the same order.

File: src/model/AirLoopHVAC.cpp [hunk 3]
```diff
@@ -721,40 +721,101 @@ namespace model {
...
+        pathsToHandle.emplace_back(supplySplitter, supplyOutletNodes[0], supplySplitterClone, supplyOutletNodeClones[0], false);
+        pathsToHandle.emplace_back(supplySplitter, supplyOutletNodes[1], supplySplitterClone, supplyOutletNodeClones[1], false);
```
Comment (jmarrec) [inline src/model/AirLoopHVAC.cpp:758]: Dual Duct: From each path between supply splitter and supply outlet Node (there are 2 of them), take components, clone, and add them to the supply outlet node so they end up in the same order

File: src/model/AirLoopHVAC.cpp [hunk 4]
```diff
@@ -721,40 +721,101 @@ namespace model {
...
-          spmclone.addToNode(cloneNode);
+          auto spms = node.setpointManagers();
+          for (const auto& spm : spms) {
+            auto spmclone = spm.clone(model).cast<SetpointManager>();
+            spmclone.addToNode(cloneNode);
+          }
         }
       }
 
+      // Demand Side: same regardless of whether it's a Dual Duct or not
```
Comment (jmarrec) [inline src/model/AirLoopHVAC.cpp:817]: Actual handling of comp clones and SPM clones

**Review by jmarrec — COMMENTED** [review]
@kbenne, this is ready for review
