### PR TITLE
#4894 - `setAmbientTemperatureSchedule` and `setAmbientAirVelocitySchedule` setter for `PipeIndoor` do not work

### LINKED ISSUE #4894: `setAmbientTemperatureSchedule` and `setAmbientAirVelocitySchedule` setter for `PipeIndoor` do not work
Issue overview
--------------
The `PipeIndoor`'s `setAmbientTemperatureSchedule` and `setAmbientAirVelocitySchedule` setters don't appear to work. I'm getting the following error when trying to use them: `[openstudio.model.ScheduleTypeRegistry] <2> No 'Ambient Temperature Schedule' Schedule is registered for class PipeIndoor.`.

## Steps to Reproduce
```
model = OpenStudio::Model::Model.new
pipe = OpenStudio::Model::PipeIndoor.new(model)
pipe.setAmbientTemperatureSchedule(model.alwaysOnDiscreteSchedule)
```

### Environment
 - Platform: Windows 11
 - Version of OpenStudio: 3.6

### Context
I'm using the `setPointer` workaround but it would be nice if if the setters could work.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4894
 - Add missing model tests for PipeIndoor, exercising all fields
 - Fix a PipeIndoor ScheduleTypeRegistry typo

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/PipeIndoor_GTest.cpp [hunk 1]
```diff
@@ -27,25 +27,130 @@
...
+  ThermalZone ambientTemperatureZone(m);
+  EXPECT_TRUE(pipeIndoor.setAmbientTemperatureZone(ambientTemperatureZone));
+  ASSERT_TRUE(pipeIndoor.ambientTemperatureZone());
+  EXPECT_EQ(ambientTemperatureZone, pipeIndoor.ambientTemperatureZone().get());
+
+  // Ambient Temperature Schedule: Optional Object
+  ScheduleConstant ambientTemperatureSchedule(m);
+  EXPECT_TRUE(pipeIndoor.setAmbientTemperatureSchedule(ambientTemperatureSchedule));
+  ASSERT_TRUE(pipeIndoor.ambientTemperatureSchedule());
+  EXPECT_EQ(ambientTemperatureSchedule, pipeIndoor.ambientTemperatureSchedule().get());
```
Comment (jmarrec) [inline src/model/test/PipeIndoor_GTest.cpp:82]: Without fix:

```
[ RUN      ] ModelFixture.PipeIndoor_GettersSetters
unknown file: Failure
C++ exception with description "/Users/julien/Software/Others/OpenStudio/src/model/ScheduleTypeRegistry.cpp@68 : No 'Ambient Temperature Schedule' Schedule is registered for class PipeIndoor." thrown in the test body.
[  FAILED  ] ModelFixture.PipeIndoor_GettersSetters (4 ms)
```

File: src/model/ScheduleTypeRegistry.cpp [hunk 2]
```diff
@@ -340,8 +340,8 @@ namespace model {
       {"People", "Ankle Level Air Velocity", "ankleLevelAirVelocitySchedule", true, "Velocity", 0.0, OptionalDouble()},
       {"PhotovoltaicPerformanceSimple", "Efficiency", "efficiencySchedule", true, "", 0.0, 1.0},
       {"PlantComponentTemperatureSource", "Source Temperature", "sourceTemperatureSchedule", true, "Temperature", OptionalDouble(), OptionalDouble()},
-      {"PipeIndoor", "Ambient Temperature", "ambientTemperatureSchedule", true, "Temperature", OptionalDouble(), OptionalDouble()},
-      {"PipeIndoor", "Ambient Air Velocity", "ambientAirVelocitySchedule", true, "Velocity", 0.0, OptionalDouble()},
+      {"PipeIndoor", "Ambient Temperature Schedule", "ambientTemperatureSchedule", true, "Temperature", OptionalDouble(), OptionalDouble()},
+      {"PipeIndoor", "Ambient Air Velocity Schedule", "ambientAirVelocitySchedule", true, "Velocity", 0.0, OptionalDouble()},
```
Comment (jmarrec) [inline src/model/ScheduleTypeRegistry.cpp:344]: Actual fix for #4894
