### PR TITLE
Fix #3866 - Error when querying surfaces() of ZoneHVACLowTemperature objects and surfaces have no construction 

### LINKED ISSUE #3866: Forward translator Runtime Error if a model has a ZoneHVAC:LowTemperatureRadiant:VariableFlow but no constructions assigned
I can reliably get an "Access violation - no RTTI data! (RuntimeError)" if a model has a ZoneHVAC:LowTemperatureRadiant:VariableFlow, but no constructions assigned to any surface and is run through the forward translator. This will cause the 'Apply Measure Now' window to show an error for any measure, which causes a lot of confusion. 

Code to replicate:

```
require 'openstudio'
require 'openstudio-standards' # to quickly create and populate default constructions set

m = OpenStudio::Model::Model.new

# make a space with some surfaces
points = OpenStudio::Point3dVector.new
points << OpenStudio::Point3d.new(0,0,0)
points << OpenStudio::Point3d.new(0,1,0)
points << OpenStudio::Point3d.new(1,1,0)
points << OpenStudio::Point3d.new(1,0,0)

sp = OpenStudio::Model::Space.fromFloorPrint(points,1,m)
if sp.is_initialized
  sp = sp.get
end

# make a zone, add the space
tz = OpenStudio::Model::ThermalZone.new(m)
sp.setThermalZone(tz)

# make some plant loops
clg = OpenStudio::Model::PlantLoop.new(m)
htg = OpenStudio::Model::PlantLoop.new(m)

# translate - won't fail (no low temp radiant system yet)
ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
if ft.translateModel(m)
  puts "OK"
end

# make a radiant low temperature system
schedule = m.alwaysOnDiscreteSchedule
htg_sch = OpenStudio::Model::ScheduleRuleset.new(m)
htg_coil = OpenStudio::Model::CoilHeatingLowTempRadiantVarFlow.new(m,htg_sch)
htg.addDemandBranchForComponent(htg_coil)
clg_sch = OpenStudio::Model::ScheduleRuleset.new(m)
clg_coil = OpenStudio::Model::CoilCoolingLowTempRadiantVarFlow.new(m,clg_sch)
clg.addDemandBranchForComponent(clg_coil)
obj = OpenStudio::Model::ZoneHVACLowTempRadiantVarFlow.new(m,schedule,htg_coil,clg_coil)
obj.addToThermalZone(tz)

# translate - will fail
ft.translateModel(m)
# => cons_issue.rb:44:in `translateModel': Access violation - no RTTI data! (RuntimeError)

# use Standards to create default schedule set - if constructions are assigned to the surfaces the forwardtranslator will not fail
std = Standard.build("90.1-2013")
def_cons = std.model_add_construction_set(m,"ASHRAE 169-2006-1A","MediumOffice",nil,'No')
if def_cons.is_initialized
  def_cons = def_cons.get.to_DefaultConstructionSet.get
  m.getBuilding.setDefaultConstructionSet(def_cons)
end 

# now translate - won't fail
if ft.translateModel(m)
  puts "Works now"
end
```
@jmarrec

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3866 
 - Error when querying surfaces() of ZoneHVACLowTemperature objects and surfaces have no construction 
 - Started by adding Gtest in FT, realized problem was in model API and for all three types, so implemented 3 gtests there. All 4 fail without fix, pass with fix.

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [x] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate): N/A
 - [x] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/ZoneHVACLowTemperatureRadiantElectric.cpp [hunk 1]
```diff
@@ -182,26 +182,28 @@ namespace detail {
...
-            else if(istringEqual("Floor", surfaceType) && istringEqual("Floors",surfGrpName)){
-              surfaces.push_back(surface);
-            }
-            else if((istringEqual("Floor", surfaceType) || istringEqual("RoofCeiling", surfaceType)) && istringEqual("CeilingsandFloors",surfGrpName)){
-              surfaces.push_back(surface);
-            }
-            else if(istringEqual("AllSurfaces",surfGrpName)){
-              surfaces.push_back(surface);
+          //skip surfaces who do not have a construction, or whose construction is not internal source
+          if (boost::optional<ConstructionBase> _constructionBase = surface.construction()) {
```
Comment (jmarrec) [inline src/model/ZoneHVACLowTemperatureRadiantElectric.cpp]: Actual fix is to start by checking if it has a construction before we try to optionalCast it to InternalSource

File: src/model/ZoneHVACLowTempRadiantVarFlow.cpp [hunk 2]
```diff
@@ -257,26 +257,28 @@ namespace detail {
...
-            else if(istringEqual("Floor", surfaceType) && istringEqual("Floors",surfGrpName)){
-              surfaces.push_back(surface);
-            }
-            else if((istringEqual("Floor", surfaceType) || istringEqual("RoofCeiling", surfaceType)) && istringEqual("CeilingsandFloors",surfGrpName)){
-              surfaces.push_back(surface);
-            }
-            else if(istringEqual("AllSurfaces",surfGrpName)){
-              surfaces.push_back(surface);
+          //skip surfaces who do not have a construction, or whose construction is not internal source
+          if (boost::optional<ConstructionBase> _constructionBase = surface.construction()) {
```
Comment (jmarrec) [inline src/model/ZoneHVACLowTempRadiantVarFlow.cpp]: Actual fix is to start by checking if it has a construction before we try to optionalCast it to InternalSource

File: src/model/ZoneHVACLowTempRadiantConstFlow.cpp [hunk 3]
```diff
@@ -239,26 +239,28 @@ namespace detail {
...
-            else if(istringEqual("Floor", surfaceType) && istringEqual("Floors",surfGrpName)){
-              surfaces.push_back(surface);
-            }
-            else if((istringEqual("Floor", surfaceType) || istringEqual("RoofCeiling", surfaceType)) && istringEqual("CeilingsandFloors",surfGrpName)){
-              surfaces.push_back(surface);
-            }
-            else if(istringEqual("AllSurfaces",surfGrpName)){
-              surfaces.push_back(surface);
+          //skip surfaces who do not have a construction, or whose construction is not internal source
+          if (boost::optional<ConstructionBase> _constructionBase = surface.construction()) {
```
Comment (jmarrec) [inline src/model/ZoneHVACLowTempRadiantConstFlow.cpp]: Actual fix is to start by checking if it has a construction before we try to optionalCast it to InternalSource
