### PR TITLE
#4957 - Some copy constructors aren't declared in SWIG 

### LINKED ISSUE #4957: Some copy constructors aren't declared in SWIG
Issue overview
--------------

@shorowit reported this change of behavior between 3.6.1 and 3.7.0-alpha. This used to work in 3.6.1, and now the copy constructor isn't swigg'ed.

```
[6] 3_7_0(main)> OpenStudio::Point3d.new(OpenStudio::Point3d.new(0, 0, 0))
ArgumentError: Wrong arguments for overloaded method 'Point3d.new'.
Possible C/C++ prototypes are:
    Point3d.new()
    Point3d.new(double x, double y, double z)

from (pry):6:in `initialize'
[7] 3_7_0(main)> OpenStudio::Vector3d.new(OpenStudio::Vector3d.new(0, 0, 0))
ArgumentError: Wrong arguments for overloaded method 'Vector3d.new'.
Possible C/C++ prototypes are:
    Vector3d.new()
    Vector3d.new(double x, double y, double z)
```

## Possible Solution

**This is due to this commit of mine, where I applied Rule of 1 in the C++ code, not realizing that this had an impact on SWIG**: https://github.com/NREL/OpenStudio/commit/565bea0567882199b86a0e2b4376fdb10130d27f#diff-9ef35a3df57f646ab394775dab1b9d3212fd52c1d5bbce281c2585c6df05a952

For these geometry classes, it's probably a good idea to ensure that the copy ctor is swigged.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0-alpha, 0ab02805c62a5f459e669bf3f4c65c95a1d8eed7

### Context

https://github.com/NREL/OpenStudio-HPXML/blob/5e218b5d148effc86f12cbdeb682c21fe8a63db1/BuildResidentialHPXML/resources/geometry.rb#L2360

```
length = OpenStudio::Vector3d.new(point_one - point_two).length
```

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4957
 - Add a couple of convenience methods in the Polyhedron.hpp while I'm at it

**Note**: The missing swig copy ctors were never in any official release, this was only on 3.7.0-alpha, so I'm labeling as "Developer Issue"

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/geometry/Point3d.hpp [hunk 1]
```diff
@@ -27,11 +27,11 @@ class UTILITIES_API Point3d
...
-  // Copy and move operators are implicitly declared
-  // Point3d(const Point3d& other) = default;
-  // Point3d(Point3d&& other) = default;
-  // Point3d& operator=(const Point3d&) = default;
-  // Point3d& operator=(Point3d&&) = default;
+  // Copy and move operators are implicitly declared, but we want the copy ctor for SWIG so we have to define all of them
+  Point3d(const Point3d& other) = default;
+  Point3d(Point3d&& other) noexcept = default;
+  Point3d& operator=(const Point3d&) = default;
+  Point3d& operator=(Point3d&&) noexcept = default;
```
Comment (jmarrec) [inline src/utilities/geometry/Point3d.hpp:34]: Put back the copy ctor for swig. Have to declare all of them or the move operations are implicitly deleted

File: src/utilities/geometry/Polyhedron.cpp [hunk 2]
```diff
@@ -118,10 +118,23 @@ Surface3d::Surface3d(std::vector<Point3d> t_vertices, std::string t_name, size_t
       itnext = std::begin(vertices);
     }
 
-    edges.emplace_back(*it, *itnext, t_name, t_surfNum);
+    edges.emplace_back(*it, *itnext, name, surfNum);
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.cpp:121]: Fix an unrelated issue, t_name (the parameter) was moved from, so it's generally an empty string.

File: src/utilities/geometry/Polyhedron.hpp [hunk 3]
```diff
@@ -164,6 +166,7 @@ using PolyhedronVector = std::vector<Polyhedron>;
 
 /// ostream operator
 UTILITIES_API std::ostream& operator<<(std::ostream& os, const Surface3dEdge& edge);
+UTILITIES_API std::ostream& operator<<(std::ostream& os, const Surface3d& surface3d);
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.hpp:169]: Add an ostream operator<< for convenience

File: src/utilities/geometry/Polyhedron.hpp [hunk 4]
```diff
@@ -138,6 +138,8 @@ class UTILITIES_API Polyhedron
     * proportion of conflicted edges / total number of edges */
   std::vector<Surface3d> findSurfacesWithIncorrectOrientation() const;
 
+  std::vector<Surface3d> surface3ds() const;
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.hpp:141]: Convenience getter for inspection / debugging in Polyhedron

File: src/utilities/geometry/Geometry.i [hunk 5]
```diff
@@ -169,6 +169,14 @@
   }
 }
 
+%extend openstudio::Surface3d {
+  std::string __str__() const {
+    std::ostringstream os;
+    os << *self;
+    return os.str();
+  }
+}
```
Comment (jmarrec) [inline src/utilities/geometry/Geometry.i:178]: Use the new Surface3d::operator<< in the swig interface file

**Review by shorowit — APPROVED** [review]
Confirmed that this fixes the error we were hitting.
