### PR TITLE
Fix new failing tests, add missing Sql Regression test, add 'Year' to IlluminanceMap and a missing autosize method

### LINKED ISSUE #3891: Update List of SQL files for all E+ version we support
Issue overview
--------------

https://github.com/NREL/OpenStudio/blob/582d93bff9a0c8d60b6d7caddeea548ef4a7f711/resources/CMakeLists.txt#L71-L78

Stopped at 8.4.0

This is used here: https://github.com/NREL/OpenStudio/blob/582d93bff9a0c8d60b6d7caddeea548ef4a7f711/src/utilities/sql/Test/SqlFile_GTest.cpp#L557-L565

**Add to Release checklist if we want to keep that up to date** : https://github.com/NREL/OpenStudio/issues/3526

### LINKED ISSUE #3894: SqlFile need to support the "Year" field for IlluminanceMaps
Issue overview
--------------

In adding the "Year" field in Sql in https://github.com/NREL/OpenStudio/pull/3453, I realized IlluminanceMap didn't have it.

This was fixed in https://github.com/NREL/EnergyPlus/pull/7235 which was merged in 9.2.0

So now need to update that: https://github.com/NREL/OpenStudio/blob/56be62a24ca52f0f9eb49d3dbb253d3f089aebe4/src/utilities/sql/SqlFile_Impl.cpp#L600-L604

### LINKED ISSUE #3895: Fix new failing tests: IddFixture.EpIddFile  and SqlFileFixture.Regressions
Issue overview
--------------

```
	  1 - IddFixture.EpIddFile (Failed)
	168 - SqlFileFixture.Regressions (Failed)
```

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3895: fix two newly failing tests `IddFixture.EpIddFile` and `SqlFileFixture.Regressions`
     * `IddFixture.EpIddFile` was because I tried to align our idd against E+ idd, and so I added `\required-field` in some places that actually have `\default xxx` already.
 - Fixes #3891 - Add missing SQL Regression files (8.5.0 to 9.1.0 included) for SqlFileFixture.Regressions
    * I created a bash script to do that for all missing versions, and I committed it there, so it can be used for each new E+ version to automatically get the 1ZoneEvapCooler.idf from the E+ version in question, add the Output:Sqlite and Output:Variable we need for the test, get the E+ installer, run it with it, and copy the sql version where needed.
 - Fixes #3894 - After adding the reg test for 8.9.0, realized the 'Time' table has the 'Year' field but it's always zero. And while fixing that, realized #3894 was needed so I fixed it too.
 - Added a missing Autosizing method `ZoneHVACTerminalUnitVariableRefrigerantFlow::autosizedMaximumSupplyAirTemperaturefromSupplementalHeater()` (ref https://github.com/NREL/OpenStudio-resources/pull/92)

 - DESCRIBE PURPOSE OF THIS PULL REQUEST

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/ZoneHVACTerminalUnitVariableRefrigerantFlow.cpp [hunk 1]
```diff
@@ -577,6 +577,10 @@ namespace detail {
     return getAutosizedValue("Design Size Outdoor Air Flow Rate When No Cooling or Heating is Needed", "m3/s");
   }
 
+  boost::optional<double> ZoneHVACTerminalUnitVariableRefrigerantFlow_Impl::autosizedMaximumSupplyAirTemperaturefromSupplementalHeater() const {
+    return getAutosizedValue("Design Size Maximum Supply Air Temperature from Supplemental Heater", "C");
+  }
+
```
Comment (jmarrec) [inline src/model/ZoneHVACTerminalUnitVariableRefrigerantFlow.cpp]: Missing autosize method

File: resources/energyplus/ProposedEnergy+.idd [hunk 2]
```diff
@@ -42724,37 +42715,32 @@ HeatPump:WaterToWater:EIR:Heating,
...
         \minimum> 0.0
         \units W
         \autosizable
         \default autosize
    N4,  \field Reference Coefficient of Performance
-        \required-field
         \type real
         \minimum> 0.0
         \default 7.5
         \units W/W
```
Comment (jmarrec) [inline resources/energyplus/ProposedEnergy+.idd]: `IddFixture.EpIddFile` would fail because this field has a `\default` but I recently had added `\required-field` to match E+ idd...

File: resources/CMakeLists.txt [hunk 3]
```diff
@@ -76,6 +76,14 @@ set(utilities_resources_src
...
   utilities/SqlFile/1ZoneEvapCooler-V8-3-0.sql
   utilities/SqlFile/1ZoneEvapCooler-V8-4-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V8-5-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V8-6-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V8-7-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V8-8-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V8-9-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V9-0-1.sql
+  utilities/SqlFile/1ZoneEvapCooler-V9-1-0.sql
+  utilities/SqlFile/1ZoneEvapCooler-V9-2-0.sql
```
Comment (jmarrec) [inline resources/CMakeLists.txt]: This is the actual fix for `SqlFileFixture.Regressions`

File: src/cli/test/bundle_git/Gemfile [hunk 4]
```diff
@@ -4,4 +4,3 @@ gem 'xml-simple'
 gem 'json_pure'
 gem 'openstudio-extension', github: 'nrel/openstudio-extension-gem', tag: 'v0.2.0'
 gem 'tilt', github: 'rtomayko/tilt', ref: 'abe77eaf1b5f8da0a7e46135f'
-gem 'simplecov', github: 'NREL/simplecov'
```
Comment (jmarrec) [inline src/cli/test/bundle_git/Gemfile]: Fix for the "bundle_git" test. We no longer need NREL/simplecov.

File: src/utilities/sql/SqlFile.cpp [hunk 5]
```diff
@@ -1733,4 +1733,12 @@ bool SqlFile::hasYear() const {
   return true;
 }
 
+bool SqlFile::hasIlluminanceMapYear() const {
```
Comment (jmarrec) [inline src/utilities/sql/SqlFile.cpp]: New method since `hasYear` works for 8.9.0 (or 9.0.1 at least) but the illuminance map added year only in 9.2.0

File: src/utilities/sql/SqlFile_Impl.cpp [hunk 6]
```diff
@@ -597,21 +616,25 @@ namespace openstudio{
...
-      PreparedStatement stmt1("insert into daylightmaphourlyreports (HourlyReportIndex, MapNumber, Month, DayOfMonth, Hour) values (?, ?, ?, ?, ?)", m_db, true);
+
+      // E+ added the "Year" field to the DaylightMapHourlyReports in version 9.2.0 (NREL/EnergyPlus#7235)
+      // assignment of PreparedStatement does not work, so use a pointer to statement to handle the case where you do or do not have Year
+      std::shared_ptr<PreparedStatement> stmt1;
+      if (hasIlluminanceMapYear()) {
+        stmt1 = std::make_shared<PreparedStatement>("insert into daylightmaphourlyreports (HourlyReportIndex, MapNumber, Year, Month, DayOfMonth, Hour) values (?, ?, ?, ?, ?, ?)", m_db, true);
+      } else {
+        stmt1 = std::make_shared<PreparedStatement>("insert into daylightmaphourlyreports (HourlyReportIndex, MapNumber, Month, DayOfMonth, Hour) values (?, ?, ?, ?, ?)", m_db, true);
+      }
```
Comment (jmarrec) [inline src/utilities/sql/SqlFile_Impl.cpp]: Conditionally handle the 'Year' field, so we can read older Sql files too.

File: src/utilities/sql/Test/SqlFile_GTest.cpp [hunk 7]
```diff
@@ -562,6 +579,13 @@ TEST_F(SqlFileFixture, Regressions) {
   regressionTestSqlFile("1ZoneEvapCooler-V8-2-0.sql", 43.28, 20, 20);
   regressionTestSqlFile("1ZoneEvapCooler-V8-3-0.sql", 43.28, 20, 20);
   regressionTestSqlFile("1ZoneEvapCooler-V8-4-0.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V8-5-0.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V8-6-0.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V8-7-0.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V8-8-0.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V8-9-0.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V9-0-1.sql", 43.28, 20, 20);
+  regressionTestSqlFile("1ZoneEvapCooler-V9-1-0.sql", 43.28, 20, 20);
```
Comment (jmarrec) [inline src/utilities/sql/Test/SqlFile_GTest.cpp]: Register missing Sql regression tests.

**Comment by jmarrec** [comment]
Windows has one failing test at least, seems like it's due to sdk_merge

```
Running main() from gmock_main.cc
Note: Google Test filter = ApplicationPathHelpers.Simple_test_forThisModule
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ApplicationPathHelpers
[ RUN      ] ApplicationPathHelpers.Simple_test_forThisModule
D:\jenkins\openstudio\develop\src\utilities\core\test\ApplicationPathHelpers_GTest.cpp(228): error: Expected equality of these values:
  toString(expectedOpenstudioModulePath)
    Which is: "D:/jenkins/openstudio/develop/build/Products/Release/libopenstudiolib.dll"
  toString(openstudioModulePath)
    Which is: "D:/jenkins/openstudio/develop/build/Products/Release/openstudiolib.dll"
[  FAILED  ] ApplicationPathHelpers.Simple_test_forThisModule (3 ms)
[----------] 1 test from ApplicationPathHelpers (3 ms total)
```
