### PR TITLE
Fix bug of ITE object supply/approach temperature difference schedule

### LINKED ISSUE #3793: Bug of ITE object supply/approach temperature difference schedule
There's a typo in the ScheduleTypeRegistry for these schedules

### PR DESCRIPTION
**Pull request by KaiyuSun**
Pull request overview
---------------------

 - Fixes #3793 
 - Fix bug of ITE object supply/approach temperature difference schedule:

The display names of these two schedules were not correct in ScheduleTypeRegistry, which leads to the two functions "setSupplyTemperatureDifferenceSchedule" and "setReturnTemperatureDifferenceSchedule" not working. Bug is now fixed and related test was added into ElectricEquipmentITEAirCooled_GTest as well.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [x] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [x] If change to an IDD file, add the label `IDDChange`
 - [x] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [x] Perform a Code Review on GitHub
 - [x] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [x] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp [hunk 1]
```diff
@@ -134,6 +134,9 @@ boost::optional<IdfObject> ForwardTranslator::translateElectricEquipmentITEAirCo
             LOG(Warn, modelObject.briefDescription() << " The FlowControlWithApproachTemperatures only applies to ITE zones with single duct VAV terminal unit.");
             return boost::none;
           }
+        } else {
+          LOG(Warn, modelObject.briefDescription() << " The FlowControlWithApproachTemperatures only applies to ITE zones with single duct VAV terminal unit.");
+          return boost::none;
         }
```
Comment (jmarrec) [inline openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp]: This doesn't capture the case where there's not even a thermalZone to begin with.

File: openstudiocore/src/energyplus/Test/ElectricEquipmentITEAirCooled_GTest.cpp [hunk 2]
```diff
@@ -461,12 +478,17 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_ElectricEquipmentITEAirCooled_Constr
...
+  definition3.setAirFlowCalculationMethod("FlowControlWithApproachTemperatures");
+
   ForwardTranslator forwardTranslator;
   Workspace workspace = forwardTranslator.translateModel(model);
 
-  // electricEquipmentITEAirCooled2 was not translated because the terminal is not single duct VAV terminal
+  // electricEquipmentITEAirCooled2 and 3 were not translated because the terminal is not single duct VAV terminal
   ASSERT_EQ(1u, workspace.getObjectsByType(IddObjectType::ElectricEquipment_ITE_AirCooled).size());
-  ASSERT_EQ(2u, workspace.getObjectsByType(IddObjectType::Zone).size());
+  ASSERT_EQ(3u, workspace.getObjectsByType(IddObjectType::Zone).size());
```
Comment (jmarrec) [inline openstudiocore/src/energyplus/Test/ElectricEquipmentITEAirCooled_GTest.cpp]: :+1:

File: openstudiocore/src/model/ScheduleTypeRegistry.cpp [hunk 3]
```diff
@@ -251,8 +251,8 @@ ScheduleTypeRegistrySingleton::ScheduleTypeRegistrySingleton()
     {"ElectricEquipment","Electric Equipment","schedule",true,"",0.0,1.0},
     {"ElectricEquipmentITEAirCooled", "Design Power Input", "designPowerInputSchedule", true, "", 0.0, 1.0},
     {"ElectricEquipmentITEAirCooled", "CPU Loading", "cPULoadingSchedule", true, "", 0.0, 1.0},
-    {"ElectricEquipmentITEAirCooledDefinition", "Supply Temperature Difference", "supplyTemperatureDifferenceSchedule", true, "Temperature", 0.0, 50.0},
-    {"ElectricEquipmentITEAirCooledDefinition", "Return Temperature Difference", "returnTemperatureDifferenceSchedule", true, "Temperature", -50.0, 50.0},
+    {"ElectricEquipmentITEAirCooledDefinition", "Supply Temperature Difference Schedule", "supplyTemperatureDifferenceSchedule", true, "Temperature", 0.0, 50.0},
+    {"ElectricEquipmentITEAirCooledDefinition", "Return Temperature Difference Schedule", "returnTemperatureDifferenceSchedule", true, "Temperature", -50.0, 50.0},
```
Comment (jmarrec) [inline openstudiocore/src/model/ScheduleTypeRegistry.cpp]: Confirmed this matches the `ElectricEquipmentITEAirCooledDefinition_Impl::getScheduleTypeKeys`:

https://github.com/NREL/OpenStudio/blob/a1449287fe7855d289d7dc80eb5aa474ef9de9f6/openstudiocore/src/model/ElectricEquipmentITEAirCooledDefinition.cpp#L101

https://github.com/NREL/OpenStudio/blob/a1449287fe7855d289d7dc80eb5aa474ef9de9f6/openstudiocore/src/model/ElectricEquipmentITEAirCooledDefinition.cpp#L105

Comment (jmarrec) [reply openstudiocore/src/model/ScheduleTypeRegistry.cpp]: The `[0;50]` and `[-50;50]` bounds are unusual though. 

@KaiyuSun what are the source for these? Are these bounds taken from the E+ source code?

@kbenne: Would replacing the (+-) 50 by `OptionalDouble()` be a more reasonable approach?

File: openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp [hunk 4]
```diff
@@ -264,5 +264,22 @@ TEST_F(ModelFixture, ElectricEquipmentITEAirCooled_inletportlist) {
...
 
-// life cycle cost
+// test ITE approach temperature schedule
+TEST_F(ModelFixture, ElectricEquipmentITEAirCooledDefinition_approachtemperatureschedule) {
+  Model model;
+
+  ElectricEquipmentITEAirCooledDefinition definition(model);
+  ElectricEquipmentITEAirCooled electricEquipmentITEAirCooled(definition);
+  ScheduleCompact supplydeltasch(model, 5);
+  ScheduleCompact returndeltasch(model, -5);
```
Comment (jmarrec) [inline openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp]: (Side note: prefer using actual `double` (that is `5.` or `5.0`) to avoid unecessary int to double implicit conversions)

File: openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp [hunk 5]
```diff
@@ -264,5 +264,22 @@ TEST_F(ModelFixture, ElectricEquipmentITEAirCooled_inletportlist) {
...
+
+  EXPECT_EQ(7u, model.numObjects());
 
+  ASSERT_TRUE(definition.setAirFlowCalculationMethod("FlowControlWithApproachTemperatures"));
+  ASSERT_EQ("FlowControlWithApproachTemperatures", definition.airFlowCalculationMethod());
+  ASSERT_TRUE(definition.setSupplyTemperatureDifferenceSchedule(supplydeltasch));
+  ASSERT_TRUE(definition.setReturnTemperatureDifferenceSchedule(returndeltasch));
+
+  model.save(toPath("./ITE8.osm"), true);
```
Comment (jmarrec) [inline openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp]: Remove this line please.

Comment (jmarrec) [reply openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp]: Also, use `EXPECT_` instead of `ASSERT_` whenever you can: ASSERT should be limited to cases where it would produce a hard crash if the condition wasn't satisfied, that is before a `cast` or a `.get` on an optional.

The difference being that EXPECT will let the rest of the statements execute instead of stopping the execution altogether, so it's easier to diagnose multiple problems.

Comment (jmarrec) [reply openstudiocore/src/model/test/ElectricEquipmentITEAirCooled_GTest.cpp]: Addressed these cosmetic changes in https://github.com/NREL/OpenStudio/pull/3781/commits/48c89a19f0146508ebe35ee1acb56da66243afa7

File: openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp (hunk 1 above)
Comment (jmarrec) [reply openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateElectricEquipmentITEAirCooled.cpp]: Proposed to address: https://github.com/NREL/OpenStudio/pull/3781/commits/4772146febe2cb873c03eed69ce2c32a880313cb

**Comment by jmarrec** [comment]
@KaiyuSun Thanks for this PR, looks great. I pushed two minor (mostly cosmetic) commits to address some of the review comments I made. Please review these to see if you're happy with them.

The only thing open for discussion is the comment about the limits in the ScheduleTypeRegistry where I tagged @kbenne for input.

Once that's resolved, and CI is happy with this one (I tagged the PR to tell CI to build it), this can drop in.

File: openstudiocore/src/model/ScheduleTypeRegistry.cpp (hunk 3 above)
Comment (KaiyuSun) [reply openstudiocore/src/model/ScheduleTypeRegistry.cpp]: I updated the return temperature difference range to [-50;0], see the latest change. These limitations are actually restricting the +- of the temperature difference. For supply temperature difference (IT inlet T - AHU supply T), it should always be positive; For return, it should always be negative (AHU return T - IT outlet T).

Comment (KaiyuSun) [reply openstudiocore/src/model/ScheduleTypeRegistry.cpp]: @jmarrec @kbenne Please advise if there is more common method of implementing this kind of limitation. Thank you!

Comment (jmarrec) [reply openstudiocore/src/model/ScheduleTypeRegistry.cpp]: If this is just a sign thing, then OptionalDouble() is the way to go.

Comment (jmarrec) [reply openstudiocore/src/model/ScheduleTypeRegistry.cpp]: For peace of mind, changed it to https://github.com/NREL/OpenStudio/pull/3807
