### PR TITLE
Fix #5147 and generally modernize measure templates + get openstudio to run pytest

### LINKED ISSUE #5147: Issue with runner.lastEnergyPlusSqlFile
Issue overview
--------------

## Current Behavior

In measure testing:

```ruby
-sqlFile = OpenStudio::SqlFile.new(OpenStudio::Path.new(sql_path(test_name))) # Works
+sqlFile = runner.lastEnergyPlusSqlFile.get # Fails
 hours = sqlFile.hoursSimulated
 refute_empty(hours)
 assert_equal(8760.0, hours.get)
```

```
OpenStudioResults_Test#test_example_model_si:
RuntimeError: Error creating prepared statement: SELECT Value FROM TabularDataWithStrings
                                  WHERE ReportName='InputVerificationandResultsSummary'
                                  AND ReportForString='Entire Facility'
                                  AND TableName='General'
                                  AND RowName='Hours Simulated'
                                  AND Units='hrs' with error code 21, extended code 21, errmsg: bad parameter or other API misuse
    OpenStudioResults_Test.rb:263:in `hoursSimulated'
    OpenStudioResults_Test.rb:263:in `test_example_model_si
```

## Possible Solution

Pretty sure it's because "sql_file.close" is at the end of the measure template...

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5147

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/cli/MeasureUpdateCommand.cpp [hunk 1]
```diff
@@ -367,6 +368,56 @@ namespace cli {
...
+
+      fmt::print("runPytestCmd={}\n", runPytestCmd);
+      pythonEngine->exec(runPytestCmd);
+
+      fmt::print(fmt::fg(fmt::color::red),
+                 "┌{0:─^{2}}┐\n"
+                 "│{1: ^{2}}│\n"
+                 "└{0:─^{2}}┘",
+                 "", "Starting ruby tests", 80);
+      fmt::print("\n");
```
Comment (jmarrec) [inline src/cli/MeasureUpdateCommand.cpp:419]: openstudio measure --run-tests will now run Pytests with coverage

this won't be on the dashboard yet.

@DavidGoldwasser @kbenne will need to figure out who should trigger pytest, the C++ CLI or the measure tester gem.

Anyways, for now, I think like this we could just tweak measure-tester-gem to consume the pytest xmls if they are present, since the ruby code runs after the python one.

But if you use measure-tester as a gem and use the rake task, then you'd have to manually run pytest.

File: python/requirements.txt [hunk 2]
```diff
@@ -1,4 +1,7 @@
-jinja2 == 3.1.2
+jinja2 == 3.1.3
 numpy == 1.24.4
 pandas == 2.0.3
-pytest == 7.4.2
+pytest == 8.1.1
+coverage == 7.4.4
+pytest-cov == 5.0.0
```
Comment (jmarrec) [inline python/requirements.txt:6]: Bumped pytest and added coverage / pytest-cov.

I bumped jinja2 too.

pandas and numpy are frozen because we use python 3.8

File: ruby/engine/embedded_help.rb [hunk 3]
```diff
@@ -806,7 +806,7 @@ def self.find(*paths, ignore_error: true)
       ps = [path]
       while file = ps.shift
         catch(:prune) do
-          yield file.dup.taint
+          yield file.dup # .taint
```
Comment (jmarrec) [inline ruby/engine/embedded_help.rb:809]: That was leading to a nasty error when running rubocop via measure tester

File: src/utilities/bcl/BCLMeasure.cpp [hunk 4]
```diff
@@ -59,7 +59,7 @@ static constexpr std::array<std::pair<std::string_view, std::string_view>, 3> ap
   {"resources", "resource"},
 }};
 
-static constexpr std::array<std::string_view, 1> ignoredSubFolders{"tests/output"};
+static constexpr std::array<std::string_view, 3> ignoredSubFolders{"tests/output", "__pycache__", "tests/__pycache__"};
```
Comment (jmarrec) [inline src/utilities/bcl/BCLMeasure.cpp:62]: When updating BCLMeasure / copying it, do not grab `__pycache__`

At some point we may want to also not grab anything .gitignored

File: src/utilities/bcl/templates/ModelMeasure/tests/model_measure_test.rb [hunk 5]
```diff
@@ -111,14 +117,21 @@ def test_good_argument_values
 
     # assert that it ran correctly
     assert_equal('Success', result.value.valueName)
-    assert(result.info.size == 1)
-    assert(result.warnings.empty?)
+    assert_equal(1, result.stepInfo.size)
+    assert_empty(result.stepWarnings)
```
Comment (jmarrec) [inline src/utilities/bcl/templates/ModelMeasure/tests/model_measure_test.rb:121]: Throughout the tests, I modernized the templates to

1. Use non-deprecated methods (warnings is deprecated since 2.x, replaced with stepWarnings)
2. Use minitest assertions that provide much better failure messages

File: src/utilities/bcl/templates/ModelMeasure/tests/model_measure_test.rb [hunk 6]
```diff
@@ -102,6 +105,9 @@ def test_good_argument_values
       argument_map[arg.name] = temp_arg_var
     end
 
+    # Ensure the model did not start with a space named like requested
+    refute_includes(model.getSpaces.map(&:nameString), "New Space")
```
Comment (jmarrec) [inline src/utilities/bcl/templates/ModelMeasure/tests/model_measure_test.rb:109]: another example

File: src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb [hunk 7]
```diff
@@ -139,25 +140,28 @@ def test_with_drybulb_temp
...
+    assert_equal('Success', result.value.valueName)
+    assert_empty(result.stepWarnings)
+
+    sqlFile = runner.lastEnergyPlusSqlFile.get
+    if !sqlFile.connectionOpen
+      sqlFile.reopen
+    end
+    hours = sqlFile.hoursSimulated
+    refute_empty(hours)
+    assert_equal(8760.0, hours.get)
```
Comment (jmarrec) [inline src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb:161]: That makes it clear that #5147 shouldn't happen if you do things correctly.

The reporting measure.rb does sql_file.close at the end.

File: src/utilities/bcl/templates/EnergyPlusMeasure/tests/test_energyplus_measure.py [hunk 8]
```diff
@@ -1,11 +1,16 @@
...
 from pathlib import Path
 
 import openstudio
 import pytest
 
+CURRENT_DIR_PATH = Path(__file__).parent.absolute()
+sys.path.insert(0, str(CURRENT_DIR_PATH.parent))
 from measure import EnergyPlusMeasureName
+sys.path.pop(0)
+del sys.modules['measure']
```
Comment (jmarrec) [inline src/utilities/bcl/templates/EnergyPlusMeasure/tests/test_energyplus_measure.py:13]: To be able to load several pytest files when --run-tests is happening, and because every measure is `measure.py`, we need del sys.modules['measures'] or it remembers the first one it found

File: src/utilities/bcl/templates/EnergyPlusMeasure/tests/test_energyplus_measure.py [hunk 9]
```diff
@@ -113,3 +118,12 @@ def test_good_argument_values(self):
...
         workspace.save(output_file_path, True)
+
+
+# This allows running openstudio CLI on this file (`openstudio test_measure.py`, maybe with extra args)
+if __name__ == "__main__":
+    import sys
+    if len(sys.argv) > 1:
+        pytest.main([__file__] + sys.argv[1:])
+    else:
+        pytest.main()
```
Comment (jmarrec) [inline src/utilities/bcl/templates/EnergyPlusMeasure/tests/test_energyplus_measure.py:129]: This bit is really optional, but I think it's nice to be able to do this, like you could do `openstudio measure_test.rb`

File: src/cli/test/test_bcl_measure_templates.py [hunk 10]
```diff
@@ -0,0 +1,114 @@
...
+        print(f"Instantiating new measure {measure_language} - {measure_type}:")
+        print(f"cmd = {shlex.join(cmd)}")
+    output = _run_subprocess_and_capture(cmd)
+    if verbose:
+        print(output)
+
+    if measure_language == 'Ruby':
+        run_minitest(osclipath=osclipath, measure_dir_path=measure_dir_path, verbose=verbose)
+    else:
+        run_pytest(osclipath=osclipath, measure_dir_path=measure_dir_path, verbose=verbose)
```
Comment (jmarrec) [inline src/cli/test/test_bcl_measure_templates.py:106]: This pytest will:

* Instantiate every Measure Type + Measure Language combination
* Calll pytest or minitest on it

This ensures we have WORKING templates.

File: src/cli/MeasureUpdateCommand.cpp (hunk 1 above)
Comment (DavidGoldwasser) [reply src/cli/MeasureUpdateCommand.cpp:419]: This is great. We can try to do work in measure tester gem shortly after 3.8.0 is out to include in 3.8.x or 3.9.0. Many Python measures may also use additional python libraries. In the case when their is extra libraries, I wouldn't expect tests to run with out of the box install without some extra configuration for the additional libraries.

File: src/cli/CMakeLists.txt [hunk 11]
```diff
@@ -283,11 +283,18 @@ if(BUILD_TESTING)
...
+    add_test(NAME OpenStudioCLI.test_output_files
       COMMAND ${Python_EXECUTABLE} -m pytest --verbose --os-cli-path $<TARGET_FILE:openstudio> "${CMAKE_CURRENT_SOURCE_DIR}/test/test_output_files.py"
       WORKING_DIRECTORY "${PROJECT_BINARY_DIR}/resources/workflow/output_test/"
     )
 
+    file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/Testing/")
+    add_test(NAME OpenStudioCLI.test_bcl_measure_templates
+      COMMAND ${Python_EXECUTABLE} -m pytest --verbose --os-cli-path $<TARGET_FILE:openstudio> "${CMAKE_CURRENT_SOURCE_DIR}/test/test_bcl_measure_templates.py"
+      WORKING_DIRECTORY "${PROJECT_BINARY_DIR}/Testing/"
+    )
```
Comment (jmarrec) [inline src/cli/CMakeLists.txt:295]: register the pytest as a cmakelists one.

Voluntarily not using "-n auto" (pytest-xdist) so I check for loading errors (the thing del `sys.modules['measure']` fixes).

I used system pytest (because it wasn't working with the CLI at first) but we could replace it with openstudio, or do it with both.

Mind that the ReportingMeasure tests are quite slow (there's a simulation happening)

Comment (jmarrec) [reply src/cli/CMakeLists.txt:295]: And maybe another one for `openstudio measure --run_tests Testing/bcl_templates` once all measures have been instantiated too.

We can figure that out later

File: src/cli/MeasureUpdateCommand.cpp (hunk 1 above)
Comment (jmarrec) [reply src/cli/MeasureUpdateCommand.cpp:419]: it should work as long as you pass `--python_path` options to the CLI.

**Comment by jmarrec** [comment]
Lol windows runner is always so fun

```
[189/9099] Updating EnergyPlus simulation in D:/git/OS-build-release-v2/resources/energyplus/Daylighting_School/, this may take a while

FAILED: resources/energyplus/Daylighting_School/eplusout.err D:/git/OS-build-release-v2/resources/energyplus/Daylighting_School/eplusout.err 

cmd.exe /C "cd /D D:\git\OS-build-release-v2\resources && "C:\Program Files\CMake\bin\cmake.exe" -E copy energyplus/Daylighting_School/in.idf energyplus/Daylighting_School/in.idf && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/git/OS-build-release-v2/EnergyPlus-24.1.0-9d7789a3ac-Windows-x86_64/Energy+.idd energyplus/Daylighting_School/Energy+.idd && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/git/OS-build-release-v2/EnergyPlus-24.1.0-9d7789a3ac-Windows-x86_64/WeatherData/USA_CO_Golden-NREL.724666_TMY3.epw energyplus/Daylighting_School/in.epw && "C:\Program Files\CMake\bin\cmake.exe" -E chdir energyplus/Daylighting_School D:/git/OS-build-release-v2/EnergyPlus-24.1.0-9d7789a3ac-Windows-x86_64/energyplus.exe > energyplus/Daylighting_School/screen.out"

Program terminated: EnergyPlus Terminated--Error(s) Detected.
```
