### PR TITLE
Fix #4547 - FT always warns about missing Design Specification Outdoor Air for AirTerminalSingleDuctInletSideMixer

### LINKED ISSUE #4547: FT always warns about missing Design Specification Outdoor Air for AirTerminalSingleDuctInletSideMixer
Issue overview
-------------
@jmarrec 
minor bug.

`dsoa_found` is never set to true, so the warning is always issued:
https://github.com/NREL/OpenStudio/blob/1aef8bf29e655ec13836c012fae8c0aa35dff424/src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctInletSideMixer.cpp#L118-L140

## Steps to Reproduce
This is probably overkill for this issue, but I made it so here it is:
```
# set everything up
m = Model.new
dsoa = DesignSpecificationOutdoorAir.new(m)
s = Space.new(m)
s.setDesignSpecificationOutdoorAir(dsoa)
tz = ThermalZone.new(m)
s.setThermalZone(tz)

c = CoilCoolingDXSingleSpeed.new(m)
hc = CoilHeatingElectric.new(m)
f = FanSystemModel.new(m)
u = AirLoopHVACUnitarySystem.new(m)
u.setCoolingCoil(c)
u.setHeatingCoil(hc)
u.setSupplyFan(f)

ahu = AirLoopHVAC.new(m)
t = AirTerminalSingleDuctInletSideMixer.new(m)
ahu.addBranchForZone(tz, t)
u.addToNode(t.outletModelObject.get.to_Node.get)

# replicate the FT code to prove that zone has space with DSOA
z = ahu.demandComponents(t, ahu.demandOutletNode, "OS_ThermalZone".to_IddObjectType)
puts z.first.to_ThermalZone.get.spaces.first.to_Space.get.designSpecificationOutdoorAir.get

ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)

=>
OS:DesignSpecification:OutdoorAir,
  {56d26512-d1d1-426b-8d12-df167f5dfebb}, !- Handle
  Design Specification Outdoor Air 1,     !- Name
  ,                                       !- Outdoor Air Method
  ,                                       !- Outdoor Air Flow per Person {m3/s-person}
  ,                                       !- Outdoor Air Flow per Floor Area {m3/s-m2}
  ,                                       !- Outdoor Air Flow Rate {m3/s}
  ,                                       !- Outdoor Air Flow Air Changes per Hour {1/hr}
  ;                                       !- Outdoor Air Flow Rate Fraction Schedule Name

[openstudio.energyplus.ForwardTranslator] <0> Cannot set the 'Design Specification Outdoor Air' (DSOA) object for Object of type 'OS:AirTerminal:SingleDuct:InletSideMixer' and named 'Air Terminal Single Duct Inlet Side Mixer 1'. No DSOA was found but 'Control for Outdoor' was set to 'Yes'. Ensure the zone's Space/SpaceType has a DSOA attached.
```

## Possible Solution
\+ `dsoa_found = true`
https://github.com/NREL/OpenStudio/blob/1aef8bf29e655ec13836c012fae8c0aa35dff424/src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctInletSideMixer.cpp#L127-L130

 - Version of OpenStudio (if using an intermediate build, include SHA): 3.3.0+ad235ff36e

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4547

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctInletSideMixer.cpp [hunk 1]
```diff
@@ -125,6 +125,7 @@ namespace energyplus {
             auto spaces = zone.cast<model::ThermalZone>().spaces();
             if (!spaces.empty()) {
               if (auto designSpecificationOutdoorAir = spaces.front().designSpecificationOutdoorAir()) {
+                dsoa_found = true;
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctInletSideMixer.cpp:128]: fix. This was a logic error. Straightforward.

File: src/energyplus/Test/AirTerminalSingleDuctInletSideMixer_GTest.cpp [hunk 2]
```diff
@@ -118,6 +118,20 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_AirTerminalSingleDuctInletSideMixer)
...
+      for (auto& l : ft.warnings()) {
+        if (!firstTime) {
+          s += '\n';
+          firstTime = false;
+        }
+        s += l.logMessage();
+      }
+      return s;
+    }();
+    EXPECT_EQ(0, ft.errors().size());
```
Comment (jmarrec) [inline src/energyplus/Test/AirTerminalSingleDuctInletSideMixer_GTest.cpp:133]: This fails before fix, works after.

**Comment by jmarrec** [comment]
Merging, this is very straightforward and I need that one to start fixing #4628
