### PR TITLE
Addresses #4509, bad nodes created for AirLoopHVAC:UnitarySystem with only cooling coil and supplemental heating coil

### LINKED ISSUE #4509: Bad nodes created for AirLoopHVAC:UnitarySystem with only cooling coil and supplemental heating coil
Issue overview
--------------
AirLoopHVAC:UnitarySystem containing just a cooling coil and supplemental heating coil will be translated with bad component node names. Specifically, the cooling coil outlet node name will not match the supplemental heating coil inlet node name. Only happens when Unitary System has no supply fan or heating coil.

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
c = CoilCoolingDXSingleSpeed.new(m)
hc = CoilHeatingDesuperheater.new(m)

unit = AirLoopHVACUnitarySystem.new(m)
unit.setCoolingCoil(c)
unit.setSupplementalHeatingCoil(hc)

ahu = AirLoopHVAC.new(m)
unit.addToNode(ahu.supplyOutletNode)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)

u = ws.getObjectsByType("AirLoopHVAC_UnitarySystem".to_IddObjectType).first
# unitary outlet node name
puts "Unitary Inlet Node: #{u.getString(5).to_s}"
puts "Unitary Outlet Node: #{u.getString(6).to_s}"
# cooling coil air outlet node name
cc = ws.getObjectsByType("Coil_Cooling_DX_SingleSpeed".to_IddObjectType).first
puts "Cooling Coil Inlet Node: #{cc.getString(7).to_s}"
puts "Cooling Coil Outlet Node: #{cc.getString(8).to_s}"
# supplemental heating coil air inlet node name
hcc = ws.getObjectsByType("Coil_Heating_Desuperheater".to_IddObjectType).first
puts "Supplemental Heating Inlet Node: #{hcc.getString(3).to_s}"
puts "Supplemental Heating Outlet Node: #{hcc.getString(4).to_s}"
```
=> 
```
Unitary Inlet Node: Node 1
Unitary Outlet Node: Node 2
Cooling Coil Inlet Node: Node 1
Cooling Coil Outlet Node: Node 2
Supplemental Heating Inlet Node: Air Loop HVAC Unitary System 1 Cooling Coil - Supplemental Coil Node
Supplemental Heating Outlet Node: Node 2
```

Cooling Coil Outlet Node should equal the Supplemental Heating Coil inlet node ("Air Loop HVAC Unitary System 1 Cooling Coil - Supplemental Coil Node").

## Possible Solution
Need an `if (_supplementalHeatingCoil)` block somewhere around here: https://github.com/NREL/OpenStudio/blob/72156a5eb35ef8f5f8274b3180136edfcb3fe575/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp#L683

Some additional details about your environment for this issue (if relevant):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.3.0

### Context
Trying to have a Unitary System on an AirLoop (with fan outside the unitary system) that will control for humidity (Dehumidification Control Type = "CoolReheat") with a DX cooling and CoilHeatingDesuperheater coil as the required 'supplemental' reheat coil.

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4509

Checklist:
- [x] Add FT test for #4509
- [x] Fix the node name issue for cooling coil + supp heating coil
- [x] Add FT tests (i.e., node name checks) for all unitary system component combinations

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/Test/AirLoopHVACUnitarySystem_GTest.cpp [hunk 1]
```diff
@@ -88,3 +97,543 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_AirLoopHVACUnitarySystem_ControlType
...
+  WorkspaceObjectVector idfSuppHeatingCoils(workspace.getObjectsByType(IddObjectType::Coil_Heating_Desuperheater));
+  WorkspaceObject idfSuppHeatingCoil(idfSuppHeatingCoils[0]);
+
+  std::vector<std::string> nodeNames;
+  nodeNames.push_back(idfSuppHeatingCoil.getString(Coil_Heating_DesuperheaterFields::AirInletNodeName).get());
+  nodeNames.push_back(idfSuppHeatingCoil.getString(Coil_Heating_DesuperheaterFields::AirOutletNodeName).get());
+  return nodeNames;
+}
+
+TEST_F(EnergyPlusFixture, ForwardTranslator_AirLoopHVACUnitarySystem_Nodes) {
```
Comment (jmarrec) [inline src/energyplus/Test/AirLoopHVACUnitarySystem_GTest.cpp:171]: I really like this test. Clean and thorough!

**Review by jmarrec — APPROVED** [review]
Very nice @joseph-robertson , thanks!
