### PR TITLE
Fix #4756 - Update OS:ComponentData during VersionTranslation

### LINKED ISSUE #4756: VersionTranslation of Component breaks when VersionTranslator adds/remove objects
Issue overview
--------------

If you VT for example from 3.4.0 to 3.5.0 a Component (.osc) that has a TableMultiVariableLookup, that TableMultiVariableLookup is changed to a TableLookup, ModelObjectList (=TableIndependentVariableList), and several TableIndependentVariables, so the number of objects changes. It then throws here:

https://github.com/NREL/OpenStudio/blob/af81868d401fd2fc6a5b6f34170fa4f9b274b1b9/src/model/Component.cpp#L200-L205

That is because the VT does NOT update the ComponentData

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fix #4756

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/osversion/VersionTranslator.hpp [hunk 1]
```diff
@@ -202,6 +202,9 @@ namespace osversion {
 
     void update(const VersionString& startVersion);
 
+    /** Deletes handles from m_untranslated and m_deprecated, and adds handles from m_new */
+    void updateComponentData(IdfFile& idfFile);
+
```
Comment (jmarrec) [inline src/osversion/VersionTranslator.hpp:207]: new

File: src/osversion/VersionTranslator.cpp [hunk 2]
```diff
@@ -645,11 +645,50 @@ namespace osversion {
         return;
       }
       IdfFile idfFile = *oIdfFile;
+      if (m_isComponent) {
+        updateComponentData(idfFile);
+      }
```
Comment (jmarrec) [inline src/osversion/VersionTranslator.cpp:650]: Doing it for each intermediate version

File: src/osversion/VersionTranslator.cpp [hunk 3]
```diff
@@ -645,11 +645,50 @@ namespace osversion {
...
+        std::erase_if(currentHandles, [&deletedHandles](auto& s) { return deletedHandles.contains(s); });
+        currentHandles.insert(newHandles.begin(), newHandles.end());
+
+        compData.clearExtensibleGroups();
+        for (auto& handle : currentHandles) {
+          compData.pushExtensibleGroup({handle});
+        }
+      }
+    }
+  }
```
Comment (jmarrec) [inline src/osversion/VersionTranslator.cpp:690]: get the OS:ComponentData, and adjust the extensible groups. I assume that this has always been and will always be the case: the extensible groups are just one string: `Name of Object X`

You remove m_untranslated/m_deprecated (they seem to function the same...), and you add the m_new stuff.

Not touching the m_refactored since the old and new objects should have the same handle

File: src/osversion/test/VersionTranslator_GTest.cpp [hunk 4]
```diff
@@ -2319,3 +2319,76 @@ TEST_F(OSVersionFixture, update_3_4_0_to_3_5_0_ZoneHVACPackaged) {
...
+  EXPECT_TRUE(var_->isEmpty(9));                         // External File Column Number
+  EXPECT_TRUE(var_->isEmpty(10));                        // External File Starting Row Number
+
+  // Values
+  ASSERT_EQ(x1.size(), var_->numExtensibleGroups());
+  for (size_t i = 0; auto& eg : var_->extensibleGroups()) {
+    EXPECT_EQ(x1[i], eg.getDouble(0).get());
+    ++i;
+  }
+}
```
Comment (jmarrec) [inline src/osversion/test/VersionTranslator_GTest.cpp:2394]: New test
