### PR TITLE
Fix #4882 - Avoid a crash in createFluidProperties during FT that's due to Undefined Behavior

### LINKED ISSUE #4882: OS 3.6 segmentation fault
Issue overview
--------------
Occurs w/ ResStock updated to using OpenStudio 3.6.

```
[BOOST_ASSERT] <2> Assertion m_impl failed on line 2031 of openstudio::IdfObject::IdfObject(const openstudio::IdfObject&) in file /srv/jenkins/openstudio/git/nightly/ubuntu_2004/src/utilities/idf/IdfObject.cpp.
[BOOST_ASSERT] <2> Assertion m_impl failed on line 2031 of openstudio::IdfObject::IdfObject(const openstudio::IdfObject&) in file /srv/jenkins/openstudio/git/nightly/ubuntu_2004/src/utilities/idf/IdfObject.cpp.
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/model.rb:124: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0016 p:---- s:0119 e:000118 CFUNC  :translateModel
c:0015 p:0124 s:0114 e:000113 METHOD :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/model.rb:124
c:0014 p:0240 s:0102 E:000fd0 METHOD :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_translation.rb:72
c:0013 p:0084 s:0096 e:000095 METHOD :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291
c:0012 p:0041 s:0088 e:000087 METHOD :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233
c:0011 p:1045 s:0082 E:0026b0 METHOD :/openstudio_cli.rb:1187
c:0010 p:0256 s:0062 e:000061 METHOD :/openstudio_cli.rb:817
c:0009 p:0605 s:0055 E:002408 EVAL   :/openstudio_cli.rb:1984 [FINISH]
c:0008 p:---- s:0049 e:000048 CFUNC  :eval
c:0007 p:0074 s:0042 e:000041 METHOD eval:188
c:0006 p:0060 s:0033 e:000032 BLOCK  eval:173 [FINISH]
c:0005 p:---- s:0028 e:000027 CFUNC  :each
c:0004 p:0015 s:0024 e:000023 METHOD eval:167
c:0003 p:0331 s:0018 e:000017 METHOD eval:126
c:0002 p:0005 s:0007 e:000006 EVAL   eval:3 [FINISH]
c:0001 p:0000 s:0003 E:0003d0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
eval:3:in `<main>'
eval:126:in `require'
eval:167:in `require_embedded'
eval:167:in `each'
eval:173:in `block in require_embedded'
eval:188:in `require_embedded_absolute'
eval:188:in `eval'
:/openstudio_cli.rb:1984:in `<main>'
:/openstudio_cli.rb:817:in `execute'
:/openstudio_cli.rb:1187:in `execute'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_translation.rb:72:in `perform'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/model.rb:124:in `translate_to_energyplus'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/model.rb:124:in `translateModel'
```

## Steps to Reproduce
The simplest example I can provide starts with an HPXML file:
1. Clone https://github.com/NREL/OpenStudio-HPXML
2. Download [these HPXML and OSW files](https://github.com/NREL/OpenStudio/files/11444213/segfault.zip) to the top-level dir of the repo.
3. Run `openstudio run -w run-hpxml.osw` and observe segmentation fault.

But it's really bizarre. The simulation will work successfully if I make quite a few different changes to the HXPML file. For example
1. Remove use of ScheduleFile for occupancy (remove `<SchedulesFilePath>schedules.csv</SchedulesFilePath>` in the HPXML)
2. Change the cooling system fraction load met (change `<FractionCoolLoadServed>0.6</FractionCoolLoadServed>` to `<FractionCoolLoadServed>1.0</FractionCoolLoadServed>` in the HPXML)
3. Remove all the ventilation fans (remove the entire `<MechanicalVentilation>...</MechanicalVentilation>` section in the HPXML)

Since these changes are all very different in terms of what model objects they touch, it seems like the segmentation fault somehow requires this particular combination of model objects.

### Environment

Some additional details about your environment for this issue (if relevant):
 - WSL (Ubuntu 20.04)
 - OpenStudio 3.6.0+860f5de185

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4882

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/Test/PlantLoop_GTest.cpp [hunk 1]
```diff
@@ -170,3 +170,20 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_PlantLoop_AvailabilityManagers_Sched
...
+    for (int i = 0; i < n; ++i) {
+      PlantLoop p(m);
+      EXPECT_TRUE(p.setFluidType("PropyleneGlycol"));
+      EXPECT_TRUE(p.setGlycolConcentration(50 + i));
+    }
+    ForwardTranslator ft;
+    // EXPECT_TRUE(false) << "Failed for " << n << " PlantLoops";
+    ASSERT_NO_THROW(ft.translateModel(m)) << "Failed for " << n << " PlantLoops";
+  }
+}
```
Comment (jmarrec) [inline src/energyplus/Test/PlantLoop_GTest.cpp:189]: Before fix it crashes at 5 PlantLoops

```shell
[ RUN      ] EnergyPlusFixture.ForwardTranslator_PlantLoop_createFluidProperties
/Users/julien/Software/Others/OpenStudio/src/energyplus/Test/PlantLoop_GTest.cpp:186: Failure
Value of: false
  Actual: false
Expected: true
Failed for 1 PlantLoops
/Users/julien/Software/Others/OpenStudio/src/energyplus/Test/PlantLoop_GTest.cpp:186: Failure
Value of: false
  Actual: false
Expected: true
Failed for 2 PlantLoops
/Users/julien/Software/Others/OpenStudio/src/energyplus/Test/PlantLoop_GTest.cpp:186: Failure
Value of: false
  Actual: false
Expected: true
Failed for 3 PlantLoops
/Users/julien/Software/Others/OpenStudio/src/energyplus/Test/PlantLoop_GTest.cpp:186: Failure
Value of: false
  Actual: false
Expected: true
Failed for 4 PlantLoops
/Users/julien/Software/Others/OpenStudio/src/energyplus/Test/PlantLoop_GTest.cpp:186: Failure
Value of: false
  Actual: false
Expected: true
Failed for 5 PlantLoops
[BOOST_ASSERT] <2> Assertion m_impl failed on line 2031 of openstudio::IdfObject::IdfObject(const openstudio::IdfObject &) in file /Users/julien/Software/Others/OpenStudio/src/utilities/idf/IdfObject.cpp.
Assertion failed: (false), function assertion_failed, file Assert.hpp, line 61.


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.49 sec

The following tests FAILED:
        2890 - EnergyPlusFixture.ForwardTranslator_PlantLoop_createFluidProperties (Subprocess aborted)
```

File: src/energyplus/ForwardTranslator.cpp [hunk 2]
```diff
@@ -4506,16 +4506,17 @@ namespace energyplus {
...
     fluidPropGlyConcentration.setString(FluidProperties_GlycolConcentrationFields::GlycolType, glycolType);
     fluidPropGlyConcentration.setDouble(FluidProperties_GlycolConcentrationFields::GlycolConcentration, glycolConcentration * 0.01);
 
-    return fluidPropName;
+    // NOTE: do not do another emplace_back before returning
+    IdfObject& fluidPropName = m_idfObjects.emplace_back(openstudio::IddObjectType::FluidProperties_Name);
+    fluidPropName.setString(FluidProperties_NameFields::FluidName, glycolName);
+    fluidPropName.setString(FluidProperties_NameFields::FluidType, "Glycol");
+
+    return {fluidPropName};
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator.cpp:4519]: fix here

**Comment by joseph-robertson** [comment]
I tested the Ubuntu 22.04 installer locally on WSL2, and it seems to correct the issue.
