### PR TITLE
Fix set string index 1 for ModelObjects

### LINKED ISSUE #4205: WorkspaceObject::setString allows setting invalid names for ModelObjects
Issue overview
--------------
WorkspaceObject::setString allows setting invalid names for ModelObjects

## Current Behavior
WorkspaceObject::setString assumes name index is always 0, for ModelObjects name index is 1.  This allows user to set invalid names using WorkspaceObject::setString.

## Expected Behavior
The following test should pass:

```
  Model model;
  Space space1(model);
  Space space2(model);
  unsigned nameIndex = 1;

  EXPECT_TRUE(space1.setString(nameIndex, "Space 1"));
  ASSERT_TRUE(space1.getString(nameIndex));
  EXPECT_EQ("Space 1", space1.getString(nameIndex).get());

  EXPECT_FALSE(space2.setString(nameIndex, "Space 1"));
  ASSERT_TRUE(space2.getString(nameIndex));
  EXPECT_NE("Space 1", space2.getString(nameIndex).get());

  EXPECT_FALSE(space2.setString(nameIndex, ""));
  ASSERT_TRUE(space2.getString(nameIndex));
  EXPECT_NE("", space2.getString(nameIndex).get());
```

### PR DESCRIPTION
**Pull request by macumber**
Pull request overview
---------------------

 - Fixes #4205  - WorkspaceObject::setString allows setting invalid names for ModelObjects

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [x] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes

**Labels:**

 - [x] If change to an IDD file, add the label `IDDChange`
 - [x] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by macumber** [comment]
Relates to https://github.com/openstudiocoalition/OpenStudioApplication/issues/314

File: src/model/test/SwimmingPoolIndoor_GTest.cpp [hunk 1]
```diff
@@ -87,7 +87,7 @@ TEST_F(ModelFixture, SwimmingPoolIndoor_GettersSetters) {
   boost::optional<Space> space2 = Space::fromFloorPrint(floorPrint, 3, m);
   ASSERT_TRUE(space2);
   auto surfaces2 = space2->surfaces();
-  auto floorSurfaceIt2 = std::find_if(std::begin(surfaces), std::end(surfaces), [](const auto& surface) { return surface.surfaceType() == "Floor"; });
+  auto floorSurfaceIt2 = std::find_if(std::begin(surfaces2), std::end(surfaces2), [](const auto& surface) { return surface.surfaceType() == "Floor"; });
```
Comment (macumber) [inline src/model/test/SwimmingPoolIndoor_GTest.cpp:90]: This is a bug in this test unrelated to this pull request

File: src/utilities/idf/WorkspaceObject.cpp [hunk 2]
```diff
@@ -431,8 +431,11 @@ namespace detail {
     }
 
     // regular field -- name or data
-    if ((index == 0) && (iddObject().hasNameField())) {
```
Comment (macumber) [inline src/utilities/idf/WorkspaceObject.cpp:434]: Could add additional check if this field is a handle here and route that to setName to preserve existing behavior.

File: src/utilities/idf/WorkspaceObject.cpp [hunk 3]
```diff
@@ -370,7 +370,7 @@ namespace detail {
       }
 
       // check collection NameConflict
-      if (!uniquelyIdentifiableByName()) {
+      if (!newName.empty() && iddObject().isRequiredField(*index) && !uniquelyIdentifiableByName()) {
```
Comment (macumber) [inline src/utilities/idf/WorkspaceObject.cpp:373]: This change is mostly to support OutputMeter having an empty name on construction.  If we change to OutputMeter `Meter Name` we can revert this line.

File: src/utilities/idf/WorkspaceObject.cpp [hunk 4]
```diff
@@ -359,7 +359,7 @@ namespace detail {
     if (checkValidity && (level > StrictnessLevel::None)) {
 
       // do not set if would violate field NullAndRequired
-      if ((level > StrictnessLevel::Draft) && newName.empty() && iddObject().isRequiredField(*index)) {
+      if ((level >= StrictnessLevel::Draft) && newName.empty() && iddObject().isRequiredField(*index)) {
```
Comment (macumber) [inline src/utilities/idf/WorkspaceObject.cpp:362]: I thought this was enforced at `Draft` strictness, we don't use `Final` strictness for anything that I know of

File: src/model/test/ModelObject_GTest.cpp [hunk 5]
```diff
@@ -125,3 +127,25 @@ TEST_F(ModelFixture, ModelObject_Clone_DifferentModel) {
   EXPECT_TRUE(anotherNewSurface.construction().get().cast<LayeredConstruction>().layers()
               == newSurface.construction().get().cast<LayeredConstruction>().layers());
 }
+
+TEST_F(ModelFixture, ModelObject_SetString) {
```
Comment (macumber) [inline src/model/test/ModelObject_GTest.cpp:131]: This is a new test to verify the bug fix

**Comment by macumber** [comment]
Looks like the Python bindings might have issues accessing PyPi, possibly due to not allowing access to secrets on a pull request from a fork?

https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

```
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.
Error: Process completed with exit code 1.
```

File: src/utilities/idf/WorkspaceObject.cpp [hunk 6]
```diff
@@ -431,8 +431,11 @@ namespace detail {
     }
 
     // regular field -- name or data
-    if ((index == 0) && (iddObject().hasNameField())) {
-      return setName(value, checkValidity).has_value();
+    if (iddObject().hasNameField()) {
+      boost::optional<unsigned> nameIndex = iddObject().nameFieldIndex(); 
+      if (nameIndex && (*nameIndex == index)) {
+        return setName(value, checkValidity).has_value();
+      }
```
Comment (jmarrec) [inline src/utilities/idf/WorkspaceObject.cpp]:
```suggestion
   // regular field -- name or data
    if ((iddObject().hasNameField()) && (index == iddObject().nameFieldIndex().get())) {
      return setName(value, checkValidity).has_value();
    }  // name
```

if hasNameField, I don't think you also need to check if nameIndex exits.

**Comment by jmarrec** [comment]
@macumber I rebased this branch onto develop and merged #4206 into this (after rebasing it onto develop as well so I could resolve conflicts properly)

**Comment by jmarrec** [comment]
> Looks like the Python bindings might have issues accessing PyPi, possibly due to not allowing access to secrets on a pull request from a fork?

The repo/fork is the one that should have the proper TESTPYPI_TOKEN, so it's expected that it fails. don't worry about it.

File: src/model/test/ModelObject_GTest.cpp (hunk 5 above)
Comment (jmarrec) [reply src/model/test/ModelObject_GTest.cpp:131]: Merge from #4206 adds a very similar one for at Workspace level, I think both are relevant and I don't see a problem testing twice.

**Comment by jmarrec** [comment]
oops, seems like this never got built by CI and didn't notice it broke https://github.com/NREL/OpenStudio/blob/3650208f2f09905ba612ea122737035bc6577f56/src/utilities/idf/Test/WorkspaceObject_GTest.cpp#L578-L581

File: src/utilities/idf/WorkspaceObject.cpp (hunk 3 above)
Comment (jmarrec) [reply src/utilities/idf/WorkspaceObject.cpp:373]: This change created https://github.com/NREL/OpenStudio/issues/4247

`OS:Coil:Heating:Electric` does not have `\required-field` on its Name field, and now unicity of name isn't enforced anymore.
