### PR TITLE
Addresses #5208, OS 3.8 broke json-schema validation

### LINKED ISSUE #5208: OS 3.8 broke json-schema validation
Issue overview
--------------
OpenStudio 3.7 works (validation error returned):

```ruby
openstudio -e 'require "json-schema"; require "stringio"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'
The property '#/a' of type String did not match the following type: integer
```

OpenStudio 3.8 fails (ruby exception):

```ruby
openstudio -e 'require "json-schema"; require "stringio"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'
terminate called after throwing an instance of 'RubyException'
  what():  NameError: uninitialized constant IO::StringIO
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #5208.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by joseph-robertson** [comment]
I tested the `openstudio -e 'require "json-schema"; require "stringio"; ...` line using the windows installer, and it works.

File: ruby/bindings/InitRubyBindings.cpp [hunk 1]
```diff
@@ -471,6 +471,7 @@ def safe_puts(message=nil, opts=nil)
   end
 end
 
+require 'stringio' # JJR: remove this once json-schema is updated to require 'stringio'? (cf https://github.com/voxpupuli/json-schema/pull/512)
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:474]:
```suggestion
require 'stringio' # TODO: remove this once json-schema version is > 3.4.0, (cf https://github.com/voxpupuli/json-schema/pull/512)
```

**Review by jmarrec — APPROVED** [review]
