### PR TITLE
Fix #4268 - correct implementation of IdfObject_Impl::resizeToMinFields so that it handles truncated extensible groups correctly

### LINKED ISSUE #4268: OS_ASSERT error in IdfObject::extensibleGroups in epJSON test
Issue overview
--------------

**This has nothing to do with epJSONTranslator, it fails with OpenStudio 3.1.0 and develop alike**. It's an error loading the Idf files... (I'm pretty sure one of IDF is faulty, but will confirm)

I was seeing these two tests failling locally but *intermittently* and CI wasn't complaining... I now realize this is just happening in **Debug** mode since it's an OS_ASSERT...

## Current Behavior

```ruby
OpenStudio::openStudioLongVersion
"3.1.0+e165090621"

[1] OS-build(main)> source_idf_path = '/home/julien/Software/Others/OS-build/EnergyPlus-9.5.0-003df71316-Linux-Ubuntu18.04-x86_64/ExampleFiles/UnitaryHybridAC_DedicatedOutsideAir.idf'
=> "/home/julien/Software/Others/OS-build/EnergyPlus-9.5.0-003df71316-Linux-Ubuntu18.04-x86_64/ExampleFiles/UnitaryHybridAC_DedicatedOutsideAir.idf"
[2] OS-build(main)> w = OpenStudio::Workspace::load(OpenStudio::Path.new(source_idf_path)).get; wo = w.getObjectsByType("ZoneHVAC:HybridUnitaryHVAC")[0]; wo.extensibleGroups.size
[BOOST_ASSERT] <2> Assertion nExtFields % groupSize == 0 failed on line 1048 of unsigned int openstudio::detail::IdfObject_Impl::numExtensibleGroups() const in file /home/ubuntu/git/OpenStudio/src/utilities/idf/IdfObject.cpp.
[BOOST_ASSERT] <2> Assertion nExtFields % groupSize == 0 failed on line 1048 of unsigned int openstudio::detail::IdfObject_Impl::numExtensibleGroups() const in file /home/ubuntu/git/OpenStudio/src/utilities/idf/IdfObject.cpp.
=> 10

```

### Details

```
$ ctest --rerun-failed --output-on-failure -R epJSON
Test project /home/julien/Software/Others/OS-build
    Start 2874: epJSONFixture.TranslateIDFToEPJSON_ASHRAE9012016_OutPatientHealthCare_Denver
1/2 Test #2874: epJSONFixture.TranslateIDFToEPJSON_ASHRAE9012016_OutPatientHealthCare_Denver ...Subprocess aborted***Exception:   5.32 sec
Running main() from gmock_main.cc
Note: Google Test filter = epJSONFixture.TranslateIDFToEPJSON_ASHRAE9012016_OutPatientHealthCare_Denver
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from epJSONFixture
[ RUN      ] epJSONFixture.TranslateIDFToEPJSON_ASHRAE9012016_OutPatientHealthCare_Denver
EnergyPlus Starting
EnergyPlus, Version 9.5.0-003df71316, YMD=2021.03.30 11:18
Converted input file format. Exiting.
EnergyPlus Run Time=00hr 00min  0.44sec
EnergyPlus Completed Successfully.
[BOOST_ASSERT] <2> Assertion nExtFields % groupSize == 0 failed on line 983 of unsigned int openstudio::detail::IdfObject_Impl::numExtensibleGroups() const in file /home/julien/Software/Others/OpenStudio/src/utilities/idf/IdfObject.cpp.
openstudio_epjson_tests: /home/julien/Software/Others/OpenStudio/src/utilities/bcl/../core/Assert.hpp:61: void boost::assertion_failed(const char*, const char*, const char*, long int): Assertion `false' failed.

    Start 2878: epJSONFixture.TranslateIDFToEPJSON_UnitaryHybridAC_DedicatedOutsideAir
2/2 Test #2878: epJSONFixture.TranslateIDFToEPJSON_UnitaryHybridAC_DedicatedOutsideAir .........Subprocess aborted***Exception:   2.63 sec
Running main() from gmock_main.cc
Note: Google Test filter = epJSONFixture.TranslateIDFToEPJSON_UnitaryHybridAC_DedicatedOutsideAir
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from epJSONFixture
[ RUN      ] epJSONFixture.TranslateIDFToEPJSON_UnitaryHybridAC_DedicatedOutsideAir
EnergyPlus Starting
EnergyPlus, Version 9.5.0-003df71316, YMD=2021.03.30 11:18
Converted input file format. Exiting.
EnergyPlus Run Time=00hr 00min  0.31sec
EnergyPlus Completed Successfully.
[BOOST_ASSERT] <2> Assertion nExtFields % groupSize == 0 failed on line 983 of unsigned int openstudio::detail::IdfObject_Impl::numExtensibleGroups() const in file /home/julien/Software/Others/OpenStudio/src/utilities/idf/IdfObject.cpp.
openstudio_epjson_tests: /home/julien/Software/Others/OpenStudio/src/utilities/bcl/../core/Assert.hpp:61: void boost::assertion_failed(const char*, const char*, const char*, long int): Assertion `false' failed.


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   8.16 sec

The following tests FAILED:
	2874 - epJSONFixture.TranslateIDFToEPJSON_ASHRAE9012016_OutPatientHealthCare_Denver (Subprocess aborted)
	2878 - epJSONFixture.TranslateIDFToEPJSON_UnitaryHybridAC_DedicatedOutsideAir (Subprocess aborted)
```

## Possible Solution

Failed tests:

* [x] TranslateIDFToEPJSON_ASHRAE9012016_OutPatientHealthCare_Denver: `IdfObject_Impl::resizeToMinFields` is wrong (that shows how little we use IdfObject::load probably)
* [x] TranslateIDFToEPJSON_UnitaryHybridAC_DedicatedOutsideAir: this is an E+ example file issue. I filed it at https://github.com/NREL/EnergyPlus/issues/8670 and fixed it in https://github.com/NREL/EnergyPlus/pull/8671

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #4268 - correct implementation of IdfObject_Impl::resizeToMinFields so that it handles truncated extensible groups correctly

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] IdfObject Changes / Additions
 - [x] Tested changes before and after via two new unit tests API methods are tested (in `src/model/test`)
 - [x] All new and existing tests passes

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/idf/Test/IdfObject_GTest.cpp [hunk 1]
```diff
@@ -784,3 +785,67 @@ TEST_F(IdfFixture, IdfObject_SetDouble_NaN_and_Inf) {
...
+  )";
+
+  IdfObject obj = IdfObject::load(idf_text).get();
+
+  unsigned nNonExtensible = obj.iddObject().numFields();
+  unsigned groupSize = obj.iddObject().properties().numExtensible;
+  EXPECT_EQ(nNonExtensible, obj.numNonextensibleFields());
+  EXPECT_EQ(nNonExtensible + groupSize * 2, obj.numFields());
+  ASSERT_NO_THROW(obj.numExtensibleGroups());
+  EXPECT_EQ(2, obj.numExtensibleGroups());
```
Comment (jmarrec) [inline src/utilities/idf/Test/IdfObject_GTest.cpp:850]: Now this is the issue that the ASHRAE9012016_OutPatientHealthCare_Denver.idf on #4268 is exhibiting. The end of the extensible group is truncated, and resizeToMinFields messed it up: instead of adding **2** fields, it would add **4**, and you'd end up with a broken object that would have 16 fields instead of 14:

```diff
ZoneHVAC:EquipmentList,
  Zone1Equipment,                         !- Name
  SequentialLoad,                         !- Load Distribution Scheme
  ZoneHVAC:AirDistributionUnit,           !- Zone Equipment Object Type 1
  Zone1DirectAir ADU,                     !- Zone Equipment Name 1
  1,                                      !- Zone Equipment Cooling Sequence 1
  1,                                      !- Zone Equipment Heating or No-Load Sequence 1
  ,                                       !- Zone Equipment Sequential Cooling Fraction Schedule Name 1
  ,                                       !- Zone Equipment Sequential Heating Fraction Schedule Name 1
  ZoneHVAC:WaterToAirHeatPump,            !- Zone Equipment Object Type 2
  Zone1WTAHP,                             !- Zone Equipment Name 2
  2,                                      !- Zone Equipment Cooling Sequence 2
  2,                                      !- Zone Equipment Heating or No-Load Sequence 2
  ,                                       !- Zone Equipment Sequential Cooling Fraction Schedule Name 2
  ,                                       !- Zone Equipment Sequential Heating Fraction Schedule Name 2
-  ,                                       !- Zone Equipment Object Type 3
-  ;                                       !- Zone Equipment Name 3
```

File: src/utilities/idf/IdfObject.cpp [hunk 2]
```diff
@@ -1383,14 +1383,14 @@ namespace detail {
...
+      n = min_n;
     }
     // also make sure extensible groups are whole
     if (m_iddObject.properties().extensible) {
-      n = numFields();
       int nExtFields = n - m_iddObject.numFields();
       if (nExtFields > 0) {
         int groupSize = m_iddObject.properties().numExtensible;
-        int nToAdd = nExtFields % groupSize;
+        int nToAdd = (groupSize - nExtFields) % groupSize;
```
Comment (jmarrec) [inline src/utilities/idf/IdfObject.cpp:1393]: Fix for #4268 is here.

m_iddObject.numFields() = 2
groupSize = 6
nExtFields =  6 + 4 (missing 2) = 10

Before

```
nToAdd = nExtFields % groupSize = 10 % 6 = 4
```

Now

```
nToAdd = (6 - 10) % 6 = (-4) % 6 = 2
```

| nExtFields | groupSize – nExtFields | nToAdd = (groupSize – nExtFields)<br>         % groupSize |
|------------|------------------------|-----------------------------------------------------------|
| 1          | 5                      | 5                                                         |
| 2          | 4                      | 4                                                         |
| 3          | 3                      | 3                                                         |
| 4          | 2                      | 2                                                         |
| 5          | 1                      | 1                                                         |
| **6**          | 0                      | **0**                                                          |
| 7          | -1                     | 5                                                         |
| 8          | -2                     | 4                                                         |
| 9          | -3                     | 3                                                         |
| 10         | -4                     | 2                                                         |
| 11         | -5                     | 1                                                         |
| **12**         | -6                     | **0**                                                         |
| 13         | -7                     | 5                                                         |
| 14         | -8                     | 4                                                         |
| 15         | -9                     | 3                                                         |
| 16         | -10                    | 2                                                         |
| 17         | -11                    | 1                                                         |
| **18**         | -12                    | **0**                                                      |
| 19         | -13                    | 5                                                         |
| 20         | -14                    | 4                                                         |

**Comment by jmarrec** [comment]
Oops CI is very unhappy here. Weird, locally it was supposedly working... I'll fix it

File: src/utilities/idf/Test/IdfObject_GTest.cpp (hunk 1 above)
Comment (tijcolem) [reply src/utilities/idf/Test/IdfObject_GTest.cpp:850]: nice find!

File: src/utilities/idf/IdfObject.cpp (hunk 2 above)
Comment (tijcolem) [reply src/utilities/idf/IdfObject.cpp]: so this was specific to ASHRAE9012016_OutPatientHealthCare_Denver.idf or just any idf with extensible fields. If the later I'm surprised this hasn't surfaced before. PR looks good to me and ready to merge.

**Review by tijcolem — APPROVED** [review]

File: src/utilities/idf/IdfObject.cpp (hunk 2 above)
Comment (jmarrec) [reply src/utilities/idf/IdfObject.cpp]: Any IDF with extensible fields **where the extensible group was truncated**. We rarely load plain IDF files (we're more into writing them), even less with Debug builds, so it hasn't surfaced before the epJSONTranslator test.
