### PR TITLE
Addresses #5214, EpwFile getTimeSeries fails for leap year weather file w/no leap day

### LINKED ISSUE #5214: EpwFile .getTimeSeries method fails if the weather file contains a leap year but only 28 days are given for that February
Issue overview
--------------
Related to #3801 

The EpwFile .getTimeSeries method fails when retrieving information from a weather file that contains a leap year but for which only 28 days of February data are provided.  Examples of such files are the CWEC 2020 weather files for [Toronto](https://github.com/NREL/openstudio-standards/blob/nrcan_data_test/data/weather/CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw) and [Vancouver](https://github.com/NREL/openstudio-standards/blob/nrcan_data_test/data/weather/CAN_BC_Vancouver.Intl.AP.718920_CWEC2020.epw).

In both of the above files, the data for February is from a leap year (2004 for Toronto, 2000 for Vancouver).  However, only 28 days of weather data for February are provided (no data for Feb. 29).

When using the EpwFile .getTimeSeries method to get dry bulb temperatures with such a file, the following error is produced:

``[utilities.time.Date] <2> Bad Date: year = 2009, month = Feb(2), day = 29.
C:/Users/Chris/projects/weather_test/weather_test.rb:6:in `getTimeSeries': D:\OSN\Openstudio\src\utilities\time\Date.cpp@382 : Bad Date: year = 2009, month = Feb(2), day = 29.  (RuntimeError)``

The problem does not occur if the year in the weather file for February is replaced with one that is not a leap year.  This issue is especially problematic in TMY weather files since it is not obvious if the February in the file will be from a leap year but will only include 28 days of data.

## Current Behavior
The following error:

``[utilities.time.Date] <2> Bad Date: year = 2009, month = Feb(2), day = 29.
C:/Users/Chris/projects/weather_test/weather_test.rb:6:in `getTimeSeries': D:\OSN\Openstudio\src\utilities\time\Date.cpp@382 : Bad Date: year = 2009, month = Feb(2), day = 29.  (RuntimeError)``

## Expected Behavior
Time series weather data should be returned.

## Steps to Reproduce
weather_file = 'path/to/CAN_ON_Toronto.Intl.AP.716240_CWEC2020.epw'
epw = OpenStudio::EpwFile.new(weather_file)
epw.getTimeSeries('Dry Bulb Temperature')

### Environment

Some additional details about your environment for this issue (if relevant):
- Platform (Operating system, version):  Windows 11, 22631.3672
- Version of OpenStudio (if using an intermediate build, include SHA): 3.8.0
- Platform (Operating system, version):  Ubuntu, 20.04
- Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0

### Context
Using the method to retrieve weather data to calculate PHIUS information.  This issue causes unpredictable errors when conducting analyses using a variety of TMY weather files as it is not always clear which weather file will contain leap years with only 28 days of data in February.  A replacement method is being implemented in openstudio-standards to replace this method until this issue is resolved.

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #5214

As far as I can tell, the `Bad Date: year = 2009, month = Feb(2), day = 29.` error is thrown for each of the following scenarios:
* AMY leap year missing 2/29 -- **This will just be considered a TMY** (file should contain Feb 29 for leap years...)
* TMY leap Feb w/out 2/29 -- **This is what the issue wants to support**
* TMY leap Feb with 2/29 -- **getTimeSeries will still fail** (the assumed 2009 year will be used, and so Feb 29 would never be supported...)

Possible solutions:
- [ ] optional `isActualOverride` bool supplied to `EpwFile::getTimeSeries` (demonstrated in this PR)
- [ ] increase the 1 day delta tolerance [here](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3917-L3923) so, e.g., Feb28 - Mar1 doesn't trigger
- [ ] specifically except the Feb28 - Mar1 1 day delta [here](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3917-L3923) for leap years
- [x] intercept loading of `m_data` to change xxxx-Feb-29 00:00:00 to xxxx-Mar-01 00:00:00 for TMY with leap Feb

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by joseph-robertson** [comment]
After a bit of digging, it appears that `realYear` (and therefore `epw.isActual`) gets set to `false` [here](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3917-L3923) since we have a delta greater than 1 day in the epw file. I'm assuming this works as intended for TMY where months jump years.

Therefore we fall into [this block](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3672-L3673) instead of [this one](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3670).

If `epw.isActual` were set to `true`, is the issue resolved here? If so, perhaps we could provide some type of override on `isActual` (either in the epw ctor, or as a setter somewhere)?

**Comment by joseph-robertson** [comment]
Possible solutions:
* optional `isActualOverride` bool supplied to `EpwFile::getTimeSeries` (demonstrated in this PR)
* increase the 1 day delta tolerance [here](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3917-L3923) so, e.g., Feb28 - Mar1 doesn't trigger
* specifically except the Feb28 - Mar1 1 day delta [here](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3917-L3923) for leap years

**Comment by joseph-robertson** [comment]
Ah ha, here's the core issue. For all 3 of the above scenarios, `m_data` has dateTimes that look like:
```
2012-Feb-28 20:00:00
2012-Feb-28 21:00:00
2012-Feb-28 22:00:00
2012-Feb-28 23:00:00
2012-Feb-29 00:00:00 => Bad Date: year = 2009, month = Feb(2), day = 29.
2012-Mar-01 01:00:00
2012-Mar-01 02:00:00
2012-Mar-01 03:00:00
2012-Mar-01 04:00:00
```
[This](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L3673) is the line that fails. The assumedYear in the Data ctor [here](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/time/Date.cpp#L185-L187) is 2009, and so fails on the line above.

Why doesn't the EpwDataPoint have a dateTime of `2012-Mar-01 00:00:00` instead of `2012-Feb-29 00:00:00`?

File: src/utilities/filetypes/EpwFile.cpp [hunk 1]
```diff
@@ -3967,6 +3974,31 @@ bool EpwFile::parse(std::istream& ifs, bool storeData) {
     }
   }
 
+  for (unsigned int i = 0; i < epw_strings.size(); i++) {
```
Comment (joseph-robertson) [inline src/utilities/filetypes/EpwFile.cpp:3977]: Do this after the previous loop, and not inside of it, because we first need to get `realYear`.

**Comment by ckirney** [comment]
The fix looks good.   I tried it on Windows with a couple of different weather files that had the issue before and everything seems to work.  Thanks for resolving this.

File: src/utilities/filetypes/EpwFile.cpp [hunk 2]
```diff
@@ -3887,6 +3887,17 @@ bool EpwFile::parse(std::istream& ifs, bool storeData) {
     return false;
   }
 
+  struct epw_string
+  {
+    int lineNumber;
```
Comment (kbenne) [inline src/utilities/filetypes/EpwFile.cpp:3892]: Perhaps these can be const based on your use case.

File: src/utilities/filetypes/EpwFile.cpp [hunk 3]
```diff
@@ -3887,6 +3887,17 @@ bool EpwFile::parse(std::istream& ifs, bool storeData) {
     return false;
   }
 
+  struct epw_string
```
Comment (kbenne) [inline src/utilities/filetypes/EpwFile.cpp:3890]: Since this is a type, wouldn't it be more aligned with our conventions to call it `EPWString`, or otherwise start with an uppercase letter?

File: src/utilities/filetypes/EpwFile.cpp [hunk 4]
```diff
@@ -3948,13 +3960,8 @@ bool EpwFile::parse(std::istream& ifs, bool storeData) {
...
           }
-          boost::optional<EpwDataPoint> pt = EpwDataPoint::fromEpwStrings(year, month, day, hour, currentMinute, strings);
-          if (pt) {
-            m_data.push_back(pt.get());
-          } else {
-            LOG(Error, "Failed to parse line " << lineNumber << " of EPW file '" << m_path << "'");
-            return false;
-          }
+          epw_string epw_s = {lineNumber, year, month, day, hour, currentMinute, strings};
+          epw_strings.push_back(epw_s);
```
Comment (kbenne) [inline src/utilities/filetypes/EpwFile.cpp:3964]: I think you could save a copy by doing the construction in place. `push_back` will perform move and save a copy. Here it doesn't matter that much because the copy is presumably super cheap. Something like this...

```
epw_strings.push_back({lineNumber, year, month, day, hour, currentMinute, strings});
```

File: src/utilities/filetypes/EpwFile.cpp (hunk 1 above)
Comment (kbenne) [inline src/utilities/filetypes/EpwFile.cpp:3977]: wouldn't 

```
for (const auto &epw_string: epw_strings) {
...
...
}
```

be a bit more modern? I don't believe you need the index, unless I missed it.

File: src/utilities/filetypes/EpwFile.cpp [hunk 5]
```diff
@@ -3967,6 +3974,31 @@ bool EpwFile::parse(std::istream& ifs, bool storeData) {
     }
   }
 
+  for (unsigned int i = 0; i < epw_strings.size(); i++) {
+    int year = epw_strings[i].year;
+    int month = epw_strings[i].month;
+    int day = epw_strings[i].day;
+    int hour = epw_strings[i].hour;
+    int currentMinute = epw_strings[i].currentMinute;
```
Comment (kbenne) [inline src/utilities/filetypes/EpwFile.cpp:3982]: Making these copies seems superfluous. Perhaps you could just use `epw_string.currentMinute` when you need to access these members. At minimum they could be const.

File: src/utilities/filetypes/EpwFile.cpp [hunk 6]
```diff
@@ -3967,6 +3974,31 @@ bool EpwFile::parse(std::istream& ifs, bool storeData) {
...
+    if ((!realYear) && (month == 2) && (day == 28) && (hour == 24) && (currentMinute == 0)) {
+      Date date(month, day, year);
+      if (date.isLeapYear()) {
+        day = 29;
+      }
+    }
+
+    boost::optional<EpwDataPoint> pt = EpwDataPoint::fromEpwStrings(year, month, day, hour, currentMinute, epw_strings[i].strings);
+    if (pt) {
+      m_data.push_back(pt.get());
```
Comment (kbenne) [inline src/utilities/filetypes/EpwFile.cpp:3995]: Here the temporary `pt` makes sense to me since you have the `push_back` protected by a conditional.

**Review by kbenne — APPROVED** [review]
Hey @joseph-robertson. I left a few pedantic comments about coding nitpicks. You can take them or leave them.

I like the additional unit test coverage, otherwise I'd have a hard time knowing for sure that the approach works.

File: src/utilities/filetypes/EpwFile.cpp (hunk 3 above)
Comment (joseph-robertson) [reply src/utilities/filetypes/EpwFile.cpp]: Changed `epw_string` to `EPWString`.

File: src/utilities/filetypes/EpwFile.cpp (hunk 2 above)
Comment (joseph-robertson) [reply src/utilities/filetypes/EpwFile.cpp]: Changed `int` to `const int`.

File: src/utilities/filetypes/EpwFile.cpp (hunk 6 above)
Comment (joseph-robertson) [reply src/utilities/filetypes/EpwFile.cpp:3990]: No action.

File: src/utilities/filetypes/EpwFile.cpp (hunk 5 above)
Comment (joseph-robertson) [reply src/utilities/filetypes/EpwFile.cpp]: Moving all `epw_string.month`, `epw_string.day`, etc to where they are used below.

File: src/utilities/filetypes/EpwFile.cpp (hunk 6 above)
Comment (jmarrec) [reply src/utilities/filetypes/EpwFile.cpp:3991]: `m_data.emplace_back(std::move(*pt))`

File: src/utilities/filetypes/EpwFile.cpp (hunk 4 above)
Comment (jmarrec) [reply src/utilities/filetypes/EpwFile.cpp]: ` epw_strings.emplace_back(lineNumber, year, month, day, hour, currentMinute, std::move(strings));`

Comment (jmarrec) [reply src/utilities/filetypes/EpwFile.cpp]: A benchmark: https://github.com/jmarrec/CppBenchmarks/blob/main/bench_EPWStrings.cpp

image

Comment (jmarrec) [reply src/utilities/filetypes/EpwFile.cpp]: The full range:

image
