### PR TITLE
4438 gbxml export

### LINKED ISSUE #4438: gbXML export is not reproducible
Issue overview
--------------
Objects export order is not reproducible in the gbXML ForwardTranslator.  The ForwardTranslator should sort objects to ensure the export is reproducible.

## Current Behavior
Objects are exported in non-reproducible order.

## Expected Behavior
Objects are exported in reproducible order.

## Steps to Reproduce
Create an OSM model via a script, export to gbXML.  Repeat, exported gbXML is not in same order.  This is especially problematic for interior floor/ceilings as sometimes the floor is exported and sometimes the ceiling is.  Sorting by surface type would ensure that interior floors are always exported (the interior ceiling would be listed as the adjacent surface).

## Possible Solution
Sort all objects when doing gbXML export.  Need to sort surfaces by surface type (Wall, Roof, Floor, etc) first.  Need to figure out sorting criteria for each objects (probably want to sort spaces by story or min z coord, then maybe min x and min y coords, then name)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context
Topologic Energy uses OpenStudio's gbXML export, this issue causes confusion and possible wrong results when the results imported into other tools such as Spider Aragog gbXML Viewer.  

Reported by @wassimj at https://unmethours.slack.com/archives/C0ADY1ZRB/p1631800632015300

### PR DESCRIPTION
**Pull request by ggartside**
Pull request overview
---------------------

 - Fixes #4438 

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/Model.cpp [hunk 1]
```diff
@@ -1518,7 +1518,13 @@ namespace model {
     buildingStory.setNominalFloortoFloorHeight(3);
 
     // create spaces from floor print
-
+    // GG 10/26/21 - Change the spac egeneration to use fromFloorPrint instead of using Clone
```
Comment (macumber) [inline src/model/Model.cpp:1521]: Clone would give each object a new unique UUID handle but that should not matter if you are properly sorting the surfaces by name.  Another good test would be to write the model to file and re-read it back in, that is a typical use case.

File: src/model/Model.cpp [hunk 2]
```diff
@@ -1548,18 +1554,24 @@ namespace model {
     space1->setThermalZone(thermalZone);
     space1->setBuildingStory(buildingStory);
 
-    ModelObject clone = space1->clone(model);
```
Comment (macumber) [inline src/model/Model.cpp:1551]: Oh I see, this probably wasn't deterministic because clone isn't deterministic.  You could make clone sort the children to fix that:

https://github.com/NREL/OpenStudio/blob/develop/src/model/ParentObject.cpp#L106

File: src/model/Model.cpp (hunk 1 above)
Comment (ggartside) [reply src/model/Model.cpp:1521]: I think what I was trying to do here was create what I know to be identical models in OpenStudio and export them to gbxml and then using an external file comparison verified that the files are identical. When I used Clone the order of the surfaces came back different each time so the files would never be the same (i.e. for example Surface 5 in one model was a floor and in the other model a ceiling) so I used fromfloorPrint to generate the spaces instead.

File: src/model/Model.cpp (hunk 2 above)
Comment (ggartside) [reply src/model/Model.cpp:1551]: See my above comment - would sorting fix the issue I was addressing? Namlelt that creating the export model twice did not produce identical models?

Comment (macumber) [reply src/model/Model.cpp:1551]: Yes sorting the result of children in ParentObject_Impl::clone should go a long way towards making the models identical.  The objects will have different UUIDs so the models won't be completely identical.

**Comment by tijcolem** [comment]
@macumber @ggartside Looks like this is good to go?

**Comment by macumber** [comment]
I don't know if @ggartside plans to update `ParentObject_Impl::clone` to sort children or not.  If so, some of the changes to `Model::exampleModel` could be reverted

File: src/model/Model.cpp (hunk 2 above)
Comment (ggartside) [reply src/model/Model.cpp:1551]: I don't know much about the clone itself but that seems to imply that children() doesn't return a specific order of children each time it is called? Its not just that they are coming back in a different order each time clone is called the surfaces are different, for example the first time clone is called I get this

image

and the second time I get this

image

(screenshots are comparing the two xml files)

Comment (ggartside) [reply src/model/Model.cpp:1551]: I think my best course of action is to create my own simpler variant of exampleModel specifically for my test

**Comment by ggartside** [comment]
> 

No - I created a method that creates a simple model that can be used for my test, I reverted exampleModel back to its original incarnation
