### PR TITLE
Fix glass U factor sql error

### LINKED ISSUE #4678: Glass U Factor sql error
Issue overview
--------------
User on Unmet Hours hits an error when using `window.uFactor`. Reported at https://unmethours.com/question/80413/problem-in-openstudio-measure-in-34/.

Looks like a closing single quotation mark is missing from all these sql statements:
https://github.com/NREL/OpenStudio/blob/135d27832ebee5682c545a2a6f507e25e0cffa40/src/model/SubSurface.cpp#L377
https://github.com/NREL/OpenStudio/blob/135d27832ebee5682c545a2a6f507e25e0cffa40/src/model/SubSurface.cpp#L450
https://github.com/NREL/OpenStudio/blob/d75af8b9309517294089066e6a5b3c0373d43d9e/src/model/Surface.cpp#L659
https://github.com/NREL/OpenStudio/blob/d75af8b9309517294089066e6a5b3c0373d43d9e/src/model/Surface.cpp#L732

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4678
 - [x] Write test(s)

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/SubSurface.cpp [hunk 1]
```diff
@@ -338,48 +338,30 @@ namespace model {
...
-            outputResult = sqlFile->execAndReturnFirstDouble(query, *rowId);
-          }
+          std::string query = R"(SELECT Value from TabularDataWithStrings
+                                    WHERE ReportName = 'EnvelopeSummary'
+                                      AND ReportForString = 'Entire Facility'
+                                      AND TableName = 'Opaque Exterior'
+                                      AND ColumnName = 'U-Factor with Film'
+                                      AND Units='W/m2-K'
+                                      AND RowName = ?;)";
+          outputResult = sqlFile->execAndReturnFirstDouble(query, to_upper_copy(*subSurfaceName));
```
Comment (jmarrec) [inline src/model/SubSurface.cpp:352]: :+1: smart!

File: src/model/test/Surface_GTest.cpp [hunk 2]
```diff
@@ -3798,3 +3800,40 @@ TEST_F(ModelFixture, Issue_4374) {
...
+  OptionalConstructionBase oConstruction = surface->construction();
+
+  ASSERT_TRUE(oConstruction);
+
+  EXPECT_TRUE(oConstruction->isOpaque());
+  EXPECT_FALSE(oConstruction->isFenestration());
+
+  ASSERT_TRUE(surface->uFactor());
+  double uFactor = surface->uFactor().get();
+  EXPECT_TRUE(openstudio::equal(0.310, uFactor, 1.0E-3));
```
Comment (jmarrec) [inline src/model/test/Surface_GTest.cpp:3834]: `EXPECT_DOUBLE_EQ(val1, val2)` is meant for this, and will report a nicer output in case it fails. 

> Verifies that the two double values val1 and val2 are approximately equal, to within 4 ULPs from each other.

If you need a specific tolerance (I don't think you do), then use `EXPECT_NEAR(val1, val2, abs_error)`

File: src/model/test/Surface_GTest.cpp [hunk 3]
```diff
@@ -3798,3 +3800,40 @@ TEST_F(ModelFixture, Issue_4374) {
...
+
+  ASSERT_TRUE(surface->thermalConductance());
+  double thermalConductance = surface->thermalConductance().get();
+  EXPECT_TRUE(openstudio::equal(0.325, thermalConductance, 1.0E-3));
```
Comment (jmarrec) [inline src/model/test/Surface_GTest.cpp:3838]:
```suggestion
  EXPECT_DOUBLE_EQ(0.310, uFactor);

  ASSERT_TRUE(surface->thermalConductance());
  double thermalConductance = surface->thermalConductance().get();
  EXPECT_DOUBLE_EQ(0.325, thermalConductance);
```

**Review by jmarrec — APPROVED** [review]
