### PR TITLE
Incorrect FT of ScheduleRules at end of year

### LINKED ISSUE #5113: Incorrect FT of ScheduleRules at end of year
Issue overview
--------------
Weird FT behavior of schedule rules toward the end of Dec.

## Current Behavior
```
OS:Schedule:Ruleset,
  {127e075e-6d4e-4ec9-a59c-e0ba335d2e70}, !- Handle
  misc plug loads schedule,               !- Name
  {eb9cb2c8-1bc5-48fa-8361-44ae5de4fb82}, !- Schedule Type Limits Name
  {353df2d7-6659-4fc9-8b3f-a0625b330ac1}; !- Default Day Schedule Name

OS:Schedule:Day,
  {353df2d7-6659-4fc9-8b3f-a0625b330ac1}, !- Handle
  misc plug loads schedule default day,   !- Name
  {eb9cb2c8-1bc5-48fa-8361-44ae5de4fb82}, !- Schedule Type Limits Name
  ,                                       !- Interpolate to Timestep
  24,                                     !- Hour 1
  0,                                      !- Minute 1
  0;                                      !- Value Until Time 1

OS:Schedule:Rule,
  {2f4abaf7-89ad-4428-a12a-07009bb61b01}, !- Handle
  misc plug loads schedule allday ruleset1, !- Name
  {127e075e-6d4e-4ec9-a59c-e0ba335d2e70}, !- Schedule Ruleset Name
  1,                                      !- Rule Order
  {63fee88c-dd9c-4c7d-9973-b0e6fabb8ac5}, !- Day Schedule Name
  Yes,                                    !- Apply Sunday
  Yes,                                    !- Apply Monday
  Yes,                                    !- Apply Tuesday
  Yes,                                    !- Apply Wednesday
  Yes,                                    !- Apply Thursday
  Yes,                                    !- Apply Friday
  Yes,                                    !- Apply Saturday
  DateRange,                              !- Date Specification Type
  1,                                      !- Start Month
  1,                                      !- Start Day
  12,                                     !- End Month
  31;                                     !- End Day

OS:Schedule:Day,
  {63fee88c-dd9c-4c7d-9973-b0e6fabb8ac5}, !- Handle
  misc plug loads schedule allday1,       !- Name
  {eb9cb2c8-1bc5-48fa-8361-44ae5de4fb82}, !- Schedule Type Limits Name
  ,                                       !- Interpolate to Timestep
  6,                                      !- Hour 1
  0,                                      !- Minute 1
  0.705882352941177,                      !- Value Until Time 1
  7,                                      !- Hour 2
  0,                                      !- Minute 2
  0.745098039215686,                      !- Value Until Time 2
  8,                                      !- Hour 3
  0,                                      !- Minute 3
  0.803921568627451,                      !- Value Until Time 3
  15,                                     !- Hour 4
  0,                                      !- Minute 4
  0.823529411764706,                      !- Value Until Time 4
  16,                                     !- Hour 5
  0,                                      !- Minute 5
  0.862745098039216,                      !- Value Until Time 5
  17,                                     !- Hour 6
  0,                                      !- Minute 6
  0.92156862745098,                       !- Value Until Time 6
  18,                                     !- Hour 7
  0,                                      !- Minute 7
  0.980392156862745,                      !- Value Until Time 7
  19,                                     !- Hour 8
  0,                                      !- Minute 8
  1,                                      !- Value Until Time 8
  20,                                     !- Hour 9
  0,                                      !- Minute 9
  0.980392156862745,                      !- Value Until Time 9
  21,                                     !- Hour 10
  0,                                      !- Minute 10
  0.941176470588235,                      !- Value Until Time 10
  22,                                     !- Hour 11
  0,                                      !- Minute 11
  0.862745098039216,                      !- Value Until Time 11
  23,                                     !- Hour 12
  0,                                      !- Minute 12
  0.784313725490196,                      !- Value Until Time 12
  24,                                     !- Hour 13
  0,                                      !- Minute 13
  0.725490196078431;                      !- Value Until Time 13

OS:Schedule:Rule,
  {f5b6c5db-0e91-451d-bb44-428e6b87360a}, !- Handle
  misc plug loads schedule unavailable period ruleset0, !- Name
  {127e075e-6d4e-4ec9-a59c-e0ba335d2e70}, !- Schedule Ruleset Name
  0,                                      !- Rule Order
  {8c0a1ef9-2183-48fb-873f-faead3507a89}, !- Day Schedule Name
  Yes,                                    !- Apply Sunday
  Yes,                                    !- Apply Monday
  Yes,                                    !- Apply Tuesday
  Yes,                                    !- Apply Wednesday
  Yes,                                    !- Apply Thursday
  Yes,                                    !- Apply Friday
  Yes,                                    !- Apply Saturday
  DateRange,                              !- Date Specification Type
  12,                                     !- Start Month
  15,                                     !- Start Day
  12,                                     !- End Month
  21;                                     !- End Day

OS:Schedule:Day,
  {8c0a1ef9-2183-48fb-873f-faead3507a89}, !- Handle
  misc plug loads schedule unavailable period0, !- Name
  {eb9cb2c8-1bc5-48fa-8361-44ae5de4fb82}, !- Schedule Type Limits Name
  ,                                       !- Interpolate to Timestep
  24,                                     !- Hour 1
  0,                                      !- Minute 1
  0;                                      !- Value Until Time 1
```

FTs to

```
Schedule:Week:Daily,
  misc plug loads schedule Week Rule - Dec10-Dec16, !- Name
  misc plug loads schedule allday1,       !- Sunday Schedule:Day Name
  misc plug loads schedule allday1,       !- Monday Schedule:Day Name
  misc plug loads schedule allday1,       !- Tuesday Schedule:Day Name
  misc plug loads schedule allday1,       !- Wednesday Schedule:Day Name
  misc plug loads schedule allday1,       !- Thursday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Friday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Saturday Schedule:Day Name
  misc plug loads schedule default day,   !- Holiday Schedule:Day Name
  misc plug loads schedule default day,   !- SummerDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- WinterDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- CustomDay1 Schedule:Day Name
  misc plug loads schedule default day;   !- CustomDay2 Schedule:Day Name

Schedule:Week:Daily,
  misc plug loads schedule Week Rule - Dec17-Dec23, !- Name
  misc plug loads schedule unavailable period0, !- Sunday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Monday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Tuesday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Wednesday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Thursday Schedule:Day Name
  misc plug loads schedule allday1,       !- Friday Schedule:Day Name
  misc plug loads schedule allday1,       !- Saturday Schedule:Day Name
  misc plug loads schedule default day,   !- Holiday Schedule:Day Name
  misc plug loads schedule default day,   !- SummerDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- WinterDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- CustomDay1 Schedule:Day Name
  misc plug loads schedule default day;   !- CustomDay2 Schedule:Day Name

Schedule:Week:Daily,
  misc plug loads schedule Week Rule - Dec24-Dec30, !- Name
  misc plug loads schedule unavailable period0, !- Sunday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Monday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Tuesday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Wednesday Schedule:Day Name
  misc plug loads schedule unavailable period0, !- Thursday Schedule:Day Name
  misc plug loads schedule allday1,       !- Friday Schedule:Day Name
  misc plug loads schedule allday1,       !- Saturday Schedule:Day Name
  misc plug loads schedule default day,   !- Holiday Schedule:Day Name
  misc plug loads schedule default day,   !- SummerDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- WinterDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- CustomDay1 Schedule:Day Name
  misc plug loads schedule default day;   !- CustomDay2 Schedule:Day Name

Schedule:Week:Daily,
  misc plug loads schedule Week Rule - Dec31-Dec31, !- Name
  misc plug loads schedule allday1,       !- Sunday Schedule:Day Name
  misc plug loads schedule allday1,       !- Monday Schedule:Day Name
  misc plug loads schedule allday1,       !- Tuesday Schedule:Day Name
  misc plug loads schedule allday1,       !- Wednesday Schedule:Day Name
  misc plug loads schedule allday1,       !- Thursday Schedule:Day Name
  misc plug loads schedule allday1,       !- Friday Schedule:Day Name
  misc plug loads schedule allday1,       !- Saturday Schedule:Day Name
  misc plug loads schedule default day,   !- Holiday Schedule:Day Name
  misc plug loads schedule default day,   !- SummerDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- WinterDesignDay Schedule:Day Name
  misc plug loads schedule default day,   !- CustomDay1 Schedule:Day Name
  misc plug loads schedule default day;   !- CustomDay2 Schedule:Day Name
```

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #5113.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/ForwardTranslator/ForwardTranslateScheduleRuleset.cpp [hunk 1]
```diff
@@ -283,11 +283,14 @@ namespace energyplus {
         if (date == dec31) {
 
           // we may now think of date as being the next saturday on or after 12/31
+          // we may need 2 more week schedules:
+          // 1 if the week that includes 12/31 is the same as the last week schedule
+          // 2 if the week that includes 12/31 is different from the last week schedule
 
           // set last week schedule before we overwrite week schedule
-          lastDate = date - Time(1);
-          while (lastDate.dayOfWeek().value() != DayOfWeek::Saturday) {
```
Comment (joseph-robertson) [inline src/energyplus/ForwardTranslator/ForwardTranslateScheduleRuleset.cpp:289]: I'm fairly certain that this bug is relevant for simulations whose year ends on a Sunday. The `lastDate = date - Time(1)` line here makes `lastDate` a Saturday, and so we don't enter this `while` block.

**Review by jmarrec — APPROVED** [review]
From a cursory look this looks sensible, and there are tests for it too. Looks good to me.
