### PR TITLE
adding fix and test for oas removal when doas is removed

### LINKED ISSUE #4539: When removing an AirLoopHVAC:DedicatedOutdoorAirSystem, also remove the associated OutdoorAirSystem
Enhancement Request
--------------
Reimplement `remove` for AirLoopHVAC:DedicatedOutdoorAirSystem to also remove the associated AirLoopHVAC:OutdoorAirSystem

## Detailed Description
Currently, if I call `remove` on an AirLoopHVAC:DedicatedOutdoorAirSystem, only the object is removed, but the associated OutdoorAirSystem (and any coils/fans/setpointmanagers on that system) remain in the model: 

```
m = Model.new
# build the DOAS
oas = AirLoopHVACOutdoorAirSystem.new(m, ControllerOutdoorAir.new(m))
doas = AirLoopHVACDedicatedOutdoorAirSystem.new(oas)
h = CoilHeatingElectric.new(m)
f = FanSystemModel.new(m)
f.addToNode(oas.outboardOANode.get)
h.addToNode(oas.outboardOANode.get)
spm = SetpointManagerOutdoorAirReset.new(m)
spm.addToNode(h.outletModelObject.get.to_Node.get)

# remove the DOAS
m.getAirLoopHVACDedicatedOutdoorAirSystems.each(&:remove)
puts m
```

Most of what's left is not forward translated, _except the SetpointManager_, which will cause EnergyPlus to fail because the referenced setpoint node doesn't exist:

```
ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)
puts ws
=>
...other stuff...
SetpointManager:OutdoorAirReset,
  Setpoint Manager Outdoor Air Reset 1,   !- Name
  Temperature,                            !- Control Variable
  22,                                     !- Setpoint at Outdoor Low Temperature {C}
  10,                                     !- Outdoor Low Temperature {C}
  10,                                     !- Setpoint at Outdoor High Temperature {C}
  24,                                     !- Outdoor High Temperature {C}
  Node 4;                                 !- Setpoint Node or NodeList Name
...other stuff...
```

Since the AirLoopHVAC:OutdoorAirSystem only exists for the DOAS, it should be removed with the DOAS.

### PR DESCRIPTION
**Pull request by kflemin**
Pull request overview
---------------------

 - Fixes #4539 

Deletes AirLoopHVAC:OutdoorAirSystem when the AirLoopHVAC:DedicatedOutdoorAirSystem is removed so as not to leave extra pieces to get translated that will crash EnergyPlus

Testing script:

```bash
require 'openstudio'
m = OpenStudio::Model::Model.new
# build the DOAS
oas = OpenStudio::Model::AirLoopHVACOutdoorAirSystem.new(m, OpenStudio::Model::ControllerOutdoorAir.new(m))
doas = OpenStudio::Model::AirLoopHVACDedicatedOutdoorAirSystem.new(oas)
h = OpenStudio::Model::CoilHeatingElectric.new(m)
f = OpenStudio::Model::FanSystemModel.new(m)
f.addToNode(oas.outboardOANode.get)
h.addToNode(oas.outboardOANode.get)
spm = OpenStudio::Model::SetpointManagerOutdoorAirReset.new(m)
spm.addToNode(h.outletModelObject.get.to_Node.get)

# remove the DOAS
m.getAirLoopHVACDedicatedOutdoorAirSystems.each(&:remove)
puts m
```

before the fix, a setpoint manager would get translated:
```
...other stuff...
SetpointManager:OutdoorAirReset,
  Setpoint Manager Outdoor Air Reset 1,   !- Name
  Temperature,                            !- Control Variable
  22,                                     !- Setpoint at Outdoor Low Temperature {C}
  10,                                     !- Outdoor Low Temperature {C}
  10,                                     !- Setpoint at Outdoor High Temperature {C}
  24,                                     !- Outdoor High Temperature {C}
  Node 4;                                 !- Setpoint Node or NodeList Name
...other stuff...
```
After the fix, there is no longer this object.

### Pull Request Author

 - [x ] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] All new and existing tests passes

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/AirLoopHVACDedicatedOutdoorAirSystem.hpp [hunk 1]
```diff
@@ -112,6 +112,8 @@ namespace model {
 
     void removeAllAirLoops();
 
+    virtual std::vector<openstudio::IdfObject> remove();
+
```
Comment (jmarrec) [inline src/model/AirLoopHVACDedicatedOutdoorAirSystem.hpp:116]:
```suggestion
```

File: src/model/AirLoopHVACDedicatedOutdoorAirSystem.cpp [hunk 2]
```diff
@@ -378,6 +385,10 @@ namespace model {
     getImpl<detail::AirLoopHVACDedicatedOutdoorAirSystem_Impl>()->removeAllAirLoops();
   }
 
+  std::vector<IdfObject> AirLoopHVACDedicatedOutdoorAirSystem::remove() {
+    return getImpl<detail::AirLoopHVACDedicatedOutdoorAirSystem_Impl>()->remove();
+  }
+
```
Comment (jmarrec) [inline src/model/AirLoopHVACDedicatedOutdoorAirSystem.cpp:391]:
```suggestion
```

The public side remove() is already defined in WorkspaceObject and forwards to the Impl, which is virtual, so no need to define it in the public class.

**Review by jmarrec — CHANGES_REQUESTED** [review]
