### PR TITLE
Fix #5544 - Do not Warn about adding a GenericModelObject for CommentOnly

### LINKED ISSUE #5544: Should not Warn when loading a model that has comments
### Description

‘Creating GenericModelObject for IddObjectType 'CommentOnly’.

### Current Behavior

It warns

### Expected Behavior

It shouldn't warn. This is expected behavior

### Steps to reproduce

```ruby
m = Model.new

i = OpenStudio::IdfObject.new('CommentOnly'.to_IddObjectType)
i.setComment("This is a (free) comment")
m.addObject(i)

[openstudio.model.Model] <0> Creating GenericModelObject for IddObjectType 'CommentOnly'.

puts m
```

### Possible Solution

Protect here: https://github.com/NREL/OpenStudio/blob/887ed96f7135b1fbc44744806b942fbbcd809db4/src/model/Model.cpp#L155-L164

### Operating System affected

All

### Environment

All

### Version of OpenStudio

3.11.0-rc1

### Context

https://unmethours.com/question/102854/error-creating-genericmodelobject-for-iddobjecttype-commentonly/?answer=102934#post-id-102934

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fix #5544
 - Do not Warn about adding a GenericModelObject for CommentOnly

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/Model_GTest.cpp [hunk 1]
```diff
@@ -1203,3 +1204,15 @@ TEST_F(ModelFixture, Model_load) {
...
+TEST_F(ModelFixture, Model_nowarn_GenericModelObject_CommentOnly) {
+  // Test for #5544
+  Model m;
+  openstudio::IdfObject i(openstudio::IddObjectType::CommentOnly);
+  i.setComment("This is a (free) comment");
+
+  StringStreamLogSink sink;
+  sink.setLogLevel(Warn);
+  EXPECT_TRUE(m.addObject(i));
+  EXPECT_EQ(0, sink.logMessages().size()) << "Expected zero log messages but found " << sink.logMessages().size() << ": " << sink.string();
```
Comment (jmarrec) [inline src/model/test/Model_GTest.cpp:1217]: Before fix there is 1 Warning

```
[ RUN      ] ModelFixture.Model_nowarn_GenericModelObject_CommentOnly
/Users/julien/Software/Others/OpenStudio/src/model/test/Model_GTest.cpp:1217: Failure
Expected equality of these values:
  0
  sink.logMessages().size()
    Which is: 1
Expected zero log messages but found 1: [openstudio.model.Model] <0> Creating GenericModelObject for IddObjectType 'CommentOnly'.
```

File: src/model/Model.cpp [hunk 2]
```diff
@@ -156,7 +156,9 @@ namespace model {
       auto result = modelObjectCreator.getNew(this, object, keepHandle);
 
       if (!result) {
-        LOG(Warn, "Creating GenericModelObject for IddObjectType '" << object.iddObject().type().valueName() << "'.");
+        if (object.iddObject().type().value() != IddObjectType::CommentOnly) {
+          LOG(Warn, "Creating GenericModelObject for IddObjectType '" << object.iddObject().type().valueName() << "'.");
+        }
```
Comment (jmarrec) [inline src/model/Model.cpp:161]: Protect the Warn
