### PR TITLE
Fix a problem in reading "Interval" from E+ Time sql table when reporting two meters at various frequencies

### LINKED ISSUE #3947: Calibration measure failure when reading timeseries
Issue overview
--------------

This issue was reported by @brianlball on slack. The Calibration measure with 3.0.0 fails with messages such as 

```
[utilities.TimeSeries_Impl] <-2> Initial: dateTime=2013-Mar-02 00:00:00, m_firstReportDateTime=2013-Jan-01 01:00:00
[utilities.TimeSeries_Impl] <-2> Querying with dateTimeWithYear=2013-Mar-02 00:00:00, firstReportDateTimeWithYear=2013-Jan-01 01:00:00
[utilities.TimeSeries_Impl] <-2> Cannot compute value 5180400 seconds after first reporting time when duration is 1310400 seconds
```

It used to work on 2.9.1, which seems to imply a change in OpenStudio or EnergyPlus (2.9.1 was on E+ 9.2.0, 3.0.0 is on E+ 9.3.0)

## Steps to Reproduce

I'm creating this issue post-mortem after having fixed it, but the bottom line is that you need an OSM with the same Meter Key but with two reporting frequencies:

```
Output:Meter:MeterFileOnly,
  Electricity:Facility,                   !- Key Name
  Timestep;                               !- Reporting Frequency

Output:Meter:MeterFileOnly,
  Electricity:Facility,                   !- Key Name
  Daily;                                  !- Reporting Frequency
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.0-rc2

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3947
 - If you request the same meter such as 'Electricity:Facility' as both 'Timestep' and 'Daily' reporting frequencies, E+ will report a TimeIndex that lists the 'Interval' as 60 minutes instead of 24*60=1440. So compute that directly.

This is similar to https://github.com/NREL/OpenStudio/issues/1692.

And the E+ side was reported as https://github.com/NREL/EnergyPlus/issues/7922 but it is not a regression (E+ 9.2.0 did exactly the same), and I expect it may be wanted behavior.

I changed something that was added in #3878 too

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/sql/SqlFile_Impl.cpp [hunk 1]
```diff
@@ -2504,18 +2504,29 @@ namespace openstudio{
 
           unsigned month = sqlite3_column_int(sqlStmtPtr, b++);
           unsigned day = sqlite3_column_int(sqlStmtPtr, b++);
-          unsigned intervalMinutes = sqlite3_column_int(sqlStmtPtr, b++); // used for run periods
-          if (reportingFrequency == ReportingFrequency::Annual){
-            intervalMinutes = 8760; // used for annual periods
```
Comment (jmarrec) [inline src/utilities/sql/SqlFile_Impl.cpp:2509]: https://github.com/NREL/OpenStudio/pull/3878#pullrequestreview-392115730

File: src/utilities/sql/SqlFile_Impl.cpp [hunk 2]
```diff
@@ -2504,18 +2504,29 @@ namespace openstudio{
...
+          } else if (reportingFrequency == ReportingFrequency::Daily) {
+            intervalMinutes = 24 * 60;
+          } else if (reportingFrequency == ReportingFrequency::Monthly) {
+            intervalMinutes = day * 24 * 60;
+          } else {
+            // If Detailed, Timestep, RunPeriod, or Annual: it varies
+            intervalMinutes = sqlite3_column_int(sqlStmtPtr, b++); // used for run periods
+            if ((reportingFrequency == ReportingFrequency::Annual) &&
+                !((intervalMinutes == 365*24*60) || (intervalMinutes != 366*24*60))) {
+              LOG(Error, "For an 'Annual' frequency, expected intervalMinutes to correspond to 365 or 366 days");
```
Comment (jmarrec) [inline src/utilities/sql/SqlFile_Impl.cpp:2523]: https://github.com/NREL/OpenStudio/pull/3878#pullrequestreview-392115730

For Annual, it can vary (Leap year), but should corresponding to either 365 (8760 hours * 60 minutes)  or 366 days.

File: src/utilities/sql/SqlFile_Impl.cpp [hunk 3]
```diff
@@ -2504,18 +2504,29 @@ namespace openstudio{
...
+          // the intervalMinutes will be reported by E+ for the Timestep one, so you get the wrong one for Daily...
+          // And since we can compute this easily, might as well do it
+          unsigned intervalMinutes;
+          if (reportingFrequency == ReportingFrequency::Hourly) {
+            intervalMinutes = 60;
+          } else if (reportingFrequency == ReportingFrequency::Daily) {
+            intervalMinutes = 24 * 60;
+          } else if (reportingFrequency == ReportingFrequency::Monthly) {
+            intervalMinutes = day * 24 * 60;
+          } else {
```
Comment (jmarrec) [inline src/utilities/sql/SqlFile_Impl.cpp:2518]: For fixed-length reporting frequencies, just calculate it instead of querying the Sql which could be wrong.

**Comment by jmarrec** [comment]
I'm changing the base branch to "develop" or CI won't build this one, but it must go into `3.0.0-rc2` instead I think. @tijcolem FYI
