### PR TITLE
#3917 - Properly disallow connecting two ThermalZones in Series on an AirLoopHVAC demand branch

### LINKED ISSUE #3917: Connecting two ThermalZones in series on an AirLoopHVAC demand branch shouldn't be allowed
Issue overview
--------------

Reported in https://unmethours.com/question/43320/thermal-zones-in-series/

## Current Behavior

It's possible to add two thermal zones in series.

## Expected Behavior

It should be disallowed.

## Steps to Reproduce

Open OpenStudioApplication, create a couple of ThermalZones, add a template airloopHVAC, then connect two zones one after another.

image

You end up with this (two duplicated branches):

image

Worse, try to delete one zone, and you end up with an empty demand side:

image

## Possible Solution

https://github.com/NREL/OpenStudio/blob/9fcb8418a56cce41cbff51c28c0aa45af9ea32f7/src/model/ThermalZone.cpp#L2078

When you try to connect above, the inlet isn't a thermal zone... it's a node, but that node is connected to a thermal zone...

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): current develop (9fcb8418a56cce41cbff51c28c0aa45af9ea32f7, circa OS 3.0)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3917
 - Properly disallow connecting two ThermalZones in parallel on an AirLoopHVAC demand branch

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [x] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [x] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
Checked behavior via model GTest, and in OpenStudioApplication as well.

File: src/model/test/ThermalZone_GTest.cpp [hunk 1]
```diff
@@ -761,3 +762,69 @@ TEST_F(ModelFixture, ThermalZone_ZoneControlHumidistat)
...
+  AirTerminalSingleDuctConstantVolumeNoReheat atu(m,s);
+
+  AirLoopHVACZoneMixer mixer = a.zoneMixer();
+  AirLoopHVACZoneSplitter splitter = a.zoneSplitter();
+
+  EXPECT_EQ(5u, a.demandComponents().size());
+
+  EXPECT_TRUE(a.addBranchForHVACComponent(atu));
+  EXPECT_EQ(7u, a.demandComponents().size());
+
```
Comment (kbenne) [inline src/model/test/ThermalZone_GTest.cpp]: Wow. What a comment.

File: src/model/test/ThermalZone_GTest.cpp [hunk 2]
```diff
@@ -761,3 +762,69 @@ TEST_F(ModelFixture, ThermalZone_ZoneControlHumidistat)
...
+  // 9 components:
+  // Inlet -- (Mixer) -- Node ----- ATU ----- Node ---- ThermalZone ----- Node ----- (SPlitter) -------- OutletNode
+
+  //            -----o-----ATU-----o-----TZ-----o-----
+  // -----o-----|                                    |-----o------
```
Comment (jmarrec) [inline src/model/test/ThermalZone_GTest.cpp]: You mean this comment @kbenne I think
