### PR TITLE
Issue 4288 demand side vrf

### LINKED ISSUE #4288: VRF Terminal Unit supply fan not translated if connected to AirTerminal:SingleDuct:Mixer
Issue overview
--------------
@jmarrec 

The change [here ](https://github.com/NREL/OpenStudio/blame/develop/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACTerminalUnitVariableRefrigerantFlow.cpp#L289-L299)to support adding VRF Terminals to the supply branch of an AirLoopHVAC appears to have the unintended side effect of not translating the terminal supply fan if the terminal is connected to the _demand_ side of an air loop with an AirTerminal:SingleDuct:Mixer. This will cause EnergyPlus to fail with 
```
   ** Severe  ** ZoneHVAC:TerminalUnit:VariableRefrigerantFlow = TZ_2_AVENUE VRF TERMINAL
   **   ~~~   ** Illegal Supply Air Fan Placement.
```
☹️ 

## Current Behavior
If a VRF terminal unit is connected to an AirLoopHVAC on the demand side, and that AirLoopHVAC has a supply fan (as is typical), the terminal unit fan won't translate. 

See steps to reproduce.

## Expected Behavior
A VRF Terminal unit on the demand side of an AirLoopHVAC should keep its supply fan. 

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
# create air loop with fan on supply branch
ahu = AirLoopHVAC.new(m)
fan = FanSystemModel.new(m)
fan.addToNode(ahu.supplyInletNode)

#create inlet side mixer and add to ahu
at = AirTerminalSingleDuctInletSideMixer.new(m)
ahu.addBranchForZone(ThermalZone.new(m), at)

# create VRF terminal unit and connect to Air Terminal Mixer
vrf_tu = ZoneHVACTerminalUnitVariableRefrigerantFlow.new(m)
vrf_tu.addToNode(at.outletModelObject.get.to_Node.get)

# translate
ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)

puts vrf_tu
ws.getObjectsByType("ZoneHVAC_TerminalUnit_VariableRefrigerantFlow".to_IddObjectType).each {|obj| puts obj}
```
=> 
```
OS:ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
  {5f9ea9ea-dd50-4cc4-a804-1ab38785d111}, !- Handle
  Zone HVAC Terminal Unit Variable Refrigerant Flow 1, !- Name
  {a844a593-d8e1-4c34-9352-f40b12a04394}, !- Terminal Unit Availability schedule
  {cc9e9300-6d70-487c-b324-b6fbac1a279c}, !- Terminal Unit Air Inlet Node
  {d210db8d-51c5-4970-9d61-80b8569972a7}, !- Terminal Unit Air Outlet Node
  autosize,                               !- Supply Air Flow Rate During Cooling Operation {m3/s}
  autosize,                               !- Supply Air Flow Rate When No Cooling is Needed {m3/s}
  autosize,                               !- Supply Air Flow Rate During Heating Operation {m3/s}
  autosize,                               !- Supply Air Flow Rate When No Heating is Needed {m3/s}
  autosize,                               !- Outdoor Air Flow Rate During Cooling Operation {m3/s}
  autosize,                               !- Outdoor Air Flow Rate During Heating Operation {m3/s}
  autosize,                               !- Outdoor Air Flow Rate When No Cooling or Heating is Needed {m3/s}
  {a844a593-d8e1-4c34-9352-f40b12a04394}, !- Supply Air Fan Operating Mode Schedule
  DrawThrough,                            !- Supply Air Fan Placement
  {4eda1b89-957c-42c5-b7be-e6ec9c349e71}, !- Supply Air Fan
  ,                                       !- Outside Air Mixer
  {d17e8544-639c-4152-a92a-decda7cb5092}, !- Cooling Coil
  {9575a134-a620-4725-b4c0-1d905cdb757e}, !- Heating Coil
  30,                                     !- Zone Terminal Unit On Parasitic Electric Energy Use {W}
  20,                                     !- Zone Terminal Unit Off Parasitic Electric Energy Use {W}
  1,                                      !- Rated Total Heating Capacity Sizing Ratio {W/W}
  ,                                       !- Availability Manager List Name
  ,                                       !- Design Specification ZoneHVAC Sizing Object Name
  ,                                       !- Supplemental Heating Coil Name
  Autosize,                               !- Maximum Supply Air Temperature from Supplemental Heater {C}
  21;                                     !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation {C}

ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
  Zone HVAC Terminal Unit Variable Refrigerant Flow 1, !- Zone Terminal Unit Name
  Always On Discrete,                     !- Terminal Unit Availability Schedule
  Node 5,                                 !- Terminal Unit Air Inlet Node Name
  Node 9,                                 !- Terminal Unit Air Outlet Node Name
  Autosize,                               !- Cooling Supply Air Flow Rate {m3/s}
  Autosize,                               !- No Cooling Supply Air Flow Rate {m3/s}
  Autosize,                               !- Heating Supply Air Flow Rate {m3/s}
  Autosize,                               !- No Heating Supply Air Flow Rate {m3/s}
  Autosize,                               !- Cooling Outdoor Air Flow Rate {m3/s}
  Autosize,                               !- Heating Outdoor Air Flow Rate {m3/s}
  Autosize,                               !- No Load Outdoor Air Flow Rate {m3/s}
  Always On Discrete,                     !- Supply Air Fan Operating Mode Schedule Name
  DrawThrough,                            !- Supply Air Fan Placement
  ,                                       !- Supply Air Fan Object Type                          <=== missing!
  ,                                       !- Supply Air Fan Object Name
  ,                                       !- Outside Air Mixer Object Type
  ,                                       !- Outside Air Mixer Object Name
  Coil:Cooling:DX:VariableRefrigerantFlow, !- Cooling Coil Object Type
  Zone HVAC Terminal Unit Variable Refrigerant Flow 1 Cooling Coil, !- Cooling Coil Object Name
  Coil:Heating:DX:VariableRefrigerantFlow, !- Heating Coil Object Type
  Zone HVAC Terminal Unit Variable Refrigerant Flow 1 Heating Coil, !- Heating Coil Object Name
  30,                                     !- Zone Terminal Unit On Parasitic Electric Energy Use {W}
  20,                                     !- Zone Terminal Unit Off Parasitic Electric Energy Use {W}
  1,                                      !- Rated Heating Capacity Sizing Ratio {W/W}
  ,                                       !- Availability Manager List Name
  ,                                       !- Design Specification ZoneHVAC Sizing Object Name
  ,                                       !- Supplemental Heating Coil Object Type
  ,                                       !- Supplemental Heating Coil Name
  Autosize,                               !- Maximum Supply Air Temperature from Supplemental Heater {C}
  21,                                     !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation {C}
  Thermal Zone 1;                         !- Controlling Zone or Thermostat Location
```
## Possible Solution
Check if terminal is a supply component before skipping fan translation. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.2.0-alpha+bc2dd59a59

### PR DESCRIPTION
**Pull request by kbenne**
Pull request overview
---------------------

 - Fixes #4288

### CODE REVIEW

**Comment by eringold** [comment]
Thank you @kbenne, this works.

**Comment by tijcolem** [comment]
@kbenne Thanks for the fix!

**Review by tijcolem — APPROVED** [review]

File: src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACTerminalUnitVariableRefrigerantFlow.cpp [hunk 1]
```diff
@@ -291,7 +291,7 @@ namespace energyplus {
         LOG(Info, "Will not translate fan for VRF named '" << modelObject.name().get() << "' since it is on an AirLoopHVACOutdoorAirSystem.");
         return;
       }
-      if (modelObject.airLoopHVAC() && modelObject.airLoopHVAC()->supplyFan()) {
+      if (modelObject.airLoopHVAC() && modelObject.airLoopHVAC()->supplyFan() && modelObject.airLoopHVAC()->supplyComponent(modelObject.handle())) {
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACTerminalUnitVariableRefrigerantFlow.cpp:294]: Thanks @kbenne ! :+1:
