### PR TITLE
Fix #4815 - Adjust `ForwardTranslatorOptions::string()` for backward compat with openstudio-workflow-gem

### LINKED ISSUE #4815: OS 3.6 CLI error when running OSW
Issue overview
--------------
I'm using the OS develop build (`c7160fa7b0`) and getting an error running an OSW. The error did not exist in OS 3.5.

To reproduce:
1. Check out https://github.com/NREL/OpenStudio-HPXML/tree/os360
2. Run `openstudio run -w workflow/template-run-hpxml.osw`

Error produced:
```
openstudio run -w workflow/template-run-hpxml.osw
Error executing argv: ["run", "-w", "workflow/template-run-hpxml.osw"]
Error: undefined method `each' for nil:NilClass in :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/adapters/input/local.rb:368:in `ft_options'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:205:in `initialize'
:/openstudio_cli.rb:1181:in `new'
:/openstudio_cli.rb:1181:in `execute'
:/openstudio_cli.rb:814:in `execute'
:/openstudio_cli.rb:1983:in `<main>'
eval:188:in `eval'
eval:188:in `require_embedded_absolute'
eval:173:in `block in require_embedded'
eval:167:in `each'
eval:167:in `require_embedded'
eval:126:in `require'
eval:3:in `<main>'
```

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix #4815
-  `ForwardTranslatorOptions::string()` was returning `"null"`, set to empty

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/filetypes/test/WorkflowJSON_GTest.cpp [hunk 1]
```diff
@@ -1170,3 +1170,9 @@ TEST(Filetypes, RunOptions_ForwardTranslate_BackwardCompatibility) {
   EXPECT_EQ("my_ruby_file.rb", workflow2->runOptions()->customOutputAdapter()->customFileName());
   EXPECT_EQ("MyOutputAdapter", workflow2->runOptions()->customOutputAdapter()->className());
 }
+
+TEST(Filetypes, RunOptions_NoFtOptions) {
+  // Test for #4815
+  const RunOptions options;
+  EXPECT_EQ("", options.forwardTranslateOptions());
+}
```
Comment (jmarrec) [inline src/utilities/filetypes/test/WorkflowJSON_GTest.cpp:1178]: Before Fix, this returns `"null"` so it would throw on https://github.com/NREL/OpenStudio-workflow-gem/blob/cf99e6096f33b717df79a71c245a4d7aa4ccb7a6/lib/openstudio/workflow/adapters/input/local.rb#L368

`Error: undefined method `each' for nil:NilClass in :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/adapters/input/local.rb:368:in `ft_options'`

File: src/utilities/filetypes/ForwardTranslatorOptions.cpp [hunk 2]
```diff
@@ -253,11 +253,15 @@ namespace detail {
...
+    const Json::Value data = this->json();
+    if (data.isNull()) {
+      return "";
+    }
     // Write to string
     Json::StreamWriterBuilder wbuilder;
     // mimic the old StyledWriter behavior:
     wbuilder["indentation"] = "   ";
-    std::string result = Json::writeString(wbuilder, json());
+    std::string result = Json::writeString(wbuilder, data);
```
Comment (jmarrec) [inline src/utilities/filetypes/ForwardTranslatorOptions.cpp:264]: Simple fix

**Review by shorowit — APPROVED** [review]
Didn't look at the code but confirmed that this fixes my issue. Thanks, @jmarrec.
