### PR TITLE
Fix addToNode resetting plant loop fluid type

### LINKED ISSUE #5458: GroundHeatExchangerVertical_Impl::addToNode sets plant loop fluid type to Water
Issue overview
--------------
The `addToNode` method for `GroundHeatExchangerVertical` (re)sets its plant loop's fluid type to "Water". This seems unexpected/incorrect. For comparison, the same method for `GroundHeatExchangerHorizontalTrench` does not do this.

## Current Behavior
The plant loop for which you are adding the GHE Vertical object as a supply component has its fluid type set to Water.

For the same `addToNode` method, both BoilerHotWater and BoilerSteam sets their fluid type to Water and Steam, respectively. While this seems more appropriate, perhaps this behavior should be removed as well?

## Expected Behavior
The plant loop should not have its fluid type changed.

## Steps to Reproduce
1. Create a plant loop with Fluid Type = "PropyleneGlycol" and Glycol Concentration = "20".
2. Create a ground heat exchanger vertical.
3. Call `plant_loop.addSupplyBranchForComponent(ground_heat_exch_vert)`.
4. See that now Fluid Type = "Water".

## Possible Solution
Delete the line(s) that reset the fluid type to Water. Follow GroundHeatExchangerHorizontalTrench's `addToNode` method as a guide.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #5458

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [x] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/GroundHeatExchangerVertical.cpp [hunk 1]
```diff
@@ -353,14 +353,10 @@ namespace model {
...
     bool GroundHeatExchangerVertical_Impl::addToNode(Node& node) {
-      if (boost::optional<PlantLoop> plant = node.plantLoop()) {
-        if (plant->supplyComponent(node.handle())) {
-          if (StraightComponent_Impl::addToNode(node)) {
-            plant->setFluidType("Water");
-            return true;
-          }
+      if (auto plant = node.plantLoop()) {
+        if (!plant->demandComponent(node.handle())) {
+          return StraightComponent_Impl::addToNode(node);
```
Comment (jmarrec) [inline src/model/GroundHeatExchangerVertical.cpp:359]: Okay I guess.

File: src/model/BoilerSteam.cpp [hunk 2]
```diff
@@ -341,12 +341,9 @@ namespace model {
...
     bool BoilerSteam_Impl::addToNode(Node& node) {
-      if (boost::optional<PlantLoop> plant = node.plantLoop()) {
-        if (plant->supplyComponent(node.handle())) {
-          if (StraightComponent_Impl::addToNode(node)) {
-            plant->setFluidType("Steam");
-            return true;
-          }
+      if (auto plant = node.plantLoop()) {
+        if (!plant->demandComponent(node.handle())) {
+          return StraightComponent_Impl::addToNode(node);
```
Comment (jmarrec) [inline src/model/BoilerSteam.cpp]: Why the switch from plant->supplyComponent to !plant->demandComponent?

What happens if you call it with a supply node on plantloop that's another model? It's NOT a demandComponent, so addToNode is called, when you could have avoided doing it?

Comment (jmarrec) [reply src/model/BoilerSteam.cpp]: I think BoilerSteam is the weird case here FYI, and ultimately, we should refuse to add it with a warning if done on a PlantLoop that's water/glycol and not steam. But probably do that in https://github.com/NREL/OpenStudio/pull/5455

File: src/model/BoilerHotWater.cpp [hunk 3]
```diff
@@ -372,12 +372,9 @@ namespace model {
...
     bool BoilerHotWater_Impl::addToNode(Node& node) {
-      if (boost::optional<PlantLoop> plant = node.plantLoop()) {
-        if (plant->supplyComponent(node.handle())) {
-          if (StraightComponent_Impl::addToNode(node)) {
-            plant->setFluidType("Water");
-            return true;
-          }
+      if (auto plant = node.plantLoop()) {
+        if (!plant->demandComponent(node.handle())) {
+          return StraightComponent_Impl::addToNode(node);
```
Comment (jmarrec) [inline src/model/BoilerHotWater.cpp]: Curious whether you can use Glycol ones with a BoilerHotWater or not in E+. Have you tried?

Comment (joseph-robertson) [reply src/model/BoilerHotWater.cpp]: I have not tried.

File: src/model/BoilerSteam.cpp (hunk 2 above)
Comment (joseph-robertson) [reply src/model/BoilerSteam.cpp]: I was just following the `addToNode` method for GroundHeatExchangerHorizontalTrench. Sounds like this PR should just change `addToNode` for GroundHeatExchangerVertical, and leave BoilerHotWater/BoilerSteam alone.

Comment (joseph-robertson) [reply src/model/BoilerSteam.cpp]: [ecba60c](https://github.com/NREL/OpenStudio/pull/5459/commits/ecba60c4e9542d124789ed090f96aa2fc582b49d)
