### PR TITLE
4766 different surface counts

### LINKED ISSUE #4766: Different number of wall surfaces between ThreeJS reverse translator and Floorspace reverse translatot
Issue overview
--------------
The Floorspace and ThreeJS reverse translators should produce identical models as far as surface count and vertex matching of surfaces goes. 

## Current Behavior
Using the sample file provided in #4222 floorplan_mcve.json Space 1-6 has a different count of internal wall surfaces
This difference appears to be an issue with surface alignment that differ between the two imports

## Expected Behavior
Surface count should be the same and surface matching vertices should produce no errors

## Steps to Reproduce

The source json data looks like this

image

There is an inline vertex indicated by the red dot
In the ThreeJS import the surfaces along this edge are aligned as follows

image

In the Floorspace import he surfaces along this edge do not align

image

It is possible that somewhere in the Floorspace import the inline vertex has been removed somehow resulting in combining two adjacent edges into one edge that is not parallel with the edge on space 1-12. The result is the surfaces on Space 1-6 and Space 1-12 are not considered to have equal planes and therefore are not intersected

For an idea of scale of what we are dealing with here, this is an overview of the section in question with the inline vertex identified by the red dot

image

As can be seen the inline vertex is very close to the corner vertex of Space 1-12 which may be the reason it has been removed, the distance between the two vertices is approximately 2" so that should be outside the tolerance of merging vertices 

image

## Possible Solution
Find out where the vertex is removed and do not remove it.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by ggartside**
Pull request overview
---------------------

 - Fixes #4766

To resolve an issue caused by removing inline vertices that altered the direction vector of the combined edges enough to make surface matching fail

This call was originally added to resolve the issue with Space 2 - 1 in the floorplan_school model where the vertices are not ordered correctly and the resulting surfaces are overlapping. Removing this call meant that the way wall sub-surfaces are made and associated with the walls had to be modified to allow for the situation that we are no longer able to match edge ids

This fix has also resulted in creating issue #4776 and #4783
 

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/geometry/Point3d.cpp [hunk 1]
```diff
@@ -113,4 +113,25 @@ std::ostream& operator<<(std::ostream& os, const std::vector<Point3d>& pointVect
...
+      os << "\"Y\":" << points[j].y() << ",";
+      os << "\"Z\":" << points[j].z();
+      os << "},";
+    }
+    os << "],";
+  }
+  os << "]";
+
+  return os;
+}
```
Comment (jmarrec) [inline src/utilities/geometry/Point3d.cpp:135]: * Range-based for loop
* Point3d has an ostream operator already, can't we just use that already? At least I find uppercase X, Y, Z quite weird

Proposed implementation:

```
std::ostream& operator<<(std::ostream& os, const std::vector<std::vector<Point3d>>& pointVectorVector) {
  os << "[\n";
  for (const auto& points: pointVectorVector) {
    os << "  [";
    for (const auto& point: points) {
      os << "\n    " << point << ", ";
    }
    os << "\n  ],\n";
  }
  os << "]";

  return os;
}
```

And alternative relying on `<fmt/ranges.h>` and `<fmt/ostream.h>`

```c++
std::ostream& operator<<(std::ostream& os, const std::vector<std::vector<Point3d>>& pointVectorVector) {
  os << fmt::format("{}", pointVectorVector);
  return os;
}
```

File: src/utilities/geometry/Test/Intersection_GTest.cpp [hunk 2]
```diff
@@ -2349,33 +2349,39 @@ TEST_F(GeometryFixture, Offset) {
   poly1.push_back(Point3d(8, 10, 0));
   poly1.push_back(Point3d(11, 10, 0));
   poly1.push_back(Point3d(11, 7, 0));
+  Point3dVector poly2;
+  poly2.push_back(Point3d(7.5, 10.5, 0));
+  poly2.push_back(Point3d(11.5, 10.5, 0));
+  poly2.push_back(Point3d(11.5, 6.5, 0));
+  poly2.push_back(Point3d(7.5, 6.5, 0));
```
Comment (jmarrec) [inline src/utilities/geometry/Test/Intersection_GTest.cpp:2356]: An FYI but going forward you can do:

```
Point3dVector poly2 {
        {7.5, 10.5, 0.0},
        {11.5, 10.5, 0.0},
        {11.5, 6.5, 0.0},
        {7.5, 6.5, 0.0},
    };
```

This will avoid costly vector resize operations. (granted, this is a test here...).
The copy constructor will be called 7 times in the case of 4 push_backs, versus 4 times with initializer list.

The most efficient is this but it's annoying to type in a test

```
Point3dVector poly2;
poly2.reserve(4);
poly2.emplace_back(7.5, 10.5, 0);
poly2.emplace_back(11.5, 10.5, 0);
poly2.emplace_back(11.5, 6.5, 0);
poly2.emplace_back(7.5, 6.5, 0);
```

here's a testbed if you want to see for yourself: https://compiler-explorer.com/z/zf9EEr31j

File: src/utilities/geometry/Test/Intersection_GTest.cpp [hunk 3]
```diff
@@ -2349,33 +2349,39 @@ TEST_F(GeometryFixture, Offset) {
...
 
   boost::optional<std::vector<Point3d>> result1 = openstudio::buffer(poly1, 0.5, 0.01);
   ASSERT_TRUE(result1);
+  Point3dVectorVector tmp;
+  tmp.push_back(poly1);
+  tmp.push_back(*result1);
```
Comment (jmarrec) [inline src/utilities/geometry/Test/Intersection_GTest.cpp:2362]: Same here: `Point3dVectorVector tmp{poly1, *result1}`;

**Review by jmarrec — CHANGES_REQUESTED** [review]

File: src/model/Space.cpp [hunk 4]
```diff
@@ -2314,18 +2314,16 @@ namespace model {
       Transformation transformation = this->transformation().inverse() * other.transformation();
 
       for (Surface surface : this->surfaces()) {
-
-        std::vector<Point3d> vertices = removeCollinear(surface.vertices());
-
+        if (surface.adjacentSurface()) continue;
```
Comment (jmarrec) [inline src/model/Space.cpp:2317]: braces

File: src/model/FloorspaceReverseTranslator.cpp [hunk 5]
```diff
@@ -563,34 +559,18 @@ namespace model {
...
-        wallVertices.push_back(Point3d(v1.x(), v1.y(), minZ));
-      }
+      Point3dVector wallVertices;
+      wallVertices.push_back(Point3d(p2.x(), p2.y(), maxZ));
+      wallVertices.push_back(Point3d(p1.x(), p1.y(), maxZ));
+      wallVertices.push_back(Point3d(p1.x(), p1.y(), minZ));
+      wallVertices.push_back(Point3d(p2.x(), p2.y(), minZ));
+      Point3dVector wallSegment;
+      wallSegment.push_back(p1);
+      wallSegment.push_back(p2);
```
Comment (jmarrec) [inline src/model/FloorspaceReverseTranslator.cpp:573]: this is production code here, so I would go with reserve + emplace_back

File: src/model/FloorspaceReverseTranslator.cpp [hunk 6]
```diff
@@ -602,34 +582,43 @@ namespace model {
 
           // Create a window subsurface for every window that is on this edge
           for (const auto& window : m_currentFSStory->windows()) {
-            if (window.edge()->id() == edgeRef.edge().id()) {
-              createWindowSubsurface(window, surface, edgeRef, minZ, maxZ);
+            // Get window's x/y position which is the alpha based on its edge
+            // windows can have multiple alphas but we only need one
+            auto edge = *window.edge();
```
Comment (jmarrec) [inline src/model/FloorspaceReverseTranslator.cpp:587]: We're sure it's inintialized? (I realize this was existing code, the -> operator was called already before)

File: src/model/Space.cpp [hunk 7]
```diff
@@ -2404,12 +2408,20 @@ namespace model {
...
               hasSubSurfaceMap[otherSurfaceHandle] = !otherSurface.subSurfaces().empty();
               hasAdjacentSurfaceMap[otherSurfaceHandle] = otherSurface.adjacentSurface().has_value();
             }
 
             if (hasSubSurfaceMap[otherSurfaceHandle] || hasAdjacentSurfaceMap[otherSurfaceHandle]) {
+
+              auto subSurfaces = otherSurface.subSurfaces();
+              for (auto subSurface : subSurfaces) {
+                std::string subSurfaceName = subSurface.nameString();
+              }
```
Comment (jmarrec) [inline src/model/Space.cpp:2424]: 1. This does nothing so it's useless
2. If it did do something, this creates a copy for each iteration, use const auto& or auto&

File: src/model/Space.cpp [hunk 8]
```diff
@@ -2404,12 +2408,20 @@ namespace model {
 
           for (Surface otherSurface : otherSurfaces) {
             std::string otherSurfaceHandle = toString(otherSurface.handle());
+            std::string otherSurfaceName = otherSurface.nameString();
+            std::string otherSurfaceType = otherSurface.surfaceType();
```
Comment (jmarrec) [inline src/model/Space.cpp:2412]: this doesn't appear to be used anywhere

File: src/model/Space.cpp [hunk 9]
```diff
@@ -2392,6 +2394,8 @@ namespace model {
 
         for (Surface surface : surfaces) {
           std::string surfaceHandle = toString(surface.handle());
+          std::string surfaceName = surface.nameString();
+          std::string surfaceType = surface.surfaceType();
```
Comment (jmarrec) [inline src/model/Space.cpp:2398]: This doesn't appear to be used anywhere

File: src/model/Surface.cpp [hunk 10]
```diff
@@ -1027,6 +1027,8 @@ namespace model {
       double tol = 0.01;       //  1 cm tolerance
       double areaTol = 0.001;  // 10 cm2 tolerance
 
+      bool extraLogging = false;
```
Comment (jmarrec) [inline src/model/Surface.cpp:1030]: Same idea. Should be a constexpr

File: src/model/Surface.cpp [hunk 11]
```diff
@@ -1088,13 +1090,26 @@ namespace model {
       //std::reverse(otherFaceVertices.begin(), otherFaceVertices.end());
 
       //LOG(Info, "Trying intersection of '" << this->name().get() << "' with '" << otherSurface.name().get());
-
+      if (extraLogging) {
```
Comment (jmarrec) [inline src/model/Surface.cpp:1093]: if-constexpr

File: src/utilities/floorspace/FSModel.hpp [hunk 12]
```diff
@@ -332,7 +332,7 @@ class UTILITIES_API FSFiller : public FSBase
   boost::optional<FSSpace> space() const;
   std::vector<double> alphas() const;
   // Calculates and returns the center vertex position of the window or door
-  Point3d centerVertex(double alpha);
+  Point3d centerVertex(double alpha) const;
```
Comment (jmarrec) [inline src/utilities/floorspace/FSModel.hpp:335]: :+1:

**Review by jmarrec — CHANGES_REQUESTED** [review]

**Comment by jmarrec** [comment]
at 5e06a4 you have failing tests. There are also conflicts.

The following tests FAILED:

	2524 - ModelFixture.FloorspaceReverseTranslator_Issue_4312 (Failed)
	2526 - ModelFixture.FloorspaceReverseTranslator_Issue_4488 (Failed)
	2530 - ModelFixture.FloorspaceReverseTranslator_Issue_4237 (Failed)

Errors while running CTest

File: resources/CMakeLists.txt [hunk 13]
```diff
@@ -68,6 +68,13 @@ set(utilities_resources_src
   utilities/Geometry/surface_match_floorplan.json
   utilities/Geometry/threejs.json
   utilities/Geometry/window_floorplan.json
+  utilities/Geometry/issue-4222.json
+  utilities/Geometry/issue-4312.json
+  utilities/Geometry/issue-4203.json
+  utilities/Geometry/issue-4488.json
+  utilities/Geometry/issue-4670.json
+  utilities/Geometry/issue-4313.json
+  utilities/Geometry/floorplan_mcve.json
```
Comment (jmarrec) [inline resources/CMakeLists.txt:77]: 4237 missing here

File: src/model/test/FloorspaceReverseTranslator_GTest.cpp [hunk 14]
```diff
@@ -1389,3 +1406,480 @@ TEST_F(ModelFixture, FloorspaceReverseTranslator_FloorplanJS_Site_ClimateZones_4
...
+  }
+
+  CompareTwoModels(*model1, *model);
+}
+
+TEST_F(ModelFixture, FloorspaceReverseTranslator_Issue_4237) {
+
+  ThreeJSReverseTranslator rt;
+
+  openstudio::path p = resourcesPath() / toPath("utilities/Geometry/issue_4237.json");
```
Comment (jmarrec) [inline src/model/test/FloorspaceReverseTranslator_GTest.cpp:1735]: wrong name here

File: src/model/test/FloorspaceReverseTranslator_GTest.cpp [hunk 15]
```diff
@@ -1389,3 +1406,480 @@ TEST_F(ModelFixture, FloorspaceReverseTranslator_FloorplanJS_Site_ClimateZones_4
...
+  model1->save(resourcesPath() / toPath("utilities/Geometry/issue_4237-direct.osm"), true);
+
+  CompareTwoModels(*model1, *model);
+}
+
+TEST_F(ModelFixture, FloorspaceReverseTranslator_Issue_4776) {
+
+  ThreeJSReverseTranslator rt;
+
+  openstudio::path p = resourcesPath() / toPath("utilities/Geometry/issue-4203.json");
```
Comment (jmarrec) [inline src/model/test/FloorspaceReverseTranslator_GTest.cpp:1761]: Is this normal the json and issue aren't matching?

**Review by jmarrec — CHANGES_REQUESTED** [review]

File: resources/CMakeLists.txt (hunk 13 above)
Comment (jmarrec) [reply resources/CMakeLists.txt]: Done in 853811433efa6480d6b14f252d22ed3642b2e6b2

File: src/model/test/FloorspaceReverseTranslator_GTest.cpp (hunk 14 above)
Comment (jmarrec) [reply src/model/test/FloorspaceReverseTranslator_GTest.cpp]: Done in 853811433efa6480d6b14f252d22ed3642b2e6b2

File: src/utilities/geometry/Intersection.cpp [hunk 16]
```diff
@@ -746,6 +827,7 @@ boost::optional<IntersectionResult> intersect(const std::vector<Point3d>& polygo
   std::vector<std::vector<Point3d>> newPolygons1;
   std::vector<std::vector<Point3d>> newPolygons2;
 
+  bool extraLogging = false;
```
[the remark this answers is not in the document]
Comment (jmarrec) [reply src/utilities/geometry/Intersection.cpp]: I went with constexpr bool in 2cca961e2235296f840dc89c1664a97571ea77eb. You can revisit if you think it's good to pass an optional parameter (but penalize everyone)

File: src/model/Space.cpp (hunk 4 above)
Comment (jmarrec) [reply src/model/Space.cpp]: Done in db79456fe87054ed8957888e22f329598bdcec6f

File: src/model/FloorspaceReverseTranslator.cpp (hunk 5 above)
Comment (jmarrec) [reply src/model/FloorspaceReverseTranslator.cpp]: Done in db79456fe87054ed8957888e22f329598bdcec6f

File: src/model/Space.cpp (hunk 7 above)
Comment (jmarrec) [reply src/model/Space.cpp]: I removed it in db79456fe87054ed8957888e22f329598bdcec6f

File: src/model/Space.cpp (hunk 8 above)
Comment (jmarrec) [reply src/model/Space.cpp]: Removed in db79456fe87054ed8957888e22f329598bdcec6f

File: src/model/Space.cpp (hunk 9 above)
Comment (jmarrec) [reply src/model/Space.cpp]: Removed in db79456fe87054ed8957888e22f329598bdcec6f

File: src/model/Surface.cpp (hunk 10 above)
Comment (jmarrec) [reply src/model/Surface.cpp]: constexpr done in db79456fe87054ed8957888e22f329598bdcec6f

File: src/utilities/geometry/Intersection.cpp [hunk 17]
```diff
@@ -771,13 +859,24 @@ boost::optional<IntersectionResult> intersect(const std::vector<Point3d>& polygo
...
+  }
+
   // check if intersection is empty
   if (intersectionResult.empty()) {
     //LOG_FREE(Info, "utilities.geometry.intersect", "Intersection is empty");
     return boost::none;
   }
 
   intersectionResult = removeSpikes(intersectionResult);
+  if (intersectionResult.size() == 0) {
```
[the remark this answers is not in the document]
Comment (jmarrec) [reply src/utilities/geometry/Intersection.cpp]: (done)

File: src/utilities/geometry/Intersection.cpp [hunk 18]
```diff
@@ -762,6 +844,12 @@ boost::optional<IntersectionResult> intersect(const std::vector<Point3d>& polygo
     return boost::none;
   }
 
+  BoostMultiPolygon polys;
+  boost::optional<BoostPolygon> poly = boostPolygonFromVertices(polygon2, allPoints, tol);
```
[the remark this answers is not in the document]
Comment (jmarrec) [reply src/utilities/geometry/Intersection.cpp]: done.

File: src/utilities/geometry/Intersection.cpp [hunk 19]
```diff
@@ -401,7 +482,7 @@ std::vector<Point3d> verticesFromBoostPolygon(const BoostPolygon& polygon, std::
              "Converting polygon with " << polygon.inners().size() << " inner loops to OpenStudio vertices, inner loops ignored");
   }
 
-  result = removeCollinearLegacy(result);
+  if (removeCollinear) result = removeCollinearLegacy(result);
```
[the remark this answers is not in the document]
Comment (jmarrec) [reply src/utilities/geometry/Intersection.cpp]: (done)

File: src/utilities/geometry/Intersection.cpp [hunk 20]
```diff
@@ -1243,12 +1326,13 @@ Polygon3d PolygonFromBoostPolygon(const BoostPolygon& boostPolygon, Point3dVecto
...
       Point3d point3d(inner[i].x(), inner[i].y(), 0.0);
-      Point3d resultPoint = getCombinedPoint(point3d, allPoints, tol);
+      const Point3d resultPoint = getCombinedPoint(point3d, allPoints, tol);
       // don't keep repeated vertices
       if ((i > 0) && (hole.back() == resultPoint)) {
         continue;
       }
-      hole.push_back(point3d);
+      // TODO: shouldn't this be resultPoint instead?! Or maybe the repeated check should use point3d in which case resultPoint is pointless
+      hole.emplace_back(std::move(point3d));
```
Comment (jmarrec) [inline src/utilities/geometry/Intersection.cpp:1335]: @ggartside here's someone I noticed while doing the refactor. I think there's something wrong here. Please advise

**Review by jmarrec — CHANGES_REQUESTED** [review]

**Comment by jmarrec** [comment]
@ggartside I've merged develop and resolved conflicts, and cleaned up a bunch of things. There are still some remaining comments that are left open.

File: src/utilities/geometry/Intersection.cpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (ggartside) [reply src/utilities/geometry/Intersection.cpp]: Braces it is - but I see you already made this change?

File: src/utilities/geometry/Intersection.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (ggartside) [reply src/utilities/geometry/Intersection.cpp]: The intention was to provide for extra logging without having to change the code - just change the value in the debugger. Logging gets clogged up with lots of unnecessary content otherwise.

But - whatever you prefer, definitely don't want to add an extra argument to the function

File: src/utilities/geometry/Intersection.cpp [hunk 21]
```diff
@@ -762,6 +844,12 @@ boost::optional<IntersectionResult> intersect(const std::vector<Point3d>& polygo
     return boost::none;
   }
 
+  BoostMultiPolygon polys;
+  boost::optional<BoostPolygon> poly = boostPolygonFromVertices(polygon2, allPoints, tol);
+  if (extraLogging) {
+    polys.push_back(*poly);
```
[the remark this answers is not in the document]
Comment (ggartside) [reply src/utilities/geometry/Intersection.cpp:843]: Technically true but this is code is only supposed to be activated when debugging so I didn't think it would be an issue

File: src/utilities/geometry/Point3d.cpp (hunk 1 above)
Comment (ggartside) [reply src/utilities/geometry/Point3d.cpp:135]: I'll make that change - the initial implementation was formatted so I could load the json file in to Simergy for debugging purposes so I could view the polygons output from doing intersections but on reflection it would be better to modify the back end code to accept an list of three doubles.

Done

File: src/utilities/geometry/Test/Intersection_GTest.cpp (hunk 2 above)
Comment (ggartside) [reply src/utilities/geometry/Test/Intersection_GTest.cpp:2356]: I'll use the initializer list - it's also closer to how it would be constructed in C# so I like that.

File: src/utilities/geometry/Test/Intersection_GTest.cpp (hunk 3 above)
Comment (ggartside) [reply src/utilities/geometry/Test/Intersection_GTest.cpp:2362]: Done

File: src/model/Space.cpp (hunk 7 above)
Comment (ggartside) [reply src/model/Space.cpp]: I think this was some debug code that I didn't remove

File: src/model/Surface.cpp (hunk 10 above)
Comment (ggartside) [reply src/model/Surface.cpp]: Thanks

File: src/utilities/geometry/Intersection.cpp (hunk 20 above)
Comment (ggartside) [reply src/utilities/geometry/Intersection.cpp:1335]: @jmarrec Me too - I think resultPoint should be used as getCombinedPoint might have modified the original Point3d

File: src/utilities/geometry/Intersection.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (ggartside) [reply src/utilities/geometry/Intersection.cpp:843]: Done

File: src/utilities/geometry/Intersection.cpp (hunk 20 above)
Comment (ggartside) [reply src/utilities/geometry/Intersection.cpp]: @jmarrec Yes I think this should use resultPoint as the original point has potentially been modified by getCombinedPoint so I've made the change

File: src/model/test/FloorspaceReverseTranslator_GTest.cpp (hunk 15 above)
Comment (ggartside) [reply src/model/test/FloorspaceReverseTranslator_GTest.cpp:1769]: @jmarrec The test is re-using the same json file.

File: src/utilities/geometry/Point3d.cpp (hunk 1 above)
Comment (jmarrec) [reply src/utilities/geometry/Point3d.cpp]: Thanks for the change. Note that i don't think there's anything wrong with producing a valid json for a purpose, I didn't have the context

Comment (ggartside) [reply src/utilities/geometry/Point3d.cpp]: This was creating a json file I could load in to Simergy to see the output from intersections but I agree a more generic list of doubles is better so I used your implementation and changed our code to suit

File: src/utilities/geometry/Intersection.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (jmarrec) [reply src/utilities/geometry/Intersection.cpp]: Just for context, the reason I am wary of doing extra work all the time only for debugging purposes is that I know (from profiling and benchmarking) that the geometry stuff can take a long time and lots of resources for specific models.

**Comment by jmarrec** [comment]
Thanks for the changes @ggartside . I have fixed up the cppcheck and merged latest develop in. There are only 2 open comments that needs addressing at this point.

File: src/model/FloorspaceReverseTranslator.cpp (hunk 6 above)
Comment (ggartside) [reply src/model/FloorspaceReverseTranslator.cpp:586]: Yes confident about that otherwise the floorspace model would be invalid but lets make 100% sure

**Comment by ggartside** [comment]
Added a new commit that applies a scale factor when converting between openstudio and boost data formats to improve the numerical accuracy of the boolean operations.

Idea came from this comment in the boostorg/geometry repo https://github.com/boostorg/geometry/issues/1034#issuecomment-1284180101 where the author indicates that scaling the values by 10 improved the result and talks about rounding to an integer grid, so by increasing the range of values we pass to boost we should be improving the resolution of the integer rounding

File: src/utilities/geometry/Intersection.cpp [hunk 22]
```diff
@@ -102,36 +102,113 @@ inline bool has_self_intersections(Geometry const& geometry, bool throw_on_self_
...
+  os << "[";
+  for (const auto& poly : boostPolygons) {
+    os << poly;
+  }
+  os << "]";
+  return os;
+}
+
+// Scale factor for parameters passed to boost
+double scaleBy = 1000.0;
```
Comment (jmarrec) [inline src/utilities/geometry/Intersection.cpp:155]: Never use a global variable like this.

```suggestion
// Scale factor for parameters when converting between openstudio and boost data formats to improve the numerical accuracy of the boolean operations.
// Idea came from this comment in the boostorg/geometry repo: https://github.com/boostorg/geometry/issues/1034#issuecomment-1284180101
// where the author indicates that scaling the values by 10 improved the result and talks about rounding to an integer grid, 
// so by increasing the range of values we pass to boost we should be improving the resolution of the integer rounding
static constexpr double scaleBy = 1000.0;
```

**Comment by jmarrec** [comment]
Ubuntu test failures are unrelated:

```
The following tests FAILED:
	639 - BCLFixture.RemoteBCLTest (Failed)
	640 - BCLFixture.RemoteBCLTest2 (Failed)
	642 - BCLFixture.RemoteBCLMetaSearchTest (Failed)
	643 - BCLFixture.RemoteBCL_EncodingURI (Failed)
```
