### PR TITLE
Fix floorplanjs issue

### LINKED ISSUE #5327: [CI] Mac incremental has failing tests on all branches
Issue overview
--------------

The following tests FAILED:

	538 - GeometryFixture.FloorplanJS (SEGFAULT)

	664 - BCLFixture.RemoteBCL_BCLSearchResult (Failed)

	1561 - ModelFixture.FloorplanJSForwardTranslator (Failed)

	1562 - ModelFixture.FloorplanJSForwardTranslator_Merging (SEGFAULT)

	2636 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS (SEGFAULT)

	2637 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SurfaceMatch (SEGFAULT)

	2650 - ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Site_ClimateZones_4166 (SEGFAULT)

## Current Behavior

https://ci.openstudio.net/blue/organizations/jenkins/openstudio-incremental-osx/detail/PR-5321/2/pipeline

## Expected Behavior

CI should be all green or it's pointless

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): mac
 - Version of OpenStudio (if using an intermediate build, include SHA): develop, 10eb60d580bd8b1447c03350d82ad158f7efddaf

### PR DESCRIPTION
**Pull request by wenyikuang**
Pull request overview
---------------------

 - Fixes #5327 (IF THIS IS A DEFECT)

Fix the test about floorPlanJS.

The line:

```
std::string storyName = stories[storyIdx].get("name", storyName).asString();
```
contains bad initilization which is using the storyName before it initilizaed properly.

The bad initiliazation trigger some kind of undefined behavior and the undefined behavior is ....undefined.

Therefore, somehow it works, somehow it broken.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [x] CI status: all green or justified

A run of tests from the remote CI box:

```
[----------] 173 tests from GeometryFixture
[ RUN      ] GeometryFixture.BoundingBox
[       OK ] GeometryFixture.BoundingBox (0 ms)
[ RUN      ] GeometryFixture.BoundingBox_Empty
[       OK ] GeometryFixture.BoundingBox_Empty (0 ms)
[ RUN      ] GeometryFixture.BoundingBox_Touching
[       OK ] GeometryFixture.BoundingBox_Touching (0 ms)
[ RUN      ] GeometryFixture.BoundingBox_NoIntersection
[       OK ] GeometryFixture.BoundingBox_NoIntersection (0 ms)
[ RUN      ] GeometryFixture.FloorplanJS
[       OK ] GeometryFixture.FloorplanJS (9 ms)
```

```
./Products/openstudio_model_tests --gtest_filter="*ThreeJSReverseTranslator_FloorplanJS*"
Running main() from gmock_main.cc
Note: Google Test filter = *ThreeJSReverseTranslator_FloorplanJS*
[==========] Running 15 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 15 tests from ModelFixture
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS
Starting toThreeScene in source
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS (37 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SurfaceMatch
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SurfaceMatch (20 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Doors
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Doors (16 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Windows
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Windows (60 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper (231 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Shading
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Shading (11 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SplitLevel
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SplitLevel (17 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_StorySpaceHeights
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_StorySpaceHeights (24 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Colors
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Colors (8 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_DifferingNumVertices
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_DifferingNumVertices (10 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_School
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_School (295 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_StoryMultipliers
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_StoryMultipliers (28 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_StoryMultipliers2
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_StoryMultipliers2 (22 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_OpenToBelow
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_OpenToBelow (18 ms)
[ RUN      ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Site_ClimateZones_4166
Starting toThreeScene in source
[       OK ] ModelFixture.ThreeJSReverseTranslator_FloorplanJS_Site_ClimateZones_4166 (28 ms)
[----------] 15 tests from ModelFixture (831 ms total)

[----------] Global test environment tear-down
[==========] 15 tests from 1 test suite ran. (832 ms total)
[  PASSED  ] 15 tests.
```
TODO:
- Make the CI passed since some update probably needed to add in the machine.

### CODE REVIEW

File: src/utilities/geometry/FloorplanJS.cpp [hunk 1]
```diff
@@ -1078,11 +1078,10 @@ ThreeScene FloorplanJS::toThreeScene(bool openstudioFormat) const {
   for (Json::ArrayIndex storyIdx = 0; storyIdx < storyN; ++storyIdx) {
 
     if (checkKeyAndType(stories[storyIdx], "name", Json::stringValue)) {
-      std::string storyName = stories[storyIdx].get("name", storyName).asString();
-      buildingStoryNames.push_back(storyName);
+      buildingStoryNames.push_back(stories[storyIdx].get("name", "").asString());
     }
 
-    std::string storyColor;
+    std::string storyColor = "";
```
Comment (jmarrec) [inline src/utilities/geometry/FloorplanJS.cpp:1084]: This change is pointless. The default ctor is an empty string already, equivalent to ""

Comment (jmarrec) [inline src/utilities/geometry/FloorplanJS.cpp:1084]:
```suggestion
    std::string storyColor;
```

File: src/utilities/geometry/FloorplanJS.cpp [hunk 2]
```diff
@@ -1078,11 +1078,10 @@ ThreeScene FloorplanJS::toThreeScene(bool openstudioFormat) const {
   for (Json::ArrayIndex storyIdx = 0; storyIdx < storyN; ++storyIdx) {
 
     if (checkKeyAndType(stories[storyIdx], "name", Json::stringValue)) {
-      std::string storyName = stories[storyIdx].get("name", storyName).asString();
-      buildingStoryNames.push_back(storyName);
+      buildingStoryNames.push_back(stories[storyIdx].get("name", "").asString());
```
Comment (jmarrec) [inline src/utilities/geometry/FloorplanJS.cpp:1081]: The old notation was definitely extremely weird to look at. It's weird that this compiles, but I guess we shush some warnings, and especially we use `-Wno-uninitialized`

**Review by jmarrec — APPROVED** [review]

File: src/utilities/geometry/FloorplanJS.cpp (hunk 1 above)
Comment (wenyikuang) [reply src/utilities/geometry/FloorplanJS.cpp]: Yeah, we don't need it, was thinking following the next lines.

File: conan.lock [hunk 3]
```diff
@@ -19,7 +19,7 @@
         "libxslt/1.1.37#8c0548495527cea12de08ad6212fc3ce%1703714812.414",
         "libxml2/2.11.6#41c14895baba105865cb22ecaf948115%1703682489.517",
         "libiconv/1.17#9d9082101394d053c67e95d3bc9f1e78%1701083487.832",
-        "libgettext/0.22#2c87563d7a69544dd9379f038aca3b0b%1692434363.136",
+        "libgettext/0.22",
```
Comment (jmarrec) [inline conan.lock:22]: This is unrelated to this PR, and should probably be a separate (and justified with an explanation) PR, so we have a way to understand why this is happening instead of lumping it here.

**Comment by wenyikuang** [comment]
Great, at least the FloorJS fixed.

File: conan.lock (hunk 3 above)
Comment (wenyikuang) [reply conan.lock:22]: Agree, let me revise it.
