### PR TITLE
Fix #3951 - Assign proper surfaceType in GbXMLReverseTranslator

### LINKED ISSUE #3951: 3.0.0-rc1: GbXMLReverseTranslator produces incorrect geometry with respect to the windows and exterior walls of the gbxml
Issue overview
--------------

3.0.0-rc1: GbXMLReverseTranslator produces incorrect geometry with respect to the windows and exterior walls of the gbxml

On the other hand the 2.9.1 GbXMLReverseTranslator  produces completely normal geometry.

Reported by @antonszilasi 

## Current Behavior

It doesn't work with 3.0.0, but worked by 2.9.1

## Expected Behavior

It should produce valid geometry.

## Steps to Reproduce

The following XML exhibits the issue: 

[3951_Geometry_bug.xml.txt](https://github.com/NREL/OpenStudio/files/4501889/3951_Geometry_bug.xml.txt)

I can create an OSM for both 2.9.1 and 3.0.0-rc3 and compare the diffs:

```
C:\openstudio-2.9.1\bin\openstudio.exe -e "rt = OpenStudio::GbXML::GbXMLReverseTranslator.new; m = rt.loadModel('3951_Geometry_bug.xml').get; m.save('291.osm', true)"
```

```
C:\openstudio-3.0.0-rc3\bin\openstudio.exe -e "rt = OpenStudio::GbXML::GbXMLReverseTranslator.new; m = rt.loadModel('3951_Geometry_bug.xml').get; m.save('300.osm', true)"
```

**From a diff between the two, it appears that all `OS:Surface` in 3.0.0 have a 'Surface Type' of 'Wall' instead of RoofCeiling, Floors, etc.**

## Possible Solution

This is probably a regression introduced during the transition from QXml to pugixml.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.0-rc1, 3.0.0-rc3

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3951
 - Assign proper surfaceType in GbXMLReverseTranslator. This is a regression introduced during the conversion from `QXml` to `pugixml`

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] GbXML API Changes / Additions
 - [x] All new and existing tests passes

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/gbxml/Test/ReverseTranslator_GTest.cpp [hunk 1]
```diff
@@ -268,119 +268,53 @@ TEST_F(gbXMLFixture, ReverseTranslator_FloorSurfaces)
...
+  });
+
+  for (auto& expectedSurfaceInfo : expectedSurfaceInfos) {
+    OptionalSurface _surf = model->getConcreteModelObjectByName<Surface>(expectedSurfaceInfo.name);
+    ASSERT_TRUE(_surf);
+    EXPECT_EQ(expectedSurfaceInfo.surfaceType, _surf->surfaceType()) << "Wrong surfaceType for " << expectedSurfaceInfo.name;
+    auto _space = _surf->space();
+    ASSERT_TRUE(_space);
+    EXPECT_EQ(expectedSurfaceInfo.spaceName, _space->nameString())  << "Wrong space for " << expectedSurfaceInfo.name;
+  }
```
Comment (jmarrec) [inline src/gbxml/Test/ReverseTranslator_GTest.cpp:317]: Extend existing test and make it dryer. Checking all surfaces makes it fail without fix just like #3951 does.

File: src/gbxml/Test/ReverseTranslator_GTest.cpp [hunk 2]
```diff
@@ -562,3 +496,32 @@ TEST_F(gbXMLFixture, ReverseTranslator_TwoStoryOffice_Trane)
...
+
+  {
+    auto _surf = _model->getModelObjectByName<Surface>("storey-1-ceiling-space-1");
+    ASSERT_TRUE(_surf);
+    EXPECT_EQ("RoofCeiling", _surf->surfaceType());
+    auto _space = _surf->space();
+    ASSERT_TRUE(_space);
+    EXPECT_EQ("storey-1-space-1", _space->nameString());
+  }
+}
```
Comment (jmarrec) [inline src/gbxml/Test/ReverseTranslator_GTest.cpp:527]: Added new test with an extract from the user-provided file in #3951: I kept only the bare minimum to make a MCVE

File: src/gbxml/ReverseTranslator.cpp [hunk 3]
```diff
@@ -648,31 +648,31 @@ namespace gbxml {
...
+      } else if (surfaceType.find("InteriorFloor") != std::string::npos) {
         surface.setSurfaceType("Floor");
-      } else if (surfaceType.find("RaisedFloor")) {
+      } else if (surfaceType.find("RaisedFloor") != std::string::npos) {
         surface.setSurfaceType("Floor");
-      } else if (surfaceType.find("ExposedFloor")) {
+      } else if (surfaceType.find("ExposedFloor") != std::string::npos) {
         surface.setSurfaceType("Floor");
-      } else if (surfaceType.find("Air")) {
+      } else if (surfaceType.find("Air") != std::string::npos) {
```
Comment (jmarrec) [inline src/gbxml/ReverseTranslator.cpp:675]: Actual fix for #3951

File: resources/gbxml/3951_Geometry_bug.xml [hunk 4]
```diff
@@ -0,0 +1,92 @@
+<gbXML xmlns="http://www.gbxml.org/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.gbxml.org/schema http://gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" useSIUnitsForResults="true" SurfaceReferenceLocation="Centerline" temperatureUnit="F" lengthUnit="Feet" areaUnit="SquareFeet" volumeUnit="CubicFeet" version="6.01">
```
Comment (jmarrec) [inline resources/gbxml/3951_Geometry_bug.xml:1]: new gbxml test

File: resources/CMakeLists.txt [hunk 5]
```diff
@@ -283,6 +283,7 @@ SET(gbxml_resources_src
   gbxml/TestCubeAlternateUnits.xml
   gbxml/TwoStoryOffice_Trane.xml
   gbxml/ZNETH.xml
+  gbxml/3951_Geometry_bug.xml
```
Comment (jmarrec) [inline resources/CMakeLists.txt:286]: Register new gbxml test
