### PR TITLE
Addresses #4483, OS:Coil:Heating:DX:MultiSpeed:StageData has no Name field

### LINKED ISSUE #4483: `OS:Coil:Heating:DX:MultiSpeed:StageData` has no Name field but `OS:Coil:Cooling:DX:MultiSpeed:StageData` does
Issue overview
--------------

The OpenStudio.idd `OS:Coil:Heating:DX:MultiSpeed:StageData` has no Name field.

The `OS:Coil:Cooling:DX:MultiSpeed:StageData` does.

## Expected Behavior

Both should be similar.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context

Moved from https://github.com/openstudiocoalition/OpenStudioApplication/issues/434

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4483

This PR changes `CoilHeatingDXMultiSpeed` to have an extensible list of stages (like `CoilCoolingDXMultiSpeed`).

Checklist:
- [x] Update idd
- [x] New FT test file for `CoilHeatingDXMultiSpeed`
- [x] Update model tests
- [x] New VT and test

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/Test/CoilHeatingDXMultiSpeed_GTest.cpp [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+
+#include <resources.hxx>
+#include <sstream>
+
+using namespace openstudio::energyplus;
+using namespace openstudio::model;
+using namespace openstudio;
+
+/* It should allow for up to 4 stages. Tests that issue #2812 is fixed and doesn't come back */
+TEST_F(EnergyPlusFixture, ForwardTranslator_CoilHeatingDXMultiSpeed_4Stages) {
```
Comment (jmarrec) [inline src/energyplus/Test/CoilHeatingDXMultiSpeed_GTest.cpp:189]: Ok this is a copy of the CoilCoolingDXMultiSpeed_Gtest.cpp file. 

I suppose we could/should add a basic test for all the fields in addition. I'll do that

File: src/model/CoilHeatingDXMultiSpeed.cpp [hunk 2]
```diff
@@ -322,25 +310,27 @@ namespace model {
...
+    }
+
     ModelObject CoilHeatingDXMultiSpeed_Impl::clone(Model model) const {
       auto t_clone = StraightComponent_Impl::clone(model).cast<CoilHeatingDXMultiSpeed>();
 
-      if (auto stageDataList = this->stageDataList()) {
-        auto stageDataListClone = stageDataList->clone(model).cast<ModelObjectList>();
-        t_clone.getImpl<detail::CoilHeatingDXMultiSpeed_Impl>()->setStageDataList(stageDataListClone);
+      auto t_stages = stages();
+      for (auto stage : t_stages) {
```
Comment (jmarrec) [inline src/model/CoilHeatingDXMultiSpeed.cpp]: extra copy on each iteration here

File: src/model/CoilHeatingDXMultiSpeed.cpp [hunk 3]
```diff
@@ -353,51 +343,130 @@ namespace model {
...
-    boost::optional<ModelObjectList> CoilHeatingDXMultiSpeed_Impl::stageDataList() const {
-      return getObject<ModelObject>().getModelObjectTarget<ModelObjectList>(OS_Coil_Heating_DX_MultiSpeedFields::StageDataList);
+    unsigned CoilHeatingDXMultiSpeed_Impl::numberOfStages() const {
+      return numExtensibleGroups();
+    }
+
+    std::vector<CoilHeatingDXMultiSpeedStageData> CoilHeatingDXMultiSpeed_Impl::stages() const {
+      std::vector<CoilHeatingDXMultiSpeedStageData> result;
+      auto groups = extensibleGroups();
+      for (auto group : groups) {
```
Comment (jmarrec) [inline src/model/CoilHeatingDXMultiSpeed.cpp]: Extra copy

**Review by jmarrec — APPROVED** [review]
All good! I made the few minor changes that I wanted to see already and the rest was spotless. thanks @joseph-robertson !

I'll let CI run on the changes I made, then we can merge.
