### PR TITLE
Fix zone controller ownership

### LINKED ISSUE #2049: fix ownership issues with zone controllers
This includes thermostats, humidistats, and new ZoneControlContaminantController. Make the API more robust and enforce our will.

### PR DESCRIPTION
**Pull request by kbenne**
close #2049 

Hey @macumber. This should make you happy. I bet we can still pick something out, but far more robust than where we were.

### CODE REVIEW

File: openstudiocore/src/model/ThermalZone.cpp [hunk 1]
```diff
@@ -998,14 +993,32 @@ namespace detail {
 
   bool ThermalZone_Impl::setThermostat(const Thermostat & thermostat)
   {
-    resetThermostat();
-    return setPointer(OS_ThermalZoneFields::ThermostatName, thermostat.handle());
+    auto t_model = model();
+
+    if( t_model != thermostat.model() ) {
```
Comment (macumber) [inline openstudiocore/src/model/ThermalZone.cpp]: This check seems ridiculous but honestly I've considered it, it is legit error checking.  I guess normally this is included if you check the return value of set methods but this could save you headache to do it first.

File: openstudiocore/src/model/ThermalZone.cpp [hunk 2]
```diff
@@ -998,14 +993,32 @@ namespace detail {
...
+      return false;
+    }
+
+    if( auto currentZone = thermostat.thermalZone() ) {
+      if( currentZone->handle() == handle() ) {
+        // or should it be false?
+        // I think this is similar to what you would see in 
+        // Lights::setSpace() under similar conditions
```
Comment (macumber) [inline openstudiocore/src/model/ThermalZone.cpp]: True this can happen in the setSpace but there setting the same thing twice is benign, except I guess you get unnecessary change signals emitted

Comment (macumber) [inline openstudiocore/src/model/ThermalZone.cpp]: I'd say should return true because the condition that the function was supposed to do is true at the end of the function

File: openstudiocore/src/model/ZoneControlHumidistat.cpp [hunk 3]
```diff
@@ -119,6 +123,20 @@ namespace detail {
     OS_ASSERT(result);
   }
 
+  boost::optional<ThermalZone> ZoneControlHumidistat_Impl::controlledZone() const
+  {
+    Handle h = handle();
+    auto zones = model().getModelObjects<model::ThermalZone>();
```
Comment (macumber) [inline openstudiocore/src/model/ZoneControlHumidistat.cpp]: Probably a faster look up using get sources

File: openstudiocore/src/model/test/ThermalZone_GTest.cpp [hunk 4]
```diff
@@ -636,33 +623,138 @@ TEST_F(ModelFixture, ThermalZone_Ports)
...
+
+  {
+    Model m;
+    ThermalZone zone(m);
+    ThermostatSetpointDualSetpoint thermostat(m); 
+    zone.setThermostat(thermostat);
+    auto zone2 = zone.clone().cast<model::ThermalZone>();
+
+    EXPECT_TRUE(zone2.thermostat());
+    EXPECT_EQ(2u,m.getModelObjects<model::Thermostat>().size());
```
Comment (macumber) [inline openstudiocore/src/model/test/ThermalZone_GTest.cpp]: Is the second thermostat hooked up to the cloned zone?  It looked like the thermostat field got blanked in the ThermalZone::clone:

      tz.setString(OS_ThermalZoneFields::ThermostatName,"");

Comment (macumber) [inline openstudiocore/src/model/test/ThermalZone_GTest.cpp]: Huh I guess it is since you are checking 

    EXPECT_TRUE(zone2.thermostat());

maybe just pop in a 

    ASSERT_TRUE(zone1.thermostat());
    ASSERT_TRUE(zone2.thermostat());
    EXPECT_NE(zone.thermostat()->handle(), zone2.thermostat()->handle());

Comment (macumber) [inline openstudiocore/src/model/test/ThermalZone_GTest.cpp]: PS: I'll do this, I owe you that much :-)

File: openstudiocore/src/model/ThermalZone.cpp (hunk 1 above)
Comment (kbenne) [inline openstudiocore/src/model/ThermalZone.cpp]: Yeah and the other thing is that the set method return value can come too late. Like say for instance if you do a reset first.
