### PR TITLE
Fix #5371 - add FuelTypes to PlantComponentUserDefined

### LINKED ISSUE #5371: PlantComponentUserDefined missing fuelTypes
Issue overview
--------------

Found today while working on 179d.
A proposed model that is created using this method: 

`create_central_air_source_heat_pump(model`

https://github.com/NREL/openstudio-standards/blob/429974633cf77f8386e838479b6dd69116a40805/lib/openstudio-standards/prototypes/common/objects/Prototype.CentralAirSourceHeatPump.rb#L14

## Current Behavior

Baseline determination ends up with a system that uses a gas boiler when the proposed model has only electricity 

## Expected Behavior

https://github.com/NREL/OpenStudio/blob/98207d21649408d964fbc2660110a4cbdb35eb7d/src/model/PlantComponentUserDefined.cpp#L501-L515

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.10.0 alpha

### Context

179d

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5371

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/EnergyManagementSystemSubroutine.hpp [hunk 1]
```diff
@@ -65,6 +67,9 @@ namespace model {
     /** @name Other */
     //@{
 
+    // Convenience method to return all EnergyManagementSystemMeteredOutputVariable that refer to this Subroutine
+    std::vector<EnergyManagementSystemMeteredOutputVariable> energyManagementSystemMeteredOutputVariables() const;
```
Comment (jmarrec) [inline src/model/EnergyManagementSystemSubroutine.hpp:71]: Convenience

File: src/model/EnergyManagementSystemSubroutine.cpp [hunk 2]
```diff
@@ -336,6 +339,12 @@ namespace model {
       }
       return result;
     }
+
+    std::vector<EnergyManagementSystemMeteredOutputVariable>
+      EnergyManagementSystemSubroutine_Impl::energyManagementSystemMeteredOutputVariables() const {
+      return getObject<ModelObject>().getModelObjectSources<EnergyManagementSystemMeteredOutputVariable>(
+        EnergyManagementSystemMeteredOutputVariable::iddObjectType());
+    }
```
Comment (jmarrec) [inline src/model/EnergyManagementSystemSubroutine.cpp:347]: Simple

**Review by joseph-robertson — APPROVED** [review]
