### PR TITLE
Fix #4240 (and more): add missing `\ip-units gal/min` via a script

### LINKED ISSUE #4240: Wrong IP unit for Cooled Beam air terminal 'maximum total chilled water volumetric flow rate'
Issue overview
--------------
AirTerminal:SingleDuct:ConstantVolume:CooledBeam input field 'Maximum Total Chilled Water Volumetric Flow Rate' displays IP unit as 'cfm'.

## Expected Behavior
water flow rate should convert to IP unit gal/min.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution
Add `\ip-units gal/min` to idd:

```
  N2, \field Maximum Total Chilled Water Volumetric Flow Rate
       \type real
       \units m3/s
       \minimum 0.0
       \autosizable
       \default autosize
```
### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #4240 (and more): add missing `\ip-units gal/min` via a script

Perhaps we should call the script on one of the CI runners @tijcolem ?

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: developer/ruby/FindAndAddMissingIPUnits.rb [hunk 1]
```diff
@@ -0,0 +1,99 @@
+require '/home/julien/Software/Others/OS-build/Products/ruby/openstudio'
+require 'optparse'
+
+# define the input parameters
+options = Hash.new
+
+optparse = OptionParser.new do |opts|
+
+  opts.on("-f", "--[no-]fix", "Add the missing ipUnits to the OpenSutdio.idd (note: LOTS of whitespace changes...)") do |fix|
```
Comment (jmarrec) [inline developer/ruby/FindAndAddMissingIPUnits.rb:9]: This would require running the "iddWrapper.save" once to do the whitespace changes once. I don't think it's really worth it here...

File: resources/model/OpenStudio.idd [hunk 2]
```diff
@@ -11810,6 +11814,7 @@ OS:AirTerminal:SingleDuct:ConstantVolume:CooledBeam,
   N2, \field Maximum Total Chilled Water Volumetric Flow Rate
        \type real
        \units m3/s
+       \ip-units gal/min
```
Comment (jmarrec) [inline resources/model/OpenStudio.idd:11817]: this is the actual specific fix for #4240

**Comment by tijcolem** [comment]
Windows looks good after rebuild.  This is good to drop in

**Review by tijcolem — APPROVED** [review]
