### PR TITLE
Fix #5178 - Init the RUBY_DESCRIPTION properly

### LINKED ISSUE #5178: Embedded ruby 3.2.2 in CLI is missing "RUBY_DESCRIPTION" global constant
Issue overview
--------------

Missing RUBY_DESCRIPTION constant in ruby 3.2.2.

Caught while testing openstudio-ee-gem, with a VERY cryptic message:

```
NameError: uninitialized constant Git::Lib::RUBY_DESCRIPTION
```

This is because git 1.12.0 (which is quite old too, 1.19.1 is out, and there's a 2.0.0-pre too, probably should update @DavidGoldwasser ) uses it https://github.com/ruby-git/ruby-git/blob/ea79dadf07e65896a08487af011e60336e86d3e3/lib/git/lib.rb#L1209-L1213

The same would happen with this

```
module Test
  class Lib
    def f
      puts NON_DEFINED_CONSTANT
    end
  end
end

Test::Lib.new.f()
```

```
openstudio test.rb
Error: uninitialized constant Test::Lib::NON_DEFINED_CONSTANT
```

## Current Behavior

It fails

## Expected Behavior

It should be there

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution

https://github.com/NREL/OpenStudio/blob/ca6043ee1660ddab352b1b39329706e026382203/ruby/engine/InitRubyEngine.cpp#L280

`Init_ruby_description` is needed. Note that it doesn't take void param anymore but a pointer to a typedefed struct...

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.8.0-rc1

### Context

testing on openstudio-ee-gem

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5178

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: ruby/engine/InitRubyEngine.cpp [hunk 1]
```diff
@@ -14,6 +14,9 @@ extern "C"
 {
   // static void Init_builtin_prelude(void);
   // void Init_builtin_gem_prelude(void);
+  struct ruby_cmdline_options;
+  typedef struct ruby_cmdline_options ruby_cmdline_options_t;
+  void Init_ruby_description(ruby_cmdline_options_t*);
```
Comment (jmarrec) [inline ruby/engine/InitRubyEngine.cpp:19]: Forward declare.

In 2.7.2, it was simpler, just `void Init_ruby_description(void)`

File: ruby/engine/InitRubyEngine.cpp [hunk 2]
```diff
@@ -22,6 +25,8 @@ void RubyEngine::initRubyEngine() {
   RUBY_INIT_STACK;
   ruby_init();
 
+  Init_ruby_description(nullptr);
```
Comment (jmarrec) [inline ruby/engine/InitRubyEngine.cpp:28]: Use it.

We don't just MJIT or YJIT, so it just doesn't use the param `ruby_cmdline_options_t *opt` anyways.

See https://github.com/ruby/ruby/blob/e51014f9c05aa65cbf203442d37fef7c12390015/version.c#L129-L162

File: ruby/test/Constants_Test.rb [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+########################################################################################################################
+
+require 'minitest/autorun'
+
+class ConstantsTest < Minitest::Test
+
+  # Note: putting all of these tests under the same one because of the way we
+  # run the tests with the CLI (we run a CLI instance for each individual test,
+  # and it takes almost 20 seconds for each which is ridiculous)
+  def test_ruby_constants
```
Comment (jmarrec) [inline ruby/test/Constants_Test.rb:13]: new test. Grouping everything under a single minitest because it is WWAAAAAY to slow otherwise with the CLI.

File: ruby/test/Constants_Test.rb [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+    assert_equal("3.2.2", RUBY_VERSION)
+
+    refute_empty(RUBY_DESCRIPTION)
+    assert_match(/ruby 3.2.2 \(.*\) \[.*\]/, RUBY_DESCRIPTION)
```
Comment (jmarrec) [inline ruby/test/Constants_Test.rb:18]: Before fix

```
Run options: --seed 12379

# Running:

E

Finished in 0.001386s, 721.3269 runs/s, 721.3269 assertions/s.

  1) Error:
ConstantsTest#test_ruby_constants:
NameError: uninitialized constant ConstantsTest::RUBY_DESCRIPTION
    eval:414:in `const_missing'
    /home/julien/Software/Others/OpenStudio/ruby/test/Constants_Test.rb:17:in `test_ruby_constants'

1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
```

File: src/model/DesignDay.cpp [hunk 5]
```diff
@@ -641,13 +641,10 @@ namespace model {
...
-      boost::optional<int> day;
-
-      month = getInt(OS_SizingPeriod_DesignDayFields::Month);
-      if (month && (month.get() == 2)) {
-        day = this->getInt(OS_SizingPeriod_DesignDayFields::DayofMonth);
-        if (day && (day.get() == 29)) {
+      boost::optional<int> month_ = getInt(OS_SizingPeriod_DesignDayFields::Month);
+      if (month_ && (*month_ == 2)) {
+        boost::optional<int> day_ = this->getInt(OS_SizingPeriod_DesignDayFields::DayofMonth);
+        if (day_ && (*day_ == 29)) {
```
Comment (jmarrec) [inline src/model/DesignDay.cpp:647]: Unrelated, but fix cppcheck workflow that has been failing for some time
