### PR TITLE
Fix #5510 - Order of Output:Meter:XXX objects (w/ different reporting frequences) in IDF are not deterministic

### LINKED ISSUE #5510: Order of Output:Meter:MeterFileOnly objects (w/ different reporting frequences) in IDF are not deterministic
Issue overview
--------------
I still see the issue where `Output:Meter:MeterFileOnly` objects in the IDF are ordered differently from run to run when using `OpenStudio::Model::OutputMeter`. It's incredibly helpful to have deterministic IDFs for diffing purposes.

This was supposed to have been fixed [here](https://github.com/NREL/OpenStudio/issues/3770). Maybe the issue is that this now only occurs for meter objects w/ the same key name but different reporting frequencies?

Example (the objects have swapped order):
Image

## Steps to Reproduce
1. Clone OpenStudio-HPXML and run: `for i in 1 2 3; do openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml -o test$i; done`
2. Compare the IDF files from the three runs and you should see a diff.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 24.04
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.10.0+86d7e215a1

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5510

I've tested  on OpenStudio-HPXML

```bash
for i in {1..10}; do $os_build_rel/Products/openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml -o test$i --debug; done
```

python:

```python
from pathlib import Path

HPXML_ROOT = Path('/home/julien/Software/Others/openstudio_gems/OpenStudio-HPXML')
idf_paths = sorted(list(HPXML_ROOT.glob('test*/run/in.idf')))
assert len(idf_paths) == 10
expected = idf_paths[0].read_text()
for idf_path in idf_paths[1:]:
    assert expected == idf_path.read_text()
```

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/ForwardTranslator.cpp [hunk 1]
```diff
@@ -174,6 +176,47 @@ namespace energyplus {
...
+    // 4. cumulative
+    const bool cumA = meterA.cumulative();
+    const bool cumB = meterB.cumulative();
+    if (cumA != cumB) {
+      return !cumA;  // A comes first if it's not cumulative
+    }
+
+    // Equal in all fields
+    return false;
+  }
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator.cpp:218]: Predicate for deterministic ordering of OutputMeters

File: src/energyplus/ForwardTranslator.cpp [hunk 2]
```diff
@@ -599,7 +642,11 @@ namespace energyplus {
 
       // get objects by type in sorted order
       std::vector<WorkspaceObject> objects = model.getObjectsByType(iddObjectType);
-      std::sort(objects.begin(), objects.end(), WorkspaceObjectNameLess());
+      if (iddObjectType == IddObjectType::OS_Output_Meter) {
+        std::sort(objects.begin(), objects.end(), OutputMeterSorterPredicate);
+      } else {
+        std::sort(objects.begin(), objects.end(), WorkspaceObjectNameLess());
+      }
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator.cpp:649]: Most meters (except children of Building) are translated here when we loop on iddObjectsToTranslate, so we sort differently then

File: src/energyplus/ForwardTranslator.cpp [hunk 3]
```diff
@@ -640,18 +687,11 @@ namespace energyplus {
...
-      std::string bname;
-      boost::optional<std::string> obname = b.name();
-      if (obname) {
-        bname = *obname;
+      if (a.iddObject().type() == IddObjectType::OS_Output_Meter) {
+        return OutputMeterSorterPredicate(a, b);
       }
-      return istringLess(aname, bname);
+
+      return WorkspaceObjectNameLess()(a, b);
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator.cpp:694]: On 16db3677740ead473e862d32beda680511b96dd8 I explained this.

Anyways, let's put it here too. This is the ChildSorter operator() comparator. Here's the explanation why it's needed:

----

I did it in two commits to be clearer...

I realized that the OutputMeter with an InstallLocationType::Building are children of the Building object.

https://github.com/NREL/OpenStudio/blob/c7f13ad61579ceacf4fbe742b9a6e0c71a14cb4d/src/model/Building.cpp#L574-L583

In FT, we instantiate the Building object earlier and translate it here:

https://github.com/NREL/OpenStudio/blob/c7f13ad61579ceacf4fbe742b9a6e0c71a14cb4d/src/energyplus/ForwardTranslator.cpp#L473-L478

And in translateAndMapModelObject, we translate the children of the object right after it

https://github.com/NREL/OpenStudio/blob/c7f13ad61579ceacf4fbe742b9a6e0c71a14cb4d/src/energyplus/ForwardTranslator.cpp#L3341-L3356

So the Meters such as "Electricity:Total" are translated right there, and not later when we iterate on iddObjectsToTranslate here

https://github.com/NREL/OpenStudio/blob/c7f13ad61579ceacf4fbe742b9a6e0c71a14cb4d/src/energyplus/ForwardTranslator.cpp#L597-L608

File: src/model/OutputMeter.hpp [hunk 4]
```diff
@@ -70,6 +70,8 @@ namespace model {
                                const boost::optional<FuelType>& fuelType, const boost::optional<InstallLocationType>& installLocationType,
                                const boost::optional<std::string>& specificInstallLocation);
 
+    static std::vector<std::string> reportingFrequencyValues();
```
Comment (jmarrec) [inline src/model/OutputMeter.hpp:73]: WAs missing

File: src/energyplus/Test/OutputMeter_GTest.cpp [hunk 5]
```diff
@@ -0,0 +1,348 @@
...
+  EXPECT_TRUE(meter.setCumulative(false));
+
+  const Workspace w = ft.translateModel(m);
+  const auto idfObjs = w.getObjectsByType(IddObjectType::Output_Meter_MeterFileOnly);
+  ASSERT_EQ(1u, idfObjs.size());
+
+  const auto& idfObject = idfObjs.front();
+  EXPECT_EQ("NaturalGas:Facility", idfObject.getString(Output_Meter_MeterFileOnlyFields::KeyName).get());
+  EXPECT_EQ("Timestep", idfObject.getString(Output_Meter_MeterFileOnlyFields::ReportingFrequency).get());
+}
```
Comment (jmarrec) [inline src/energyplus/Test/OutputMeter_GTest.cpp:78]: I added a bunch of FT/RT tests since we had zero

File: src/energyplus/Test/OutputMeter_GTest.cpp [hunk 6]
```diff
@@ -0,0 +1,348 @@
...
+    EXPECT_EQ(meterInfos.size(), newMeterInfos.size());
+    for (size_t i = 0; i < meterInfos.size(); ++i) {
+      EXPECT_EQ(meterInfos[i], newMeterInfos[i]) << "MeterInfos differ at index " << i << " on iteration " << n;
+    }
+    if (meterInfos != newMeterInfos) {
+      ++n_failures;
+    }
+  }
+  EXPECT_EQ(0, n_failures) << "Out of 9 re-translations, " << n_failures << " produced different OutputMeter orderings.";
+}
```
Comment (jmarrec) [inline src/energyplus/Test/OutputMeter_GTest.cpp:385]: Specific testing for the #5510. It fails without fix.
