### PR TITLE
Fix #3314 - GBXML translate spaces etc even if Facility and/or Building aren't instantiated

### LINKED ISSUE #3314: gbXML translation does not roundtrip unless Facility object present
The following code will fail unless the model has a Facility object present

```
  ForwardTranslator forwardTranslator;
  bool test = forwardTranslator.modelToGbXML(model, p);

  EXPECT_TRUE(test);

  // Read the XML back in and check the surface
  ReverseTranslator reverseTranslator;
  boost::optional<Model> model2 = reverseTranslator.loadModel(p);

  ASSERT_TRUE(model2);
```

Also, Spaces will not be translated without a Building.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fix #3314 
 - GBXML translate spaces etc even if Facility and/or Building aren't isntantianted

Also fix a ReverseTranslator issue that I found where the Material `Roughness` ends up empty.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/gbxml/ForwardTranslator.hpp [hunk 1]
```diff
@@ -92,8 +92,12 @@ namespace gbxml {
 
     // listed in translation order
     bool translateModel(const openstudio::model::Model& model, pugi::xml_document& document);
-    boost::optional<pugi::xml_node> translateFacility(const openstudio::model::Facility& facility, pugi::xml_node& parent);
-    boost::optional<pugi::xml_node> translateBuilding(const openstudio::model::Building& building, pugi::xml_node& parent);
+
+    // Facility and Building could not be explicitly instantiated in the model, but the functions still need to be called so that Spaces and surfaces
+    // are translated. Facility and Building both are UniqueModelObjects, so passing model here as an argument is harmless
+    boost::optional<pugi::xml_node> translateFacility(const openstudio::model::Model& model, pugi::xml_node& parent);
+    boost::optional<pugi::xml_node> translateBuilding(const openstudio::model::Model& model, pugi::xml_node& parent);
```
Comment (jmarrec) [inline src/gbxml/ForwardTranslator.hpp:99]: Private methods now take `model` instead of `facility` / `building`. And in there it will conditionally check if there is a facility / building to use or default things.

File: src/gbxml/ForwardTranslator.cpp [hunk 2]
```diff
@@ -412,35 +411,36 @@ namespace gbxml {
...
-    m_translatedObjects[facility.handle()] = result;
+    std::string name = "Facility";
 
-    boost::optional<std::string> name = facility.name();
+    if (_facility) {
+      m_translatedObjects[_facility->handle()] = result;
+      if (auto _s = _facility->name()) {
+        name = _s.get();
+      }
+    }
```
Comment (jmarrec) [inline src/gbxml/ForwardTranslator.cpp:428]: Check if there is an actual explicitly instantiated Facility object to use, otherwise default things.

File: src/gbxml/ForwardTranslator.cpp [hunk 3]
```diff
@@ -412,35 +411,36 @@ namespace gbxml {
...
-    // translate building
-    boost::optional<model::Building> building = model.getOptionalUniqueModelObject<model::Building>();
-    if (building) {
-      translateBuilding(*building, result);
-    }
+    // translate building: needs to be done even if not explicitly instantiated since that's what translates Spaces in particular.
+    translateBuilding(model, result);
 
     // translate surfaces
+    // TODO: JM 2020-06-18 Why is translateSpace not responsible to call this one?
```
Comment (jmarrec) [inline src/gbxml/ForwardTranslator.cpp:443]: I find it strange that the Surfaces are translated in translateFacility
