### PR TITLE
Remove curves when deleting them directly or deleting a ParentObject if the curves end up unused

### LINKED ISSUE #3153: .remove does not work for Curve objects
Expected behavior is that adding a Curve object to an empty .osm can then be deleted with the .remove method.  This doesn't happen and the curve stays in the model.  Issue exists in at least OS v2.4 on, possibly earlier.

Example:

INPUT
```
require 'openstudio'

# make an empty model
model = OpenStudio::Model::Model.new

curve = OpenStudio::Model::CurveBiquadratic.new(model)
construction = OpenStudio::Model::Construction.new(model)
space_type = OpenStudio::Model::SpaceType.new(model)
schedule = OpenStudio::Model::ScheduleWeek.new(model)
material = OpenStudio::Model::StandardOpaqueMaterial.new(model)

puts "***MODEL BEFORE***"
puts model

puts "*** REMOVE OBJECTS ***"
remove_curve = curve.remove
puts "remove_curve: #{remove_curve}"

remove_construction = construction.remove
puts "remove_construction: #{remove_construction}"

remove_space_type = space_type.remove
puts "remove_space_type: #{remove_space_type}"

remove_schedule = schedule.remove
puts "remove_schedule: #{remove_schedule}"

remove_material = material.remove
puts "remove_material: #{remove_material}"

puts "\n***MODEL AFTER***"
puts model

```

OUTPUT
```
***MODEL BEFORE***

OS:Version,
  {a52164a1-a0cb-4967-8ebe-12c57cc2e747}, !- Handle
  2.5.1;                                  !- Version Identifier

OS:Curve:Biquadratic,
  {8a751692-e69f-4057-a802-1cfd88a7e09b}, !- Handle
  Curve Biquadratic 1,                    !- Name
  0,                                      !- Coefficient1 Constant
  0,                                      !- Coefficient2 x
  0,                                      !- Coefficient3 x**2
  0,                                      !- Coefficient4 y
  0,                                      !- Coefficient5 y**2
  0,                                      !- Coefficient6 x*y
  0,                                      !- Minimum Value of x
  1,                                      !- Maximum Value of x
  0,                                      !- Minimum Value of y
  1;                                      !- Maximum Value of y

OS:Construction,
  {87aee8e4-d22b-4170-ae76-5eff2acda03d}, !- Handle
  Construction 1,                         !- Name
  ;                                       !- Surface Rendering Name

OS:SpaceType,
  {448c16a8-8596-4e75-ad50-fdf11894088b}, !- Handle
  Space Type 1;                           !- Name

OS:Schedule:Week,
  {6202bc71-2132-4fd3-91a0-a62afcb3aa2c}, !- Handle
  Schedule Week 1,                        !- Name
  ,                                       !- Schedule Rendering Name
  ,                                       !- Sunday Schedule:Day Name
  ,                                       !- Monday Schedule:Day Name
  ,                                       !- Tuesday Schedule:Day Name
  ,                                       !- Wednesday Schedule:Day Name
  ,                                       !- Thursday Schedule:Day Name
  ,                                       !- Friday Schedule:Day Name
  ,                                       !- Saturday Schedule:Day Name
  ,                                       !- Holiday Schedule:Day Name
  ,                                       !- SummerDesignDay Schedule:Day Name
  ,                                       !- WinterDesignDay Schedule:Day Name
  ,                                       !- CustomDay1 Schedule:Day Name
  ;                                       !- CustomDay2 Schedule:Day Name

OS:Material,
  {5b35f997-9e76-465a-8904-1393845eaf5f}, !- Handle
  Material 1,                             !- Name
  Smooth,                                 !- Roughness
  0.1,                                    !- Thickness {m}
  0.1,                                    !- Conductivity {W/m-K}
  0.1,                                    !- Density {kg/m3}
  0.1;                                    !- Specific Heat {J/kg-K}

*** REMOVE OBJECTS ***
remove_curve: []
remove_construction: [#<OpenStudio::IdfObject:0x0000000774ce10 @__swigtype__="_p_openstudio__IdfObject">]
remove_space_type: [#<OpenStudio::IdfObject:0x0000000774caf0 @__swigtype__="_p_openstudio__IdfObject">]
remove_schedule: [#<OpenStudio::IdfObject:0x0000000774c870 @__swigtype__="_p_openstudio__IdfObject">]
remove_material: [#<OpenStudio::IdfObject:0x0000000774c708 @__swigtype__="_p_openstudio__IdfObject">]

***MODEL AFTER***

OS:Version,
  {a52164a1-a0cb-4967-8ebe-12c57cc2e747}, !- Handle
  2.5.1;                                  !- Version Identifier

OS:Curve:Biquadratic,
  {8a751692-e69f-4057-a802-1cfd88a7e09b}, !- Handle
  Curve Biquadratic 1,                    !- Name
  0,                                      !- Coefficient1 Constant
  0,                                      !- Coefficient2 x
  0,                                      !- Coefficient3 x**2
  0,                                      !- Coefficient4 y
  0,                                      !- Coefficient5 y**2
  0,                                      !- Coefficient6 x*y
  0,                                      !- Minimum Value of x
  1,                                      !- Maximum Value of x
  0,                                      !- Minimum Value of y
  1;                                      !- Maximum Value of y
```

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3153
 - When deleting a curve directly, or deleting an object that uses a curve, the curve is **never** deleted. This updates ParentObject_Impl::remove() to delete curves if they end up orphaned (unused). 

The historical behavior dates from @kbenne's commit https://github.com/NREL/OpenStudio/commit/aad243b46aab465671c43b163956b5f22216dfab when `Curve`s were made `ResourceObject`s

**Note: This is quite a significant change in functionality compared to historical, so it should be reviewed and weighted carefully.**

An alternative is to only allow direct deletion of a curve (eg: curve.remove()), but never delete when it's a parent that is being deleted.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [x] Model API Changes / Additions
 - [x] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate): N/A
 - [x] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`): N/A
 - [x] If a new object or method, added a test in NREL/OpenStudio-resources: N/A
 - [x] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`): N/A
 - [x] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`): N/A
 - [x] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes
 - [x] If methods have been deprecated, update rest of code to use the new methods: N/A

**Labels:**

 - [x] If change to an IDD file, add the label `IDDChange`: N/A
 - [x] If breaking existing API, add the label `APIChange`: **this isn't breaking API per se, but it's a significant change so marking it anyways**
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/ParentObject.cpp [hunk 1]
```diff
@@ -88,14 +88,16 @@ namespace detail {
...
+
+    // drop the Curve instances, if they are used by other objects
     // Perhaps this could be done in the getRecursiveChildren, but this way
     // the getRecursiveChildren method might be less surprising
     // This is probably the unique situation where you want to get children minus curves
-    auto isCurve = [](const ModelObject & modelObject) {
-      return modelObject.optionalCast<Curve>();
+    auto isUsedCurve = [](const ModelObject & modelObject) {
+      auto _curve = modelObject.optionalCast<Curve>();
+      return (_curve && _curve->directUseCount() > 1);
```
Comment (jmarrec) [inline src/model/ParentObject.cpp]: Alternative:

```
auto isCurve = [this](const ModelObject & modelObject) {
   return modelObject.optionalCast<Curve>() && (modelObject.handle() != this->handle());
}
```

Or, just override remove and test in `Curve_Impl::remove`: cf https://github.com/NREL/OpenStudio/issues/3153#issuecomment-416371906

Comment (kbenne) [reply src/model/ParentObject.cpp]: Yeah. Why can't this just be implemented in Curve_Impl::remove? I don't care for the type checking in the base class. I know there was some already there before you did this @jmarrec, but maybe now is the time to clean it up.

Comment (jmarrec) [reply src/model/ParentObject.cpp]: Curve_Impl::remove is never called if you are trying to remove a ParentObject. https://github.com/NREL/OpenStudio/blob/156dca45c0ed89ca4386bbe14cca530c11b9fbef/src/model/ParentObject.cpp#L80:L87

Comment (kbenne) [reply src/model/ParentObject.cpp]: Do you think that perhaps this filtering and behavior should happen for all ResourceObjects that are the child of a parent object? The fact that we are treating Curves in a special way concerns me a little bit.

Comment (jmarrec) [reply src/model/ParentObject.cpp]: I'm not sure I'd want to delete a now-unused `SpaceLoadDefinition` object if I remove the parent `SpaceLoadInstance`. And neither remove a `SpaceLoadInstance` if I remove the `Space`/`SpaceType` attached to it. (I also though about constructions, but apparently they never get parented)

Thinking about it a bit more, I think the main difference between curves and the rest is probably stemming from two things:
* Primary: We instantiate a lot of default curves in constructors because they are required properties, especially HVAC/ZoneHVAC objects. So that ends up bloating the model a ton more than any other `ResourceObject`
* Secondary (and a bad justification probably): the OS App (still) has no way to edit, add, or remove Curve objects, so it's much harder to clean up stuff.

Comment (kbenne) [reply src/model/ParentObject.cpp]: ok well that seems like enough justification to me. I'll go ahead and merge this.
