### PR TITLE
Fix #4994 - Old materials OSC (< 0.7.4) cannot be loaded anymore

### LINKED ISSUE #4994: Old materials OSC (< 0.7.4) cannot be loaded anymore
Issue overview
--------------

Old components like `Brick - Fired Clay - 4 in. - 130 lb/ft3` cannot be loaded anymore

## Steps to Reproduce

get `Brick - Fired Clay - 4 in. - 130 lb/ft3` from BCL.

Try to load it 

```
$ openstudio -e "vt = OpenStudio::OSVersion::VersionTranslator.new; c = vt.loadComponent('Brick_Fired_Clay_4_in_130_lb_ft3.osc')"
[utilities.idf.IdfFile] <1> Could not parse a single valid object in file.
[openstudio.model.Component] <2> Cannot construct Component from IdfFile because the file contains 0 ComponentData objects.
[openstudio.osversion.VersionTranslator] <1> Could not translate component, because /Users/julien/Software/Others/OpenStudio/src/model/Component.cpp@186 : Cannot construct Component from IdfFile because the file contains 0 ComponentData objects.
```

## Possible Solution

Issue (found from using a debugger) is the conjunction of what `update_0_7_3_to_0_7_4` does and what I added here: https://github.com/NREL/OpenStudio/blob/de661404d2ed08ef38198bf28239d2c5d89173be/src/osversion/VersionTranslator.cpp#L524

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.6.1 (Started at 3.5.1 really)

### Context

Reported at https://unmethours.com/question/97118/the-material-downloaded-from-bcl-can-not-be-dropped-on-materials-tab/

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4994

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/osversion/test/VersionTranslator_GTest.cpp [hunk 1]
```diff
@@ -4604,3 +4604,27 @@ TEST_F(OSVersionFixture, update_3_9_0_to_3_10_0_SpaceInfiltrationDesignFlowRate)
   EXPECT_EQ(0.2, si.getDouble(12).get());
   EXPECT_EQ("Outdoor", si.getString(13).get());  // Density Basis
 }
+
+TEST_F(OSVersionFixture, can_still_load_older_components) {
+  // see #4994 - Old materials OSC (< 0.7.4) cannot be loaded anymore
+  openstudio::path p = resourcesPath() / toPath("osversion/0_7_0/Brick_Fired_Clay_4_in_130_lb_ft3.osc");
+  osversion::VersionTranslator vt;
+  boost::optional<model::Component> comp_ = vt.loadComponent(p);
+  ASSERT_TRUE(comp_) << "Failed to load Component " << p;
```
Comment (jmarrec) [inline src/osversion/test/VersionTranslator_GTest.cpp:4613]: Fails before fix.

File: src/osversion/VersionTranslator.cpp [hunk 2]
```diff
@@ -514,7 +516,8 @@ namespace osversion {
         return;
       }
       IdfFile idfFile = *oIdfFile;
-      if (m_isComponent) {
+      if (m_isComponent && (is_component_update_needed || (lastVersion > VersionString(0, 7, 4)))) {
+        is_component_update_needed = true;
         updateComponentData(idfFile);
```
Comment (jmarrec) [inline src/osversion/VersionTranslator.cpp:521]: Start updating component stuff only after 0.7.4

**Review by joseph-robertson — COMMENTED** [review]
I'm out of depth here. Why does the version need to be > 0.7.4 to update component data? Is this because as of 0.7.4 the idd is without `OS:ComponentData:Attributes` and `OS:ComponentData:Tags` objects? Shouldn't we be updating components _starting with_ 0.7.4?

**Comment by jmarrec** [comment]
Yes, there is something specific related to Components https://github.com/NREL/OpenStudio/blob/d9b47f865abd46c20a34464e73e48aa6eb0d4520/src/osversion/VersionTranslator.cpp#L653

updateComponentData deals with the extensible groups, removing anything you may have removed from it.
