### PR TITLE
Fix #5464 - Properly handle "Separator" argument

### LINKED ISSUE #5464: Separator argument type causes validation error
Issue overview
--------------
The C++ CLI does not appear to support measure arguments of type Separator.

## Current Behavior
I get this error when running the measure:

`[BOOST_ASSERT] <2> Assertion false failed on line 585 of bool openstudio::measure::OSRunner::validateUserArguments(const std::vector<openstudio::measure::OSArgument>&, const std::map<std::__cxx11::basic_string<char>, openstudio::measure::OSArgument>&) in file /srv/jenkins/openstudio/git/nightly/ubuntu_2404/Openstudio/src/measure/OSRunner.cpp.`

## Expected Behavior
The measure should run successfully.

## Steps to Reproduce
1. Add this to the `arguments()` section of a measure:

```
arg = OpenStudio::Measure::OSArgument.makeSeparatorArgument('foo')
args << arg
```

2. Run the measure and observe the error.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 24.04
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.10.0+86d7e215a1

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5464
 - Skip validating the Separator argument types to avoid OS_ASSERT later
 - Add it as a valid enumeration choice in measure 3.1 schema

### Pull Request Author

 - [x] Code Change
 - [x] All new and existing tests passes

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/measure/OSRunner.cpp [hunk 1]
```diff
@@ -409,6 +409,10 @@ namespace measure {
     bool result = true;
     std::vector<WorkflowStepValue> stepValues;
     for (const OSArgument& script_argument : script_arguments) {
+      if (script_argument.type().value() == OSArgumentType::Separator) {
+        // skip separators
+        continue;
+      }
```
Comment (jmarrec) [inline src/measure/OSRunner.cpp:415]: No point validating it.

File: src/measure/test/OSMeasure_GTest.cpp [hunk 2]
```diff
@@ -457,3 +458,90 @@ TEST_F(MeasureFixture, UserScript_TestModelUserScriptDomain) {
...
+
+  virtual std::vector<OSArgument> arguments(const Model& /*model*/) const override {
+    std::vector<OSArgument> result;
+
+    OSArgument arg = OSArgument::makeDoubleArgument("double_arg", true);
+    arg.setMaxValue(10.0);
+    result.push_back(arg);
+
+    arg = OSArgument::makeSeparatorArgument("separator");
+    result.push_back(arg);
```
Comment (jmarrec) [inline src/measure/test/OSMeasure_GTest.cpp:478]: New Test, failing before

File: src/measure/test/OSMeasure_GTest.cpp [hunk 3]
```diff
@@ -457,3 +458,90 @@ TEST_F(MeasureFixture, UserScript_TestModelUserScriptDomain) {
...
+  StringStreamLogSink sink;
+  sink.setLogLevel(Fatal);
+
+  // call with a good value
+  double_arg.setValue(-1.0);
+  int_arg.setValue(1.0);
+  EXPECT_TRUE(measure.run(model, runner, argumentMap));
+
+  EXPECT_EQ(0, sink.logMessages().size()) << sink.string();
+  sink.resetStringStream();
```
Comment (jmarrec) [inline src/measure/test/OSMeasure_GTest.cpp:524]: Fails before

```
[ RUN      ] MeasureFixture.ModelMeasureWithSeparator
/media/DataExt4/Software/Others/OpenStudio3/src/measure/test/OSMeasure_GTest.cpp:523: Failure
Expected equality of these values:
  0
  sink.logMessages().size()
    Which is: 1
[BOOST_ASSERT] <2> Assertion false failed on line 585 of bool openstudio::measure::OSRunner::validateUserArguments(const std::vector<openstudio::measure::OSArgument>&, const std::map<std::__cxx11::basic_string<char>, openstudio::measure::OSArgument>&) in file /media/DataExt4/Software/Others/OpenStudio3/src/measure/OSRunner.cpp.
```

File: src/utilities/xml/resources/bcl/measure_v3.1.xsd [hunk 4]
```diff
@@ -87,6 +87,7 @@
 										<xs:enumeration value="String"/>
 										<xs:enumeration value="Choice"/>
 										<xs:enumeration value="Path"/>
+										<xs:enumeration value="Separator"/>
```
Comment (jmarrec) [inline src/utilities/xml/resources/bcl/measure_v3.1.xsd:90]: This was missing cf https://github.com/NREL/OpenStudio/issues/5464#issuecomment-3209354052

Comment (shorowit) [reply src/utilities/xml/resources/bcl/measure_v3.1.xsd:90]: Ah yes, I see there was a second error before: 
```
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1840: Element 'type': [facet 'enumeration'] The value 'Separator' is not an element of the set {'Boolean', 'Double', 'Integer', 'String', 'Choice', 'Path'}.
```

**Review by shorowit — APPROVED** [review]
Tested the Windows build and got no errors, LGTM. Thanks @jmarrec!
