### PR TITLE
#4663 #4664 - Fix CoilCoolingDXMultiSpeed::clone and extend testing for AirLoopHVAC::clone

### LINKED ISSUE #4663: multi speed DX coil stage mapping does not clone properly with airloop
Issue overview
--------------

## Current Behavior

When I clone an airloop with multi speed DX coils using the OS API, the coils themselves are cloned properly, as well as their corresponding stages (dx multi speed stage data objects). But the stage assignments do not map over (the stage fields in the coil object are blank)

## Expected Behavior

It should work.

## Steps to Reproduce

Let me know what details you need to investigate. I don't think it makes sense to attach a model will blank fields as evidence. It wouldn't really show anything...

### Environment

Some additional details about your environment for this issue (if relevant):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.4.0

### LINKED ISSUE #4664: terminal clones with airloop but then cannot be connected to zone
I'm cloning an airloop with a terminal. The terminal and some connections (zone splitter and mixer) come through but it is not connected to any zone. It makes sense that it would not be connected to a zone but the problem is that I can't seem to find a way to connect it to a zone once it has been cloned over. I tried:

1. Using addBranchForZone directly (no error but the terminal didn't get connected to the zone)
2. First using disconnect and then addBranchForZone (same outcome)

To get things to work I had to remove and rebuild the terminal from scratch and then use addBranchForZone 

I've attached the model I get after running clone so you can see what connections come through.

[Terminal_Bug.zip](https://github.com/NREL/OpenStudio/files/9445840/Terminal_Bug.zip)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4663
 - Fixes #4664

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/CoilCoolingDXMultiSpeed_GTest.cpp [hunk 1]
```diff
@@ -270,3 +272,38 @@ TEST_F(ModelFixture, CoilCoolingDXMultiSpeed_Remove) {
...
+    std::vector<CoilCoolingDXMultiSpeedStageData> stages2 = cc2.stages();
+    EXPECT_EQ(2u, stages2.size());
+    EXPECT_EQ(2u, m.getConcreteModelObjects<CoilCoolingDXMultiSpeed>().size());
+    EXPECT_EQ(4u, m.getConcreteModelObjects<CoilCoolingDXMultiSpeedStageData>().size());
+    for (auto& stage : stages) {
+      EXPECT_TRUE(std::find_if(stages2.cbegin(), stages2.cend(), [&stage](const auto& s) { return s.handle() == stage.handle(); }) == stages2.cend())
+        << "Did not expect to find, in the cloned Coil, the CoilCoolingDXMultiSpeedStageData '" << stage.nameString() << "'";
+    }
+  }
+}
```
Comment (jmarrec) [inline src/model/test/CoilCoolingDXMultiSpeed_GTest.cpp:309]: New test for CoilCoolingDXMultiSpeed::clone. Originally it fails

File: src/model/test/CoilCoolingDXMultiSpeed_GTest.cpp [hunk 2]
```diff
@@ -270,3 +272,38 @@ TEST_F(ModelFixture, CoilCoolingDXMultiSpeed_Remove) {
...
+    EXPECT_EQ(2u, cc2.stages().size());
+    EXPECT_EQ(1u, m2.getConcreteModelObjects<CoilCoolingDXMultiSpeed>().size());
+    EXPECT_EQ(2u, m2.getConcreteModelObjects<CoilCoolingDXMultiSpeedStageData>().size());
+  }
+
+  {
+    // Same model: we expect stages to be cloned and reassigned to the clone
+    auto cc2 = cc.clone(m).cast<CoilCoolingDXMultiSpeed>();
+    std::vector<CoilCoolingDXMultiSpeedStageData> stages2 = cc2.stages();
+    EXPECT_EQ(2u, stages2.size());
```
Comment (jmarrec) [inline src/model/test/CoilCoolingDXMultiSpeed_GTest.cpp:301]: Original: fails because it's 4

File: src/model/CoilCoolingDXMultiSpeed.cpp [hunk 3]
```diff
@@ -285,6 +285,8 @@ namespace model {
     ModelObject CoilCoolingDXMultiSpeed_Impl::clone(Model model) const {
       auto t_clone = StraightComponent_Impl::clone(model).cast<CoilCoolingDXMultiSpeed>();
 
+      // Deal with the stages: we want them cloned, so first clear and then clone + assign each
+      t_clone.removeAllStages();
```
Comment (jmarrec) [inline src/model/CoilCoolingDXMultiSpeed.cpp:289]: Fix https://github.com/NREL/OpenStudio/issues/4663#issuecomment-1247830322

File: src/model/test/AirLoopHVAC_GTest.cpp [hunk 4]
```diff
@@ -1478,6 +1480,198 @@ TEST_F(ModelFixture, AirLoopHVAC_singleDuct_Clone) {
...
+    auto coolingCoil2 = a2.components(openstudio::IddObjectType::OS_Coil_Cooling_Water)[0].cast<CoilCoolingWater>();
+    ASSERT_TRUE(coolingCoil2.plantLoop());
+    EXPECT_EQ(chw_loop, coolingCoil2.plantLoop().get());
+
+    ASSERT_EQ(1, a2.components(openstudio::IddObjectType::OS_Coil_Heating_Water).size());
+    auto heatingCoil2 = a2.components(openstudio::IddObjectType::OS_Coil_Heating_Water)[0].cast<CoilHeatingWater>();
+    ASSERT_TRUE(heatingCoil2.plantLoop());
+    EXPECT_EQ(hw_loop, heatingCoil2.plantLoop().get());
+  }
+}
```
Comment (jmarrec) [inline src/model/test/AirLoopHVAC_GTest.cpp:1673]: New full test for #4664

**Comment by jmarrec** [comment]
@mleachNREL If you could try out one of the installers listed above in https://github.com/NREL/OpenStudio/pull/4683#issuecomment-1247929804 that would be awesome.
