### PR TITLE
Fix #4837 - Geometry improvements - Detect incorrectly oriented surfaces in spaces, non convex spaces

### LINKED ISSUE #4837: Detect incorrectly oriented surfaces in spaces (Autocalculated volumes for some spaces are incorrect otherwise)
Issue overview
--------------
In between OS 3.2.1 and OS 3.5.1 there appears to have been a change in how volumes are calculated.  In OS 3.5.1 some spaces whose volume calculation method is either not set or is set to 'autocalculateVolume' return incorrect volumes when the '.volume' method is used.  This behavior is in OS 3.2.1 as well but to a lesser extent.

## Current Behavior
In OS 3.5.1 (and to a lesser degree OS 3.2.1) the '.volume' method returns incorrect volumes for some spaces whose volume is autocalculated.

## Expected Behavior
The value returned by the '.volume' method should be correct for all autocalculated spaces.

## Steps to Reproduce
1.  Download the attached 'test_file.txt' and then change the .txt extension to .osm.
2.  Use OpenStudio API space.volume method to return the volumes of the three spaces in the file.  Do this using both OS 3.2.1 and OS 3.5.1.
3.  Look at the geometry of the spaces and calculate their volumes manually.
4.  Compare the results.

[test_file.txt](https://github.com/NREL/OpenStudio/files/11041010/test_file.txt)

I did the above and got the following results:

|  Space Name                 |  OS 3.2.1 Vol. (m3)    |  OS 3.5.1 Vol. (m3)    |   Man. Calc. Vol. (m3)    |
|  ------------------------  |  ---------------------  |  --------------------- | ------------------------  |
|  Zone 1 Office               |   1011                        |  1011                        |  1011                            | 
|  Zone 2 Fine Storage     |  9513                         |  2953                       |  10876                          |
|  Zone 3 Bulk Storage    |  27350                        |  35278                     |  27338                          | 

## Details
See above.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):  Ubuntu 22.04 for OS 3.5.1, Ubuntu 18.04 for OS 3.2.1 (both are based on the release versions of their respective NREL/openstudio Docker images)
 - Version of OpenStudio (if using an intermediate build, include SHA):  OS 3.2.1 and OS 3.5.1

### Context
We use the volume of spaces for many things including calculating average ceiling heights and a variety of normalizations.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4837 

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/Space_GTest.cpp [hunk 1]
```diff
@@ -3220,10 +3230,508 @@ TEST_F(ModelFixture, Space_Polyhedron_Volume) {
...
+    auto s_ = Space::fromFloorPrint(points, 2, m, "rectangularPolygon");
+    ASSERT_TRUE(s_);
+    auto [x, y] = getPos(counter++);
+    s_->setXOrigin(x);
+    s_->setYOrigin(y);
+    EXPECT_TRUE(s_->isConvex());
+    EXPECT_TRUE(s_->findNonConvexSurfaces().empty());
+  }
+
+  // m.save("Test_convexity.osm", true);
```
Comment (jmarrec) [inline src/model/test/Space_GTest.cpp:3709]: This tests the StandardShapes.hpp and the Space::isConvex / Space::findNonConvexSurfaces.

Resulting model:

Regular_shapes

File: src/model/Space.cpp [hunk 2]
```diff
@@ -918,6 +924,121 @@ namespace model {
       return result;
     }
 
+    std::vector<Surface> Space_Impl::findSurfacesWithIncorrectOrientationRaycasting() const {
```
Comment (jmarrec) [inline src/model/Space.cpp:927]: This was my original method to detect incorrect orientations. But it doesn't work for non convex spaces. This is unused at the moment, but not exposed publicly. I am not remove the code because there might be other applications (calculating viewFactors for eg).

Anyways the idea was to take the surface's outwardNormal, reverse it so it points inward, then shoot a ray in that direction from the centroid of the surface. You then check if any other surface's plane receives the ray. if you can't find any, the outward normal is reversed.

File: src/model/Space.cpp [hunk 3]
```diff
@@ -918,6 +924,121 @@ namespace model {
...
+        if (!found) {
+          result.push_back(surface);
+        }
+      }
+
+      return result;
+    }
+
+    std::vector<Surface> Space_Impl::findSurfacesWithIncorrectOrientationPolyhedron(const Polyhedron& volumePoly) const {
+      auto sf3ds = volumePoly.findSurfacesWithIncorrectOrientation();
```
Comment (jmarrec) [inline src/model/Space.cpp:985]: This used the Polyhedron::findSurfacesWithIncorrectOrientation which checks edges. It works even if not enclosed, and not convex.

File: src/model/Space.cpp [hunk 4]
```diff
@@ -918,6 +924,121 @@ namespace model {
...
+      for (auto& surface : surfaces) {
+        auto vertices = surface.vertices();
+
+        LOG(Error, "In Space '" << nameString() << "', Surface '" << surface.nameString()
+                                << "' has an outward normal pointing in the wrong direction. Flipping it.");
+        std::reverse(vertices.begin(), vertices.end());
+        surface.setVertices(openstudio::reorderULC(vertices));
+      }
+      return true;
+    }
```
Comment (jmarrec) [inline src/model/Space.cpp:1040]: This reverses the incorrectly oriented surfaces.

File: src/model/Space.cpp [hunk 5]
```diff
@@ -926,17 +1047,24 @@ namespace model {
...
+                                        "Falling back to ceilingHeight * floorArea. Volume calculation will be potentially inaccurate.");
       }
 
-      LOG(Warn, briefDescription() << " is not enclosed, there are " << edgesNot2.size()
-                                   << " edges that aren't used exactly twice. Volume calculation will be potentially inaccurate");
-
-      double result = 0;
-
-      result = this->ceilingHeight() * this->floorArea();
+      const double result = this->ceilingHeight() * this->floorArea();
```
Comment (jmarrec) [inline src/model/Space.cpp:1067]: New Space::volume logic to dispatch and LOG whenever the space is non enclosed, or has incorrectly oriented surfaces.

File: src/model/Space.cpp [hunk 6]
```diff
@@ -2798,6 +2926,22 @@ namespace model {
...
+      }
+      Surface3d sf3d(points, fmt::format("{} floorPrint", nameString()), 0);
+      return sf3d.isConvex();
+    }
+
+    std::vector<Surface> Space_Impl::findNonConvexSurfaces() const {
+      auto surfaces = this->surfaces();
+      surfaces.erase(std::remove_if(surfaces.begin(), surfaces.end(), [](const auto& surface) { return surface.isConvex(); }), surfaces.end());
+      return surfaces;
+    }
```
Comment (jmarrec) [inline src/model/Space.cpp:2943]: Implementation for Space::isConvex / Space::findNonConvexSurfaces

File: src/utilities/geometry/Plane.hpp [hunk 7]
```diff
@@ -44,14 +44,11 @@ class Point3d;
 class Vector3d;
 
 /** Plane defines an infinite plane in 3D space.  The equation of a plane is
-   *  a*x + b*y + c*z = d, any point that satisfies this equation is on the plane.
+   *  a*x + b*y + c*z + d = 0, any point that satisfies this equation is on the plane.
```
Comment (jmarrec) [inline src/utilities/geometry/Plane.hpp:47]: This incorrect comment made me loose hours. I couldn't understand why the results where incorrect even though I was sure my math was correct.

File: src/utilities/geometry/Plane.hpp [hunk 8]
```diff
@@ -102,6 +104,13 @@ class UTILITIES_API Plane
   /// coefficient d
   double d() const;
 
+  // Returns any Point3d that's on this plane
+  Point3d anyPointOnPlane() const;
+
+  /** Project a directed ray towards a plane and returns the intersection point if any. The RayDirection should be shooting TOWARDS the plane
+    * If enforceDirectionOfPlane is true, the ray direction and the plane outward normal must be facing each other */
+  boost::optional<Point3d> rayIntersection(const Point3d& rayOrigin, const Vector3d& rayDirection, bool enforceDirectionOfPlane = false) const;
```
Comment (jmarrec) [inline src/utilities/geometry/Plane.hpp:112]: New Plane methods for getting any point3d on a plane, and to calculate the intersection point with a directed ray

File: src/utilities/geometry/Plane.cpp [hunk 9]
```diff
@@ -62,21 +55,21 @@ Plane::Plane(const Point3d& point, const Vector3d& outwardNormal) {
...
-  double det = m(0, 0) * m(1, 1) * m(2, 2) + m(0, 1) * m(1, 2) * m(2, 0) + m(0, 2) * m(1, 0) * m(2, 1) - m(0, 2) * m(1, 1) * m(2, 0)
-               - m(0, 1) * m(1, 0) * m(2, 2) - m(0, 0) * m(1, 2) * m(2, 1);
+  const double det = m(0, 0) * m(1, 1) * m(2, 2) + m(0, 1) * m(1, 2) * m(2, 0) + m(0, 2) * m(1, 0) * m(2, 1) - m(0, 2) * m(1, 1) * m(2, 0)
+                     - m(0, 1) * m(1, 0) * m(2, 2) - m(0, 0) * m(1, 2) * m(2, 1);
   return det;
 }
 
 Plane::Plane(const std::vector<Point3d>& points) : m_a(0.0), m_b(0.0), m_c(0.0), m_d(0.0) {
-  size_t N = points.size();
+  const size_t N = points.size();
```
Comment (jmarrec) [inline src/utilities/geometry/Plane.cpp:64]: const correctness in entire geometry subfolder.

File: src/utilities/geometry/Plane.cpp [hunk 10]
```diff
@@ -341,7 +334,70 @@ double Plane::d() const {
...
+
+  const double v0 = -(thisOutwardNormal.dot(rayOrigin - p0) + m_d);
+  const double t = v0 / vd;
+  LOG(Trace, "vd=" << vd << ", v0=" << v0 << ", t=" << t);
+  if (t > 0.0) {
+    return rayOrigin + t * rayDirection;
+  }
+
+  return {};
+}
```
Comment (jmarrec) [inline src/utilities/geometry/Plane.cpp:397]: Implement the new plane methods.

File: src/utilities/geometry/Polyhedron.cpp [hunk 11]
```diff
@@ -58,136 +67,246 @@ bool Surface3dEdge::operator!=(const Surface3dEdge& other) const {
...
+    auto ac = c - a;
+
+    auto triangleNormal = ab.cross(ac);
+    auto d = outwardNormal.dot(triangleNormal);
+    if (d < 0) {
+      return false;
+    }
+  }
+  return true;
+}
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.cpp:197]: Convexity of a Surface3d: for each triangle of 3 points, we compute the triangleNormal by taking the cross product of AB x AC. We then take the dot product with the initial outwardNormal. If the dot product is negative, this means the triangleNomal is pointing in the opposite direction and we therefore have a non convex / concave surface.

File: src/utilities/geometry/Polyhedron.cpp [hunk 12]
```diff
@@ -58,136 +67,246 @@ bool Surface3dEdge::operator!=(const Surface3dEdge& other) const {
...
+  if (!m_isEnclosedVolume) {
+    LOG(Warn, "Polyhedron is not enclosed.");
+  } else {
+    // We call the volume calculation... if this ends up being negative, we're in the case where ALL surfaces are in the wrong orientation
+    if (!m_hasAnySurfaceWithIncorrectOrientation) {
+      m_polyhedronVolume = calcPolyhedronVolume();
+      if (m_polyhedronVolume < 0) {
+        LOG(Error, "It seems that ALL surfaces are reversed");
+        m_hasAnySurfaceWithIncorrectOrientation = true;
+        m_isCompletelyInsideOut = true;
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.cpp:218]: Catch the case where ALL surfaces are inside out.... If we initially didn't find any orientation issues, but the Polyhedron's volume is negative, then it is inside out.

File: src/utilities/geometry/Polyhedron.cpp [hunk 13]
```diff
@@ -58,136 +67,246 @@ bool Surface3dEdge::operator!=(const Surface3dEdge& other) const {
...
+              edge1.appendSurface(surface2);
+              edge2.appendSurface(surface1);
+              if (!edge1.reverseEqual(edge2)) {
+                edge1.markConflictedOrientation();
+                edge2.markConflictedOrientation();
+                m_hasAnySurfaceWithIncorrectOrientation = true;
+              }
+            }
+          }
+        }
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.cpp:270]: Performing edge matching, in one go we pair the edges (later we can check that edge.count() == 2, any Polyhedron which has edges where count() != 2 is not enclosed), and we also check if that edge matches **in reverse order** to the other.

In a polyhedron that has a consistent orientation (typically all faces are in counter clockwise order), each edge must be matched by an edge in the opposite direction.

File: src/utilities/geometry/Polyhedron.cpp [hunk 14]
```diff
@@ -198,72 +317,161 @@ Polyhedron Polyhedron::updateZonePolygonsForMissingColinearPoints() const {
...
+    LOG(Trace, fmt::format("'{}' has {:.2f}% conflicted edges ({}/{}), while '{}' has {:.2f}% conflicted edges ({}/{})", sf1.name, c1,
+                           sf1.numConflictedEdges(), sf1.edges.size(), sf2.name, c2, sf2.numConflictedEdges(), sf2.edges.size()));
+    if (c1 > c2) {
+      conflictedSurfaces.insert(sf1);
+    } else {
+      conflictedSurfaces.insert(sf2);
+    }
+  }
+
+  return {conflictedSurfaces.begin(), conflictedSurfaces.end()};
```
Comment (jmarrec) [inline src/utilities/geometry/Polyhedron.cpp:453]: When determining surfaces with incorrect orientation, we check each conflicted edge.
For each of the two surfaces that share that edge, we compute the ratio of conflicted edges / total number of edges, and we keep the one with the largest ratio as this is probably the one that's in the wrong order.

File: src/model/Space.hpp [hunk 15]
```diff
@@ -640,6 +641,25 @@ namespace model {
...
+
+    /** This method will check the floorPrint of the space, if that can't be computed, it's not convex. If it can, it checks whether that resulting
+        * Surface3d is convex. Note: having a floorPrint that's convex isn't sufficied to deem a space to be convex, the walls could still be non
+        * convex, but it should suit most typical applications */
+    bool isConvex() const;
+
+    /** Checks if every Surface is convex, returns the Concave ones.
+        * Note: having a non convex surface does not necesarilly mean that the Space is not convex
+        * eg: a box with a wall that is split into two L s would return false, while the Space is actually still convex. */
+    std::vector<Surface> findNonConvexSurfaces() const;
```
[the remark this answers is not in the document]
Comment (macumber) [reply src/model/Space.hpp:661]: Woah these are awesome!

File: src/utilities/geometry/Polyhedron.hpp [hunk 16]
```diff
@@ -43,75 +43,98 @@ namespace model {
...
+  bool isConvex() const;
 
-  bool isEnclosedVolume = false;
-  Surface3dEdgeVector edgesNot2;
+  void resetEdgeMatching();
+
+  bool operator<(const Surface3d& rhs) const;
 };
 
 class UTILITIES_API Polyhedron
```
Comment (macumber) [inline src/utilities/geometry/Polyhedron.hpp:120]: Where did this come from, is this yours @jmarrec ?

Comment (jmarrec) [reply src/utilities/geometry/Polyhedron.hpp:120]: The enclosed checks were initially in E+, I've had to modify that portion last year so after learning about polyhedron geometry I decided to tackle the Space::volume issues were still there 13 years later.
The work in this PR is original.

File: src/model/Space.hpp [hunk 17]
```diff
@@ -640,6 +641,30 @@ namespace model {
...
+
+    /// @cond
+    void cacheGeometryDiagnostics();
+    void resetCachedGeometryDiagnostics();
+    /// @endcond
```
Comment (jmarrec) [inline src/model/Space.hpp:666]: Hidden methods to cache... I can't very reliably use signals onChange because it depends on the surfaces... so I'm choosing not to, but making this hidden, so the ThreeJSForwardTranslator can use it.

File: src/utilities/geometry/ThreeJS.hpp [hunk 18]
```diff
@@ -316,6 +316,22 @@ class UTILITIES_API ThreeUserData
   //void setBelowFloorPlenum(bool v);
   //void setAboveCeilingPlenum(bool v);
 
+  // If set to false, the 4 diags below aren't used
+  bool includeGeometryDiagnostics() const;
+  void setIncludeGeometryDiagnostics(bool includeGeometryDiagnostics);
```
Comment (jmarrec) [inline src/utilities/geometry/ThreeJS.hpp:321]: Make this optional

File: src/model/ThreeJSForwardTranslator.hpp [hunk 19]
```diff
@@ -64,10 +64,16 @@ namespace model {
     /// Get error messages generated by the last translation.
     std::vector<LogMessage> errors() const;
 
+    // Check if Surface is Convex, and check if its correctly oriented given the containing space, whether the space itself is Convex, Enclosed
+    // This is computationally intensive, so it's opt-in
+    bool includeGeometryDiagnostics() const;
+    void setIncludeGeometryDiagnostics(bool includeGeometryDiagnostics);
```
Comment (jmarrec) [inline src/model/ThreeJSForwardTranslator.hpp:70]: Optional include of geometry diagnostics though with caching it's not **that** bad.

before caching:

| Test case                  | Opt-out | Opt-out | Opt-in | Opt-in  |
|----------------------------|---------|---------|--------|---------|
|                            | Debug   | Release | Debug  | Release |
| 7_7_Windows_Complete       | 84.63   | 11.78   | 26.76  | 3.68    |
| ParkUnder_Retail_Office_C2 | 120.64  | 18.08   | 15.92  | 2.13    |


**After caching, in release:**

```
1/4 Test #2562: ModelFixture.ThreeJSForwardTranslator_RefBldgOutPatientNew2004_Chicago .......................   Passed    1.39 sec
2/4 Test #2563: ModelFixture.ThreeJSForwardTranslator_RefBldgOutPatientNew2004_Chicago_GeometryDiagnostics ...   Passed    1.40 sec
3/4 Test #2560: ModelFixture.ThreeJSForwardTranslator_7_7_Windows_Complete ...................................   Passed    3.79 sec
4/4 Test #2561: ModelFixture.ThreeJSForwardTranslator_7_7_Windows_Complete_GeometryDiagnostics ...............   Passed    3.95 sec
```

**After caching, in debug:**

```
1/4 Test #2562: ModelFixture.ThreeJSForwardTranslator_RefBldgOutPatientNew2004_Chicago .......................   Passed   10.09 sec
2/4 Test #2563: ModelFixture.ThreeJSForwardTranslator_RefBldgOutPatientNew2004_Chicago_GeometryDiagnostics ...   Passed   10.19 sec
3/4 Test #2560: ModelFixture.ThreeJSForwardTranslator_7_7_Windows_Complete ...................................   Passed   27.17 sec
4/4 Test #2561: ModelFixture.ThreeJSForwardTranslator_7_7_Windows_Complete_GeometryDiagnostics ...............   Passed   28.33 sec
```

File: src/model/ThreeJSForwardTranslator.cpp [hunk 20]
```diff
@@ -482,11 +504,19 @@ namespace model {
     std::vector<PlanarSurface>::size_type N = planarSurfaces.size() + planarSurfaceGroups.size() + buildingStories.size() + buildingUnits.size()
                                               + thermalZones.size() + spaceTypes.size() + defaultConstructionSets.size() + airLoopHVACs.size() + 1;
 
+    std::vector<Space> spaces;
+    if (m_includeGeometryDiagnostics) {
+      spaces = model.getConcreteModelObjects<Space>();
+      for (auto& space : spaces) {
+        space.cacheGeometryDiagnostics();
+      }
+    }
```
Comment (jmarrec) [inline src/model/ThreeJSForwardTranslator.cpp:513]: If including, precompute and cache all space info.

File: src/model/ThreeJSForwardTranslator.cpp [hunk 21]
```diff
@@ -506,6 +536,12 @@ namespace model {
       updatePercentage(100.0 * n / N);
     }
 
+    if (m_includeGeometryDiagnostics) {
+      for (auto& space : spaces) {
+        space.resetCachedGeometryDiagnostics();
+      }
+    }
+
```
Comment (jmarrec) [inline src/model/ThreeJSForwardTranslator.cpp:544]: Then reset it
