### PR TITLE
Fix incompatible ScheduleTypeLimits issue for CoilCoolingWaterPanelRadiant cooling control temperature schedule

### LINKED ISSUE #5595: "CoilCoolingWaterPanelRadiant.setCoolingControlTemperatureSchedule" but keep getting 'incompatible ScheduleTypeLimits' error OpenstudioSDK 3.10.0
### Description

I am trying to write a measure to model ZoneHVACCoolingPanelRadiantConvectiveWater, I am trying to use an existing ScheduleRuleset to set the CoilCoolingWaterPanelRadiant.setCoolingControlTemperatureSchedule. However I keep getting a "incompatible ScheduleTypeLimits" error message saying I cannot to do it although the schedule limit is correct according to the EP+ input/output document

### Current Behavior

if you run the minimal script in the Steps to Reproduce you will get this error:

[openstudio.model.ModelObject] <0> For Object of type 'OS:Coil:Cooling:Water:Panel:Radiant' and named 'Clg Pnl Coil' cannot set Schedule Cooling Control Temperature=Medium Office Cooling Setpoint Schedule because it has an incompatible ScheduleTypeLimits

The ScheduleTypeLimits is as follows, which is what is required based on the energyplus input/output documentation

```
OS:ScheduleTypeLimits,
  {87944bcd-6f22-4b00-8b23-19ff657177c0}, !- Handle
  Temperature,                            !- Name
  -60,                                    !- Lower Limit Value
  200,                                    !- Upper Limit Value
  CONTINUOUS,                             !- Numeric Type
  Temperature;                            !- Unit Type
```

### Expected Behavior

It should successfully assign the schedule to the CoilCoolingWaterPanelRadiant

### Steps to reproduce

This python script will produce the error message in the Current Behavior section.

```
import openstudio

osmod = openstudio.model.exampleModel()
sch_rule = osmod.getScheduleRulesetByName('Medium Office Cooling Setpoint Schedule').get()
print(sch_rule)
print(sch_rule.scheduleTypeLimits().get())

clg_pnl = openstudio.model.ZoneHVACCoolingPanelRadiantConvectiveWater(osmod)
clg_pnl.setName("Clg Pnl")

hvaccomp = clg_pnl.coolingCoil()
clg_pnl_coil_optional = hvaccomp.to_CoilCoolingWaterPanelRadiant()
if clg_pnl_coil_optional.is_initialized():
    clg_pnl_coil = clg_pnl_coil_optional.get()
    clg_pnl_coil.setName("Clg Pnl Coil")
    clg_pnl_coil.setControlType('OperativeTemperature')
    isset = clg_pnl_coil.setCoolingControlTemperatureSchedule(sch_rule)
    print(isset)
```

### Possible Solution

_No response_

### Operating System affected

Ubuntu 24.04

### Environment

Platform: Ubuntu 24

### Version of OpenStudio

3.10.0

### Context

I am trying to write a measure for users to model radiant cooling panels. It will allow them to model radiant cooling panels for each conditioned zone and set the CoolingControlTemperatureSchedule at the same time using the measure.

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #5595

### Pull Request Author

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [x] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/ScheduleTypeRegistry.cpp [hunk 1]
```diff
@@ -207,7 +207,8 @@ namespace model {
       {"CoilCoolingLowTempRadiantVarFlow", "Cooling Control Temperature Schedule", "coolingControlTemperatureSchedule", true, "Temperature",
        OptionalDouble(), OptionalDouble()},
       {"CoilCoolingWater", "Availability", "availabilitySchedule", false, "Availability", 0.0, 1.0},
-      {"CoilCoolingWaterPanelRadiant", "Cooling Control Temperature", "coolingControlTemperatureSchedule", true, "", 0.0, OptionalDouble()},
+      {"CoilCoolingWaterPanelRadiant", "Cooling Control Temperature Schedule", "coolingControlTemperatureSchedule", true, "Temperature",
+       OptionalDouble(), OptionalDouble()},
```
Comment (joseph-robertson) [inline src/model/ScheduleTypeRegistry.cpp:211]: This is the fix, right here.

File: src/model/CoilCoolingWaterPanelRadiant.cpp [hunk 2]
```diff
@@ -54,6 +54,17 @@ namespace model {
...
     }
 
+    std::vector<ScheduleTypeKey> CoilCoolingWaterPanelRadiant_Impl::getScheduleTypeKeys(const Schedule& schedule) const {
+      std::vector<ScheduleTypeKey> result;
+      UnsignedVector fieldIndices = getSourceIndices(schedule.handle());
+      UnsignedVector::const_iterator b(fieldIndices.begin());
+      UnsignedVector::const_iterator e(fieldIndices.end());
+      if (std::find(b, e, OS_Coil_Cooling_Water_Panel_RadiantFields::CoolingControlTemperatureScheduleName) != e) {
+        result.push_back(ScheduleTypeKey("CoilCoolingWaterPanelRadiant", "Cooling Control Temperature Schedule"));
+      }
```
Comment (jmarrec) [inline src/model/CoilCoolingWaterPanelRadiant.cpp:64]: Nitpick but




```suggestion
      UnsignedVector fieldIndices = getSourceIndices(schedule.handle());
      UnsignedVector::const_iterator b(fieldIndices.begin());
      UnsignedVector::const_iterator e(fieldIndices.end());
      if (std::find(b, e, OS_Coil_Cooling_Water_Panel_RadiantFields::CoolingControlTemperatureScheduleName) != e) {
        result.emplace_back("CoilCoolingWaterPanelRadiant", "Cooling Control Temperature Schedule");
      }
```

**Review by jmarrec — APPROVED** [review]

File: src/model/CoilCoolingWaterPanelRadiant.cpp (hunk 2 above)
Comment (joseph-robertson) [reply src/model/CoilCoolingWaterPanelRadiant.cpp:64]: https://github.com/NatLabRockies/OpenStudio/pull/5596/changes/2afc3c8627883f2333ef422b9b641b66d8afb0c6
