### PR TITLE
Fix #4926 - WindowPropertyFrameAndDivider: "Outside Reveal Depth" not forward translated 

### LINKED ISSUE #4926: Frame & Divider "Outside Reveal Depth" not forward translated
Issue overview
--------------
In EnergyPlus, fenestration [outside reveals](https://bigladdersoftware.com/epx/docs/23-1/input-output-reference/group-thermal-zone-description-geometry.html#windowpropertyframeanddivider) (search for _Reveal Surface Fields_) are initiated by an _offset_ (or _setback_) of _SubSurface_ vertices vs base surface plane (e.g. a 4-in setback between brick cladding and glazing). As discussed [here](https://unmethours.com/question/94578/outside-reveal-depth-field-not-working-in-oswindowpropertyframeanddivider/), there are no observed issues with EnergyPlus' handling of _Frame and Dividers_ combined with **outside reveal** vertex _setbacks_ (when done by hand).

OpenStudio instead offers an additional _WindowPropertyFrameAndDivider_ field, [Outside Reveal Depth](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.6.1-doc/model/html/classopenstudio_1_1model_1_1_window_property_frame_and_divider.html#aa54a833a5c8898e00819494329595d0f). The suggestion in this _Openstudio Application_ [tutorial](https://openstudiocoalition.org/tutorials/tutorial_windowproperty_frameanddivider/) (and in UMH posts) is that _SubSurface_ vertex _setbacks_ should be completed automatically during forward translation. This does not seem to be the case.

The issue could have been filed under _OpenStudio Application_'s GitHub [issues](https://github.com/openstudiocoalition/OpenStudioApplication/issues), but it seems preferable to submit an issue here given OpenStudio's _Outside Reveal Depth_ attribute.

## Current Behavior
_SubSurface_ vertices are not **offset** (vs base surface plane) during forward translation, when linked to a _WindowPropertyFrameAndDivider_ holding a non-zero _Outside Reveal Depth_.

## Expected Behavior
_SubSurface_ vertices should be **offset** automatically during forward translation.

## Steps to Reproduce
1. Recover any OpenStudio model
2. Using the SDK, add a _WindowPropertyFrameAndDivider_, link it to one (or all) glazed sub surface(s) in the model
3. Ensure the _WindowPropertyFrameAndDivider_ has a non-zero _Outside Reveal Depth_ (e.g. 0.1m or even 0.5m)
4. Forward translate (e.g. using the CLI, the App)
5. Recover generated IDF - note if _SubSurface_ planes are the same as their base surfaces

## Details
The concept of an **offset** appears in 3 places in the OpenStudio _SubSurface_ forward translation source code:
- initiated as a zero-length 3D [vector](https://github.com/NREL/OpenStudio/blob/82304dcc76303e8a4c49c87500dc64ffe65248f5/src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp#L46)
- in principle, [offsets](https://github.com/NREL/OpenStudio/blob/82304dcc76303e8a4c49c87500dc64ffe65248f5/src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp#L56) _SubSurface_ vertices (yet as a zero-length vector, would have no effect)
- calculates a new [offset](https://github.com/NREL/OpenStudio/blob/82304dcc76303e8a4c49c87500dc64ffe65248f5/src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp#L143) vector by applying the _Outside Reveal Depth_ attribute to the _SubSurface_ outward normal (yet this **offset** doesn't seem to be reused elsewhere)

The _Outside Reveal Depth_ implementation seems _initiated_, yet _incomplete_. Apologies in advance if I'm missing something obvious.

## Possible Solution
Complete the implementation.

### Environment
 - MacOS Ventura 13.4, OpenStudio Application 1.5 (SDK 3.5.1)

### Context
Linked to this UMH [post](https://unmethours.com/question/94578/outside-reveal-depth-field-not-working-in-oswindowpropertyframeanddivider/). Thanks to @macumber for the source code links.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #4926

@brgix FYI

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/Test/WindowPropertyFrameAndDivider_GTest.cpp [hunk 1]
```diff
@@ -86,12 +90,48 @@ TEST_F(EnergyPlusFixture, WindowPropertyFrameAndDivider) {
   EXPECT_TRUE(subSurface2.setWindowPropertyFrameAndDivider(frameAndDivider));
   ASSERT_TRUE(subSurface2.windowPropertyFrameAndDivider());
 
+  model.save("WindowPropertyFrameAndDivider.osm", true);
```
Comment (joseph-robertson) [inline src/energyplus/Test/WindowPropertyFrameAndDivider_GTest.cpp:93]: Is this a temporary debug line?

File: src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp [hunk 2]
```diff
@@ -53,7 +62,7 @@ namespace energyplus {
         return boost::none;
       }
 
-      Point3d newPoint = point + offset;
+      const Point3d newPoint = point + offset;
```
[the remark this answers is not in the document]
Comment (jmarrec) [reply src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp:65]: Yes? That's what's needed no?

File: src/energyplus/Test/WindowPropertyFrameAndDivider_GTest.cpp (hunk 1 above)
Comment (jmarrec) [inline src/energyplus/Test/WindowPropertyFrameAndDivider_GTest.cpp:93]: Yes sorry
```suggestion
```

**Review by joseph-robertson — APPROVED** [review]
