### PR TITLE
Fix crash in FT for HeatPumpWaterToWaterEquationFitCooling/Heating when they refernce each other as companions

### LINKED ISSUE #3837: HeatPumpWaterToWaterEquationFit fields cause crash during forward translation
The `Companion Cooling/Heating Heat Pump Name` fields in the `HeatPumpWaterToWaterEquationFit*` objects cause several problems when a model has one cooling and one heating object that both reference each other. See code below and note that they must be connected to plant loops and both must reference each other. Removing one reference will fix the issue, but they should be able to according to the EnergyPlus `WWHPSimpleAuto.idf`. I suspect it's a recursion issue introduced in #3690.

FYI @jmarrec

2.9.0 OSM = [18154-Proposed.txt](https://github.com/NREL/OpenStudio/files/4041781/18154-Proposed.txt)

---

In the app, a model (1) will crash if a measure is added because of FT and (2) will never run EnergyPlus.

image

image

---

```
require 'openstudio'
include OpenStudio::Model

error = false

model = Model.new

plant_loop_cup_clg = PlantLoop.new(model)
plant_loop_cup_htg = PlantLoop.new(model)
plant_loop_wwhp_clg = PlantLoop.new(model)
plant_loop_wwhp_htg = PlantLoop.new(model)

wwhp_clg = HeatPumpWaterToWaterEquationFitCooling.new(model)
wwhp_htg = HeatPumpWaterToWaterEquationFitHeating.new(model)

plant_loop_cup_clg.addDemandBranchForComponent(wwhp_clg)
plant_loop_wwhp_clg.addSupplyBranchForComponent(wwhp_clg)

plant_loop_cup_htg.addDemandBranchForComponent(wwhp_htg)
plant_loop_wwhp_htg.addSupplyBranchForComponent(wwhp_htg)

if error
  wwhp_clg.setCompanionHeatingHeatPump(wwhp_htg)
  wwhp_htg.setCompanionCoolingHeatPump(wwhp_clg)
end
  
translator = OpenStudio::EnergyPlus::ForwardTranslator.new()
workspace = translator.translateModel(model)
```

If `error = true` above, the FT results in `SystemStackError: stack level too deep`

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #3837
 - FIx crash in FT for HeatPumpWaterToWaterEquationFitCooling/Heating when they refernce each other as companions
    - Both FTs reference each other via translateAndMapModelObject, which leads to a recursion issue. This ensures that m_map is updated in the beginning to avoid that problem.

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/ForwardTranslator/ForwardTranslateHeatPumpWaterToWaterEquationFitCooling.cpp [hunk 1]
```diff
@@ -54,14 +54,11 @@ namespace energyplus {
 
 boost::optional<IdfObject> ForwardTranslator::translateHeatPumpWaterToWaterEquationFitCooling( HeatPumpWaterToWaterEquationFitCooling & modelObject )
 {
-  IdfObject idfObject(IddObjectType::HeatPump_WaterToWater_EquationFit_Cooling);
-  boost::optional<double> optvalue;
-
-  m_idfObjects.push_back(idfObject);
+  // createRegisterAndNameIdfObject will add it to m_map, m_idfObjects, and name it
+  // The fact that it is added to m_map will avoid a recursion issue when it has a companion heating coil (both FT methods call each other)
+  IdfObject idfObject = createRegisterAndNameIdfObject(openstudio::IddObjectType::HeatPump_WaterToWater_EquationFit_Cooling, modelObject);
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateHeatPumpWaterToWaterEquationFitCooling.cpp]: Actual change

File: src/energyplus/ForwardTranslator/ForwardTranslateHeatPumpWaterToWaterEquationFitHeating.cpp [hunk 2]
```diff
@@ -54,14 +54,11 @@ namespace energyplus {
 
 boost::optional<IdfObject> ForwardTranslator::translateHeatPumpWaterToWaterEquationFitHeating( HeatPumpWaterToWaterEquationFitHeating & modelObject )
 {
-  IdfObject idfObject(IddObjectType::HeatPump_WaterToWater_EquationFit_Heating);
-  boost::optional<double> optvalue;
-
-  m_idfObjects.push_back(idfObject);
+  // createRegisterAndNameIdfObject will add it to m_map, m_idfObjects, and name it
+  // The fact that it is added to m_map will avoid a recursion issue when it has a companion cooling coil (both FT methods call each other)
+  IdfObject idfObject = createRegisterAndNameIdfObject(openstudio::IddObjectType::HeatPump_WaterToWater_EquationFit_Heating, modelObject);
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateHeatPumpWaterToWaterEquationFitHeating.cpp]: Actual change

File: src/energyplus/Test/HeatPumpWaterToWaterEquationFit_GTest.cpp [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+#include "../../utilities/idf/IdfObject_Impl.hpp"
+
+#include "../../utilities/idf/WorkspaceObject.hpp"
+#include "../../utilities/idf/WorkspaceObject_Impl.hpp"
+
+using namespace openstudio::energyplus;
+using namespace openstudio::model;
+using namespace openstudio;
+
+TEST_F(EnergyPlusFixture, ForwardTranslator_HeatPumpWaterToWaterEquationFit) {
```
Comment (jmarrec) [inline src/energyplus/Test/HeatPumpWaterToWaterEquationFit_GTest.cpp]: Tests segfaults without the fix, passes with it
