### PR TITLE
Fix #5401 - BCL measure update picks up subfolders like resources/__pycache__ or tests/.pytest_cache

### LINKED ISSUE #5401: BCL measure update picks up subfolders like resources/__pycache__ or tests/.pytest_cache
Issue overview
--------------

## Current Behavior

When working with python measures, you'll end up with some folders like__pycache__ and .pytest_cache and .mypy_cache around your measure.

`openstudio measure -u .` will add any of them that are in the approved subdirectories (docs/, resources/, tests/) and add them to the measure.xml which is very annoying.

## Expected Behavior

They should not be added to measure.xml

## Steps to Reproduce

1. Create a boilerplate python measure
2. cd tests && python -m pytest .
3. Notice that this created BOTH a .pytest_cache and a __pycache__ in your test folder
4. cd .. && openstudio measure -u
5. Look at your measure.xml additions...

```shell
(py312)(3.2.2)julien@OS-build2$ openstudio measure new --class-name TestPythonFolders --type ModelMeasure --language Python ./test_python_folders
Created a Python ModelMeasure with class name 'TestPythonFolders' in '/media/DataExt4/Software/Others/OS-build2/test_python_folders'
(py312)(3.2.2)julien@OS-build2$ cd test_python_folders/
(py312)(3.2.2)julien@test_python_folders$ cp measure.xml measure.xml.ori
(py312)(3.2.2)julien@test_python_folders$ cd tests/
pt(py312)(3.2.2)julien@tests$ ls -la
total 188
drwxrwxr-x 2 julien julien   4096 Apr 25 14:37 .
drwxrwxr-x 4 julien julien   4096 Apr 25 14:37 ..
-rw-rw-r-- 1 julien julien 173193 Apr 25 14:37 example_model.osm
-rw-rw-r-- 1 julien julien   5277 Apr 25 14:37 test_test_python_folders.py
(py312)(3.2.2)julien@tests$ python -m pytest .
======================================================================================= 3 passed, 1 warning in 3.26s =======================================================================================
(py312)(3.2.2)julien@tests$ ls -la
total 200
drwxrwxr-x 5 julien julien   4096 Apr 25 14:37 .
drwxrwxr-x 5 julien julien   4096 Apr 25 14:37 ..
-rw-rw-r-- 1 julien julien 173193 Apr 25 14:37 example_model.osm
drwxrwxr-x 2 julien julien   4096 Apr 25 14:37 output
drwxrwxr-x 2 julien julien   4096 Apr 25 14:37 __pycache__
drwxrwxr-x 3 julien julien   4096 Apr 25 14:37 .pytest_cache
-rw-rw-r-- 1 julien julien   5277 Apr 25 14:37 test_test_python_folders.py

(py312)(3.2.2)julien@tests$ cd ..
(py312)(3.2.2)julien@test_python_folders$ openstudio measure -u .
```

## Possible Solution

I think we should exclude:

* Any folder that starts with a `.` (dot)
* Any folder named __pycache__ (or maybe any folder starting with a leading `__`)

## Details

```
    <file>
      <filename>.pytest_cache/CACHEDIR.TAG</filename>
      <filetype>TAG</filetype>
      <usage_type>test</usage_type>
      <checksum>6DC4EC48</checksum>
    </file>
    <file>
      <filename>.pytest_cache/README.md</filename>
      <filetype>md</filetype>
      <usage_type>test</usage_type>
      <checksum>2EF77971</checksum>
    </file>
    <file>
      <filename>.pytest_cache/v/cache/nodeids</filename>
      <filetype></filetype>
      <usage_type>test</usage_type>
      <checksum>7E540310</checksum>
    </file>
    <file>
      <filename>.pytest_cache/v/cache/stepwise</filename>
      <filetype></filetype>
      <usage_type>test</usage_type>
      <checksum>0D4CBB29</checksum>
    </file>
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.9.0 (and develop at 3.10.0-alpha)

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5401 

### Pull Request Author

 - [x] Utilities API Changes / Additions
 - [x] All new and existing tests passes

**Labels:**

 - [x] If change to an IDD file, add the label `IDDChange`
 - [x] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/bcl/BCLMeasure.cpp [hunk 1]
```diff
@@ -1012,12 +1014,24 @@ bool BCLMeasure::checkForUpdatesFiles() {
...
+          if (!name.empty() && (name[0] == '.' || name == "__pycache__")) {
+            // Skip this directory and all its children
+            it.disable_recursion_pending();
+          }
+        } else if (openstudio::filesystem::is_regular_file(absoluteFilePath)) {
+          if (!isApprovedFile(absoluteFilePath, m_directory)) {
+            continue;
+          }
+          const openstudio::path relativeFilePath = openstudio::filesystem::relative(absoluteFilePath, m_directory);
+          result |= addWithUsageTypeIfNotExisting(relativeFilePath, std::string(usageType));
```
Comment (jmarrec) [inline src/utilities/bcl/BCLMeasure.cpp:1033]: use a recursive_directory_iterator and use `disable_recursion_pending` to skip it and children if it's a hidden folder or named "__pycache__"

**Review by joseph-robertson — COMMENTED** [review]
Do we want to generalize this a bit, and begin some sort of list of folder names to exclude? "pycache" would be the first entry in the list.

**Comment by jmarrec** [comment]
> Do we want to generalize this a bit, and begin some sort of list of folder names to exclude? "pycache" would be the first entry in the list.

I actually thought the same thing!
I started a constexpr std::array for it. But felt it was premature: now you're introducing a bunch of std::algorithm calls for 1 element, and kinda have to make a helper func or the code becomes harder to read.

If we find another one, then we'll do it

**Review by joseph-robertson — APPROVED** [review]
