### PR TITLE
Fix #5162 - Capture `exit` from Ruby

### LINKED ISSUE #5162: "exit 1" in ruby code is silently dismissed
Issue overview
--------------

Due to this change https://github.com/NREL/OpenStudio/commit/a52f8e00bf8cdfacd316d2c6e249b94d81fa7f9b

in **test.rb**, just put `exit 1`

`openstudio test.rb`

In 3.7.0, it was capturing the error, now it thinks it's the help command...

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5162

**Note: this _does_ fix the Minitest return value, even with the `minitest/autorun` using at_exit**

https://github.com/minitest/minitest/blob/ea9caafc0754b1d6236a490d59e624b53209734a/lib/minitest.rb#L66-L89

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by kbenne** [comment]
I think we might get some new failures from ctest as a result of this. (which is a feature not a bug of course)

**Comment by jmarrec** [comment]
Hummmm I no longer have any minitest output.

**Comment by wenyikuang** [comment]
Eventually I need build the binary from scratch so its not a big difference.

**Comment by jmarrec** [comment]
I'd say wait, I have some issues with it. Maybe it'll go in RC2.

File: ruby/engine/RubyEngine.cpp [hunk 1]
```diff
@@ -75,7 +75,13 @@ void RubyEngine::setupEmbeddedGems(const std::vector<openstudio::path>& includeD
...
 
 RubyEngine::~RubyEngine() {
-  ruby_finalize();
+  // ruby_cleanup calls ruby_finalize
+  int ex = ruby_cleanup(0);
+  if (ex != 0) {
+    fmt::print("RubyEngine return code was {}\n", ex);
+    exit(ex);
+  }
+  //ruby_finalize();
```
Comment (jmarrec) [inline ruby/engine/RubyEngine.cpp:84]: @kbenne here is the most important change.

Originally I had fixed it by using an at_exit block in executeRubyScriptCommand. THe Kernel.exit! was sufficient to propagate it to C++. But the issue was that this would be returning zero : `openstudio -e "at_exit { exit 12 }"`. So I thought "Wouldn't it be more logical to install that at_exit in the RubyEngine itself?" and that's when I realized ruby has a ruby_cleanup which returns the final exit code, so we should use that

```ruby
at_exit {{
  exit_code = ($! and $!.kind_of? SystemExit) ? $!.status : 0
  STDOUT.flush
  STDERR.flush
  if exit_code != 0
    Kernel.exit!(exit_code)
  end
}}
```


https://github.com/ruby/ruby/blob/af471c0e0127eea0cafa6f308c0425bbfab0acf5/include/ruby/internal/interpreter.h#L160-L181

File: src/cli/CMakeLists.txt [hunk 2]
```diff
@@ -476,6 +476,17 @@ if(BUILD_TESTING)
...
+  if (Python_EXECUTABLE)
+    add_test(NAME OpenStudioCLI.minitest_fail
+      COMMAND ${Python_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/test/run_minitest_fail.py" $<TARGET_FILE:openstudio>
+    )
+    if (SYSTEM_RUBY_EXECUTABLE)
+      add_test(NAME RubyTest.minitest_fail
+        COMMAND ${Python_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/test/run_minitest_fail.py" "${SYSTEM_RUBY_EXECUTABLE}"
+      )
+    endif()
+  endif()
```
Comment (jmarrec) [inline src/cli/CMakeLists.txt:488]: new tests

File: ruby/engine/RubyEngine.cpp [hunk 3]
```diff
@@ -75,7 +75,13 @@ void RubyEngine::setupEmbeddedGems(const std::vector<openstudio::path>& includeD
 }
 
 RubyEngine::~RubyEngine() {
-  ruby_finalize();
+  // ruby_cleanup calls ruby_finalize
+  int ex = ruby_cleanup(0);
+  if (ex != 0) {
+    fmt::print("RubyEngine return code was {}\n", ex);
```
Comment (shorowit) [inline ruby/engine/RubyEngine.cpp:81]: @jmarrec Did you mean to leave this in or was it for debugging? Seems weird that this is now printed.
