### PR TITLE
Fix up uninitialized optional in getPastStepValuesForMeasure

### LINKED ISSUE #5192: runner.getPastStepValuesForMeasure can cause segfault
Issue overview
--------------
I believe that certain values (i.e., containing special characters?) stored in "value" of a workflow step can cause a segfault. I have not investigated/narrowed this down, however.

## Steps to Reproduce
Execute `runner.getPastStepValuesForMeasure('apply_upgrade')` from resstock's UpgradeCosts measure. Values can contain "(", "|", etc.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5192 (hopefully, bis repetita)

old code works with std::optional, but not boost::optional 1.79.0

cf https://gcc.godbolt.org/z/7Khs774rd

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
I created a new docker image from this run at https://registry.hub.docker.com/layers/nrel/openstudio/dev-pr-5199/images/sha256-3ac0f35ab7e11412fd38b7cf462fdb80ee612bd6c46a9370383e89676fbdfa17?context=explore

And I'm testing the changes in https://github.com/NREL/resstock/pull/1243

File: src/measure/test/OSRunner_GTest.cpp [hunk 1]
```diff
@@ -385,3 +385,51 @@ TEST_F(MeasureFixture, OSRunner_getPastStepValues) {
...
+  EXPECT_EQ(1, workflow.workflowSteps().size());
+  EXPECT_EQ(workflow.string(), runner.workflow().string());
+
+  workflow.saveAs(scratchDir / "OSRunner_getPastStepValues_step_name_not_initialized.osw");
+
+  {
+    const Json::Value stepValues = runner.getPastStepValuesForMeasure("non_existing");
+    EXPECT_EQ(0, stepValues.size());  // did not set step result as Success
+  }
+}
```
Comment (jmarrec) [inline src/measure/test/OSRunner_GTest.cpp:435]: Crashing in debug mode before fix, works after

```
$ Products/openstudio_measure_tests --gtest_filter=*OSRunner_getPastStepValues_step_name_not_initialized*
Running main() from gmock_main.cc
Note: Google Test filter = *OSRunner_getPastStepValues_step_name_not_initialized*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MeasureFixture
[ RUN      ] MeasureFixture.OSRunner_getPastStepValues_step_name_not_initialized
openstudio_measure_tests: /home/julien/.conan2/p/b/boostfdc6e57e26853/p/include/boost/optional/optional.hpp:1270: boost::optional<T>::reference_type boost::optional<T>::get() [with T = std::__cxx11::basic_string<char>; boost::optional<T>::reference_type = std::__cxx11::basic_string<char>&]: Assertion `this->is_initialized()' failed.
Aborted (core dumped)
```
