### PR TITLE
Addresses #5039, fix FT for AirConditioner:VariableRefrigerantFlow

### LINKED ISSUE #5039: unexpected translation from osm to idf for `OS:AirConditioner:VariableRefrigerantFlow`
Issue overview
--------------
Unsure if this the right place to post.. But, I'm seeing couple fields in `OS:AirConditioner:VariableRefrigerantFlow` object not properly being transferred to IDF.

## Current Behavior
Below is the last 15 fields I have in the osm file:
image

Below is what I get for the same fields in the idf file (after running OS app):
image

`Maximum Outdoor Temperature in Heat Recovery Mode` switched from 20C to 30C. I couldn't find any description around this value being overridden from the [documentation](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-maximum-condenser-inlet-node-temperature-in-heat-recovery-mode-000).

`Initial Heat Recovery Cooling Capacity Fraction {W/W}` switched from 0.5 to 1. I couldn't find any description around this value being overridden from the [documentation](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-initial-heat-recovery-cooling-capacity-fraction).

## Expected Behavior
I guess I just want to see the same values between osm and idf.

## Steps to Reproduce
adding sample/example file [here](https://app.box.com/s/c99m6qfvvx24rpw7mazm24cxzbhdrxgn)

## Possible Solution
unsure

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.6.1

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #5039.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [x] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [x] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/ForwardTranslator/ForwardTranslateAirConditionerVariableRefrigerantFlow.cpp [hunk 1]
```diff
@@ -550,7 +550,7 @@ namespace energyplus {
 
     // MaximumCondenserInletNodeTemperatureinHeatRecoveryMode
 
-    if ((value = modelObject.maximumOutdoorTemperatureinHeatingMode())) {
+    if ((value = modelObject.maximumOutdoorTemperatureinHeatRecoveryMode())) {
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateAirConditionerVariableRefrigerantFlow.cpp:553]: Typo 1/2

File: src/energyplus/ForwardTranslator/ForwardTranslateAirConditionerVariableRefrigerantFlow.cpp [hunk 2]
```diff
@@ -564,7 +564,7 @@ namespace energyplus {
 
     // InitialHeatRecoveryCoolingCapacityFraction
 
-    if ((value = modelObject.initialHeatRecoveryCoolingEnergyFraction())) {
+    if ((value = modelObject.initialHeatRecoveryCoolingCapacityFraction())) {
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateAirConditionerVariableRefrigerantFlow.cpp:567]: Typo 2/2. Ok. The rest is just tests

**Review by jmarrec — APPROVED** [review]
Would be good to run the Regression tests that have this object to see if there are any EUI deviations @joseph-robertson
