### PR TITLE
Fix issues around ScheduleFixedInterval

### LINKED ISSUE #4706: Missing first day in Schedule:FixedInterval FT
Issue overview
--------------

## Current Behavior
```
OS:Schedule:FixedInterval,
  {28b3c3c6-efce-4dd0-a9ce-1abebd6d93c9}, !- Handle
  mains temperature schedule,             !- Name
  {c4cdb965-57ed-421e-8736-11ee16963354}, !- Schedule Type Limits Name
  ,                                       !- Translate to Schedule File
  ,                                       !- Interpolate to Timestep
  1440,                                   !- Interval Length {minutes}
  ,                                       !- Out Of Range Value
  1,                                      !- Start Month
  1,                                      !- Start Day
  10.0422222222222,                       !- Value 1
  9.98111111111111,                       !- Value 2
  9.92111111111111,                       !- Value 3
```
translates to
```
Schedule:Compact,
  mains temperature schedule,             !- Name
  Temperature,                            !- Schedule Type Limits Name
  Through: 01/02,                         !- Field 1
  For: AllDays,                           !- Field 2
  Until: 24:00,                           !- Field 3
  9.98111111111111,                       !- Field 4
  Through: 01/03,                         !- Field 5
  For: AllDays,                           !- Field 6
  Until: 24:00,                           !- Field 7
  9.92111111111111,                       !- Field 8
```

## Expected Behavior
Where is Value 1?

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### LINKED ISSUE #4707: OpenStudio::Model::ScheduleInterval.fromTimeSeries(ts, model).get sets Start Day to 2
Issue overview
--------------
Why is Start Day set to 2, and not 1?

## Current Behavior
```
start_date = OpenStudio::Date.new(OpenStudio::MonthOfYear.new(1), 1, 2007)
timestep_day = OpenStudio::Time.new(1, 0)
time_series_tmains = OpenStudio::TimeSeries.new(start_date, timestep_day, OpenStudio::createVector(<365 array>), 'C')
schedule_tmains = OpenStudio::Model::ScheduleInterval.fromTimeSeries(time_series_tmains, model).get

OS:Schedule:FixedInterval,
  {dc6bb0dd-f86a-4ace-a46b-207a7ba4c827}, !- Handle
  mains temperature schedule,             !- Name
  {458f5799-f689-41f7-be91-164629d9b9df}, !- Schedule Type Limits Name
  ,                                       !- Translate to Schedule File
  ,                                       !- Interpolate to Timestep
  1440,                                   !- Interval Length {minutes}
  ,                                       !- Out Of Range Value
  1,                                      !- Start Month
  2,                                      !- Start Day
```

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### LINKED ISSUE #4793: ScheduleFixedInterval ignores leap day on forward translation
Issue overview
--------------
Forward translation of ScheduleFixedInterval (to ScheduleCompact) appears to ignore the calendar year.

## Current Behavior
Where is 02/29?

`OS:ScheduleFixedInterval` has 8784 values (for hourly values of, e.g., year 2012). Then the forward translated schedule looks like:

```
Schedule:Compact,
  cooling sequential fraction,            !- Name
  Fractional,                             !- Schedule Type Limits Name

  ...

  Through: 02/27,                         !- Field 229
  For: AllDays,                           !- Field 230
  Until: 24:00,                           !- Field 231
  1,                                      !- Field 232
  Through: 02/28,                         !- Field 233
  For: AllDays,                           !- Field 234
  Until: 24:00,                           !- Field 235
  1,                                      !- Field 236
  Through: 03/01,                         !- Field 237
  For: AllDays,                           !- Field 238
  Until: 24:00,                           !- Field 239
  1,                                      !- Field 240
  Through: 03/02,                         !- Field 241
  For: AllDays,                           !- Field 242
  Until: 24:00,                           !- Field 243
  1,                                      !- Field 244

  ...

  Through: 12/31,                         !- Field 1457
  For: AllDays,                           !- Field 1458
  Until: 24:00,                           !- Field 1459
  1,                                      !- Field 1460
  Through: 01/01,                         !- Field 1461
  For: AllDays,                           !- Field 1462
  Until: 24:00,                           !- Field 1463
  1;                                      !- Field 1464
```
## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution
I'm fairly certain that this is happening because [this Date ctor](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/time/Date.cpp#L208-L211) returns an [assumed year different than that of the YearDescription object](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/time/Date.cpp#L125-L126).

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4706
 - Fixes #4707
 - Fixes #4793
 - Also removes limitation that interval must one day or smaller (e.g., permits weekly fixed interval schedules)

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [x] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/Test/ScheduleInterval_GTest.cpp [hunk 1]
```diff
@@ -277,6 +277,113 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted
...
+    daily_wh_inlet_temperatures_c[4] = 9.80444444444445;
+    TimeSeries time_series_tmains(start_date, timestep_day, daily_wh_inlet_temperatures_c, "C");
+
+    boost::optional<ScheduleInterval> scheduleInterval = ScheduleInterval::fromTimeSeries(time_series_tmains, model);
+    ASSERT_TRUE(scheduleInterval);
+    EXPECT_TRUE(scheduleInterval->optionalCast<ScheduleFixedInterval>());
+    ScheduleFixedInterval scheduleFixedInterval = scheduleInterval->optionalCast<ScheduleFixedInterval>().get();
+    EXPECT_EQ(1440, scheduleFixedInterval.intervalLength());  // one day in minutes
+    EXPECT_EQ(1, scheduleFixedInterval.startMonth());
+    EXPECT_EQ(2, scheduleFixedInterval.startDay());  // unrelated to this test, but this should be fixed to be 1
```
Comment (jmarrec) [inline src/energyplus/Test/ScheduleInterval_GTest.cpp:300]: That feels weird no? Should we address that?

Comment (joseph-robertson) [reply src/energyplus/Test/ScheduleInterval_GTest.cpp:300]: I've already created [this issue](https://github.com/NREL/OpenStudio/issues/4707) for addressing that.

File: src/energyplus/Test/ScheduleInterval_GTest.cpp [hunk 2]
```diff
@@ -277,6 +277,113 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted
...
+    Workspace workspace = ft.translateModel(model);
+
+    std::vector<WorkspaceObject> objects = workspace.getObjectsByType(IddObjectType::Schedule_Compact);
+    ASSERT_EQ(1u, objects.size());
+
+    EXPECT_EQ("Through: 01/02",
+              objects[0].getString(2, false).get());  // this aligns with start day, but start day should be 1 (so this should be 01/01)
+    EXPECT_EQ("For: AllDays", objects[0].getString(3, false).get());
+    EXPECT_EQ("Until: 24:00", objects[0].getString(4, false).get());
+    EXPECT_EQ("10.0422222222222", objects[0].getString(5, false).get());
```
Comment (joseph-robertson) [inline src/energyplus/Test/ScheduleInterval_GTest.cpp:313]: This first "days" test ensures the first timestep translated is the first from model (and not the second timestep).

File: src/energyplus/Test/ScheduleInterval_GTest.cpp [hunk 3]
```diff
@@ -277,6 +277,113 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted
...
+    Vector daily_wh_inlet_temperatures_c(5);
+    daily_wh_inlet_temperatures_c[0] = 10.0422222222222;
+    daily_wh_inlet_temperatures_c[1] = 9.98111111111111;
+    daily_wh_inlet_temperatures_c[2] = 9.92111111111111;
+    daily_wh_inlet_temperatures_c[3] = 9.86222222222222;
+    daily_wh_inlet_temperatures_c[4] = 9.80444444444445;
+    TimeSeries time_series_tmains(start_date, timestep_2day, daily_wh_inlet_temperatures_c, "C");
+
+    boost::optional<ScheduleInterval> scheduleInterval = ScheduleInterval::fromTimeSeries(time_series_tmains, model);
+    ASSERT_FALSE(scheduleInterval);
```
Comment (joseph-robertson) [inline src/energyplus/Test/ScheduleInterval_GTest.cpp:346]: Setting timestep to 2 days isn't allowed. I think that's probably ok.

File: src/energyplus/Test/ScheduleInterval_GTest.cpp [hunk 4]
```diff
@@ -277,6 +277,113 @@ TEST_F(EnergyPlusFixture, ForwardTranslator_ScheduleFixedInterval_Hourly_Shifted
...
+  ForwardTranslator ft;
+  Workspace workspace = ft.translateModel(model);
+
+  std::vector<WorkspaceObject> objects = workspace.getObjectsByType(IddObjectType::Schedule_Compact);
+  ASSERT_EQ(1u, objects.size());
+
+  EXPECT_EQ("Through: 01/01", objects[0].getString(2, false).get());
+  EXPECT_EQ("For: AllDays", objects[0].getString(3, false).get());
+  EXPECT_EQ("Until: 01:00", objects[0].getString(4, false).get());
+  EXPECT_EQ("10.0422222222222", objects[0].getString(5, false).get());
```
Comment (joseph-robertson) [inline src/energyplus/Test/ScheduleInterval_GTest.cpp:380]: I think this was already working for hourly timestep, but adding a test just to make sure.

File: src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp [hunk 5]
```diff
@@ -161,6 +161,11 @@ namespace energyplus {
       unsigned int start = 0;
       if (secondShift == 0) {
         start = 1;
+        // JJR: interval lengths of at least one day shouldn't shift the start of the loop, right? why would we ever start with the second element of the values vector?
+        if (modelObject.intervalLength() == 1440) {  // do this for the one day interval; for interval more than one day, sorry you're on your own
+          start = 0;
+          lastDate -= dayDelta;
+        }
```
[the remark this answers is not in the document]
Comment (joseph-robertson) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp:168]: This is my "fix" to ensure that the first day timestep translated is actually the first from the model (and not the second). I.e., when the interval is exactly one day, don't start in the array's second position (but rather the first) and start with one day _before_ the `firstReportDateTime.date()`.

[the remark this answers is not in the document]
Comment (joseph-robertson) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp:168]: Appears that two comments from this method are relevant here:
(1) New version assumes that the interval is less than one day.
(2) It was translated from the day version, so there could be issues associated with that.

So my interpretation is that this method was refactored from an earlier "day" version. It's possible that the new refactored method doesn't properly handle when the timestep is exactly one day.

[the remark this answers is not in the document]
Comment (jmarrec) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp:168]: `ScheduleFixedInterval::setTimeSeries` (with is called from `ScheduleInterval::fromTimeseries` for eg) enforces that the interval must be 1 day or below: https://github.com/NREL/OpenStudio/blob/26ce82cbf2b09967c096028547324ca5c42e3610/src/model/ScheduleFixedInterval.cpp#L121-L124

Unfortunately, neither `ScheduleFixedInterval::setIntervalLength` nor the IDD for 'Interval Length' enforce it.

I'm not sure why the setTimeseries disallows it, but I think we want to allow more than one day? I could see it a way to provide a 52 weekly (constant during the week) values for eg.

As a result, I think we should extend your fix to include more than one days.

[the remark this answers is not in the document]
Comment (jmarrec) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp:168]: Apparently the FT code assumes it's less than one day, and according to git blame that change is from you @joseph-robertson : https://github.com/NREL/OpenStudio/blob/26ce82cbf2b09967c096028547324ca5c42e3610/src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp#L150-L152

Commit: https://github.com/NREL/OpenStudio/commit/57350a7ee50357fb4a317bfb5f74daab18b408c9

Do you recall why?

Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp:168]: If we want to support multiple days:

`#include <cmath>  // For std::modf`

```suggestion
        // JJR: interval lengths of at least one day shouldn't shift the start of the loop, right?
        // Why would we ever start with the second element of the values vector?
        const double intervalLength = modelObject.intervalLength();
        double integralPart = 0.0;
        if (std::modf(intervalLength, &integralPart) == 0.0) {
          // The intervalLength is actually an int, not a double
          const int intervalLengthAsInt = static_cast<int>(integralPart);
          // If this is an interval representing one or more days
          if (intervalLengthAsInt % 1440 == 0) {
            start = 0;
            const int nDays = intervalLengthAsInt / 1440;
            lastDate -= dayDelta * nDays;
          }

```

Comment (joseph-robertson) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp]: According to the new ft test for weekly interval, we'll need more changes/updates than just this.

Comment (jmarrec) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp]: So, I think here the ScheduleFixedInterval.hpp is dumb.

The IDD

```diff
  N1, \field Interval Length
+       \type integer
       \required-field
       \units minutes
       \minimum 1
```


Why is it a double here?

https://github.com/NREL/OpenStudio/blob/9b1c0755f7dad4febeaf69813d2b0f795a55dfef/src/model/ScheduleFixedInterval.hpp#L72

Comment (jmarrec) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp]: I'd vote for an API break here, changing the return type to be the correct one: int. So we can get rid of that std::modf (that I suggested in the first place, I know)

Comment (joseph-robertson) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp]: What about `setIntervalLength`? Change it to accept only int (instead of double)?

Comment (joseph-robertson) [reply src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp]: Looks like you got it covered. Note to add entry in release notes about the API breaking changes.

**Comment by jmarrec** [comment]
Ah shoot I didn't realize windows was failing.
