### PR TITLE
Fix #4461 - DesignSpecificationOutdoorAir: when combining, Outdoor Air Flow rate for ACH is off by 3600 when "Maximum" method is used

### LINKED ISSUE #4461: DesignSpecificationOutdoorAir: when combining, Outdoor Air Flow rate for ACH is off by 3600 when "Maximum" method is used
Issue overview
--------------
DesignSpecificationOutdoorAir: when combining, Outdoor Air Flow rate for ACH is off by **3600** when "Maximum" method is used.

Here:
https://github.com/NREL/OpenStudio/blob/c93fb5861cb22ba7bd96c694a7e91f9595b2ac8e/src/model/ThermalZone.cpp#L1359-L1373

And Here:

https://github.com/NREL/OpenStudio/blob/c93fb5861cb22ba7bd96c694a7e91f9595b2ac8e/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L897

This is in m3/**hour** while all others are in m3/**s**. It should be divided by 3600.0!

This has been there since the first commit so 8 years ago.

**I suppose this is rather low occurrence because people would have noticed. To be affected you need** in spaces serving the **same thermal zone**:
* At least one DSOA with its method set to "Sum"
* At least one DSOA with its method set to "Maximum" **and** a non zero ACH

Most models don't match this.

## Current Behavior

It's off by 3600 because it's the value in m3/h

## Expected Behavior

It should be converted to m3/s

## Steps to Reproduce

```ruby
include OpenStudio::Model

width = 10.0
spaceFloorArea = width * width
height = 3.6
spaceVolume = spaceFloorArea * height

floorPointsSpace1 = OpenStudio::Point3dVector.new
floorPointsSpace1 << OpenStudio::Point3d.new(0.0, 0.0, 0.0)
floorPointsSpace1 << OpenStudio::Point3d.new(0.0, width, 0.0)
floorPointsSpace1 << OpenStudio::Point3d.new(width, width, 0.0)
floorPointsSpace1 << OpenStudio::Point3d.new(width, 0.0, 0.0)

m = Model.new

space1 = Space::fromFloorPrint(floorPointsSpace1, height, m).get()
space2 = Space::fromFloorPrint(floorPointsSpace1, height, m).get()
space2.setXOrigin(width)
z = ThermalZone.new(m)
space1.setThermalZone(z)
space2.setThermalZone(z)

space1.setSpaceType(officeSpaceType)
space2.setSpaceType(officeSpaceType)

dsoaSpace1 = DesignSpecificationOutdoorAir.new(m)
dsoaSpace1.setName("dsoaSpace1")
space1.setDesignSpecificationOutdoorAir(dsoaSpace1)
dsoaSpace1.setOutdoorAirFlowAirChangesperHour(0.5)
dsoaSpace2 = DesignSpecificationOutdoorAir.new(m)

# We set this one to "Maximum" to exhibit the issue
dsoaSpace2.setName("dsoaSpace2")
space2.setDesignSpecificationOutdoorAir(dsoaSpace2)
dsoaSpace2.setOutdoorAirFlowAirChangesperHour(0.5)
dsoaSpace2.setOutdoorAirMethod("Maximum")
dsoaSpace2.setOutdoorAirFlowRate(0.0)


z.setUseIdealAirLoads(true)
d = DesignDay.new(m)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new
w = ft.translateModel(m)
```

```ruby
puts w.getObjectsByType("DesignSpecification:OutdoorAir")
DesignSpecification:OutdoorAir,
  Design Specification Outdoor Air 1,     !- Name
  Sum,                                    !- Outdoor Air Method
  0,                                      !- Outdoor Air Flow per Person {m3/s-person}
  0,                                      !- Outdoor Air Flow per Zone Floor Area {m3/s-m2}
  180,                                    !- Outdoor Air Flow per Zone {m3/s}
  0.25;                                   !- Outdoor Air Flow Air Changes per Hour {1/hr}
```

It shouldn't be 180 m3/s in `Outdoor Air Flow per Zone`, but 0.05 m3/s. 

```ruby
space2.volume()*dsoaSpace2.outdoorAirFlowAirChangesperHour()/3600.0
=> 0.05

```

## Possible Solution

Divide by 3600.0

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.3.0

### Context

I added a unit test for DesignSpecificationOutdoorAir Forward Translation in the Space PR. Noticed this problem.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #4461 - DesignSpecificationOutdoorAir: when combining, Outdoor Air Flow rate for ACH is off by 3600 when "Maximum" method is used

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by jmarrec** [comment]
Issue 3: https://github.com/NREL/OpenStudio/blob/c93fb5861cb22ba7bd96c694a7e91f9595b2ac8e/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L928-L961

The not translating part if you can't find the peopleSchedule is just wrong.

File: src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp [hunk 1]
```diff
@@ -889,14 +889,15 @@ namespace energyplus {
             double outdoorAirFlowAirChangesperHour = designSpecificationOutdoorAir->outdoorAirFlowAirChangesperHour();
 
             std::string outdoorAirMethod = designSpecificationOutdoorAir->outdoorAirMethod();
-            if (istringEqual(outdoorAirMethod, "Max")) {
+            if (istringEqual(outdoorAirMethod, "Maximum")) {
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp:892]: Issue 2 on #4461: this was NEVER true since "Maximum" is one of the valid methods, not "Max"

File: src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp [hunk 2]
```diff
@@ -947,11 +948,13 @@ namespace energyplus {
...
 
-              if (peopleSchedule) {
+              if (!allPeople.empty()) {
                 IdfObject zoneVentilation(IddObjectType::ZoneVentilation_DesignFlowRate);
                 zoneVentilation.setName(modelObject.name().get() + " Ventilation per Person");
                 zoneVentilation.setString(ZoneVentilation_DesignFlowRateFields::ZoneorZoneListName, modelObject.name().get());
-                zoneVentilation.setString(ZoneVentilation_DesignFlowRateFields::ScheduleName, peopleSchedule->name().get());
+                if (peopleSchedule) {
+                  zoneVentilation.setString(ZoneVentilation_DesignFlowRateFields::ScheduleName, peopleSchedule->name().get());
+                }
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp:957]: Issue 3 on #4461: not translating it if you can't find the people schedule is wrong. You shouldn't try to write it if you didn't find it. You don't want to translate if you found zero people is all.

File: src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp [hunk 3]
```diff
@@ -889,14 +889,15 @@ namespace energyplus {
...
 
               double rateForPeople = spaces[0].numberOfPeople() * outdoorAirFlowperPerson;
               double rateForArea = spaces[0].floorArea() * outdoorAirFlowperFloorArea;
               double rate = outdoorAirFlowRate;
-              double rateForVolume = spaces[0].volume() * outdoorAirFlowAirChangesperHour;
+              // ACH * volume = m3/hour, divide by 3600 s/hr to get m3/s
+              double rateForVolume = spaces[0].volume() * outdoorAirFlowAirChangesperHour / 3600.0;
 
-              double biggestRate = std::max(rateForPeople, std::max(rateForArea, std::max(rate, rateForVolume)));
+              double biggestRate = std::max({rateForPeople, rateForArea, rate, rateForVolume});
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp:900]: Issue 1 on #4461

File: src/model/ThermalZone.cpp [hunk 4]
```diff
@@ -1356,11 +1356,12 @@ namespace model {
...
           }
 
-          // compute outdoor air rates in case we need them
+          // compute outdoor air rates (m3/s) in case we need them
           double outdoorAirForPeople = numberOfPeople * thisDesignSpecificationOutdoorAir->outdoorAirFlowperPerson();
           double outdoorAirForFloorArea = floorArea * thisDesignSpecificationOutdoorAir->outdoorAirFlowperFloorArea();
           double outdoorAirRate = thisDesignSpecificationOutdoorAir->outdoorAirFlowRate();
-          double outdoorAirForVolume = volume * thisDesignSpecificationOutdoorAir->outdoorAirFlowAirChangesperHour();
+          // ACH * volume = m3/h, divide by 3600 s/hr to get m3/s
+          double outdoorAirForVolume = volume * thisDesignSpecificationOutdoorAir->outdoorAirFlowAirChangesperHour() / 3600.0;
```
Comment (jmarrec) [inline src/model/ThermalZone.cpp:1364]: Issue 1 on #4461

File: src/model/ThermalZone.cpp [hunk 5]
```diff
@@ -1591,7 +1592,7 @@ namespace model {
 
         double outdoorAirForVolume = 0.0;
         if (sumOutdoorAirForVolume > 0 && sumVolume > 0) {
-          outdoorAirForVolume = sumOutdoorAirForVolume / sumVolume;
+          outdoorAirForVolume = 3600.0 * sumOutdoorAirForVolume / sumVolume;  // convert back to ACH
```
Comment (jmarrec) [inline src/model/ThermalZone.cpp:1595]: Issue 1 on #4461
