### PR TITLE
Fix #5397 - Controller:MechanicalVentilation should not inherit SizingSystem's OA Method if option isn't common to both

### LINKED ISSUE #5397: ControllerMechanicalVentilation.systemOutdoorAirMethod = SizingSystem.systemOutdoorAirMethod causing fatal error
Issue overview
--------------
When the `SizingSystem.systemOutdoorAirMethod` = `Standard62.1SimplifiedProcedure` it causes a fatal error because it's passed to `ControllerMechanicalVentilation.systemOutdoorAirMethod`.

```
Program Version,EnergyPlus, Version 24.2.0-94a887817b, YMD=2025.04.17 15:21,
   ** Severe  ** <root>[Controller:MechanicalVentilation][Controller Mechanical Ventilation 1][system_outdoor_air_method] - "Standard62.1SimplifiedProcedure" - Failed to match against any enum values.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=<root>[Controller:MechanicalVentilation][Controller Mechanical Ventilation 1][system_outdoor_air_method] - "Standard62.1SimplifiedProcedure" - Failed to match against any enum values.
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.10sec
```

## Current Behavior
The code for `ControllerMechanicalVentilation.systemOutdoorAirMethod` is expecting parity with `SizingSystem.systemOutdoorAirMethod`, which is incorrect per EnergyPlus IDD. 

https://github.com/NREL/OpenStudio/blob/a882f64d0989414b26e18dc071415740ee92c43c/src/model/ControllerMechanicalVentilation.cpp#L109

**EnergyPlus 24.2.0**
```
Sizing:System,
...
  A8, \field System Outdoor Air Method
      \type choice
      \key ZoneSum
      \key Standard62.1VentilationRateProcedure
      \key Standard62.1SimplifiedProcedure
      \default ZoneSum
```
```
Controller:MechanicalVentilation,
...
   A4,  \field System Outdoor Air Method
        \type choice
        \key ZoneSum
        \key Standard62.1VentilationRateProcedure
        \key Standard62.1VentilationRateProcedureWithLimit
        \key IndoorAirQualityProcedure
        \key ProportionalControlBasedOnDesignOccupancy
        \key ProportionalControlBasedOnOccupancySchedule
        \key IndoorAirQualityProcedureGenericContaminant
        \key IndoorAirQualityProcedureCombined
        \key ProportionalControlBasedOnDesignOARate
```

## Expected Behavior

No fatal error.

## Steps to Reproduce

```ruby
require 'openstudio'

include OpenStudio::Model

m = Model.new
al = AirLoopHVAC.new(m)
aloas = AirLoopHVACOutdoorAirSystem.new(m, ControllerOutdoorAir.new(m))

aloas.addToNode(al.supplyInletNode)
al.sizingSystem.setSystemOutdoorAirMethod('Standard62.1SimplifiedProcedure')

w = OpenStudio::EnergyPlus::ForwardTranslator.new.translateModel(m)
puts w.getObjectsByType('Controller:MechanicalVentilation'.to_IddObjectType)
```

```
Controller:MechanicalVentilation,
  Controller Mechanical Ventilation 1,    !- Name
  Always On Discrete,                     !- Availability Schedule Name
  No,                                     !- Demand Controlled Ventilation
  Standard62.1SimplifiedProcedure,        !- System Outdoor Air Method
  ;                                       !- Zone Maximum Outdoor Air Fraction {dimensionless}
```

## Possible Solution
1. Decouple the `ControllerMechanicalVentilation.systemOutdoorAirMethod` from `SizingSystem.systemOutdoorAirMethod`. 

or

2. Only allow common options. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5397

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/ControllerMechanicalVentilation_GTest.cpp [hunk 1]
```diff
@@ -34,9 +35,42 @@ TEST_F(ModelFixture, ControllerMechanicalVentilation) {
...
+
+  // System Outdoor Air Method is common to both ControllerMechanicalVentilation and SizingSystem
+  EXPECT_TRUE(sz.setSystemOutdoorAirMethod("ZoneSum"));
+  EXPECT_TRUE(controller_mv.isSystemOutdoorAirMethodDefaulted());
+  EXPECT_EQ("ZoneSum", controller_mv.systemOutdoorAirMethod());
+
+  // System Outdoor Air Method is NOT common to both ControllerMechanicalVentilation and SizingSystem
+  EXPECT_TRUE(sz.setSystemOutdoorAirMethod("Standard62.1SimplifiedProcedure"));
+  EXPECT_TRUE(controller_mv.isSystemOutdoorAirMethodDefaulted());
+  EXPECT_EQ("Standard62.1VentilationRateProcedure", controller_mv.systemOutdoorAirMethod());
```
Comment (jmarrec) [inline src/model/test/ControllerMechanicalVentilation_GTest.cpp:64]: Before fix 

```
[ RUN      ] ModelFixture.ControllerMechanicalVentilation_SystemOutdoorAirMethod
/media/DataExt4/Software/Others/OpenStudio3/src/model/test/ControllerMechanicalVentilation_GTest.cpp:64: Failure
Expected equality of these values:
  "Standard62.1VentilationRateProcedure"
  controller_mv.systemOutdoorAirMethod()
    Which is: "Standard62.1SimplifiedProcedure"
```

File: src/model/ControllerMechanicalVentilation.cpp [hunk 2]
```diff
@@ -109,8 +109,13 @@ namespace model {
...
             if (airLoop) {
-              const auto sizingSystem = airLoop->sizingSystem();
-              result = sizingSystem.systemOutdoorAirMethod();
+              const auto sizingSystemOAMethod = airLoop->sizingSystem().systemOutdoorAirMethod();
+              const auto possible_vals = systemOutdoorAirMethodValues();
+              if (std::find_if(possible_vals.cbegin(), possible_vals.cend(),
+                               [&sizingSystemOAMethod](const std::string& val) { return openstudio::istringEqual(val, sizingSystemOAMethod); })
+                  != possible_vals.cend()) {
+                result = sizingSystemOAMethod;
+              }
```
Comment (jmarrec) [inline src/model/ControllerMechanicalVentilation.cpp:118]: Simple fix: do not inherit the SizingSystem's System Outdoor Air Method value if this option isn't one available in Controller:MV.

image
