### PR TITLE
Fix #125 Fix #1559 - Treat ComponentData as a ResourceObject so ResourceObjects from BCL can be purged

### LINKED ISSUE #125: ComponentData object counts towards non-resource object count as well as direct use count (Bugzilla #725)
On 2012-06-07 14:28:37, @macumber wrote:

> Prevents purging unused objects that are part of a component, want to think this through a bit before changing

### LINKED ISSUE #1559: BCL Components can't be purged from model
After adding components from the BCL to a 1.6.3 model they can't be purged from Constructions or Materials and must be deleted individually. Probably a minor, low frequency bug. 

Steps to reproduce:
1. add components from BCL to model
2. try to purge from Constructions or Materials

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix #125 
- Fix #1559
- Treat ComponentData as a ResourceObject so ResourceObjects from BCL can be purged

- [ ] TODO: add a test for a non resourceobject with componentdata

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/Component_GTest.cpp [hunk 1]
```diff
@@ -354,3 +355,37 @@ TEST_F(ModelFixture, Component_BadSwaps) {
...
+  EXPECT_EQ(0u, m.numObjects());
+  OptionalComponentData ocd = m.insertComponent(cComponent);
+  ASSERT_TRUE(ocd);
+  EXPECT_EQ(2u, m.numObjects());  // Should the ComponentData count?
+
+  auto cs = m.getConcreteModelObjects<Construction>();
+  ASSERT_EQ(1u, cs.size());
+  c = cs[0];
+  EXPECT_EQ(1u, c.directUseCount());
+  EXPECT_EQ(0u, c.nonResourceObjectUseCount());
```
Comment (jmarrec) [inline src/model/test/Component_GTest.cpp:379]: 1 before fix

File: src/model/test/Component_GTest.cpp [hunk 2]
```diff
@@ -354,3 +355,37 @@ TEST_F(ModelFixture, Component_BadSwaps) {
...
+
+  auto compDatas = m.getConcreteModelObjects<ComponentData>();
+  ASSERT_EQ(1u, compDatas.size());
+  ComponentData compData = compDatas[0];
+  EXPECT_EQ(1u, compData.numComponentObjects());
+  EXPECT_EQ(c, compData.componentObjects()[0]);
+
+  // Now we can purge the unused resource objects
+  auto purgedObjects = m.purgeUnusedResourceObjects();
+  EXPECT_EQ(2u, purgedObjects.size());
```
Comment (jmarrec) [inline src/model/test/Component_GTest.cpp:389]: 0 before fix

File: src/model/test/Component_GTest.cpp [hunk 3]
```diff
@@ -354,3 +355,37 @@ TEST_F(ModelFixture, Component_BadSwaps) {
...
+  EXPECT_EQ(0u, m.numObjects());  // Should the ComponentData count?
```
Comment (jmarrec) [inline src/model/test/Component_GTest.cpp:390]: 2 before fix

File: src/model/test/Component_GTest.cpp [hunk 4]
```diff
@@ -354,3 +355,111 @@ TEST_F(ModelFixture, Component_BadSwaps) {
...
+  EXPECT_EQ(1u, compData.numComponentObjects());
+  EXPECT_EQ(c, compData.componentObjects()[0]);
+
+  // If I delete the object the ComponentData points to, the ComponentData be deleted as well
+  auto deletedObjects = c.remove();
+  EXPECT_EQ(1u, deletedObjects.size());  // ResourceObjects are kinda weird, they will likely not end up in the count
+  // But we can still verify that both got deleted
+  EXPECT_EQ(0u, m.numObjects());
+  EXPECT_EQ(0u, m.getConcreteModelObjects<Construction>().size());
+  EXPECT_EQ(0u, m.getConcreteModelObjects<ComponentData>().size());
```
Comment (jmarrec) [inline src/model/test/Component_GTest.cpp:429]: **I think this is what we want, right?**

File: src/model/test/Component_GTest.cpp [hunk 5]
```diff
@@ -354,3 +355,111 @@ TEST_F(ModelFixture, Component_BadSwaps) {
...
+  ComponentData compData = compDatas[0];
+  EXPECT_EQ(1u, compData.numComponentObjects());
+  EXPECT_EQ(designDay, compData.componentObjects()[0]);
+
+  // Now we can purge the unused resource objects: the ComponentData.
+  auto purgedObjects = m.purgeUnusedResourceObjects();
+  EXPECT_EQ(1u, purgedObjects.size());
+  EXPECT_EQ(1u, m.numObjects());
+  EXPECT_EQ(1u, m.getConcreteModelObjects<DesignDay>().size());
+  EXPECT_EQ(0u, m.getConcreteModelObjects<ComponentData>().size());
```
Comment (jmarrec) [inline src/model/test/Component_GTest.cpp:464]: * [ ] TODO: is this what we want? Do we expect the ComponentData to be purged if we can purgeUnusedResourceObjects? @kbenne @tijcolem

**Review by jmarrec — COMMENTED** [review]
Added TODOs
