### PR TITLE
Fix #3921 - some children of RefrigerationSystem can be added several times and produce a fatal when System is removed

### LINKED ISSUE #3921: some children of RefrigerationSystem can be added several times and produce a fatal when System is removed
Issue overview
--------------

As part of #3919 (and initial fix in #3920), I'm finding other problems as I go through.

eg: RefrigerationCompressor for eg can be added several times on the the same RefrigerationSystem (and on multiple refrigeration systems). On a single system it can even be assigned on two different `ModelObjectList` (compressorList and highStageCompressorList)

When the `RefrigerationSystem::remove() `is called, it will delete the `ModelObjectList` which:
1. will try to delete the compressor several times produces a crash
2. will (if it works) as a result make any other RefrigerationSystem that has that compressor just lose it which I find confusing

For 1. 
```
m = Model.new; r1 = RefrigerationSystem.new(m); c = RefrigerationCompressor.new(m); r1.addCompressor(c); r1.addCompressor(c);
[22] EnergyPlus(main)> r1.remove
[openstudio.model.RefrigerationCompressor] <2> Object of type 'OS:Refrigeration:Compressor' and named 'Refrigeration Compressor 1' does not have an Refrigeration Compressor Power Curve attached.
RuntimeError: /home/julien/Software/Others/OpenStudio/src/model/RefrigerationCompressor.cpp@134 : Object of type 'OS:Refrigeration:Compressor' and named 'Refrigeration Compressor 1' does not have an Refrigeration Compressor Power Curve attached.
from (pry):22:in `remove'
```

For 2.

```
[23] EnergyPlus(main)> m = Model.new; r1 = RefrigerationSystem.new(m); r2 = RefrigerationSystem.new(m); c = RefrigerationCompressor.new(m); r1.addCompressor(c); r2.addCompressor(c);
[24] EnergyPlus(main)> r1.remove
=> [#<OpenStudio::IdfObject:0x000055f0a602d7e8 @__swigtype__="_p_openstudio__IdfObject">,
 #<OpenStudio::IdfObject:0x000055f0a602d770 @__swigtype__="_p_openstudio__IdfObject">,
 #<OpenStudio::IdfObject:0x000055f0a602d6f8 @__swigtype__="_p_openstudio__IdfObject">,
 #<OpenStudio::IdfObject:0x000055f0a602d6a8 @__swigtype__="_p_openstudio__IdfObject">,
 #<OpenStudio::IdfObject:0x000055f0a602d630 @__swigtype__="_p_openstudio__IdfObject">,
 #<OpenStudio::IdfObject:0x000055f0a602d5b8 @__swigtype__="_p_openstudio__IdfObject">]
[25] EnergyPlus(main)> puts r2.getTarget(5).get.to_ModelObjectList.get
OS:ModelObjectList,
  {4f09a4ca-5ae8-4b1e-ba45-5fbfb194236c}, !- Handle
  Refrigeration System 2 Compressor List, !- Name
  ;                                       !- Model Object 1

```

### Possible Solution

Not sure yet. Possible options:

1. Make the assignment unique, like it is done for Case/Walkins by removing the child from any RefrigerationSystem it already belongs to https://github.com/NREL/OpenStudio/blob/d05bc3a9ba090cf986cde56b7616b7dc445ac2f1/src/model/RefrigerationSystem.cpp#L443-L450
2. Make the child (eg RefrigerationCompressor) a ResourceObject... (... with all that implies....)
3. Manually do a couple of fixes to avoid removing stuff twice (ductape)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.0-beta @ d05bc3a

### LINKED ISSUE #4053: Air to Water Heat Pump has draft level strictness of 23F on Min Inlet Air Temp Compressor Operation
Issue overview
--------------

Originally filed by @snlavu on https://github.com/openstudiocoalition/OpenStudioApplication/issues/109

Air to Water heat pump in open studio will not allow entry below 23F. Energy plus does not have this limitation.

## Current Behavior
Reverts to 23F while trying to input lower values.

## Expected Behavior
No limit on this entry similar to energy plus.
## Steps to Reproduce
Add heat pump to a zone. Edit temperature on Minimum Inlet Air Temperature for Compressor Operation to <23F. Entry reverts to 23F. 

1.
2.
3.
4.

## Possible Solution
Remove limit or provide a method to edit this limit.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows.
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):V2.8, 3.0

### Context

Trying to model an air-source heat pump that is outdoors and is being customized with curves to operate in very low ambient conditions. Not familiar with writing measure or editing the code to make this work. Will need to stay in the Open Studio realm. Please help!

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix #3921
 - some children of RefrigerationSystem can be added several times and produce a fatal when System is removed

- Fix #4053 
- Also do not translate the nodes > numberofNodes in WaterHeaterStratified (cf bullet point in #4042)

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/RefrigerationSystem.cpp [hunk 1]
```diff
@@ -174,6 +174,7 @@ namespace detail {
   {
     std::vector<IdfObject> result;
 
+    // TODO: technically this object can be shared accross multiple systems..
```
Comment (jmarrec) [inline src/model/RefrigerationSystem.cpp:177]: Should be disallow sharing `RefrigerationCondenser` accross several RefrigerationSystem? Or not delete it unless it becomes orphaned? @kbenne ?

File: src/model/RefrigerationSystem.cpp [hunk 2]
```diff
@@ -189,26 +190,37 @@ namespace detail {
...
       std::vector<IdfObject> removedCompressors = compressorList->remove();
       result.insert(result.end(), removedCompressors.begin(), removedCompressors.end());
     }
+    if (boost::optional<ModelObjectList> highStageCompressorList = this->highStageCompressorList()) {
+      std::vector<IdfObject> removedHighStageCompressors = highStageCompressorList->remove();
+      result.insert(result.end(), removedHighStageCompressors.begin(), removedHighStageCompressors.end());
+    }
 
+    // TODO: technically this object can be shared accross multiple systems..
     if ( boost::optional<RefrigerationSubcoolerMechanical> mechSubcooler = this->mechanicalSubcooler() ) {
```
Comment (jmarrec) [inline src/model/RefrigerationSystem.cpp:213]: Should be disallow sharing `RefrigerationSubcoolerMechanical` accross several RefrigerationSystem? Or not delete it unless it becomes orphaned? @kbenne ?

File: src/model/RefrigerationSystem.cpp [hunk 3]
```diff
@@ -189,26 +190,37 @@ namespace detail {
...
       std::vector<IdfObject> removedMechSubcooler = mechSubcooler->remove();
       result.insert(result.end(), removedMechSubcooler.begin(), removedMechSubcooler.end());
     }
 
+    // TODO: technically this object can be shared accross multiple systems..
     if ( boost::optional<RefrigerationSubcoolerLiquidSuction> liqSuctionSubcooler = this->liquidSuctionHeatExchangerSubcooler() ) {
```
Comment (jmarrec) [inline src/model/RefrigerationSystem.cpp:219]: Should be disallow sharing `RefrigerationSubcoolerLiquidSuction` accross several RefrigerationSystem? Or not delete it unless it becomes orphaned? @kbenne ?

File: src/model/RefrigerationSystem.cpp [hunk 4]
```diff
@@ -189,26 +190,37 @@ namespace detail {
...
+    // We're clearing the compressor/HighStage compressor list objects first. otherwise a compressor on the high stage list will call
+    // RefrgerationCompressor_Impl::system which will try to locate the compressorList which was deleted first
+    for (auto& c: compressors()) {
+      std::vector<IdfObject> removedCompressor = c.remove();
+      result.insert(result.end(), removedCompressor.begin(), removedCompressor.end());
+    }
+    for (auto& c: highStageCompressors()) {
+      std::vector<IdfObject> removedCompressor = c.remove();
+      result.insert(result.end(), removedCompressor.begin(), removedCompressor.end());
+    }
```
Comment (jmarrec) [inline src/model/RefrigerationSystem.cpp:202]: Avoids a crash, here;: https://github.com/NREL/OpenStudio/blob/fa9a77bf173556a2a044f64789a7f4f01b0df076/src/model/RefrigerationSystem.cpp#L320-L323

File: src/model/RefrigerationSystem.cpp [hunk 5]
```diff
@@ -451,6 +463,8 @@ namespace detail {
 
     if( boost::optional<RefrigerationSystem> currentSystem = refrigerationCase.system() )
     {
+      LOG(Warn, refrigerationCase.briefDescription() << " was removed from its existing RefrigerationSystem named '"
+          << currentSystem->nameString() << "'.");
```
Comment (jmarrec) [inline src/model/RefrigerationSystem.cpp:467]: Add clear warn messages when enforcing unicity and removing it form any other system.

File: src/model/RefrigerationSystem.cpp [hunk 6]
```diff
@@ -495,6 +511,14 @@ namespace detail {
...
 
   bool RefrigerationSystem_Impl::addCompressor(const RefrigerationCompressor& refrigerationCompressor) {
+    // Enforce unicity
+    if( boost::optional<RefrigerationSystem> currentSystem = refrigerationCompressor.system() )
+    {
+      LOG(Warn, refrigerationCompressor.briefDescription() << " was removed from its existing RefrigerationSystem (non High Stage) named '"
+          << currentSystem->nameString() << "'.");
+      currentSystem->removeCompressor(refrigerationCompressor);
+    }
+
```
Comment (jmarrec) [inline src/model/RefrigerationSystem.cpp:521]: Enforce unicity for Compressor, ConderserCascade and SecodnarySystem

File: src/model/RefrigerationSystem.cpp (hunk 2 above)
Comment (kbenne) [reply src/model/RefrigerationSystem.cpp:213]: im generally not a fan of sharing in cases like this, but if it is shared it seems like it would be a ResourceObject. Recall as an example Curve which recently became shared and a ResourceObject. In this case if it is not currently shared in the implementation I would be ok with merging as is, unless someone else makes an argument to share these objects.

File: src/model/RefrigerationSystem.cpp (hunk 1 above)
Comment (jmarrec) [reply src/model/RefrigerationSystem.cpp:177]: @kbenne  an illustrative code example:

```ruby
m = Model.new
r = RefrigerationSystem.new(m)
c = RefrigerationCondenserAirCooled.new(m)
sub_liquid = RefrigerationSubcoolerLiquidSuction.new(m)
sub = RefrigerationSubcoolerMechanical.new(m)
r.setRefrigerationCondenser(c)
r.setMechanicalSubcooler(sub)
r.setLiquidSuctionHeatExchangerSubcooler(sub_liquid)

r2 = RefrigerationSystem.new(m)
r2.setRefrigerationCondenser(c)
r2.setMechanicalSubcooler(sub)
r2.setLiquidSuctionHeatExchangerSubcooler(sub_liquid)
puts r
```
```
OS:Refrigeration:System,
  {5f9fab10-4145-40b8-9360-f0af0ccf3747}, !- Handle
  Refrigeration System 1,                 !- Name
  {25e031bf-bdda-42ff-a216-2ff0f96c782b}, !- Refrigerated CaseAndWalkInList Name
  {398b1be7-9edd-4b77-abf5-eb78870a0310}, !- Refrigeration TransferLoad List Name
  {fa314522-b2e9-48d8-b5d5-0bd4f46bd746}, !- Refrigeration Condenser Name
  {677b3507-b338-45b0-9160-ec200ec39f7d}, !- CompressorList Name
  21,                                     !- Minimum Condensing Temperature {C}
  R404a,                                  !- Refrigeration System Working Fluid Type
  ConstantSuctionTemperature,             !- Suction Temperature Control Type
  {5199722d-3e8c-41c0-908c-e20a6021e16b}, !- Mechanical Subcooler Name
  {c18cbca6-ba57-4ba6-9401-489223a6aeb5}, !- Liquid Suction Heat Exchanger Subcooler Name
  ,                                       !- Sum UA Suction Piping {W/K}
  ,                                       !- Suction Piping Zone Name
  ,                                       !- End-Use Subcategory
  ,                                       !- Intercooler Type
  ,                                       !- Shell-and-Coil Intercooler Effectiveness
  {28610ebc-74f7-4803-a541-4fd3574f91ff}; !- High-Stage CompressorList Name
```

Remove r2, and now r loses all three components:

```
r2.remove
puts r
```
```
OS:Refrigeration:System,
  {5f9fab10-4145-40b8-9360-f0af0ccf3747}, !- Handle
  Refrigeration System 1,                 !- Name
  {25e031bf-bdda-42ff-a216-2ff0f96c782b}, !- Refrigerated CaseAndWalkInList Name
  {398b1be7-9edd-4b77-abf5-eb78870a0310}, !- Refrigeration TransferLoad List Name
  ,                                       !- Refrigeration Condenser Name
  {677b3507-b338-45b0-9160-ec200ec39f7d}, !- CompressorList Name
  21,                                     !- Minimum Condensing Temperature {C}
  R404a,                                  !- Refrigeration System Working Fluid Type
  ConstantSuctionTemperature,             !- Suction Temperature Control Type
  ,                                       !- Mechanical Subcooler Name
  ,                                       !- Liquid Suction Heat Exchanger Subcooler Name
  ,                                       !- Sum UA Suction Piping {W/K}
  ,                                       !- Suction Piping Zone Name
  ,                                       !- End-Use Subcategory
  ,                                       !- Intercooler Type
  ,                                       !- Shell-and-Coil Intercooler Effectiveness
  {28610ebc-74f7-4803-a541-4fd3574f91ff}; !- High-Stage CompressorList Name
```

File: src/model/RefrigerationSystem.cpp (hunk 2 above)
Comment (jmarrec) [reply src/model/RefrigerationSystem.cpp:213]: It is shared currently, see the code example above.

If I add the same Subcooler to two RefrigerationSystem, and delete one RefrigerationSystem, then the other suddenly doesn't have any Subcooler anymore.

Options :
1. In RefrigerationSystem::remove: 
   1.1. check if subcooler ends up orphaned, then delete if that's the case
   1.2 do not remove anyways
2. In RefrigerationSystem::addSubcooler: enforce unicity.

I would go for 2. myself, for consistency with the rest of the object as well. I would accept falling back to 1.1. and I dislike 1.2

Comment (kbenne) [reply src/model/RefrigerationSystem.cpp:213]: 2 is good with me too. 1 (1.2 especially) sounds like ResourceObject and if you go that direction then I think the base class should be officially changed.

**Comment by jmarrec** [comment]
mac Ctest has nothing to do with this `1/1 Test #168: SqlFileFixture.AnnualTotalCosts`. @kbenne Ready for review
