### PR TITLE
#5145 - HeatExchangerAirToAirSensibleAndLatent normalization divisor error

### LINKED ISSUE #5145: HeatExchangerAirToAirSensibleAndLatent normalization divisor error
Issue overview
--------------

@mdahlhausen  reported an issue where the Normalization Divisor is zero at https://github.com/NREL/OpenStudio/pull/5099#issuecomment-2050633394

Need to determine what's causing this and ensure it doesn't happen.

## Steps to Reproduce

@mdahlhausen can you please help here?

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.8.0 circa RC1

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5145
 - This basically avoids the user being able to shoot themselves in the foot and get a zero normalization divisor in a table lookup

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/TableLookup.cpp [hunk 1]
```diff
@@ -165,8 +166,13 @@ namespace model {
...
 
-    bool TableLookup_Impl::setNormalizationDivisor(double normalizationDivisior) {
-      bool result = setDouble(OS_Table_LookupFields::NormalizationDivisor, normalizationDivisior);
+    bool TableLookup_Impl::setNormalizationDivisor(double normalizationDivisor) {
+      if (std::abs(normalizationDivisor) < std::numeric_limits<double>::min()) {
+        LOG(Warn, "Unable to set " << briefDescription() << "'s Normalization divisor to zero.");
+        return false;
+      }
+
+      bool result = setDouble(OS_Table_LookupFields::NormalizationDivisor, normalizationDivisor);
```
Comment (jmarrec) [inline src/model/TableLookup.cpp:175]: TableLookup will reject 0.0 now, and return false + a warn

File: src/model/HeatExchangerAirToAirSensibleAndLatent.cpp [hunk 2]
```diff
@@ -1026,8 +1028,13 @@ namespace model {
...
 
-    auto tableLookup = makeTable(sensibleEffectivenessat75HeatingAirFlow, sensibleEffectivenessat100HeatingAirFlow(), model(),
-                                 fmt::format("{}_SensHeatEff", nameString()));
+    const auto val100 = sensibleEffectivenessat100HeatingAirFlow();
+    if (std::abs(val100) < std::numeric_limits<double>::min()) {
+      LOG_AND_THROW("Unable to set " << briefDescription()
+                                     << "'s Sensible Effectiveness at 75 Heating Air Flow because the value at 100 is zero and would lead to a "
+                                        "Normalization divisor equal to zero.");
+    }
+    auto tableLookup = makeTable(sensibleEffectivenessat75HeatingAirFlow, val100, model(), fmt::format("{}_SensHeatEff", nameString()));
```
Comment (jmarrec) [inline src/model/HeatExchangerAirToAirSensibleAndLatent.cpp:1037]: HX: we actually throw if we get to such a condition.

File: src/model/test/HeatExchangerAirToAirSensibleAndLatent_GTest.cpp [hunk 3]
```diff
@@ -401,6 +401,26 @@ TEST_F(ModelFixture, HeatExchangerAirToAirSensibleAndLatent_Deprecated75Effectiv
...
+    EXPECT_TRUE(hx.setSensibleEffectivenessat100HeatingAirFlow(0.0));
+    EXPECT_TRUE(hx.setLatentEffectivenessat100HeatingAirFlow(0.0));
+    EXPECT_TRUE(hx.setSensibleEffectivenessat100CoolingAirFlow(0.0));
+    EXPECT_TRUE(hx.setLatentEffectivenessat100CoolingAirFlow(0.0));
+
+    EXPECT_ANY_THROW(hx.setSensibleEffectivenessat75HeatingAirFlow(0.5));
+    EXPECT_ANY_THROW(hx.setLatentEffectivenessat75HeatingAirFlow(0.5));
+    EXPECT_ANY_THROW(hx.setSensibleEffectivenessat75CoolingAirFlow(0.5));
+    EXPECT_ANY_THROW(hx.setLatentEffectivenessat75CoolingAirFlow(0.5));
+  }
```
Comment (jmarrec) [inline src/model/test/HeatExchangerAirToAirSensibleAndLatent_GTest.cpp:423]: Test that it throws with HX

File: src/model/test/TableLookup_GTest.cpp [hunk 4]
```diff
@@ -51,6 +51,10 @@ TEST_F(ModelFixture, TableLookup_GettersSetters) {
   EXPECT_TRUE(tableLookup.setNormalizationDivisor(0.5));
   EXPECT_EQ(0.5, tableLookup.normalizationDivisor());
 
+  // #5145 - We reject 0 as a normalization divisor
+  EXPECT_FALSE(tableLookup.setNormalizationDivisor(0.0));
+  EXPECT_EQ(0.5, tableLookup.normalizationDivisor());
```
Comment (jmarrec) [inline src/model/test/TableLookup_GTest.cpp:56]: Test that TableLookup just returns false and leaves it untouched
