### PR TITLE
gbXML translation fixes and enhancements

### LINKED ISSUE #4559: OpenStudio exported gbXML 'exposedToSun' attribute not written
Issue overview
--------------
On OpenStudio forward translation to gbXML the 'exposedToSun' attribute is not written to exterior surface types.

## Current Behavior
Instead of writing the 'exposedToSun' attribute for exterior surface types no attribute is written by OpenStudio forward translation to gbXML.

## Expected Behavior
The 'exposedToSun' attribute should be written for exterior surface types per the gbXML schema.

## Steps to Reproduce
1. Set a representative wall with an 'Outdoor' boundary condition.
2. Export to gbXML.
3. View gbXML with text editor and observe 'exposedToSun' attribute not set.

## Details
Please [click here](https://unmethours.com/question/71010/openstudio-exported-gbxml-exposedtosun-attribute-not-written/) for additional details posted to Unmet Hours.

### Environment
Operating system: Windows 10
Openstudio Application: v1.3.1 (SDK version 3.3.0)

### Context
Severity of not writing the 'exposedToSun' attribute for exterior surface types is unknown at this time. The issue was discovered while reviewing gbXML files for consistency using the [Spider gbXML Viewer](https://www.ladybug.tools/spider/gbxml-viewer/r14/gv-cor-core/gv-cor.html). 

The [gbXML schema](https://gbxml.org/schema_doc/6.01/GreenBuildingXML_Ver6.01.html#Link1A8) suggests the 'exposedToSun' attribute has importance in that it separates exterior surfaces that are exposed to the sun from those that are not.

Thank you for your time and consideration of this issue.

-Jake Staub

### LINKED ISSUE #4561: gbxml export does not transfer thermalZone Volume
Issue overview
--------------

Space Volume calculations in openstudio are not accurate for complex shapes (https://github.com/NREL/OpenStudio/issues/127). As a workaround one can set osThermalZone.setVolume. While this fixes the issue in the .OSM file, the gbxml forward translator does not carry over that value and uses space.volume which can have wrong value. It should use space.thermalzone.volume instead. Or offer the use a method to set the volume for a space (osSpace.setVolume does NOT exist)

## Current Behavior

For complex shapes, the volume of the space is wrong

## Expected Behavior

One or all things should happen:
1. osSpace should calculate the volume in a more accurate fashion. Address https://github.com/NREL/OpenStudio/issues/127
2. osSpace should offer a osSpace.setVolume method
3. If the above is not fixed, The gbxml Forward translator should use the saved value in the thermalZone rather than in space.volume

## Steps to Reproduce
1. Open the attached SpeckleBuilding.zip file and extract the OSM and GBXML files
2. Using a robust geometric method, compute the volumes of Space "8" and Space "9"
3. Compare the Volumes of Space "8" and Space "9" in the gbxml file to your calculations
4. Export the OSM file to gbxml and observe the volume of Space "8" and Space "9" compare to the volume set for their thermal zones.

## Possible Solution

One or allthings should happen:
1. osSpace should calculate the volume in a more accurate fashion. Address https://github.com/NREL/OpenStudio/issues/127
2. osSpace should offer a osSpace.setVolume method
3. If the above is not fixed, The gbxml Forward translator should use the saved value in the thermalZone rather than in space.volume
### Environment
[SpeckleBuilding.zip](https://github.com/NREL/OpenStudio/files/8407059/SpeckleBuilding.zip)

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA): Application: 1.3.0  SDK: 3.3.0

### Context

We are trying to output a robust and dependable gbxml from openstudio for energy analysis and a wrong volume can cause problems down the line.

### LINKED ISSUE #4570: Enhance gbXML reverse translation to bring over more data from gbXML
This would include but is not limited to interior and exterior solar absoprtance. Investgate other advacned and havc specific imports for gbXML. Possibly offer option to rely on `name` and not `id` for OpenStudio object names, for most models `name` will be more informative than `id` for a user viewing the model.

This grew out of issue #4569

### PR DESCRIPTION
**Pull request by joseph-robertson**
Pull request overview
---------------------

 - Fixes #4559
   - Updates FT of the GBXML file to store `exposedToSun=false` or `exposedToSun=true` (based on OSM `sunExposure=NoSun` or `sunExposure=SunExposed`, respectively)
 - Fixes #4561
   - FT of the GBXML can now store "correct" volume (by using value set by user with `space.setVolume()`)
   - Updates RT of the GBXML file to import Volume (by, again, using new `space.setVolume()` method)
 - Fixes #4570
   - Updates RT of the GBXML file to import Thermal/Solar/Visible Absorptance (based on GBXML fractional `ExtIR`, `ExtSolar`, and `ExtVisible` values, respectively)
   - Maps absorptances from Material, and then from Construction (for outside layer) if it exists.
 - Also fixes embedded file issue with GBXML schema xsd called during FT and RT

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/gbxml/MapEnvelope.cpp [hunk 1]
```diff
@@ -194,8 +219,29 @@ namespace gbxml {
       material.setSpecificHeat(specificHeat);
       material.setRoughness(roughness);
 
-    } else if (!rvalueElement.empty())  //Material no mass that has only R-value
-    {
+      if (extir && intir) {
+        material.setThermalAbsorptance((*extir + *intir) / 2.0);  // average of the two?
```
Comment (DavidGoldwasser) [inline src/gbxml/MapEnvelope.cpp:223]: @joseph-robertson typically I `extir` would be impact the outside material of a layered construction, and `intir` would impact the inner most material. I don't believe that no mass material can be exposed inside or outside material layer in E+. But another single layer construction like concrete, would be problematic if it had different inside and outside absorptance values.

Comment (DavidGoldwasser) [reply src/gbxml/MapEnvelope.cpp:223]: @joseph-robertson if a construction has two or more material layers then for the exposed materials one should get outside value and the other inside. But if you have a construction with single material layer, or if the same material is used on inside and outside then you can use average. It doesn't matter much for materials like insulation that are not exposed.

Comment (joseph-robertson) [reply src/gbxml/MapEnvelope.cpp:223]: @DavidGoldwasser So are you implying, because the existing FT behavior doesn't consider where the Material layer is relative to the construction, that the FT is incorrect?

Could you provide me with a concrete example for mapping between OSM Material and GBXML Material?

**Comment by DavidGoldwasser** [comment]
Here part of test gbXML

`
  <Construction id="aim0017">
    <U-value unit="WPerSquareMeterK">0.3043427</U-value>
    <Absorptance unit="Fraction" type="ExtIR">0.7</Absorptance>
    <Roughness value="Rough" />
    <LayerId layerIdRef="aim0021" />
    <Name>Basic Wall: Exterior - Render on Brick on Block</Name>
  </Construction>

  <Layer id="aim0021">
    <MaterialId materialIdRef="aim0022" />
    <MaterialId materialIdRef="aim0029" />
    <MaterialId materialIdRef="aim0036" />
    <MaterialId materialIdRef="aim0043" />
    <MaterialId materialIdRef="aim0050" />
    <MaterialId materialIdRef="aim0057" />
    <MaterialId materialIdRef="aim0064" />
  </Layer>
  
    <Material id="aim0022">
    <Name>Brick, Common, Grey: 25 [mm]</Name>
    <R-value unit="SquareMeterKPerW">0.04629629</R-value>
    <Thickness unit="Meters">0.025</Thickness>
    <Conductivity unit="WPerMeterK">0.54</Conductivity>
    <Density unit="KgPerCubicM">1550</Density>
    <SpecificHeat unit="JPerKgK">840</SpecificHeat>
  </Material>
`
Other materials have similar fields. Here is resulting OSM, note this is using extra measure to set material absorptance.

`
OS:Construction,
  {3d8d134f-9921-4ffc-b00c-553931376ef9}, !- Handle
  aim0017,                                !- Name
  ,                                       !- Surface Rendering Name
  {0143fdbe-45d9-4a10-99bb-0eca277ee8e7}, !- Layer 1
  {1571c634-6743-4f41-8a63-60737ea6af7d}, !- Layer 2
  {23f1c1b4-ee22-4e31-ad5b-f8d389be4fc7}, !- Layer 3
  {deef3ee1-dd7d-46e3-9588-746d879d8913}, !- Layer 4
  {dfe470e1-7fe0-4396-a8e9-a5b874461239}, !- Layer 5
  {4445cea0-c65a-45aa-87dd-5a3c211e20e9}, !- Layer 6
  {23691867-8cca-4dde-aeac-247d9b663636}; !- Layer 7
  
  OS:Material,
  {23691867-8cca-4dde-aeac-247d9b663636}, !- Handle
  aim0064,                                !- Name
  MediumRough,                            !- Roughness
  0.012,                                  !- Thickness {m}
  0.65,                                   !- Conductivity {W/m-K}
  1100,                                   !- Density {kg/m3}
  840,                                    !- Specific Heat {J/kg-K}
  ,                                       !- Thermal Absorptance
  0.7;                                    !- Solar Absorptance
`

**Comment by joseph-robertson** [comment]
Still pretty confused here. As far as I can tell there are 2 ways to store "Absorptance" in GBXML:

(1) [gbXMLStandard_Single_Family_Residential_2016.xml](https://github.com/NREL/OpenStudio/blob/develop/resources/gbxml/gbXMLStandard_Single_Family_Residential_2016.xml).  Absorptance is stored at the Construction level. Does only the "outside" `OS:Material` layer get this Absorptance value?

```
  <Construction id="construction-51">
    <LayerId layerIdRef="layer-51" />
    <Absorptance unit="Fraction" type="ExtIR">0.3</Absorptance>
  </Construction>

  <Layer id="layer-51">
    <MaterialId materialIdRef="mat-247" />
    <MaterialId materialIdRef="mat-244" />
  </Layer>

  <Material id="mat-247">
    <Name>Blt-Up Roof 3/8in  (BR01)</Name>
    <Description>1 cm</Description>
    <R-value unit="SquareMeterKPerW">0.0581163948110865</R-value>
    <Thickness unit="Meters">0.00954</Thickness>
    <Conductivity unit="WPerMeterK">0.1625159868276</Conductivity>
    <Density unit="KgPerCubicM">1121.29244652556</Density>
    <SpecificHeat unit="JPerKgK">1465.38</SpecificHeat>
  </Material>
```

(2) [seb.xml](https://github.com/NREL/OpenStudio/blob/develop/resources/gbxml/seb.xml). This is the flavor of GBXML that OpenStudio currently FT's to. Absorptance is stored at the Material level. Should every `OS:Material` layer get the "Ext" value? Or just the "outside" layer gets the "Ext" value? Or the average of "Ext" and "Int" values?

```
  <Construction id="EXTERIOR-WALL">
    <Name>EXTERIOR-WALL</Name>
    <LayerId layerIdRef="Stuco_Layer"/>
    <LayerId layerIdRef="Expanded_Polystyrene_-_Extruded_-_1_in._Layer"/>
  </Construction>

  <Layer id="Stuco_Layer">
    <Name>Stuco Layer</Name>
    <MaterialId materialIdRef="Stuco"/>
  </Layer>

  <Material id="Stuco">
    <Name>Stuco</Name>
    <Reflectance unit="Fraction" surfaceType="Both" type="ExtIR">0.5</Reflectance>
    <Reflectance unit="Fraction" surfaceType="Both" type="IntIR">0.5</Reflectance>
    <Roughness value="Rough"/>
    <Thickness unit="Meters">0.013</Thickness>
    <Conductivity unit="WPerMeterK">0.721139</Conductivity>
    <Density unit="KgPerCubicM">2659</Density>
    <SpecificHeat unit="JPerKgK">837</SpecificHeat>
    <Absorptance unit="Fraction" type="ExtIR">0.5</Absorptance>
    <Absorptance unit="Fraction" type="IntIR">0.5</Absorptance>
    <Absorptance unit="Fraction" type="ExtSolar">0.5</Absorptance>
    <Absorptance unit="Fraction" type="IntSolar">0.5</Absorptance>
    <Absorptance unit="Fraction" type="ExtVisible">0.5</Absorptance>
    <Absorptance unit="Fraction" type="IntVisible">0.5</Absorptance>
  </Material>
```

**Comment by tijcolem** [comment]
@axelstudios Would you be able to use try of these installers and run this through the gbxml collection of tests?

**Comment by tijcolem** [comment]
@joseph-robertson @DavidGoldwasser 

I used the [macOS installer](http://openstudio-ci-builds.s3-website-us-west-2.amazonaws.com/PR-4577/OpenStudio-3.4.1-alpha+c9e98ec584-Darwin-x86_64.dmg) on this branch to run some tests. I ran them on the gbxml-to-openstudio workflows that have a bunch of gbxml files. I hit the error (below) on all the runs. Looks like the openstudio cli is unable to load `GreenBuildingXML_Ver6.01.xsd`.  I noticed the filepath is a path on the CI machine so maybe something got hardcoded on during the build for this resource file?  


```
[07:56:39.909616 ERROR] /Users/jenkins/git/OpenStudioIncremental/develop/src/utilities/xml/XMLValidator.cpp@183 : Schema '/Users/jenkins/git/OpenStudioIncremental/develop/build/resources/gbxml/schema/         GreenBuildingXML_Ver6.01.xsd' does not exist
     /Users/tcoleman/git/gbxml-to-openstudio/measures/import_gbxml/measure.rb:70:in `loadModel'
     /Users/tcoleman/git/gbxml-to-openstudio/measures/import_gbxml/measure.rb:70:in `run'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:517:in `apply_measure'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:114:in `block in apply_measures'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'
     :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'
     :/openstudio_cli.rb:1174:in `execute'
     :/openstudio_cli.rb:804:in `execute'
     :/openstudio_cli.rb:1973:in `<main>'
     eval:188:in `eval'
     eval:188:in `require_embedded_absolute'
     eval:173:in `block in require_embedded'
     eval:167:in `each'
     eval:167:in `require_embedded'
     eval:126:in `require'
     eval:3:in `<main>'

```

**Comment by joseph-robertson** [comment]
@axelstudios Scenario demonstrating #4570:

`House.xml`

```
  <Construction id="aim0041">
    <U-value unit="WPerSquareMeterK">3.4317585</U-value>
    <Absorptance unit="Fraction" type="ExtIR">0.1</Absorptance>
    <Roughness value="VeryRough" />
    <LayerId layerIdRef="aim0045" />
    <Name>Floor: Generic - 12"</Name>
  </Construction>

  <Layer id="aim0045">
    <MaterialId materialIdRef="aim0046" />
  </Layer>

  <Material id="aim0046">
    <Name>Concrete, Normal Weight, 5 ksi: 1'</Name>
    <R-value unit="SquareMeterKPerW">0.2913958</R-value>
    <Thickness unit="Meters">0.3048</Thickness>
    <Conductivity unit="WPerMeterK">1.046</Conductivity>
    <Density unit="KgPerCubicM">2300</Density>
    <SpecificHeat unit="JPerKgK">657</SpecificHeat>
  </Material>
```

Before, "Thermal Absorptance" for the Material mapped to 0.9 (the idd default). Now it maps to 0.1 because the outside layer of the Construction has "ExtIR=0.1". See [here](https://github.com/NREL/OpenStudio/blob/gbxml-updates/src/gbxml/MapEnvelope.cpp#L121-L132) for the actual code implementation. I assume the `materials` array is ordered in the direction of outside layer -> inside layer.

**Review by axelstudios — APPROVED** [review]
Tested against Autodesk's gbXML files, results for all files (excluding House.xml which we're looking into) were nearly identical
