### PR TITLE
Fix #4404 #4453 - Fix issues with ForwardTranslator options

### LINKED ISSUE #4404: ForwardTranslator::setExcludeLCCObjects doesn't exclude all LCC objects
Issue overview
--------------
Using `ft.setExcludeLCCObjects(true)` excludes most all LCC objects, but not the `LifeCycleCost:NonrecurringCost` object. This is annoying, because it results in an EnergyPlus warning:

```
   ************* There are 1 unused objects in input.
   ************* Use Output:Diagnostics,DisplayUnusedObjects; to see them.
```

If I use the Output:Diagnostics,DisplayUnusedObjects object, I get:

```
   ** Warning ** The following lines are "Unused Objects".  These objects are in the input
   **   ~~~   **  file but are never obtained by the simulation and therefore are NOT used.
   **   ~~~   **  Only the first unused named object of an object class is shown.  Use Output:Diagnostics,DisplayAllWarnings; to see all.
   **   ~~~   **  See InputOutputReference document for more details.
   ************* Object=LifeCycleCost:NonrecurringCost=Default Cost
```

I looked briefly at the source code and it seems to be cause by [these lines](https://github.com/NREL/OpenStudio/blob/1b8f0d3549d67f5e461677439ee85c5d6f6cad0c/src/energyplus/ForwardTranslator.cpp#L4201-L4219). Perhaps this code should be wrapped in an if statement like [here](https://github.com/NREL/OpenStudio/blob/1b8f0d3549d67f5e461677439ee85c5d6f6cad0c/src/energyplus/ForwardTranslator.cpp#L423)?

The context here is that I'm trying to write tests around my software to ensure that there are no unused objects reported by EnergyPlus (which may indicate a bug), but am unable to do so because of this.

## Steps to Reproduce
1. Clone the [OpenStudio-HPXML repo](https://github.com/NREL/OpenStudio-HPXML).
2. Run a sample file using the run_simulation.rb script (which uses setExcludeLCCObjects(true)): `openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml -o test --debug`
3. Note the unused object warning in test/run/eplusout.err.

### LINKED ISSUE #4453: ForwardTranslator::setExcludeHTMLOutputReport doesn't exclude Output:Table:SummaryReports
Issue overview
--------------

ForwardTranslator::setExcludeHTMLOutputReport doesn't exclude Output:Table:SummaryReports

Found while investigating #4404

## Current Behavior

```
[1] energyplus(main)> m = Model.new
=> #<OpenStudio::Model::Model:0x0000559e22574200 @__swigtype__="_p_openstudio__model__Model">
[2] energyplus(main)> ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
=> #<OpenStudio::EnergyPlus::ForwardTranslator:0x0000559e220c0150 @__swigtype__="_p_openstudio__energyplus__ForwardTranslator">
[3] energyplus(main)> ft.setExcludeHTMLOutputReport(true)
=> nil
[4] energyplus(main)> w = ft.translateModel(m)
[openstudio.model.YearDescription] <-1> 'UseWeatherFile' is not yet a supported option for YearDescription
[openstudio.model.YearDescription] <-1> 'UseWeatherFile' is not yet a supported option for YearDescription
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Discrete', points to an object named OnOff from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff 1 from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional from field 1, but that object cannot be located.
=> #<OpenStudio::Workspace:0x0000559e23143310 @__swigtype__="_p_openstudio__Workspace">
[5] energyplus(main)> puts w.getObjects
w.getObjects               w.getObjectsByName         w.getObjectsByReference    w.getObjectsByType         w.getObjectsByTypeAndName  
[5] energyplus(main)> puts w.getObjectsByType("Output:Table:SummaryReports")
Output:Table:SummaryReports,
  AllSummary;                             !- Report Name 1

=> nil

```

## Expected Behavior

It should exclude the object

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 92796372b7e719241b2912eacbbc8a9907f82a05

### Context

cf #4404

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

- Fix  #4404
- Fix #4453

I added a unit test for all options. #4404 is confirmed, but I also found out that Output:Table:SummaryReports was problematic also.

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/energyplus/ForwardTranslator.cpp [hunk 1]
```diff
@@ -464,22 +464,25 @@ namespace energyplus {
...
+      // If the user manually added an OutputTableSummaryReports, but he also opted-in to exclude it on the FT, which decision do we keep?
+      // Given that it's a much harder to set the option on the FT, I'll respect that one
+      if (!m_excludeHTMLOutputReport) {
+        auto optOutputTableSummaryReports = model.getOptionalUniqueModelObject<model::OutputTableSummaryReports>();
+        // Add default one if none explicitly specified
+        if (!optOutputTableSummaryReports) {
+          auto outputTableSummaryReports = model.getUniqueModelObject<model::OutputTableSummaryReports>();
+          outputTableSummaryReports.addSummaryReport("AllSummary");
+          translateAndMapModelObject(outputTableSummaryReports);
+        }
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator.cpp:476]: Fix #4453

File: src/energyplus/ForwardTranslator.cpp [hunk 2]
```diff
@@ -4198,24 +4201,22 @@ namespace energyplus {
...
+               || (iddObjType == openstudio::IddObjectType::LifeCycleCost_RecurringCosts);
+      });
+
+      if (!hasAtLeastOneCost) {
+        // add default cost
+        auto& idfObject = m_idfObjects.emplace_back(openstudio::IddObjectType::LifeCycleCost_NonrecurringCost);
+        idfObject.setString(LifeCycleCost_NonrecurringCostFields::Name, "Default Cost");
+        idfObject.setString(LifeCycleCost_NonrecurringCostFields::Category, "Construction");
+        idfObject.setDouble(LifeCycleCost_NonrecurringCostFields::Cost, 0.0);
+        idfObject.setString(LifeCycleCost_NonrecurringCostFields::StartofCosts, "ServicePeriod");
```
Comment (jmarrec) [inline src/energyplus/ForwardTranslator.cpp:4217]: Fix #4404  + use std::any_of instead of looping on all objects (and not even breaking as soon as one is found).
Also use emplace_back to construct in place for performance reasons

File: src/energyplus/Test/ForwardTranslator_GTest.cpp [hunk 3]
```diff
@@ -758,3 +758,124 @@ TEST_F(EnergyPlusFixture, BadVariableName) {
...
+    EXPECT_EQ(0u, w.numObjectsOfType(IddObjectType::LifeCycleCost_RecurringCosts));
+
+    EXPECT_EQ(0u, w.numObjectsOfType(IddObjectType::Output_VariableDictionary));
+    EXPECT_EQ(0u, w.numObjectsOfType(IddObjectType::Output_SQLite));
+    EXPECT_EQ(0u, w.numObjectsOfType(IddObjectType::Output_Table_SummaryReports));
+
+    // This also turns off the OutputControl:Table:Style
+    EXPECT_EQ(0u, w.numObjectsOfType(IddObjectType::OutputControl_Table_Style));
+  }
+}
```
Comment (jmarrec) [inline src/energyplus/Test/ForwardTranslator_GTest.cpp:881]: Add a unit test for all options

**Comment by shorowit** [comment]
I'd be happy to test this but I don't see any Ubuntu or Windows builds above?

**Comment by jmarrec** [comment]
@shorowit installers are up now

**Comment by shorowit** [comment]
Verified that this fixes the issue for me. Thanks, @jmarrec!

**Review by tijcolem — APPROVED** [review]
@jmarrec Looks great and thanks @shorowit for confirming!
