### PR TITLE
Fix AVMList clone between different models

### LINKED ISSUE #4033: Limited functionality of clone AirLoopHVAC
Issue overview
--------------
My use case is cloning from one model to another model, not within a model. I may find more issues, but I wanted to file with this initial problem.

- [ ] AvailabilityManagerAssignmentList isn't cloned with the air loop. This results in crash of app when go to control tab for the air loop, or failed export to IDF. This may be general clone Loop issue and not specific to plant loops. I have not tested plant loops yet.

## Current Behavior

Screen Shot 2020-08-05 at 10 23 33 AM

## Expected Behavior
Clone should result in valid air loop 

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution

Here is my ruby work around, not proposed solution, but shows what needs to change to make the loop valid
```
    # create and assign AvailabilityManagerAssignmentList to cloned air loops
    model.getAirLoopHVACs.sort.each do |air_loop|
      if air_loop.getString(4).to_s == ""
        list = OpenStudio::Model::AvailabilityManagerAssignmentList.new(air_loop)
        # line above adds list but doesn't associate it with air_loop. Line below is a work around to force it in
        air_loop.setString(4,list.handle.to_s)
      end
    end
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context
Clone air loops from one model to another as part of effort to combine many OSM's to one OSM.

### LINKED ISSUE #4034: Limited functionality of clone PlantLoop
Issue overview
--------------
Similar issue to Issue #4033 with missing availability manger assignment list in cloned plant loop.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution
The work around is similar to air loop bud different field to change in the plant loop.
```
    # todo - code below here should be removed when SDK updated to handle this with clone plant loop method
    # create and assign AvailabilityManagerAssignmentList to cloned plant loops
    model.getPlantLoops.sort.each do |plant_loop|
      if plant_loop.getString(22).to_s == ""
        list = OpenStudio::Model::AvailabilityManagerAssignmentList.new(plant_loop)
        # line above adds list but doesn't associate it with air_loop. Line below is a work around to force it in
        plant_loop.setString(22,list.handle.to_s)
      end
    end
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by kbenne**
close #4033
close #4034

Pull request overview
---------------------

 - Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)
 - DESCRIBE PURPOSE OF THIS PULL REQUEST

Please read [OpenStudio Pull Requests](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Pull-Requests) to better understand the OpenStudio Pull Request protocol.

### Pull Request Author

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Checked behavior in OpenStudioApplication, adjusted policies as needed (`src/openstudio_lib/library/OpenStudioPolicy.xml`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

**Comment by kbenne** [comment]
what do you think @jmarrec?

File: src/model/AvailabilityManagerAssignmentList.hpp [hunk 1]
```diff
@@ -60,6 +60,8 @@ class MODEL_API AvailabilityManagerAssignmentList : public ModelObject {
    */
   explicit AvailabilityManagerAssignmentList(const Loop& loop);
 
+  explicit AvailabilityManagerAssignmentList(const Model& model);
```
Comment (jmarrec) [inline src/model/AvailabilityManagerAssignmentList.hpp:63]: Can we make it protected/private? Or at least ignore in the bindings... I don't like the fact that this becomes public, as users shouldn't have any business creating orphaned ones.

Comment (kbenne) [reply src/model/AvailabilityManagerAssignmentList.hpp:63]: yeah. I can do that. note that even if you use `AvailabilityManagerAssignmentList(const Loop& loop)` the new AVM is still orphaned. The loop argument is actually only used to set the name of the AVM. This itself should probably be considered a bug. https://github.com/NREL/OpenStudio/blob/fa9a77bf173556a2a044f64789a7f4f01b0df076/src/model/AvailabilityManagerAssignmentList.cpp#L409

Comment (jmarrec) [reply src/model/AvailabilityManagerAssignmentList.hpp]: I suppose to some extent and to echo #4072 AvailabilityManagerAssignmentList doesn't _really_ have any business having a name in the OSM since the user isn't meant to interact with it... It could be created at FT time.

Comment (kbenne) [reply src/model/AvailabilityManagerAssignmentList.hpp]: @jmarrec you are certainly welcome to add to the list of objects in #4077 to "un-name" If it is not user facing then I think it is fair game. For those that have non uuid names, and perhaps even those that do, I would anticipate a performance advantage.

Comment (kbenne) [reply src/model/AvailabilityManagerAssignmentList.hpp]: Certainly users will appreciate having nice names in the finished EnergyPlus idf. AVMlist named after the loop it belongs to etc.
