### PR TITLE
Fix #4336 - Encode searchTerm in BCL (including spaces, not only "+" signs)

### LINKED ISSUE #4336: BCL searchMeasureLibrary should encode spaces in the pattern
Issue overview
--------------

If you search for a bcl measure using a space in the pattern, it crashes

```
terminate called after throwing an instance of 'web::uri_exception'
  what():  provided uri is invalid: /api/metasearch/test a space.xml?fq%5B%5D=bundle:nrel_measure&fq%5B%5D=tid:953&api_version=2.0
Process 30980 stopped
```

## Current Behavior

It crashes

## Expected Behavior

It should encode the space, like it does the + as %2B https://github.com/NREL/OpenStudio/blob/92a416c03a98b44b67668e5b3d6d3c89be729afa/src/utilities/bcl/RemoteBCL.cpp#L631-L647

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution

encode

## Details

backtrace

```
(lldb) bt
* thread #1, name = 'OpenStudioApp', stop reason = signal SIGABRT
  * frame #0: 0x00007fffe8d0e18b libc.so.6`raise + 203
    frame #1: 0x00007fffe8ced859 libc.so.6`abort + 299
    frame #2: 0x00007fffe90c5a31 libstdc++.so.6`___lldb_unnamed_symbol33$$libstdc++.so.6 + 93
    frame #3: 0x00007fffe90d15dc libstdc++.so.6`___lldb_unnamed_symbol443$$libstdc++.so.6 + 12
    frame #4: 0x00007fffe90d1647 libstdc++.so.6`std::terminate() + 23
    frame #5: 0x00007fffe90d18e9 libstdc++.so.6`__cxa_throw + 73
    frame #6: 0x00007ffff415ce96 libopenstudiolib.so`web::uri::uri(web::details::uri_components const&) (.cold) + 236
    frame #7: 0x00007ffff607ddae libopenstudiolib.so`web::uri_builder::to_uri() const + 14
    frame #8: 0x00007ffff607e91f libopenstudiolib.so`web::uri_builder::to_string[abi:cxx11]() const + 47
    frame #9: 0x00007ffff41f1b08 libopenstudiolib.so`openstudio::RemoteBCL::startComponentLibraryMetaSearch(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 1208
    frame #10: 0x00007ffff41f1dd1 libopenstudiolib.so`openstudio::RemoteBCL::metaSearchComponentLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const + 49
    frame #11: 0x00007ffff41f36c6 libopenstudiolib.so`openstudio::RemoteBCL::searchMeasureLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int) const + 102
    frame #12: 0x0000555556557707 OpenStudioApp`openstudio::BuildingComponentDialogCentralWidget::setTid(this=0x0000555557ada3c0, filterType="measures", tid=953, pageIdx=0, title=b'""', searchString=b'""') at BuildingComponentDialogCentralWidget.cpp:202:47
    frame #13: 0x0000555556554a92 OpenStudioApp`openstudio::BuildingComponentDialog::requestComponents(this=0x00007fffd8009ce0, filterType="measures", tids=953, pageIdx=0, searchString=b'""') at BuildingComponentDialog.cpp:278:26
    frame #14: 0x0000555556554c4e OpenStudioApp`openstudio::BuildingComponentDialog::on_searchButton(this=0x00007fffd8009ce0) at BuildingComponentDialog.cpp:297:20
    frame #15: 0x0000555556555fdf OpenStudioApp`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (openstudio::BuildingComponentDialog::*)()>::call(f=48 4b 55 56 55 55 00 00 00 00 00 00 00 00 00 00, o=0x00007fffd8009ce0, arg=0x00007fffffffbea0)(), openstudio::BuildingComponentDialog*, void**) at qobjectdefs_impl.h:152:20
    frame #16: 0x0000555556555e3a OpenStudioApp`void QtPrivate::FunctionPointer<void (openstudio::BuildingComponentDialog::*)()>::call<QtPrivate::List<>, void>(f=48 4b 55 56 55 55 00 00 00 00 00 00 00 00 00 00, o=0x00007fffd8009ce0, arg=0x00007fffffffbea0)(), openstudio::BuildingComponentDialog*, void**) at qobjectdefs_impl.h:185:95
    frame #17: 0x00005555565559c9 OpenStudioApp`QtPrivate::QSlotObject<void (openstudio::BuildingComponentDialog::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x0000555557a3e850, r=0x00007fffd8009ce0, a=0x00007fffffffbea0, ret=0x0000000000000000) at qobjectdefs_impl.h:418:49

```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context

Transfered from https://github.com/openstudiocoalition/OpenStudioApplication/issues/274#issuecomment-851707878

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

Fix #4336 - Encode searchTerm in BCL (including spaces, not only "+" signs)

The Cpprestsdk documentation is not great (and I couldn't find any post on stackoverflow), but I found a function that does just what's expected. 

https://microsoft.github.io/cpprestsdk/classweb_1_1uri.html#ac1a92ee41ad0e77e262a8b4fcb235ac1

Also bumped the conan.cmake to v0.16.1

### Pull Request Author

 - [x] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/bcl/RemoteBCL.cpp [hunk 1]
```diff
@@ -639,8 +639,9 @@ bool RemoteBCL::startComponentLibraryMetaSearch(const std::string& searchTerm, c
   auto client = getClient(remoteUrl(), m_timeOutSeconds);
   web::uri_builder builder(U("/api/metasearch/"));
 
-  auto query = searchTerm.empty() ? "*" : searchTerm;
-  query = std::regex_replace(query, std::regex("\\+"), "%2B");
+  // web::uri::encode_data_string will Encodes a string by converting all characters
+  // except for RFC 3986 unreserved characters to their hexadecimal representation. (eg: '+' => %2B, ' ' => %20)
+  auto query = searchTerm.empty() ? "*" : web::uri::encode_data_string(searchTerm);
```
Comment (jmarrec) [inline src/utilities/bcl/RemoteBCL.cpp:644]: Same change as this one repeated.

File: ConanInstall.cmake [hunk 2]
```diff
@@ -6,8 +6,8 @@
 
 if(NOT CONAN_OPENSTUDIO_ALREADY_RUN)
 
-  set(CMAKE_CONAN_EXPECTED_HASH 773399d30bb924959b86883f95d64df6)
-  set(CMAKE_CONAN_VERSION "v0.15")
+  set(CMAKE_CONAN_EXPECTED_HASH 170c3250029af321395135a3952a9045)
+  set(CMAKE_CONAN_VERSION "v0.16.1")
```
Comment (jmarrec) [inline ConanInstall.cmake:10]: bump conan.cmake

**Review by tijcolem — APPROVED** [review]
Looks good to me.  Thanks for making windows happy =)
