### PR TITLE
Fix #5313 - AirLoopHVACUnitaryHeatPump(Multispeed) fixes

### LINKED ISSUE #5313: Using CoilHeatingWaters in the Supplemental Heating Coil Object Type field for the AirLoopHVACUnitaryHeatPumpAirToAir group causes failure.
Issue overview
--------------
When using OpenStudio::Model::AirLoopHVACUnitaryHeatPumpAirToAir.new(), specifying a supplementary heating coil of type CoilHeatingWater fails. This occurs even though the plant loop, branches, and connector objects to support the hot water supplemental heating coil are placed on the demand side of the plantloop.

## Current Behavior
The following error in Windows:
`[BOOST_ASSERT] <2> Assertion result failed on line 244 of class openstudio::model::HVACComponent __cdecl openstudio::model::detail::AirLoopHVACUnitaryHeatPumpAirToAir_Impl::supplementalHeatingCoil(void) const in file D:\OSN\Openstudio\src\model\AirLoopHVACUnitaryHeatPumpAirToAir.cpp.`

And the following more severe error with a segmentation fault in the Linux-based development environment:
`[BOOST_ASSERT] <2> Assertion result failed on line 244 of openstudio::model::HVACComponent openstudio::model::detail::AirLoopHVACUnitaryHeatPumpAirToAir_Impl::supplementalHeatingCoil() const in file /srv/jenkins/openstudio/git/nightly/ubuntu_2004/src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp. 
hp_test_lnx.rb:53: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`

The above segmentation fault is followed by several hundred lines of error code under headings 'Control frame information', 'Ruby level backtrace information', 'Machine register context', and 'Other runtime information'.

## Expected Behavior
The AirLoopHVACUnitaryHeatPumpAirToAir should accept a CoilHeatingWater for the supplemental heating coil, at least according to the [EnergyPlus 24.2.0 documentation](https://bigladdersoftware.com/epx/docs/24-2/input-output-reference/group-unitary-equipment.html#field-supplemental-heating-coil-object-type-1).

## Steps to Reproduce
Try to specify a hot water supplemental heating coil in the AirLoopHVACUnitaryHeatPumpAirToAir group. Example files [here](https://github.com/hobsonbw/supp_hw_bug.git).

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10 Enterprise, 10.0.19045 Build 19045
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0, 3.9.0
-  Platform (Operating system, version): Ubuntu, 20.04.6 LTS
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0, 3.9.0

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5313
 - Fixup addToNode & clone for AirLoopHVACUnitaryHeatPumpMultispeed: realized that the class had ZERO tests, and after adding them, realized the methods were broken

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/model/test/AirLoopHVACUnitaryHeatPumpAirToAir_GTest.cpp [hunk 1]
```diff
@@ -209,3 +212,19 @@ TEST_F(ModelFixture, AirLoopHVACUnitaryHeatPumpAirToAir_CoilSystemIntegratedHeat
...
+
+  CoilCoolingDXVariableSpeed cc(m);
+  CoilHeatingDXVariableSpeed hc(m);
+
+  // Wrong supplemental heating coil type, I expect a graceful failure, not a segfault
+  CoilHeatingDXVariableSpeed suppHC(m);
+
+  // The segfault is caught here, but if graceful, the remove() was called!
+  EXPECT_THROW(AirLoopHVACUnitaryHeatPumpAirToAir(m, s, supplyFan, hc, cc, suppHC), openstudio::Exception);
+  EXPECT_EQ(0, m.getConcreteModelObjects<AirLoopHVACUnitaryHeatPumpAirToAir>().size());
```
Comment (jmarrec) [inline src/model/test/AirLoopHVACUnitaryHeatPumpAirToAir_GTest.cpp:229]: Before fix: 

```
[BOOST_ASSERT] <2> Assertion result failed on line 244 of openstudio::model::HVACComponent openstudio::model::detail::AirLoopHVACUnitaryHeatPumpAirToAir_Impl::supplementalHeatingCoil() const in file /media/DataExt4/Software/Others/OpenStudio2/src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp.
openstudio_model_tests: /media/DataExt4/Software/Others/OpenStudio2/src/model/test/../../utilities/core/Assert.hpp:37: void boost::assertion_failed(const char*, const char*, const char*, long int): Assertion `false' failed.
Aborted (core dumped)
```

File: src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp
Comment (jmarrec) [inline src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:1]: We had this test file, yet it was fully empty... We should do another pass to find untested classes @kbenne @DavidGoldwasser

File: src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp [hunk 2]
```diff
@@ -10,5 +10,338 @@
...
+
+  // Wrong cooling type, I expect a graceful failure, not a segfault
+  CoilCoolingDXSingleSpeed cc(m);
+  CoilHeatingElectricMultiStage hc(m);
+  CoilHeatingElectric suppHC(m);
+
+  // The segfault is caught here, but if graceful, the remove() was called!
+  EXPECT_THROW(AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed(m, supplyFan, hc, cc, suppHC), openstudio::Exception);
+  EXPECT_EQ(0, m.getConcreteModelObjects<AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed>().size());
+}
```
Comment (jmarrec) [inline src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:347]: Before fix, this doesn't segfault because there is a LOG_AND_THROW and not an OS_ASSERT, but the remove() is never called though.

```
[ RUN      ] ModelFixture.AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_Ctor_WrongChildType
/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:346: Failure
Expected equality of these values:
  0
  m.getConcreteModelObjects<AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed>().size()
    Which is: 1
```

File: src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp [hunk 3]
```diff
@@ -10,5 +10,338 @@
...
+
+  auto testObjectClone = testObject.clone(m).cast<AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed>();
+  // Clone should reset the inlet/outlet nodes
+  ASSERT_FALSE(testObjectClone.inletModelObject());
+  ASSERT_FALSE(testObjectClone.outletModelObject());
+
+  supplyOutletNode = airLoop.supplyOutletNode();
+  EXPECT_TRUE(testObjectClone.addToNode(supplyOutletNode));
+  EXPECT_EQ(5, airLoop.supplyComponents().size());
+}
```
Comment (jmarrec) [inline src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:332]: Completely wrong originally.

The Clone method was using MdoelObject_Impl::clone, which does not reset the inlet/outlet nodes.
And the addToNode was not overriden so it'd accept ANY connection.


```
[ RUN      ] ModelFixture.AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_addToNode
/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:310: Failure
Value of: testObject.addToNode(inletNode)
  Actual: true
Expected: false

/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:311: Failure
Expected equality of these values:
  5
  airLoop.demandComponents().size()
    Which is: 7

/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:316: Failure
Value of: testObject.addToNode(supplyOutletNode)
  Actual: true
Expected: false

/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:317: Failure
Expected equality of these values:
  5
  plantLoop.supplyComponents().size()
    Which is: 7

/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:321: Failure
Value of: testObject.addToNode(demandOutletNode)
  Actual: true
Expected: false

/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:322: Failure
Expected equality of these values:
  5
  plantLoop.demandComponents().size()
    Which is: 7

/media/DataExt4/Software/Others/OpenStudio2/src/model/test/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_GTest.cpp:331: Failure
Expected equality of these values:
  5
  airLoop.supplyComponents().size()
    Which is: 3
```

File: resources/model/OpenStudio.idd [hunk 4]
```diff
@@ -11569,6 +11569,7 @@ OS:AirLoopHVAC:UnitaryHeatPump:AirToAir,
        \type object-list
        \required-field
        \object-list HeatingCoilsGasElec
+       \object-list HeatingCoilsWater
```
Comment (jmarrec) [inline resources/model/OpenStudio.idd:11572]: Specific for #5313 - Suppl HC should allow Coil:Heating:Water (Coil:Heating:Steam isn't wrapped in OS)

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAir_Impl.hpp [hunk 5]
```diff
@@ -186,21 +186,10 @@ namespace model {
...
-      bool setControllingZoneAsModelObject(const boost::optional<ModelObject>& modelObject);
-      bool setSupplyAirFanAsModelObject(const boost::optional<ModelObject>& modelObject);
-      bool setHeatingCoilAsModelObject(const boost::optional<ModelObject>& modelObject);
-      bool setCoolingCoilAsModelObject(const boost::optional<ModelObject>& modelObject);
-      bool setSupplementalHeatingCoilAsModelObject(const boost::optional<ModelObject>& modelObject);
-      bool setSupplyAirFanOperatingModeScheduleAsModelObject(const boost::optional<ModelObject>& modelObject);
+      boost::optional<HVACComponent> optionalSupplyAirFan() const;
+      boost::optional<HVACComponent> optionalHeatingCoil() const;
+      boost::optional<HVACComponent> optionalCoolingCoil() const;
+      boost::optional<HVACComponent> optionalSupplementalHeatingCoil() const;
```
Comment (jmarrec) [inline src/model/AirLoopHVACUnitaryHeatPumpAirToAir_Impl.hpp:192]: Remove useless methods AsModelObject (never used anywhere), and replace with actual useful methods.

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp [hunk 6]
```diff
@@ -114,10 +116,19 @@ namespace model {
...
+      }
+      if (boost::optional<HVACComponent> coolingCoil = this->optionalCoolingCoil()) {
+        result.push_back(std::move(*coolingCoil));
+      }
+      if (boost::optional<HVACComponent> heatingCoil = this->optionalHeatingCoil()) {
+        result.push_back(std::move(*heatingCoil));
+      }
+      if (boost::optional<HVACComponent> supplementalHeatingCoil = this->optionalSupplementalHeatingCoil()) {
+        result.push_back(std::move(*supplementalHeatingCoil));
+      }
```
Comment (jmarrec) [inline src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp:131]: Fix for the crash is here

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp [hunk 7]
```diff
@@ -419,6 +437,8 @@ namespace model {
         isTypeOK = true;
       } else if (hvacComponent.optionalCast<CoilHeatingElectric>()) {
         isTypeOK = true;
+      } else if (hvacComponent.optionalCast<CoilHeatingWater>()) {
+        isTypeOK = true;
```
Comment (jmarrec) [inline src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp:441]: And here too

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp [hunk 8]
```diff
@@ -591,8 +597,18 @@ namespace model {
...
 
+    bool AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_Impl::addToNode(Node& node) {
+      if (boost::optional<AirLoopHVAC> airLoop = node.airLoopHVAC()) {
+        if (airLoop->supplyComponent(node.handle())) {
+          return StraightComponent_Impl::addToNode(node);
+        }
+      }
+
+      return false;
+    }
```
Comment (jmarrec) [inline src/model/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp:608]: Restrict addToNode.

Note that ideally we should also allow demand side of a plant loop and connect the Heat Recovery Water Nodes there, but outside the scope and no one ever asked for it.

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp [hunk 9]
```diff
@@ -591,8 +597,18 @@ namespace model {
...
+
     ModelObject AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed_Impl::clone(Model model) const {
-      auto modelObjectClone = ModelObject_Impl::clone(model).cast<AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed>();
+      auto modelObjectClone = StraightComponent_Impl::clone(model).cast<AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed>();
```
Comment (jmarrec) [inline src/model/AirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp:611]: Fixup clone here

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp (hunk 7 above)
Comment (joseph-robertson) [reply src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp:441]: Why don't we check type on Multispeed?

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAir_Impl.hpp (hunk 5 above)
Comment (jmarrec) [reply src/model/AirLoopHVACUnitaryHeatPumpAirToAir_Impl.hpp:192]: Yes

File: src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp (hunk 7 above)
Comment (jmarrec) [reply src/model/AirLoopHVACUnitaryHeatPumpAirToAir.cpp:441]:
```diff
OS:AirLoopHVAC:UnitaryHeatPump:AirToAir,
  [...]
  A10, \field Supplemental Heating Coil Name
       \note Needs to match in the supplemental heating coil object
       \type object-list
       \required-field
+      \object-list HeatingCoilsGasElec
```

```diff
OS:AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed,
   A12, \field Supplemental Heating Coil
        \type object-list
+       \object-list HeatingCoilName
```

Technically speaking, checking specifically on the `AirLoopHVACUnitaryHeatPumpAirToAir::setSupplementalHeatingCoil` is probably pointless **unless** the `HeatingCoilsGasElec` englobes more coils than are actually accepted, since `setPointer` will enforce the references. But 1) it was existing, so I'm just adding to it, and 2) it is probably safer?

**Review by joseph-robertson — APPROVED** [review]
