### PR TITLE
Fix #5181 - when using --bundle in the CLI, use Embedded native gems when they are present and version compatible

### LINKED ISSUE #5181: CLI issue when using bundle and it has a native gem listed as a dependency
Issue overview
--------------

This is **exactly** the same issue as https://github.com/NREL/OpenStudio/issues/5091 which was specifically for `racc`.

This popped up again yesterday when @wenyikuang and @DavidGoldwasser tried to upgrade rubocop to > 1.31.

Rubocop 1.31 added `json, ~> 2.3` as a dependency, and that is a native extension. We do have a json 2.6.3 in the CLI, but it would still fails because

```
Source locally installed gems is ignoring #<Bundler::StubSpecification name=json version=2.7.2 platform=ruby> because it is missing extensions
terminate called after throwing an instance of 'RubyException'
  what():  Bundler::GemNotFound: Could not find json-2.7.2 in locally installed gems
```

## Steps to Reproduce

checkout https://github.com/NREL/openstudio-ee-gem/pull/52/commits/e0f9fdc4877cd8868164a710fdffb61ab2f045a4

using system ruby 3.2.2 with bundler 2.4.10

```
bundle _2.4.10_ install --path=$(pwd)/.bundle
```

Example command would be `bundle exec rake openstudio:test_with_openstudio`.

Or directly and more succinctly

```
$os_build_rel2/Products/openstudio --loglevel Trace --bundle '/home/julien/Software/Others/openstudio_gems/openstudio-ee-gem/Gemfile' --bundle_path '/home/julien/Software/Others/openstudio_gems/openstudio-ee-gem/.bundle' -e 'puts "hello"'
```

## Possible Solution

We should just use the embedded native gems when they are **both**:

* Preset
* Compatible with the requirements

eg rubocop requires json ~> 2.3

`bundle _2.4.10_ install --path=$(pwd)/.bundle` would resolve it as json-2.7.2.

But our CLI embeds json 2.6.3, which is compatible.

So we should just use the CLI one.

@kbenne FYI.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.8.0-rc1

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5181

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: ruby/bindings/InitRubyBindings.cpp [hunk 1]
```diff
@@ -874,6 +878,27 @@ void locateEmbeddedGems(bool use_bundler) {
...
+
+          # This avoids getting an annoying message for no reason
+          if $ignore_native_gem_names.any? {|name| name == spec.name }
+            return false
+          end
+
+          return ori_spec_missing_extensions?(spec, default)
+        end
+      end
+    end
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:900]: Define a global variable that will store the gem names for which we do have a compatible native extension inside the CLI.

And patch spec_missing_extensions? to just shush the warning that will remain anyways

File: ruby/bindings/InitRubyBindings.cpp [hunk 2]
```diff
@@ -920,6 +945,37 @@ void locateEmbeddedGems(bool use_bundler) {
 
     $logger.info "Bundling with groups [#{keep_groups.join(',')}]"
 
+    # Filter out dependencies with native extensions that we already have embedded in the CLI and that satisfy the requirements
+    locked_specs = Bundler.definition.instance_variable_get(:@locked_specs)
+
+    embedded_gems_to_activate.each do |spec|
+      next if spec.extensions.empty?
+
+      next unless locked_specs.any? {|locked_spec| locked_spec.name == spec.name}
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:954]: Alright, main dish starts here. Apologies in advance for what you're going to witness...


Step 1, grab the locked_specs, which is a private instance variable, and is the key one that bundler will use to resolve.

We start by looping on the emedded_gems_to_activate, and we keep only:
* Gems with native extensions
* Gems actually used by bundler as well.

File: ruby/bindings/InitRubyBindings.cpp [hunk 3]
```diff
@@ -920,6 +945,37 @@ void locateEmbeddedGems(bool use_bundler) {
...
+
+      dep_to_requirements = {}
+      locked_specs.each do |locked_spec|
+        deleted_deps = locked_spec.dependencies.select { |dep| dep.name == spec.name && dep.requirement.satisfied_by?(spec.version) }
+        locked_spec.dependencies.reject! { |dep| dep.name == spec.name && dep.requirement.satisfied_by?(spec.version) }
+        deleted_deps&.each do |dep|
+          dep_to_requirements[locked_spec.name] = dep.requirement.to_s
+        end
+      end
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:963]: Pass one, we loop on all of these locked_specs, and we can their dependencies to try to see if they meet our current spec or not. If so, delete it (and store the requirements in a hash for reporting purposes).

For reference, spec (from embedded_gems_to_activate) looks like

```ruby
Gem::Specification.new do |s|
      s.name = "json"
      s.version = Gem::Version.new("2.7.2")
...
```

**locked_spec** looks like this

```ruby
locked_spec
 => 
#<Bundler::LazySpecification:0x00007f52209429f0                  
 @dependencies=                                                  
  [Gem::Dependency.new("json", Gem::Requirement.new(["~> 2.3"]), :runtime),
   Gem::Dependency.new("parallel", Gem::Requirement.new(["~> 1.10"]), :runtime),
   Gem::Dependency.new("parser", Gem::Requirement.new([">= 3.2.0.0"]), :runtime),
   Gem::Dependency.new("rainbow", Gem::Requirement.new([">= 2.2.2", "< 4.0"]), :runtime),
   Gem::Dependency.new("regexp_parser", Gem::Requirement.new([">= 1.8", "< 3.0"]), :runtime),
   Gem::Dependency.new("rexml", Gem::Requirement.new([">= 3.2.5", "< 4.0"]), :runtime),
   Gem::Dependency.new("rubocop-ast", Gem::Requirement.new([">= 1.28.0", "< 2.0"]), :runtime),
   Gem::Dependency.new("ruby-progressbar", Gem::Requirement.new(["~> 1.7"]), :runtime),
   Gem::Dependency.new("unicode-display_width", Gem::Requirement.new([">= 2.4.0", "< 3.0"]), :runtime)],
 @force_ruby_platform=false,
 @full_name="rubocop-1.52.0",
 @name="rubocop",
 @platform="ruby",
 @source=#<Bundler::Source::Rubygems:0x30140 locally installed gems>,
 @use_exact_resolved_specifications=true,
 @version=Gem::Version.new("1.52.0")>
```

File: ruby/bindings/InitRubyBindings.cpp [hunk 4]
```diff
@@ -920,6 +945,37 @@ void locateEmbeddedGems(bool use_bundler) {
...
+
+      if locked_specs.none? { |locked_spec| locked_spec.dependencies.any? {|x| x.name == spec.name} }
+        locked_spec_v = locked_specs.select{|locked_spec| locked_spec.name == spec.name}.first.version
+        $logger.debug("Removing native gem #{spec.name} from Bundler locked_specs (version #{locked_spec_v}), using the embedded dependency (CLI one has version #{spec.version})")
+        $logger.trace("Gems having #{spec.name} as a dependency: #{dep_to_requirements}")
+        raise "Failed to activate #{spec.name}" unless spec.activate
+        $ignore_native_gem_names << spec.name
+        locked_specs.delete_by_name(spec.name)
+      end
+    end
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:974]: If after cleaning all dependencies, there are none left, then we actually remove the locked_spec called "spec.name" itself.

So for eg,

locked_specs has originally one for rubocop, with a dependency on json. We remove this one. And it was the only one.

Then we actually delete the locked_spec named json.

Comment (jmarrec) [reply ruby/bindings/InitRubyBindings.cpp:974]: As a result, when you run with Trace loglevel, you see


```
[ruby] <-1> Bundling with groups [default,development]
[ruby] <-2> Removing native gem json from Bundler locked_specs (version 2.7.2), using the embedded dependency (CLI one has version 2.6.3)
[ruby] <-3> Gems having json as a dependency: {"rubocop"=>"~> 2.3"}
Found no changes, using resolution from the lockfile
[ruby] <-1> Specs to be included [rake,public_suffix,addressable,ansi,ast,builder,multipart-post,faraday,minitar,rchardet,git,minitest,ruby-progressbar,minitest-reporters,parser,parallel,rainbow,regexp_parser,rexml,rubocop-ast,unicode-display_width,rubocop,rubocop-checkstyle_formatter,rubocop-performance,docile,simplecov-html,simplecov,openstudio_measure_tester,rubyzip,ruby-ole,spreadsheet,systemu,macaddr,uuid,yamler,zliby,bcl,bundler,diff-lcs,json-schema,matrix,sawyer,octokit,openstudio-ee,openstudio-extension,oslg,osut,topolys,tbd,openstudio-standards,openstudio-workflow,rspec-support,rspec-core,rspec-expectations,rspec-mocks,rspec]
```

Specs to be included no longer contains json.

File: ruby/bindings/InitRubyBindings.cpp [hunk 5]
```diff
@@ -920,6 +945,37 @@ void locateEmbeddedGems(bool use_bundler) {
...
+          dep_to_requirements[locked_spec.name] = dep.requirement.to_s
+        end
+      end
+
+
+      if locked_specs.none? { |locked_spec| locked_spec.dependencies.any? {|x| x.name == spec.name} }
+        locked_spec_v = locked_specs.select{|locked_spec| locked_spec.name == spec.name}.first.version
+        $logger.debug("Removing native gem #{spec.name} from Bundler locked_specs (version #{locked_spec_v}), using the embedded dependency (CLI one has version #{spec.version})")
+        $logger.trace("Gems having #{spec.name} as a dependency: #{dep_to_requirements}")
+        raise "Failed to activate #{spec.name}" unless spec.activate
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:970]: I'm not sure this is even needed to try and activate now, but I find it logical. Maybe I should have also deleted it from embedded_gems_to_activate, not sure.

File: ruby/bindings/InitRubyBindings.cpp [hunk 6]
```diff
@@ -934,8 +990,11 @@ void locateEmbeddedGems(bool use_bundler) {
       RbConfig::CONFIG['arch'] = original_arch
     end
 
-      Dir.chdir(current_dir)
-    end
+    Dir.chdir(current_dir)
+
+    # clean up the global
+    $ignore_native_gem_names = nil
```
Comment (jmarrec) [inline ruby/bindings/InitRubyBindings.cpp:996]: At the end I clean up the global, because I'm a good citizen.

In ruby `$<whatever>` returns nil anyways if not defined.

I think we should also do the same for our `$logger` global variable, but not the point there.

**Review by kbenne — APPROVED** [review]
