### PR TITLE
Fix #5518 - Design conditions incorrectly parsed for TMYx EPWs

### LINKED ISSUE #5518: Design conditions incorrectly parsed for TMYx EPWs
Issue overview
--------------
TMYx EPWs have different numbers of values for DESIGN CONDITIONS in the header relative to TMY3 EPWs. If you compare, e.g., [this TMYx](https://climate.onebuilding.org/WMO_Region_4_North_and_Central_America/USA_United_States_of_America/VA_Virginia/USA_VA_Charlottesville-Albemarle.AP.724016_TMYx.2009-2023.zip) and [this TMY3](https://energyplus-weather.s3.amazonaws.com/north_and_central_america_wmo_region_4/USA/VA/USA_VA_Richmond.Intl.AP.724010_TMY3/USA_VA_Richmond.Intl.AP.724010_TMY3.zip), you'll find:
- Heating: 15 values (TMY3) vs 16 values (TMYx)
- Cooling: 32 values (TMY3) vs 32 values (TMYx)
- Extremes: 16 values (TMY3) vs 15 values (TMYx)

It appears that OpenStudio [reads the values by position](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/filetypes/EpwFile.cpp#L570), so this causes all the cooling design values to be assigned to the wrong property. For example, the 0.4% MCWB is assigned to the 1% Cooling DB.

Instead of reading the data positionally, OpenStudio should read the data relative to each "header" (i.e., Heating, Cooling). This would be more robust.

This issue causes OpenStudio-HPXML to use 74.4F as the cooling design temperature instead of 90.7F for the above TMYx, resulting in very wrong HVAC autosizing results for cooling.

### PR DESCRIPTION
**Pull request by jmarrec**
Pull request overview
---------------------

 - Fixes #5518
 - I compared the ASHRAE Handbook of Fundamentals Chatpter 14 Climatic Design Conditions for all vintages from 2009 to 2025, cf this spreadsheet: https://docs.google.com/spreadsheets/d/14wPHNDVmDZyLqcGrGDeW8pH6tx_psQn8-8SZ1Fp6tJY/edit?usp=sharing

The summary of the differences is this:

image

### Pull Request Author

 - [ ] Model API Changes / Additions
 - [ ] Any new or modified fields have been implemented in the EnergyPlus ForwardTranslator (and ReverseTranslator as appropriate)
 - [ ] Model API methods are tested (in `src/model/test`)
 - [ ] EnergyPlus ForwardTranslator Tests (in `src/energyplus/Test`)
 - [ ] If a new object or method, added a test in NREL/OpenStudio-resources: Add Link
 - [ ] If needed, added VersionTranslation rules for the objects (`src/osversion/VersionTranslator.cpp`)
 - [ ] Verified that C# bindings built fine on Windows, partial classes used as needed, etc.
 - [ ] All new and existing tests passes
 - [ ] If methods have been deprecated, update rest of code to use the new methods

**Labels:**

 - [ ] If change to an IDD file, add the label `IDDChange`
 - [ ] If breaking existing API, add the label `APIChange`
 - [ ] If deemed ready, add label `Pull Request - Ready for CI` so that CI builds your PR

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] Code Style, strip trailing whitespace, etc.
 - [ ] All related changes have been implemented: model changes, model tests, FT changes, FT tests, VersionTranslation, OS App
 - [ ] Labeling is ok
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified

### CODE REVIEW

File: src/utilities/filetypes/EpwFile.hpp [hunk 1]
```diff
@@ -126,6 +128,16 @@ OPENSTUDIO_ENUM(EpwComputedField,
...
 );
+
+// cppcheck-suppress [unknownMacro, syntaxError]
+OPENSTUDIO_ENUM(ASHRAEHoFVintage,
+  ((ASHRAE_2009)(ASHRAE Handbook of Fundamentals 2009))
+  ((ASHRAE_2013)(ASHRAE Handbook of Fundamentals 2013))
+  ((ASHRAE_2017)(ASHRAE Handbook of Fundamentals 2017))
+  ((ASHRAE_2021)(ASHRAE Handbook of Fundamentals 2021))
+  ((ASHRAE_2025)(ASHRAE Handbook of Fundamentals 2025))
+);
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.hpp:139]: New enum for ASHRAE Handbook of Fundamentals vintage

File: src/utilities/filetypes/EpwFile.cpp [hunk 2]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+  setExtremeN50YearsMaxDryBulb(stringValues[index(EpwDesignField::ExtremeN50YearsMaxDryBulb)]);
+}
+
 boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStrings(const std::vector<std::string>& strings) {
   EpwDesignCondition dc;
+
+  const size_t num_strings = strings.size();
   // Expect 68 items in the strings
-  if (strings.size() < 68) {
+  if (num_strings < 67 || num_strings > 68) {
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:678]: Bail early. I have never seen a TMYx file prepared with HoF 2017 vintage climatic design conditions which has one field less than the rest, but I suppose it could happen.

File: src/utilities/filetypes/EpwFile.cpp [hunk 3]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+      } else {
+        // Assume future version is the same as 2025
+        LOG_FREE(Debug, "openstudio.EpwFile",
+                 "Unrecognized ASHRAE design year (" << year << ") in EPW design condition title. Assuming 2025 vintage for parsing.");
+        assumedVersion = ASHRAEHoFVintage::ASHRAE_2025;
+      }
+    } else {
+      LOG_FREE(Debug, "openstudio.EpwFile", "Did not detect a valid ASHRAE design year in EPW design condition title.");
+    }
+  }
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:712]: So, I start by trying to figure out the version in the title. Technically speaking, this isn't necessary, but I would like to Warn the user if there is a valid year source in there but the number of fields don't match: we look for `20xx` and if it's 2009 or any four (4) year increment, it's valid.

File: src/utilities/filetypes/EpwFile.cpp [hunk 4]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+    return boost::none;
+  }
+
+  std::span<const std::string> heatingStrings(std::next(itHeating, 1), itCooling);
+  std::span<const std::string> coolingStrings(std::next(itCooling, 1), itExtreme);
+  std::span<const std::string> extremesStrings(std::next(itExtreme, 1), strings.cend());
+
+  const auto numHeatingFields = heatingStrings.size();
+  const auto numCoolingFields = coolingStrings.size();
+  const auto numExtremeFields = extremesStrings.size();
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:741]: Now we chunk into `std::span`s by looking for the "Heating", "Cooling", and "Extremes" fields.

If we can't find them, bail.

File: src/utilities/filetypes/EpwFile.cpp [hunk 5]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+    if (numExtremeFields != expectedNumExtremeFields) {
+      LOG_FREE(Warn, "openstudio.EpwFile",
+               "Based on the assumed vintage parsed in the title string of " << assumedVersion->valueDescription() << ", we expected "
+                                                                             << expectedNumExtremeFields << " Extreme fields but got "
+                                                                             << numExtremeFields << ", falling to back to heuristics.");
+      needHeuristics = true;
+    }
+  } else {
+    needHeuristics = true;
+  }
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:783]: If there was a parsable version in the title, we check that the number of fields are matching what we expect. If not, we warn and still fall back to using heuristics.

File: src/utilities/filetypes/EpwFile.cpp [hunk 6]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+      // This has to be 2021 or 2025
+      assumedVersion = ASHRAEHoFVintage::ASHRAE_2021;
+      expectedNumHeatingFields = 16;
+      expectedNumExtremeFields = 15;
+    } else {
+      LOG_FREE(Error, "openstudio.EpwFile",
+               "Unexpected number of heating design condition fields (" << numHeatingFields << ", expected 15 or 16) in EPW design condition string");
+      return boost::none;
+    }
+  }
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:807]: If there wasn't a parsable version or the numbers of fields weren't ok, we use heuristics, and assign the earliest version of the HoF that matches the number of heating and extreme fields we actually found.

File: src/utilities/filetypes/EpwFile.cpp [hunk 7]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+
+  if (numExtremeFields != expectedNumExtremeFields) {
+    LOG_FREE(Error, "openstudio.EpwFile",
+             "Based on the assumed vintage of " << assumedVersion->valueDescription() << ", we expected " << expectedNumExtremeFields
+                                                << " Extreme fields but got " << numExtremeFields << ".");
+    return boost::none;
+  }
+
+  dc.m_ashraeHoFVersion = *assumedVersion;
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:829]: Final check of the actual number of fields in each span. Return none if anything is wrong.

File: src/utilities/filetypes/EpwFile.cpp [hunk 8]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+
+  dc.assignHeatingData(heatingStrings);
+  dc.assignCoolingData(coolingStrings);
+  dc.assignExtremesData(extremesStrings);
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:833]: And now we assign based on that.

File: src/utilities/filetypes/EpwFile.hpp [hunk 9]
```diff
@@ -146,6 +158,7 @@ OPENSTUDIO_ENUM(EpwDesignField,
   ((HeatingColdestMonthMeanCoincidentDryBulb1)(Heating Coldest Month Mean Coincident Dry Bulb 1%))
   ((HeatingMeanCoincidentWindSpeed99pt6)(Heating Mean Coincident Wind Speed))
   ((HeatingPrevailingCoincidentWindDirection99pt6)(Heating Prevailing Coincident Wind Direction 99.6%))
+  ((HeatingWindShelterFactor)(Heating Wind Shelter Factor)) // ASHRAE HOF, Ch 14, 2021 and 2025 editions
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.hpp:161]: New Heating Wind Shelter Factor for 2021 and upwards

File: src/utilities/filetypes/EpwFile.hpp [hunk 10]
```diff
@@ -178,12 +191,13 @@ OPENSTUDIO_ENUM(EpwDesignField,
   ((CoolingEnthalpyMeanCoincidentDryBulb1)(Cooling Enthalpy Mean Coincident Dry Bulb 1%))
   ((CoolingEnthalpy2)(Cooling Enthalpy 2%))
   ((CoolingEnthalpyMeanCoincidentDryBulb2)(Cooling Enthalpy Mean Coincident Dry Bulb 2%))
-  ((CoolingHours8To4AndDryBulb12pt8To20pt6)(Cooling Hours 8 to 4 and Dry Bulb 12.8% to 20.6%))
+  ((CoolingHours8To4AndDryBulb12pt8To20pt6)(Cooling Hours 8 to 4 and Dry Bulb 12.8% to 20.6%)) // ASHRAE HOF, Ch 14, up to 2013 (included) editions
+  ((CoolingExtremeMaxWetBulb)(Cooling Extreme Max Wet Bulb)) // ASHRAE HOF, Ch 14, 2017, 2021 and 2025 editions
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.hpp:195]: Up to 2013, There was the CoolingHours8To4AndDryBulb12pt8To20pt6 at the end of the data section.
The (cooling) Extreme Maximum Wet Bulb was in the Extreme Section.

At 2017 and up, the CoolingHours8To4AndDryBulb12pt8To20pt6 is gone and the Cooling Extreme Maximum Wet Bulb field is taking its place

File: src/utilities/filetypes/EpwFile.hpp [hunk 11]
```diff
@@ -845,10 +891,11 @@ class UTILITIES_API EpwDesignCondition
   boost::optional<double> m_coolingEnthalpy2;
   boost::optional<double> m_coolingEnthalpyMeanCoincidentDryBulb2;
   boost::optional<int> m_coolingHours8To4AndDryBulb12pt8To20pt6;
+
   boost::optional<double> m_extremeWindSpeed1;
   boost::optional<double> m_extremeWindSpeed2pt5;
   boost::optional<double> m_extremeWindSpeed5;
-  boost::optional<double> m_extremeMaxWetBulb;
+  boost::optional<double> m_extremeMaxWetBulb;  // This also stores CoolingExtremeMaxWetBulb for versions starting at 2017
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.hpp:898]: Note that since this field is technically just moved, I'm reusing the same member regardless of the whether we're < 2017 or >= 2017

File: src/utilities/filetypes/EpwFile.hpp [hunk 12]
```diff
@@ -632,15 +652,26 @@ class UTILITIES_API EpwDesignCondition
...
-  /** Returns the number of cooling hours between 8am and 4pm with dry bulb temperature between 12.8 and 20.6 degrees C */
+  /** Returns the number of cooling hours between 8am and 4pm with dry bulb temperature between 12.8 and 20.6 degrees C.
+   *  This is only available for Design Conditions taken from the ASHRAE Handbook of Fundamentals up to 2013 (included) editions
+   **/
   boost::optional<int> coolingHours8To4AndDryBulb12pt8To20pt6() const;
+  /** Returns the cooling maximum wet bulb temperature in degrees C.
+   *  Prior to the 2017 edition of the ASHRAE Handbook of Fundamentals, this is stored in the Extreme section, and starting at 2017
+   *  it is stored in the Cooling Section. This is an alias for extremeMaxWetBulb() (pre-existing method) for clarity.
+   **/
+  boost::optional<double> coolingExtremeMaxWetBulb() const;
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.hpp:663]: For clarity I'm adding an alias getter (and Enum value) though.

File: src/utilities/filetypes/EpwFile.cpp [hunk 13]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+  setHeatingColdestMonthWindSpeed0pt4(stringValues[index(EpwDesignField::HeatingColdestMonthWindSpeed0pt4)]);
+  setHeatingColdestMonthMeanCoincidentDryBulb0pt4(stringValues[index(EpwDesignField::HeatingColdestMonthMeanCoincidentDryBulb0pt4)]);
+  setHeatingColdestMonthWindSpeed1(stringValues[index(EpwDesignField::HeatingColdestMonthWindSpeed1)]);
+  setHeatingColdestMonthMeanCoincidentDryBulb1(stringValues[index(EpwDesignField::HeatingColdestMonthMeanCoincidentDryBulb1)]);
+  setHeatingMeanCoincidentWindSpeed99pt6(stringValues[index(EpwDesignField::HeatingMeanCoincidentWindSpeed99pt6)]);
+  setHeatingPrevailingCoincidentWindDirection99pt6(stringValues[index(EpwDesignField::HeatingPrevailingCoincidentWindDirection99pt6)]);
+
+  if (m_ashraeHoFVersion >= ASHRAEHoFVintage::ASHRAE_2021) {
+    setHeatingWindShelterFactor(stringValues[index(EpwDesignField::HeatingWindShelterFactor)]);
+  }
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:598]: assignHeatingData: we parse Wind Shelter Factor if >= 2021

File: src/utilities/filetypes/EpwFile.cpp [hunk 14]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+  setCoolingEnthalpyMeanCoincidentDryBulb0pt4(stringValues[index(EpwDesignField::CoolingEnthalpyMeanCoincidentDryBulb0pt4)]);
+  setCoolingEnthalpy1(stringValues[index(EpwDesignField::CoolingEnthalpy1)]);
+  setCoolingEnthalpyMeanCoincidentDryBulb1(stringValues[index(EpwDesignField::CoolingEnthalpyMeanCoincidentDryBulb1)]);
+  setCoolingEnthalpy2(stringValues[index(EpwDesignField::CoolingEnthalpy2)]);
+  setCoolingEnthalpyMeanCoincidentDryBulb2(stringValues[index(EpwDesignField::CoolingEnthalpyMeanCoincidentDryBulb2)]);
+  if (m_ashraeHoFVersion <= ASHRAEHoFVintage::ASHRAE_2013) {
+    setCoolingHours8To4AndDryBulb12pt8To20pt6(stringValues[index(EpwDesignField::CoolingHours8To4AndDryBulb12pt8To20pt6)]);
+  } else {
+    setExtremeMaxWetBulb(stringValues[index(EpwDesignField::CoolingExtremeMaxWetBulb) - 1]);
+  }
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:641]: assignCoolingData: depending on vintage, the last field is CoolingHours8To4AndDryBulb12pt8To20pt6 or CoolingExtremeMaxWetBulb (notice the index -1 here)

File: src/utilities/filetypes/EpwFile.cpp [hunk 15]
```diff
@@ -567,79 +568,271 @@ boost::optional<EpwDesignCondition> EpwDesignCondition::fromDesignConditionsStri
...
+  };
+
+  setExtremeWindSpeed1(stringValues[index(EpwDesignField::ExtremeWindSpeed1)]);
+  setExtremeWindSpeed2pt5(stringValues[index(EpwDesignField::ExtremeWindSpeed2pt5)]);
+  setExtremeWindSpeed5(stringValues[index(EpwDesignField::ExtremeWindSpeed5)]);
+  if (m_ashraeHoFVersion <= ASHRAEHoFVintage::ASHRAE_2013) {
+    setExtremeMaxWetBulb(stringValues[index(EpwDesignField::ExtremeMaxWetBulb)]);
+  } else {
+    ++offset;
+  }
```
Comment (jmarrec) [inline src/utilities/filetypes/EpwFile.cpp:657]: assignExtremesData: skip or setExtremeMaxWetBulb  depending on vintage

File: src/utilities/filetypes/test/EpwFile_GTest.cpp [hunk 16]
```diff
@@ -1120,3 +1120,630 @@ DATA PERIODS,1,1,Data,Sunday, 1/ 1,1/1
...
 }
+
+TEST(Filetypes, EpwDesignCondition_HoF_2009) {
+
+  const std::string line = "Climate Design Data 2009 ASHRAE Handbook,,"
+                           "Heating,12,-18.8,-15.5,-21.6,0.7,-10.9,-18.8,0.9,-7.5,12.2,3.9,10.9,3.8,3,340,"
+                           "Cooling,7,15.2,33,15.7,32,15.5,30.2,15.3,18.4,27.3,17.5,26.4,16.8,25.6,4.9,0,16.1,14.3,20.2,14.9,13.2,19.9,13.9,12.3,"
+                           "19.6,59.7,27.3,56.6,26.6,54,25.7,760,"
+                           "Extremes,11.1,9.5,8.4,22.9,-22.9,36.1,3.8,1.2,-25.7,37,-27.9,37.7,-30.1,38.3,-32.8,39.2";
+  auto dc_ = EpwDesignCondition::fromDesignConditionsString(line);
```
Comment (jmarrec) [inline src/utilities/filetypes/test/EpwFile_GTest.cpp:1131]: Lots of tests, will not comment on them

File: src/utilities/filetypes/test/EpwFile_GTest.cpp [hunk 17]
```diff
@@ -1120,3 +1120,630 @@ DATA PERIODS,1,1,Data,Sunday, 1/ 1,1/1
...
+  const std::string line = "This title includes the 2009 version when it's not actually it,,"
+                           "Heating,12,-18.8,-15.5,-21.6,0.7,-10.9,-18.8,0.9,-7.5,12.2,3.9,10.9,3.8,3,340,0.635,"
+                           "Cooling,7,15.2,33,15.7,32,15.5,30.2,15.3,18.4,27.3,17.5,26.4,16.8,25.6,4.9,0,16.1,14.3,20.2,14.9,13.2,19.9,13.9,12.3,"
+                           "19.6,59.7,27.3,56.6,26.6,54,25.7,22.9,"
+                           "Extremes,11.1,9.5,8.4,-22.9,36.1,3.8,1.2,-25.7,37,-27.9,37.7,-30.1,38.3,-32.8,39.2";
+  auto dc_ = EpwDesignCondition::fromDesignConditionsString(line);
+  ASSERT_TRUE(dc_);
+  const auto dc = std::move(*dc_);
+
+  EXPECT_EQ(dc.ashraeHoFVersion(), ASHRAEHoFVintage::ASHRAE_2021);
```
Comment (jmarrec) [inline src/utilities/filetypes/test/EpwFile_GTest.cpp:1507]:
```
[ RUN      ] Filetypes.EpwDesignCondition_HoF_2021_Heuristics_OverrideVersion
[openstudio.EpwFile] <0> Based on the assumed vintage parsed in the title string of ASHRAE Handbook of Fundamentals 2009, we expected 15 Heating fields but got 16, falling to back to heuristics.
[openstudio.EpwFile] <0> Based on the assumed vintage parsed in the title string of ASHRAE Handbook of Fundamentals 2009, we expected 16 Extreme fields but got 15, falling to back to heuristics.
```

**Review by jmarrec — COMMENTED** [review]
TL;DR:

* Parse the title string of the DESIGN CONDITIONS to try to determine ASHRAE HoF Vintage
    * If present and valid (2009 and increments of four years), check the expected number of fields in each Heating and Extremes section: if not matching, we warn and fall back to using heuristics
* If no parsed versions or invalid, we use heuristics: we look at the number of found fields in the Heating and Extremes sections to determine the HoF vintage that matches 
* Final check to ensure that everything is ok, including the number of cooling fields (which do not change)
* Then we assign the heating, cooling, and extremes sections separately, handling the fields based on vintage.

**Comment by jmarrec** [comment]
I'm going to take the silence as an approbation, I want to start producing nightly builds for testing, so merging. We can address any comment that may arise later (I assume they'll be quite minor, I'm pretty confident in the changes here).

Merging
